### ISSUE TITLE
data-width option breaks responsivness 

### ISSUE THREAD

**Issue by neuropass** [snapappointments/bootstrap-select#1064]
If you set the data-width to auto the responsiveness breaks. 
It is visible on the demo page:
http://silviomoreto.github.io/bootstrap-select/

<select class="selectpicker" data-width="auto">

Is there a way to have the automatic width used but also keep the repressiveness working? (100%)

**Comment by NicolasCARPi** [comment]
This needs to be tested on the newest version with the newest browsers. Closing because of old age.
