### ISSUE TITLE
Calling $el.selectpicker('val', ''); sets divider elements as selected, and messes up the multi selected count

### ISSUE THREAD

**Issue by DrewBe121212** [snapappointments/bootstrap-select#1069]
Hello,

When using a select picker of type multi and using dividers in the select picker, then subsequently calling $el.selectpicker('val', '') causes all of the divider elements to become selected. This causes values to post as either an array or a comma delimited list of empty values depending on the backend technology, and when displaying text as type 'count', the count of items selected now considers the total elements selected + the total amount of divders in the select. Please see this js fiddle as an example.
1. Click on multiple items in the menu to show a proper count. 
2. Click on 'refresh selectpickers'
3. Click on multiple items in the menu now shows a count of the selected items + total dividers.

http://jsfiddle.net/8nh0qgvw/

**Comment by DrewBe121212** [comment]
It looks like the solution is to actually pass an empty array to the select to zero it out. This seems like really strange behavior to me. I don't think normal selects would behave this way (i can't get it to replicate), however, your 'val' method isn't much more than a passthrough to the jQuery val() method. 

Should this be caught on the plugin's side or mine? (My code deals with constantly refreshing selects data dynamically, sometimes they are multi's, sometimes they are single selects). 

Example of the different behaviors when passing it an empty string vs empty array:
http://jsfiddle.net/8nh0qgvw/1/

**Comment by caseyjhol** [comment]
This is an issue on your end. When setting a multiple select to empty, it's preferred to use `[]`. You'll see here: http://jsfiddle.net/caseyjhol/9ahLgdvz/ you get the same result without bootstrap-select. An alternative (if you really want to use `.val('')` is to set the value of the divider options to something like "null".
