### ISSUE TITLE
Show checkbox in rendered items

### ISSUE THREAD

**Issue by garygreen** [snapappointments/bootstrap-select#1074]
Is it possible to have a checkbox on each item like in the image? It's not too intuitive at the moment that you can select multiple items by toggling. I think this would be a nice option.

![multi select](https://cloud.githubusercontent.com/assets/1702638/8318838/5ebe2404-1a00-11e5-9598-0f6623f41d18.png)

**Comment by krystyna93** [comment]
Hey, did you ever figure this out?? I would love to know how I could do it.

**Comment by gpashis** [comment]
This example may help. https://codepen.io/7iomka/pen/xxxZpwN
