### ISSUE TITLE
data-icon doesn't update after refresh / render 

### ISSUE THREAD

**Issue by valix85** [snapappointments/bootstrap-select#1079]
Hi i try to add data-icon on my element option dinamically with a script and after i call refresh / render method, but nothing to do, icon that i remove dosn't update, i have both element with icon.
My idea is add an icon on active / selected element, but the picker don't update correctly UI.

**Comment by parvus71** [comment]
I have same issue. I want to change data-icon from one option to another but selectpicker doesn't remove old set icon. It shows all data icons. My examle: http://jsfiddle.net/parvus71/s1e58q3m/

**Comment by parvus71** [comment]
I have found solution. You have to use data() method to manipulate with data-icon and other data properties. And then refresh method is working properly.
New working solution: http://jsfiddle.net/parvus71/s1e58q3m/7/

**Comment by caseyjhol** [comment]
Fixed in v1.13.6.
