### ISSUE TITLE
Refresh doesn't update dropupAuto

### ISSUE THREAD

**Issue by Tomas-M** [snapappointments/bootstrap-select#1097]
My select has 4 options. If clicked, it opens down.

Then I programatically update the select to add 10 items while the dropdown is open. There is plenty of space up, but no more space down. I call  $select.selectpicker('refresh'). It updates the bootstrap-select, so newly added items are visible there, but (!) it remains open still down instead of switching to open up.

I would expect it to reconsider where to open if refresh is called.

**Comment by Tomas-M** [comment]
Update: when I click with mouse on the select to close it and open it again, it auto opens up, of course. I'm just expecting to change up/down orientation on 'refresh' command without the user needing to click it. Thank you

**Comment by Tomas-M** [comment]
I've worked around it by firing scroll event on the document after selectpicker refresh, which causes the selectpicker to rearrange up if there is more space for it.

**Comment by HeskethGD** [comment]
I am also using update options and cannot seem to disable dropupAuto via any html/jquery technique and have tried various combinations of selectpicker refresh. It still opens up and gets hidden behind the navbar, I would like it to always open down.
