### ISSUE TITLE
bootstrap-select.js not works well in browser on WINDOWS when input Chinese.

### ISSUE THREAD

**Issue by insekkei** [snapappointments/bootstrap-select#1101]
Condition: liveSearch enabled, and the optgroup contains both the English and the Chinese strings, searching for Chinese character will not work for inputing error: I can just input one character...

Example: I tried to input "韩" in the search box, but only got the result that "h", "a", "n", "c", "o", "n", "g" appear in turn... 

```
     <select id="basic" class="selectpicker show-tick form-control" data-live-search="true">
      <option>cow</option>
      <option data-subtext="option subtext">bull</option>
      <option class="get-class" disabled>ox</option>
      <optgroup label="test" data-subtext="optgroup subtext">
        <option>ASD</option>
        <option selected>Bla</option>
        <option>Ble</option>
        <option>hancong</option>
        <option>韩聪</option>
      </optgroup>
    </select>
```

<img width="617" alt="qq20150716-1 2x" src="https://cloud.githubusercontent.com/assets/5036903/8720127/6785d876-2be3-11e5-8560-4631de1e0f8e.png">
<img width="540" alt="qq20150716-2 2x" src="https://cloud.githubusercontent.com/assets/5036903/8720129/678ecbac-2be3-11e5-8f01-2939f34c6ea0.png">
<img width="633" alt="qq20150716-3 2x" src="https://cloud.githubusercontent.com/assets/5036903/8720128/678a3f06-2be3-11e5-9792-a76e6fce10ec.png">
<img width="609" alt="qq20150716-4 2x" src="https://cloud.githubusercontent.com/assets/5036903/8720131/67a125ea-2be3-11e5-8915-a41bd3f608e1.png">
<img width="599" alt="qq20150716-5 2x" src="https://cloud.githubusercontent.com/assets/5036903/8720130/67941882-2be3-11e5-9548-4a0dc10bddee.png">
<img width="599" alt="qq20150716-6 2x" src="https://cloud.githubusercontent.com/assets/5036903/8720132/67be2fc8-2be3-11e5-8aa6-d6ac88f7a1ff.png">
<img width="589" alt="qq20150716-7 2x" src="https://cloud.githubusercontent.com/assets/5036903/8720133/68270eb2-2be3-11e5-9163-b76c2e6ae14b.png">

Solution:
After note ".children('a').focus();"  in line 1253 of Bootstrap-select v1.7.2, it became normal when search for Chinese:

<img width="591" alt="qq20150716-8 2x" src="https://cloud.githubusercontent.com/assets/5036903/8720206/e8ee1478-2be3-11e5-8db1-0d7b0df0add0.png">
<img width="588" alt="qq20150716-9 2x" src="https://cloud.githubusercontent.com/assets/5036903/8720207/e90d72e6-2be3-11e5-9dfe-4c77925b833f.png">

**Comment by insekkei** [comment]
Thanks my friend 三木 @ https://github.com/yansm  for the contribution of this issue.

**Comment by insekkei** [comment]
看这里：http://www.gbtags.com/gb/share/5785.htm

**Comment by insekkei** [comment]
And Japanese! And each un-letter language!!

**Comment by lovemyliwu** [comment]
@insekkei please make a PR for it. Thanks.

**Comment by caseyjhol** [comment]
This should be fixed, but please provide a live example if not.
