### ISSUE TITLE
Donation options

### ISSUE THREAD

**Issue by Tomas-M** [snapappointments/bootstrap-select#1114]
I find your project useful, and since I have some spare bitcoin cents (worth $33), I'd like to donate them if you like. Do you have any bitcoin address for donations? Thanks

**Comment by caseyjhol** [comment]
I set up a "Buy me a coffee" page at https://www.buymeacoffee.com/caseyjhol. Or you can donate via the GitHub sponsors button at the top of the page. I have a Bitcoin address at 3B2hsCNeRakbsFkj14Z26V3tCvkz4wV44N.
