### ISSUE TITLE
the select pop up opens only in Firefox when offline 

### ISSUE THREAD

**Issue by Webinator2129** [snapappointments/bootstrap-select#1115]
was testing a project offline and noticed that the popup select does not open, thought might be an issue with data loading but figured out that was not the case. tested same form in following browers with following results

when offline
Opera: does not work
Chrome: does not work
Firefox: Works!
Safari: does not work

when Online
Opera: Works
Chrome: Works
Firefox: Works
Safari: works

![screen shot 2015-08-01 at 19 08 30](https://cloud.githubusercontent.com/assets/1534356/9024097/146e49f2-3881-11e5-85f4-cd43e02219e0.png)

**Comment by caseyjhol** [comment]
Probably a caching/local script storage issue. Please provide more information if you'd like me to look into this further.
