### ISSUE TITLE
Multiple with postback

### ISSUE THREAD

**Issue by ghost** [snapappointments/bootstrap-select#1118]
HI 

I don't know if it is issue and maybe is something wrong with my code but:

I have select with multiple option on aspx page. When I select only one item, after post back this item is still selected. But when I select more than one item, after post back is selected only first item.

Is there any solution to keep all items selected after post back?

BR, 
Thomas

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md). Any chance you can link me to a demo or jsfiddle? Have you been able to reproduce this with a reduced test case?

**Comment by khaledelmahdi** [comment]
I have the same issue, any idea how to fix it?
