### ISSUE TITLE
Include the: "width: 220px" on the: "bootstrap-select.css" for the non Internet Explorer Browsers.

### ISSUE THREAD

**Issue by zequeira** [snapappointments/bootstrap-select#1122]
When using bootstrap-select in Chrome, it detect the property: "width: 220px \0;" as invalid, and according to:
http://stackoverflow.com/questions/8004765/css-9-in-width-property
it should be defined in the "bootstrap-select.css" file also another with property for the others browsers, something like:

``` javascript
.bootstrap-select {
  width: 220px \0;
  /*IE9 and below*/
  width: 220px;
}
```

**Comment by NicolasCARPi** [comment]
@caseyjhol It's probably safe to remove that hack now.

**Comment by NicolasCARPi** [comment]
Going through the issues, it looks like this is causing problems to users and should really be removed!

**Comment by adschm** [comment]
Ping. Getting "Invalid property value" for Chromium here as well ...

**Comment by NicolasCARPi** [comment]
I made a PR, but lately the main maintainer does not respond on GitHub, so there's that.

**Comment by NicolasCARPi** [comment]
fixed by https://github.com/snapappointments/bootstrap-select/commit/17cffd46760365bcb4a590d0efb445d3b48a02dd
