### ISSUE TITLE
Standalone version (not BS)

### ISSUE THREAD

**Issue by Mushr0000m** [snapappointments/bootstrap-select#1126]
Hi, Is there a way to uses this plugin without Bootstrap ? I mean do you plan to have a standalone version ?

Thanks

**Comment by serGlazkov** [comment]
+1

**Comment by wekii** [comment]
+1

**Comment by mehocode** [comment]
+1

**Comment by Ares566** [comment]
+1

**Comment by amitsquare** [comment]
+1

**Comment by NicolasCARPi** [comment]
This project is called "**bootstrap**-select", so it's reasonable to use it in a bootstrap context.
