### ISSUE TITLE
Dropdown won't open on Chrome v46 dev channel

### ISSUE THREAD

**Issue by Godwack** [snapappointments/bootstrap-select#1129]
Hello!

There is a slight problem with dropdowns, they won't open when clicked on. This happens in Chrome v46 dev channel version.

Just a heads-up, dunno if this will still be present in beta or public releases.

**Comment by Hawkeye66** [comment]
Working fine for me in both in v46.0.2478.0 dev-m (64-bit) and v46.0.2486.0 dev-m under Windows. All work fine on http://silviomoreto.github.io/bootstrap-select/

**Comment by cyanpunk** [comment]
Possibly this occurs only on Mac.

**Comment by tpendragon** [comment]
@Hawkeye66 @cyanpunk Can confirm this. However, the examples work. Difference may be jQuery 2.2?
