### ISSUE TITLE
add options 'AllowClear'

### ISSUE THREAD

**Issue by liaosankai** [snapappointments/bootstrap-select#1132]
Allow a selected option to be cleared back to the placeholder by enabling the allowClear option.This will display an "x" that the user can click to clear the current selection. It is designed to be used for cases where a single selection can be made.

**Comment by juliorosseti** [comment]
I fully agree! ☝🏼☝🏼

**Comment by juliorosseti** [comment]
For those who are using Bootstrap > 4.3:

https://codepen.io/anon/pen/OGzweV

**Comment by rhythmpatel** [comment]
This is a much needed option.
Using the plugin to filter a list of items, clearing would reset the filter.

**Comment by caseyjhol** [comment]
Thanks for the suggestion! Closing in favor of #1449. Please 👍 to vote and subscribe 🔉 for updates.
