### ISSUE TITLE
Poor scrolling performance when the dropdown is hidden

### ISSUE THREAD

**Issue by phizaz** [snapappointments/bootstrap-select#1144]
It's very weird to me that my large list of options works just fine, until the dropdown box (`div.dropdown-menu.open`) is closed (`display: none`) (while the dropdown is present the scrolling performance is back to normal)

I've captured the timeline here:
![screen shot 2558-09-05 at 16 07 21](https://cloud.githubusercontent.com/assets/451667/9698603/c5d0d480-53e8-11e5-883f-d1ecc306932e.png)
The timeline above is when I scroll the whole page while the dropdown box is closed (`display: none`)

And here is when I scroll the whole page when the dropdown is open (`display: block`)
![screen shot 2558-09-05 at 16 07 27](https://cloud.githubusercontent.com/assets/451667/9698626/a0d2c5e8-53e9-11e5-9657-717985f6f059.png)

This problem can be mitigated when I stop using `display: none` and start using `visibility: hidden` instead, though the visuals are not the same.

**Comment by andyghiuta** [comment]
A fix we are using for this: 

```
$('.selectpicker').on('hidden.bs.select',
 function (e) {
  var dropdown = $(e.currentTarget).parents('.bootstrap-select').find('div.dropdown-menu');
  dropdown.removeClass('open');
});
$('.selectpicker').on('show.bs.select', function (e) {
  var dropdown = $(e.currentTarget).parents('.bootstrap-select').find('div.dropdown-menu');
  dropdown.addClass('open');
});
