### ISSUE TITLE
Issue with auto width when using flexbox

### ISSUE THREAD

**Issue by CoralSilver** [snapappointments/bootstrap-select#1153]
I added flex properties to my site to get a sticky footer when content does not fill the viewport height.

```
body {
  display: flex;
  flex-direction: column;
  min-height: 100%;
}

main {
  flex: 1;
}
```

But when setting `data-width="auto"` on the select it miscalculates the width, causes it to be even wider than its containing element
![screen shot 2015-09-14 at 2 12 27 pm](https://cloud.githubusercontent.com/assets/6298173/9857964/be15c3fe-5aeb-11e5-8dce-1fdf16736062.png)

I'm new to flexbox, but I tried overriding the flex:1 for the select, but it doesn't do anything.

```
.bootstrap-select, .selectpicker {
  flex: none;  
  flex-grow: initial;
}
```

Any ideas how to fix this?

**Comment by arkadini** [comment]
It seems to happen because the temporary copy (for calculating the auto width) of the dropdown elements is being attached to `body`, which in flex mode by default stretches its items along the cross axis.

A workaround that worked for me:
```css
body > .bootstrap-select,
body > .bootstrap-select > button {
  align-self: flex-start;
}
```
