### ISSUE TITLE
Native selects aren't working properly in Firefox for Android

### ISSUE THREAD

**Issue by amkoehler** [snapappointments/bootstrap-select#1161]
I have recreated this issue in Firefox for Android on a Galaxy Tab, Nexus 4 and a OnePlus One. In Firefox for Android (version 40.0.3) the native selects do not work properly. Instead, the dropdown/desktop view shows like it would if you were opening the bootstrap-select on a desktop browser. This can be replicated on the main examples page: http://silviomoreto.github.io/bootstrap-select/. I searched through the issues for other Firefox for Android issues and couldn't find anything related to this issue, and it looks like this hasn't always been the case.

**Comment by kaludjer** [comment]
Anyone solved this issue on multiple option? It's still present in Firefox mobile browser if you apply native option.

**Comment by caseyjhol** [comment]
Looks like they've fixed it in recent versions of Firefox.
