### ISSUE TITLE
Use te plugin with a button in a btn-group

### ISSUE THREAD

**Issue by Emyleen** [snapappointments/bootstrap-select#1162]
Hello,

I wish I could have a select and a button glued to each other as do the buttons in a btn-group. Is it possible? For I have found that if I put them in a btn-group this puts the button under the select and I want it inline.

Thank you in advance.

**Comment by jandayanan** [comment]
I use the following snippet for inline icons. But there is a problem (see #1034)

                            <div class="col-md-3">
                                <div class="input-group ">
                                    <select class="form-control selectpicker">
                                        <option value="">An Option</option>
                                        
                                    </select>
                                    <a class="input-group-btn btn btn-success" href="#">
                                        <i class='fa fa-refresh'></i>
                                    </a>
                                </div>
                            </div>

**Comment by caseyjhol** [comment]
bootstrap-select should now work inside btn-group.
