### ISSUE TITLE
Bootstrap-Select and Jquery Validation option check

### ISSUE THREAD

**Issue by Khrysller** [snapappointments/bootstrap-select#1223]
I am using Bootstrap with Bootstrap-Select and Jquery Validation. I am facing the following issue:
- In the select with Bootstrap-Select, when there is no selected option and I click in Filter, the selectbox changes to red (desired behavior), and after if I select any option it should go to the default state (blue).
- In the selectbox without the Bootstrap-Select it works.

https://jsfiddle.net/0q5qz3hp/

http://stackoverflow.com/questions/34089048/bootstrap-select-and-jquery-validation-option-check

Any help on this?

**Comment by caseyjhol** [comment]
First, use the newest version of bootstrap-select (you're using v1.6.5 in your example). Also, for some reason, jQuery Validation uses `blur` instead of the `change` event to trigger `unhighlight`.

This snippet should work:

```js
$('.selectpicker').on('change', function() {
    var $el = $(':focus');
    $(this).blur();
    $el.focus();
});
```

**Comment by dmitrychuba** [comment]
Here is simple solution which worked for me:
`
    var validator = $('#myForm').validate({
        .
        .
        .
    });
  
    $('select.select-field').on('change', function () {
        validator.element($(this));
    });
`  
That's it

**Comment by matmiranda** [comment]
Thank you @caseyjhol problem fixed.
