### ISSUE TITLE
live-search + iphone 6 bug. 

### ISSUE THREAD

**Issue by slavchic** [snapappointments/bootstrap-select#1224]
The drop-down menu automatically disappears and selects some value when I click on search input. 
Also, if you select something (without using of search) the plugin selects a wrong item 
- check this ani-gif from "true" iphone simulator: 
  ![](http://i.imgur.com/w0PkoVM.gif)

**Comment by nixonmedia** [comment]
Any fix for this yet? This isn't specific to iphone 6. It also happens on iphone 5. Live search doesn't work at all on iphones. Can you address asap?

**Comment by nixonmedia** [comment]
For what it's worth, this issue is resolved in iOS 9.2.
