### ISSUE TITLE
select picker - Don't grab half of my $_POST on phones...

### ISSUE THREAD

**Issue by ZombienDK** [snapappointments/bootstrap-select#1225]
Well i have run into an issue i really can't find a solution to...

I have a huge form with alot of select inputs, this works fine on the desktop

the following get by print_r($_POST) "Desktop";  
array(25) { ["mainarea"]=> string(8) "settings" ["whatTODO"]=> string(12) "save_profile" ["id"]=> string(6) "274456" ["strEmail"]=> string(20) "my@mail.dk" ["intDay"]=> string(2) "29" ["intMonth"]=> string(2) "08" ["intYear"]=> string(4) "1984" ["ridGender"]=> string(1) "1" ["ridArea"]=> string(1) "7" ["intPostcode"]=> string(4) "8800" ["ridLookingFor"]=> string(1) "1" ["ridLookingFor2"]=> string(1) "1" ["intHeight"]=> string(3) "191" ["intWeight"]=> string(2) "83" ["ridPartnerStatus"]=> string(0) "" ["ridHairColor"]=> string(0) "" ["ridEyeColor"]=> string(0) "" ["ridBodyBuild"]=> string(0) "" ["ridSmoker"]=> string(0) "" ["ridChildren"]=> string(0) "" ["ridEducation"]=> string(0) "" ["ridBusiness"]=> string(0) "" ["ridMusic"]=> string(0) "" ["ridStarsign"]=> string(0) "" ["ridTattoo"]=> string(0) "" } 

this is what i get on the phones
array(25) { ["mainarea"]=> string(8) "settings" ["whatTODO"]=> string(12) "save_profile" ["id"]=> string(6) "274456" ["strEmail"]=> string(20) "my@mail.dk" ["intDay"]=> string(2) "29" ["intMonth"]=> string(2) "08" ["intYear"]=> string(4) "1984" ["ridGender"]=> string(1) "1" ["ridArea"]=> string(1) "7" ["intPostcode"]=> string(4) "8800" ["ridLookingFor"]=> string(1) "1" ["ridLookingFor2"]=> string(1) "1" ["intHeight"]=> string(3) "191" ["intWeight"]=> string(2) "83" } 

my selectboxes looks the same, besides change of name and data-header
<select name='ridPartnerStatus' class='selectpicker' title='Vælg venligst' data-width='100%' data-dropup-auto='false' data-header='Partnerstatus' data-style='btn-warning'>

and i have added after it loads the boottrap-select.js
if( /Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent) ) {
$('.selectpicker').selectpicker('mobile');
}

if i force it to use selectpicker without the mobile setting it post the form correctly with all the inputs...

and do i remove the selectpicker class it also post the input field...

so what can be wrong in the $('.selectpicker').selectpicker('mobile');? and making this conflict so it drops the alot of the $_POST variables?

**Comment by caseyjhol** [comment]
Try it again with the latest version in `master` and let me know if you have different results.

**Comment by ZombienDK** [comment]
I have just updated Bootstrap-select v1.7.2 to Bootstrap-select v1.8.1

Sadly this did'nt solve my issue, since it still cuts off half the $_POST variabel when using the $('.selectpicker').selectpicker('mobile');

got 13 select boxes right after each orther, but that should'nt be a problem right?

**Comment by holtkamp** [comment]
@ZombienDK what about the newer https://github.com/silviomoreto/bootstrap-select/releases/tag/v1.12.2 ?

**Comment by NicolasCARPi** [comment]
@caseyjhol This can be closed. Reason: author didn't provide feedback with new version.
