### ISSUE TITLE
Select title not working

### ISSUE THREAD

**Issue by shails** [snapappointments/bootstrap-select#1246]
I have been trying to insert title to my dropdown but its not working . 
$form->addOption('destination-group','choose','choose','','class=bs-title-selected=selected');
$form->addOption('destination-group', 'USA', 'USA', 'Hill Stations');

The empty title is not getting inserted before my other select options ..
Any suggestions?

**Comment by NicolasCARPi** [comment]
@caseyjhol this can be closed. reason: old support with no answers, OP probably moved on 6 years later.
