### ISSUE TITLE
How to disable the "space" key select me a choice?

### ISSUE THREAD

**Issue by JamesChe91** [snapappointments/bootstrap-select#1249]
Sorry for the english, but I need disable this, because when a selectpicker do a postback, it's annoying that when searching for an option and I press space then the item is selected

**Comment by junnykx** [comment]
I've the same problem here. Ajax is working gracefully with selectpicker. But when the user is searching for something and press the _space key_, selectpicker automatically select an item and close the list and searchbox. Anyone know a fix for it?

**Comment by JamesChe91** [comment]
What I did was look for this
$ (Document) .data ('spaceSelect'), true);
and change it to
$ (Document) .data ('spaceSelect'), false);

In the file .min not work for me, then what I did was modify the other and use any tool to change it to .min

**Comment by junnykx** [comment]
Well, this really works! Thanks. This fix is already in bootstrap-select.js and bootstrap-select.min.js, but don't work with min.js. Awful...

**Comment by JamesChe91** [comment]
just use a tool like this http://jscompress.com/ with the bootstrap-select.js and this will generate the .min.js file
