### ISSUE TITLE
double initilization

### ISSUE THREAD

**Issue by vlllad** [snapappointments/bootstrap-select#1259]
Hi, 

I'm having some problem when i try to load instantiate the selectpicker on a popup window. The first time i open the popup its generated correct. But the second time it get's generated again. I don't know hoe to prevent that. I tried to destroy it when i close the popup, but then it will not be generated alt all. I will attach a video with the issue.

http://screencast.com/t/fJbEbTNlja

Thanks!

**Comment by machadolab** [comment]
I'm having the same issue with an app that dynamically adds content to the dom. Seems like it is not handling this case well.

**Comment by pasevin** [comment]
experiencing same issue, did anyone managed to overcome this?

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by doggkruse** [comment]
I ran into this same issue when loading dynamically.  The solution I found was to add  `data-enhance="false" ` to a wrapping div and then call ` $('select').selectpicker();` once the content is loaded.
