### ISSUE TITLE
selectpicker('val', STRING_WITH_SPACES) does not work as expected

### ISSUE THREAD

**Issue by xennygrimmato** [snapappointments/bootstrap-select#1277]
`$("#multiselect_profile").selectpicker('val', 'Windows drv word');`
It seems that when I pass a string containing spaces to selectpicker('val', ...), the functions splits the word by spaces and then searches for that value in the dropdown to mark it as selected.
I want to select the _exact_ string in the multiple select. Am I missing something here, or this is the way 'val' is implemented here?

**Comment by caseyjhol** [comment]
Hrmm...I'm considering removing the val function, as I'm starting to question its usefulness.

I recommend the following:

```js
$("#multiselect_profile").val('Windows drv word').selectpicker('render');
```

**Comment by Nikolko10** [comment]
dgb

**Comment by caseyjhol** [comment]
I can't recreate this issue on my end. I'd recommend using `.selectpicker('val', ['Windows drv word'])` if you are unable to use my previous suggestion.
