### ISSUE TITLE
bootstrap ui-select height variation

### ISSUE THREAD

**Issue by alaksandarjesus** [snapappointments/bootstrap-select#1278]
Hi..i am using bootstrap select version - 1.9.3

On my initial page load the dropdown height is perfect. When i select an item from dropdown, an ajax call i made and a dynamic table is created.

On the same, the dropdown height is also increased along with the body height. 

How can i fix the height of the bootstrap-select independent of the body height.

Thanks.

**Comment by NicolasCARPi** [comment]
@caseyjhol can be closed: old support issue.
