### ISSUE TITLE
Cloned bootstrap-select:displays twice in the form when using "refresh".

### ISSUE THREAD

**Issue by sebint** [snapappointments/bootstrap-select#1285]
Hai,
 I was including the bootstrap-select in the table rows, and i wanna clone the last row for a new row creation..and everything is working fine other than the bootstrap-select. Then i used `$(".selectpicker").selectpicker('refresh');` then when a new row is created it displays twice and the first one is not working but the second one is working. How do i get rid of the first one..
i am including the code here..please help.
 ```js
$(".selectpicker").selectpicker(); //initialized on load
$(".addRow").click(function(){
    var $tr=$(".tb1 tr.row_active_entry");
    var $clone=$tr.clone();
    $clone.find('input:text').each(function() {
        $(this).val('');
    });
    $tr.after($clone);
    $(".selectpicker").selectpicker('refresh');//refreshing after creating new row
    $tr.removeClass();
});
```

**Comment by JanMlcoch** [comment]
Same problem here

**Comment by douglott** [comment]
You may have solved this already or moved on to another solution but I just came up against the same issue.  To solve this, I do not clone the post-rendered HTML selectpicker.  This (frustratingly) does not work.  

I instead clone an element that contains one or more select elements without the selectpicker class.  After cloning, I add a unique ID (not required) and the 'selectpicker' css class (required) and then call refresh.  This renders as expected with no duplicates.

**Comment by NicolasCARPi** [comment]
Closing as workaround is provided.
