### ISSUE TITLE
Warning: Fluxible client and server HTML is diff

### ISSUE THREAD

**Issue by sinkcup** [snapappointments/bootstrap-select#1293]
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) arch="true" multiple name="id"
 (server) arch="true" multiple="" name="id"

**Comment by NicolasCARPi** [comment]
@caseyjhol this can be closed because it's old and lacking information/reproducibility, also it seems to be react specific thing which I'm sure changed a lot in 5 years.
