### ISSUE TITLE
New feature option[data-header] as [data-divider]

### ISSUE THREAD

**Issue by vsn4ik** [snapappointments/bootstrap-select#1325]
`<option data-header="true">...</option>` -> `<li class="dropdown-header">...</li>`.

BS3: https://getbootstrap.com/docs/3.3/components/#dropdowns-headers
BS4: https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-headers

**Comment by caseyjhol** [comment]
Seems like it might just make more sense to use an optgroup, no?
