### ISSUE TITLE
bootstrap-select in input-group problem

### ISSUE THREAD

**Issue by bardware** [snapappointments/bootstrap-select#1329]
I switched from bootstrap-select v1.6.5 to v1.10.0 and the initially selected element was no longer visible in Firefox browser. I added the following code to make it appear:

```
.bootstrap-select > .dropdown-toggle {
width: auto;
}
```

The old hacks from Issue #618 did not work any longer

**Comment by caseyjhol** [comment]
Should be fixed in v1.13.7 (if not earlier).
