### ISSUE TITLE
Select shows twice in a Bootstrap Modal

### ISSUE THREAD

**Issue by abdhass** [snapappointments/bootstrap-select#1353]
When using latest 1.10, in a modal view, 2 selects show. one formatted and one non-bootsratp-formatted

Any ideas?

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by swapnilchincholkar** [comment]
+1

**Comment by abdhass** [comment]
Sorry about the reduced bug i submitted. I ended up just using a older version. But when i get some time, i will try and send over a demonstrable bug.

**Comment by roks82** [comment]
![twice](https://cloud.githubusercontent.com/assets/9000485/14956897/785863c4-1082-11e6-8111-401df304f5f8.jpg)
I have the same issue...

**Comment by predatorkill** [comment]
i'm getting the same  too, using the latest version

**Comment by rishadbharucha** [comment]
Make sure the CSS file is correctly imported. That fixed the issue for me.
