### ISSUE TITLE
Bootlint raises error E042 on bootstrap-select

### ISSUE THREAD

**Issue by hugo42** [snapappointments/bootstrap-select#1372]
Hi everyone,

I am trying to test an UI (inside a rails app) where I use both simple_form, bootstrap and bootstrap-select. In my tests I launch a cucumber step which run bootlint linter on each page of my app and check it doesn't raise any error. 

> For rails user I have a config/initilizers/simple_form_bootstrap.rb with a specific form wrapper containing: `wrapper.use :input, class: 'form-control'`
> 
> By this way all of my form inputs has the right width and alignment. The problem come when I use a `f.input :test, collection: [...], label: ...` in my view.

So bootstrap-select with `$('.select').selectpicker();` transforms a valid bootlint DOM element:

 `<select id="..." class="select optional form-control" name="...">`  

to:

```
<div class="btn-group bootstrap-select select optional form-control">
  <button class="btn dropdown-toggle btn-default" data-toggle="dropdown" type="button" data-id="..." title="Nothing selected"></button>
  <div class="dropdown-menu open"></div>
  <select id="..." class="select optional form-control" name="..." tabindex="-98"></select>
</div> 
```

This div raises bootlint's E042 error which means that only an input, a textarea or a select can take the .form-control class.

I didn't find a way to configure bootstrap-select as bootlint expected (by myself and in the doc) so I disabled this error in my tests to let them succeed. I don't know if this is a bug or a bad implementation but let me know if I'm doing something wrong.

**Comment by yld** [comment]
We've similar problem with a disabled select. It doesn't succeed the Bootlint (https://github.com/twbs/bootlint) tests with this warning:
```
"bootlint: " " W016 " "Using the `.disabled` class on a `<button>` or `<input>` only changes the appearance of the element. It doesn't prevent the user from interacting with the element (for example, clicking on it or focusing it). If you want to truly disable the element, use the `disabled` attribute instead.
" Object { 0: <button.btn.dropdown-toggle.disabled.btn-default>, length: 1, prevObject: Object, context: HTMLDocument → new, selector: "button.btn.disabled, input.btn.disa…" }
```

**Comment by caseyjhol** [comment]
The `form-control` class needs to be copied over to the parent element to keep styling consistent. There's nothing inherently wrong with having the class on a non-form element, so it's best to ignore the error and adjust your configuration.
