### ISSUE TITLE
Dropdown duplicates if select-element is replaced

### ISSUE THREAD

**Issue by matthiasbraun** [snapappointments/bootstrap-select#1385]
After the select element is replaced using the jQuery replaceWith method, calling selectpicker("refresh") causes a duplicate dropdown to show up. It is nested into the markup of the original dropdown button.

See this [jsfiddle](http://jsfiddle.net/zh0v1k04/18/).

Using the replaceWith method is mandatory for me because I use bootstrap-select in combination with Apache Wicket.

**Comment by matthiasbraun** [comment]
Is there anything I can do to help this getting fixed? I would really appreciate integrating bootstrap-select into our product.

**Comment by caseyjhol** [comment]
Try calling `$(".selectpicker").selectpicker("destroy");` before you use replaceWith.
