### ISSUE TITLE
ajax load selectpicker  wrong title

### ISSUE THREAD

**Issue by al404** [snapappointments/bootstrap-select#1387]
I load with jQuery load function an HML block containing a select that has the select picker class
i don't get any JS error in console, i try to addd  data-live-search="true" and i can find the search field that works

but title is set to first option element, is not getting the title from  attribute
i add the same code inside the page the title is correctly set

i also try to add a 

$('.selectpicker').selectpicker('refresh');

after load event is completed but did not fix it

**Comment by NicolasCARPi** [comment]
Please try latest version.
