### ISSUE TITLE
Doesn't work with Ember.js

### ISSUE THREAD

**Issue by theworkerant** [snapappointments/bootstrap-select#140]
Although this may not be a concern for you library, I was hoping for some insight into the problem. Basically, Ember.js takes control of it's view objects in a way that prevents bootstrap-select from working.

See my question on stackoverflow: http://stackoverflow.com/questions/16566700/integrating-bootstrap-select-to-work-with-ember

And JSFiddle: http://jsfiddle.net/TheWorkerAnt/8d2Me/1/

Cheers

**Comment by zekefast** [comment]
Guys, have you look at [ember-cli-select-picker](https://www.npmjs.com/package/ember-cli-select-picker)? It might be what you are looking for.

**Comment by zekefast** [comment]
I think integration with ember should not be a direct dependency of bootstrap-select, rather a separate project.

**Comment by caseyjhol** [comment]
I never familiarized myself with Ember, but it seems like, at least with version 1.13.13, bootstrap-select is working. https://plnkr.co/edit/YSOoGrRcffaLqSFy
