### ISSUE TITLE
title attribute disabled by jquery-migrate

### ISSUE THREAD

**Issue by agent-617** [snapappointments/bootstrap-select#1409]
When utilizing jquery-migrate, the title attribute is disabled.
Neither:
`<select class="selectpicker show-tick form-control" title="Select...">`
nor
`$('.selectpicker').selectpicker({
        title: "Select...",
});`
will render if `<script src="jquery-migrate-1.xx.js"></script>` is utilized in the stack.

**Comment by Micmaz** [comment]
I changed line 564 to:
if (element.options[element.selectedIndex].outerHTML.includes(" selected")) titleOption.selected = true;

This makes the title appear all the time except if an item is marked "selected" in the html. This may break other things so I won't make it a patch.

**Comment by NicolasCARPi** [comment]
Also the migrate plugin should not be used in production, it is there to help you spot migration issues.
