### ISSUE TITLE
Play well with Ractive

### ISSUE THREAD

**Issue by tugrulkukul** [snapappointments/bootstrap-select#1428]
Is there anyway to make the `<select>` work inside Ractive template? https://jsfiddle.net/z6kef166/1/

**Comment by ceremcem** [comment]
Edited to prove that Ractive is working: https://jsfiddle.net/ceremcem/y3m44t8y/1/

**Comment by NicolasCARPi** [comment]
@caseyjhol can be closed as a working solution was provided.
