### ISSUE TITLE
dropup class doesn't function correctly

### ISSUE THREAD

**Issue by lmj0011** [snapappointments/bootstrap-select#1430]
I have a problem getting dropup to work. (demo doesn't display dropup working, which isn't helpful)
https://silviomoreto.github.io/bootstrap-select/examples/#dropup-menu

tried the solution in this issue, and it didn't work: 
https://github.com/silviomoreto/bootstrap-select/issues/1050

I also tried with JQuery, and dropup still doesn't take effect:
`$('#selections').data("dropupAuto",false).addClass('dropup');`

**Comment by shakeycal** [comment]
Believe that the documentation is wrong on this, the dropup class should be on the parent/container, not the <select> itself.

**Comment by caseyjhol** [comment]
Using `data-dropup-auto="false"` in conjunction with applying the `dropup` class on the select element is working for me. If you you can provide an example proving otherwise, I'll reopen.

**Comment by Fabjooo** [comment]
@caseyjhol Yes this works for me too. Thanks a lot :)

**Comment by philipreichen** [comment]
It's not working for 1.13.14. because Popper is autopositioning the menu (regardless of dropup settings). Setting data-display="static" on your select element (in addition to data-dropup-auto="false") should prevent this from happening.
