### ISSUE TITLE
How to unselect and show only the title by default value ?

### ISSUE THREAD

**Issue by Rhend** [snapappointments/bootstrap-select#1433]
Hi,

I need to unselect my component on a click event but i don't know how to do this with this plugin ?

**Comment by caseyjhol** [comment]
What exactly are you trying to do?

**Comment by luk4szm** [comment]
Hi,
I have exactly the same problem. Got a form with many select inputs. At the first moment user have input without selected any option. When he will select some option there is no possibility to cancel it. We have to reload page to get "clean input". Is there any option to unselect component?

**Comment by TomKrakott** [comment]
Hi,
Same problem for me ... How to permit to unselect an option in a non-multiple select ?
We just could add an option with empty value so it's very awful.
Thanks

**Comment by sbourdette** [comment]
Same here

**Comment by NicolasCARPi** [comment]
See deselectAllText with actionbox.
