### ISSUE TITLE
refresh method not working with dynamically added elements

### ISSUE THREAD

**Issue by helloromero** [snapappointments/bootstrap-select#1438]
Hey,

When I dynamically add a new select div to the dom the newly added element doesn't work. The refresh method doesn't seem to have any effect.

Do you know whats going wrong?

**Comment by judimator** [comment]
Hello, Do you solve yout problem? I have the same situation.

**Comment by heyrm** [comment]
@judimator  nope, I am still waiting on an answer. If I find one I will post it here.

**Comment by judimator** [comment]
Ok, thanks a lot. For now I just use common bootstrap select:)

**Comment by amitsquare** [comment]
Hi Guys ,

Below given function can be used to "Add"/"Replace"/"Remove" Options in the existing Element .
Then simply replace received Element with element on which modification been done .



el :-- Clone of existing Bootstrap-select Element .
Choice :-- "add"/"all"/"remove"
options :-- normal value if(choice == "add" || choice == "remove") else Array 
 

`function selectPickerApiElement(el,choice,options){
    $(el).find('select').selectpicker() ;
    $(el).children().eq(2).siblings().remove() ;
    if(choice == "add"){

        $(el).find('.selectpicker').append("<option>"+options+"</option>") ;

    }else if(choice == "all"){
    $(el).find('.selectpicker').children().remove() ;
    for(var i = 0 ; i <options.length ; i++){
        $(el).find('.selectpicker').append("<option>"+options[i].key+"</option>") ;
    }        
    }else if(choice == "remove"){
        var selectOptionsLength = $(el).find('.selectpicker').children().length ;
        for(var i = 1 ; i <= selectOptionsLength ; i++){
            if(options == $(el).find('.selectpicker').children().eq(i).val()){
                $(el).find('.selectpicker').children().eq(i).remove() ;
                break ;
            }else{
                continue ;
            }

        }
    
    }
    $(el).find('select').selectpicker('refresh') ;
    return $(el).children().first().unwrap() ;


}`

**Comment by judimator** [comment]
Hi, but it can't work, at least for me:(

**Comment by amitsquare** [comment]
Can you give me sample code to dig out ?

As it is working fine for me !! 
hope below given JSFiddle will help you out .

https://jsfiddle.net/amitsqure/jeusqvkq/

**Comment by judimator** [comment]
Thanks! I forgot clone needed element!

**Comment by HoBi** [comment]
Can't you just use use `$('.selectpicker').selectpicker('refresh');` on each change - and add it to the end of your selectpicker code section, e.g.:

```
// some other handlers

$(document).on('change', '.selectpicker', function () {
    $('.selectpicker').selectpicker('refresh');
});
```

This works for me. :-)

**Comment by JenHa** [comment]
Hey togehter, 
I have the same Problem now. Did you found any solution on this? 
I'm adding new selects (complete new selects itself, not only new options like in the fiddle @amitsquare  provided ). Refresh only works on existing elements.

**Comment by dragipostolovski** [comment]
@tenhobi thank you, it works :)

**Comment by douglott** [comment]
You may have solved this already or moved on to another solution but I just came up against the same issue.  To solve this, I do not clone the post-rendered HTML selectpicker.  This (frustratingly) does not work.  

I instead clone an element that contains one or more select elements without the selectpicker class.  After cloning, I add a unique ID (not required) and the 'selectpicker' css class (required) and then call refresh.  This renders as expected with no duplicates.

**Comment by mwaleedraza** [comment]
$("myComboBoxSelector").data('combobox').refresh()
Run this after updating the List otherwise it will not show the updated list.

**Comment by al-hassan-cse** [comment]
@tenhobi not working..............please other any idea

**Comment by umayrh** [comment]
@alhassancse try this https://github.com/snapappointments/bootstrap-select/issues/2456#issuecomment-1262477101

**Comment by mrunalpittalia** [comment]
@umayrh ,

doing destroy & render shows updated options, but removes attached working events like, changed.bs.select , etc...
