### ISSUE TITLE
First call is 4-8x slower than following calls

### ISSUE THREAD

**Issue by birjolaxew** [snapappointments/bootstrap-select#1462]
The first time you call `.selectpicker()` on an element, it takes between 40 and 80 ms to complete (on my machine). Subsequent calls take ~10 ms. This seems to be reset occasionally (namely on user input, eg. clicks), giving you to 40-80 ms time again.

[Example JSFiddle](https://jsfiddle.net/scmn4L05/2/) (with removed V8 optimization)

![Results](https://cloud.githubusercontent.com/assets/4542461/17518923/1e0afbd2-5e4a-11e6-9a8e-6d71244b8aa3.png)

The following shows the timeline for two bootstrap-selects being created (first a 40ms one, then a 10 ms one), taken from [this JSFiddle](https://jsfiddle.net/g3c630am/1/):
![Timeline (slow)](https://cloud.githubusercontent.com/assets/4542461/17518219/4e842d2c-5e47-11e6-8f28-5f2af46f4a05.png)
![Timeline (quick)](https://cloud.githubusercontent.com/assets/4542461/17518197/310ce806-5e47-11e6-8405-e48524687d28.png)

For reference, `clickListener` (near the middle) stays almost the same (1.5ms -> 1ms).
Notably the `createLi` function drops from 8ms to 1ms, `render` from 6ms to 1ms and various other functions drop a fair bit too.

_Why_ this happens is beyond me, but as 50ms is a lot for something as "simple" as this, I'd think it would be worth it to look into optimizing the relevant functions.

If you want to load the timeline in your own dev tools (F12 > Timeline > Right click > Load timeline data...), the JSON is available [here](https://gist.github.com/birjolaxew/022431944cea6f742234e6989c55ba94).

**Comment by caseyjhol** [comment]
Performance issues have been addressed in recent versions. Please let me know if you're still encountering issues.
