### ISSUE TITLE
Simple/Multiple select pagination on dropdown options

### ISSUE THREAD

**Issue by sauldeleon** [snapappointments/bootstrap-select#1480]
Hi!

As an idea it would be great to have pagination(if it is possible) inside a multiple select.

In my case, I'm using a multiple select where a user is able to select multiple actions to asign it for a specific role, and there are more than 100 actions.

We have added the live search and the limit to show the scroll, but I have thought that a pagination in the dropdownlist and show 10 by 10 actions or something similar would be great, or maybe some aproach?

Thanks!

Regards,

Saúl

**Comment by plouismarie** [comment]
Large list in a dropdown menu can behave very slowly - 10 by 10 pagination would make things smoother to handle.

**Comment by caseyjhol** [comment]
@plouismarie Large lists are handled differently in v1.13.0+, and should be very fast. Pagination on a dropdown menu seems like poor UX to me. I'd probably implement something like #2084 before this, unless there was a lot of support.
