### ISSUE TITLE
Exact word match

### ISSUE THREAD

**Issue by vicentor** [snapappointments/bootstrap-select#1482]
Is it possible for the liveSearch to apply on exact words (words being separated by spaces)?
When I type "25" it finds "blabla 25 and "blabla 255", but we'd like it to only find the first choice.
In the opposite, "255" would find "blabla 255" only.

Does this make sense?
Any idea?

**Comment by moerg** [comment]
BUMP

**Comment by moerg** [comment]
BUMP

**Comment by NicolasCARPi** [comment]
That would mean having an option `fuzzyMatch: false` I guess.

**Comment by NicolasCARPi** [comment]
See liveSearchStyle with value 'startsWith'
