### ISSUE TITLE
Dropdown option width issue in ipad

### ISSUE THREAD

**Issue by shainanand** [snapappointments/bootstrap-select#1487]
I have long texts for dropdown options. When I use bootstrap select, the dropdown options extends the viewport and causes design issue.

**Comment by Benjamin-Lee** [comment]
I am having this issue on iPhone as well. I tried setting the width with `data-width` but that only changes the width of the select, not the dropdown. Would appreciate a fix or guidance in case I'm doing something wrong.

**Comment by bulabula001** [comment]
i have this problem too,  have you solve it  ?   could you help me about this ?
tks & bestregards

**Comment by NicolasCARPi** [comment]
Please try with latest version.
