### ISSUE TITLE
maxOptions not working for mobile

### ISSUE THREAD

**Issue by grazziotin** [snapappointments/bootstrap-select#1494]
Not sure if this a known issue, I could not find anything related anywhere.

I cant get the maxOptions option to work when I enable mobile menus.

Also cant get

$('#mySelect').on('changed.bs.select', function (e)

to work on mobile.

For desktop it is all working fine, not sure if there is any option I should be using?

Thanks,

**Comment by j-ma** [comment]
I also have the same issue for maxOptions where when I enable mobile scrolling for mobile views, it completely ignores the data options like maxOptions and header but it works when I'm on desktop view (where data-mobile="false").

Did you ever figure out a solution?

**Comment by NicolasCARPi** [comment]
> Did you ever figure out a solution?

We will never know!
