### ISSUE TITLE
Single select have differ behavior then system selectbox

### ISSUE THREAD

**Issue by meesha81** [snapappointments/bootstrap-select#1495]
Hi,

I would like to give you idea about behavior of single (=not multiple) select picker with "tab" key leaving.
1. Expand select picker options 
2. With arrows move cursor to different option
3. Press tab to leave select picker. 

Current:
After leave select picker with tab, ORIGINAL option will be selected, not the focused one.

System selectbox behavior:
After move option focus via arrows, focused option will be as selected after TAB pressed. So the selected is FOCUSED option via arrows.

System selectbox differs option focus after arrow up/down pressed and mouse over focus.

Best regards,
Michal

**Comment by caseyjhol** [comment]
You'll want to enable `selectOnTab` if you want that functionality. But I agree, in the next major release selectOnTab should be true by default, since that most closely resembles standard select functionality.

**Comment by NicolasCARPi** [comment]
See #2618
