### ISSUE TITLE
Tooltip bootstrap

### ISSUE THREAD

**Issue by plewasebastian** [snapappointments/bootstrap-select#1497]
How to display bootstrap tooltip in bootstrap-select?
If i add data-goggle='tooltip' and data-title='Title' to select with .selectpicker it wont work.
What should I do to make it work?

**Comment by arajadurai69** [comment]
Hi @l0pez I am also facing this issue, did you find any solution for this issue?

**Comment by NicolasCARPi** [comment]
Closing as duplicate of #1830
