### ISSUE TITLE
How get clicked select option in multiple?

### ISSUE THREAD

**Issue by Rafsonic** [snapappointments/bootstrap-select#1564]
Hello guys.. I have a multiple select and I want to get the clicked option value. No all of them... I have tried many ways but nothing works...

**Comment by eladgilboa** [comment]
$('selector').val() 
it return Array if multiple set to true else a string.

**Comment by mickster04** [comment]
is that deliberate? shouldn't it always return an array?

**Comment by LukeMcLachlan** [comment]
Isn't Rafsonic looking for the latest clicked option value, i.e. the value of the option that was selected? He did write "No all of them". Currently clickedIndex is returned on the event changed.bs.select, but this isn't the value of the actual select option.

**Comment by mhordii** [comment]
Found solution here - [stackoverflow.com](https://stackoverflow.com/questions/36944647/bootstrap-select-on-click-get-clicked-value)

Some modification:
```js
$(".selectpicker").on("changed.bs.select", function(e, clickedIndex, newValue, oldValue) {
   var sel = $(this).find('option').eq(clickedIndex).val();
   console.log(sel+" "+newValue);
});
```
