### ISSUE TITLE
bootstrapselect doesn't work on biult-in browser on Android (7)

### ISSUE THREAD

**Issue by napster1991** [snapappointments/bootstrap-select#1569]
my site (asp.net mvc based) is using bootstrapselect. It works fine on desktop browsers (Opera, Chrome, Firefox, etc), but it doesn't work on mobile browser. OS: Android 7.0, browser: built-in Chrome.

Details:
I click select button then drowdown-list appears, but when I select some option then drowdown disappears and the option doesn't become selected as if I clicked somewhere out of drowdownlist.
See: http://aore.uz/Home/TermsAndConditions

**Comment by caseyjhol** [comment]
Are you able to reproduce this issue here? http://silviomoreto.github.io/bootstrap-select/examples/

**Comment by napster1991** [comment]
I have solved it. The problem was in z-index css attribute. It was lower then needed. I have encreased it and vualya!
