### ISSUE TITLE
Used by

### ISSUE THREAD

**Issue by xoriatis** [snapappointments/bootstrap-select#1572]
Dear Silvio,
Great code. We're currently redeveloping our three brands using bootstrap-select:
www.storagecollect.co.uk
www.studentstoragebox.co.uk
www.onestopworldwide.com

Could you add each brand to your page at: https://silviomoreto.github.io/bootstrap-select/ please?

Logos attached!

All the best,
Alexander
![logo](https://cloud.githubusercontent.com/assets/24281437/20774329/cf09f6ca-b74d-11e6-9cbe-f333216d8629.png)
![logo](https://cloud.githubusercontent.com/assets/24281437/20774347/d8d09dee-b74d-11e6-8775-e9457d7a6ab0.png)
![logo](https://cloud.githubusercontent.com/assets/24281437/20774361/e660a2a6-b74d-11e6-8f18-69002e2a0587.png)

**Comment by caseyjhol** [comment]
Thank you for your support of bootstrap-select! Unfortunately, we are discontinuing the "used by" section.
