### ISSUE TITLE
Custom Icon Along with TITLE

### ISSUE THREAD

**Issue by TheSayantan96** [snapappointments/bootstrap-select#1574]
Is there a way to add font-awesome icons or glyphicons along with the title attribute only?I mean we can use data-icon to add icon along with options but I want to show icon with the title only!!!please help!!!!!!  
Actualy I want Zomato style location searchbar...

**Comment by rishitank** [comment]
+1

**Comment by SOSkr** [comment]
+1

**Comment by mikeploeger** [comment]
It was possible v. <1.13.6 via inline html title="<I class="youriconclasses"></I>".

But since 1.13.6 its broken.

See this for more information:
https://github.com/snapappointments/bootstrap-select/issues/2388

**Comment by NicolasCARPi** [comment]
Closing as duplicate of #2388
