### ISSUE TITLE
CSS styling. Need to add this in css.

### ISSUE THREAD

**Issue by agelbess** [snapappointments/bootstrap-select#1578]
```
.bs-deselect-all {
	overflow: hidden;
}
```

**Comment by holtkamp** [comment]
Can you explain why? What does it? Maybe you can add screenshots of the situation before and after adding it?

**Comment by agelbess** [comment]
Hi,

When the deselect all button is used with custom text, the text is rendered outside the button.
Please check [https://jsfiddle.net/bdgg58tv/1/](https://jsfiddle.net/bdgg58tv/1/)
Maybe the same applies to other buttons too.
With overflow:hidden the text will be trimmed.

Hope I helped.

Regards,
*Alex*

**Comment by NicolasCARPi** [comment]
> With overflow:hidden the text will be trimmed.

Which doesn't seem a good behavior to me. Is this still an issue in latest version?
