### ISSUE TITLE
input Event is missing

### ISSUE THREAD

**Issue by mafar** [snapappointments/bootstrap-select#1582]
bootstrap-select is missing 'input' event which is provided by jquery.

**See this fiddle:** https://jsfiddle.net/bababalcksheep/0safnvmL/9/
```input event``` is triggered when you change ```select``` and it is # NOT  a ```select-picker```

**See this fiddle:** https://jsfiddle.net/bababalcksheep/0safnvmL/8/
```input event``` is not triggered when you change ```select``` and it is a ```select-picker```

**Comment by djangosdk** [comment]
also changed.bs.select is triggered twice when a select-picker is change
```
$('.picker').on('changed.bs.select', function (e) {
 console.log('changed.bs.select deteced');
});
```

**Comment by djangosdk** [comment]
Ok now it triggers once
```
$('select.picker').on('changed.bs.select', function (e) {
 console.log('changed.bs.select deteced');
});
```

**Comment by djangosdk** [comment]
to fix this, I had to do this but this should be part of this awesome library
```
$('select.picker').on('changed.bs.select', function (e) {
  $(this).trigger('input');
});
```

**Comment by caseyjhol** [comment]
Please 👍 and follow #1305.
