### ISSUE TITLE
SelectPicker not working on mobile device Sony Xperia Tipo

### ISSUE THREAD

**Issue by calintritean** [snapappointments/bootstrap-select#1591]
First, this plugin is great. But I believe you hear this a lot ; )

Unfortunately, one of my clients is using Sony Xperia mobile phone and when trying to select any of the options from the drop down list, the value is not updating and the default option remains selected. 

You can check this URL https://silviomoreto.github.io/bootstrap-select/examples/ , any example from this page. 

If you check the attached image, you can see that Ketchup is selected, but Mustard is visible there. You can also select Relish, but Mustard will keep being visible. 

Really glad if you could fix this or guide me in the correct direction and will try to solve this.

Thank you. 

<img width="243" alt="screen shot 2016-12-15 at 16 30 26" src="https://cloud.githubusercontent.com/assets/5718977/21227732/d4e36288-c2e3-11e6-8d59-0a59accf755c.png">

**Comment by calintritean** [comment]
Hi @caseyjhol , any news regarding this bug? I tried to fix it but I can't seem to find a solution.

Thank you.

**Comment by nexus9988** [comment]
Hey @calintritean checkout @caseyjhol solution 
https://github.com/silviomoreto/bootstrap-select/issues/1058

Personally I would have liked this to be an automatically integrated feature where you can enable or disable mobile but perhaps its in a future release.

**Comment by NicolasCARPi** [comment]
By now your client has changed phone -> issue fixed! :p
