### ISSUE TITLE
form-inline -> Form-control and selectpicker conflict?

### ISSUE THREAD

**Issue by mickster04** [snapappointments/bootstrap-select#1599]
I have inline form with 1 select picker and one text box
https://jsfiddle.net/k8aqr99g/

Basically I would like the dropdown to resize like the default bootstrap inputs doo when the sceensize changes.

if you look at the jsfiddle above and resize the output window so that the form goes to inline and back. you can see how the normal bootstrap one resizes correctly and how the select is either always big or always small...

do I need to modify anything in my code to make this work as bootstrap does normally?

**Comment by erikahaiste** [comment]
Hi Mick !
I have the same issue and wondered if you managed a way out ?

**Comment by mickster04** [comment]
No sorry. I just left it looking a bit rough.

**Comment by caseyjhol** [comment]
Please follow #1969. In the meantime, setting `data-width="auto"` or `data-width="fit"` on the select should fix your problem (you're using `width="fit"` in your example, which is incorrect).

**Comment by mickster04** [comment]
@caseyjhol Can confirm data-width="fit" worked for me! thank you very much!!!
https://www.randomisemytrain.com/ 
@erikahaiste I also updated to version 4.3.1 of bootstrap and bootstrap-select 1.13.6
