### ISSUE TITLE
Issue with version 1.12.1

### ISSUE THREAD

**Issue by hegdeas** [snapappointments/bootstrap-select#1602]
It was mentioned in the doc that :
"<select class="selectpicker">
  <option>Mustard</option>
  <option>Ketchup</option>
  <option>Barbecue</option>
</select>
If you use a 1.6.3 or newer, you don't need to do anything else, as the data-api automatically picks up the <select>s with the selectpicker class.".

Iam using 1.12.1 and the select is not loading.

It works fine when I add `$('.selectpicker').selectpicker();`

But I dont want to use this in my application. Is there a solution for this?

**Comment by birjolaxew** [comment]
It [definitely still works in 1.12.1](https://jsfiddle.net/k5dcLy14/). Odds are your implementation isn't correct (eg. the select isn't in the DOM on page load), but without any details we can't really say.

**Comment by hegdeas** [comment]
Hi @birjolaxew 

import React from 'react';

Here is the code where I have used select:

export default class TestSelect extends React.Component {
  constructor(props){
    super(props);
  }

  render() {
   return (
      <div>
 	 <select data-size=“2" className=“selectpicker" data-live-search="true">
                 <option>option 1</option>
		<option>option 2</option>
		<option>option 3</option>
		<option>option 4</option>
           </select>
     </div>
 );
}
}



The page loads with select for the first time. I change the route to something else and return back to the previous route/ use browser back select is not loading.

This is the content of routes.js file.

<Router>
<Route component={App}>
<Route path=“/test"  component={test} >
<IndexRedirect to="/campaign/selection"/>
	<Route path=“select" component={TestSelect}/>
	<Route path=“checkbox" component={TestCheckbox}/>
</Route>
</Route>
</Router>



For the first time I navigate to /test/select, the select loads.
Then I navigate to /test/checkbox and the navigate back to /test/select, the select disappears.

Reloading the page will solve the problem.

**Comment by hegdeas** [comment]
Any plans of implementing automatic load on next route change?

**Comment by caseyjhol** [comment]
I don't have any plans at this time for bootstrap-select to work with React out of the box. Your best bet would probably be to listen for route changes and then call `$(".selectpicker").selectpicker('refresh)`.
