### ISSUE TITLE
Html in liveSearchNormalize

### ISSUE THREAD

**Issue by andrews05** [snapappointments/bootstrap-select#1605]
When using liveSearchNormalize with subtexts, the livesearch will pick up the entire html of the subtext and find matches in `<small class="text-muted">`.
I found commit f17c3061360bb88060cc81cf27c96a51f2d4530f changed from using .text() to .html() but I'm not clear of the exact reason for the change. I would think .text() would be preferable.

**Comment by NicolasCARPi** [comment]
Should be fixed now.
