### ISSUE TITLE
Missing scrollbar on Tablet and Mobile, when data-size is present

### ISSUE THREAD

**Issue by shehi** [snapappointments/bootstrap-select#1621]
When ```data-size``` attribute is added to a select element with many options, it limits the view to the specified number of options, adding scrollbar to the dropdown. This scrollbar is absent in Tablet and Mobile screen sizes. You can see this behavior in Examples page as well. The users on Tablet and Mobile devices can't know whether there are more options there or not.

**Comment by qant** [comment]
May be i am late but i believe scrollbar is there, just styled different and hidden by default so you need just apply styles to scrollbar on mobile or tablets if you need them. Usually it appears when some one interact with the list
