### ISSUE TITLE
Issue with IPHONE Safari - native menu

### ISSUE THREAD

**Issue by cvs172** [snapappointments/bootstrap-select#1622]
Hi there,
This is Srinivas. I am using this bootstrap select in one of project which i am currently working. This is working absolutely fine in Andriod and windows phones but causing issue with safari browser in IPHONE.

In IPHONE it is opening both mobile Native Menu and Custom Dropdown which appears normally. This you can see in attached image. Also user is unable to select items from native menu.

I tried to fix this using the script block that you mentioned as solution for mobile devices. But no use.
```
if (/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)) {
        $('.selectpicker').selectpicker('mobile');
    }
```
![image-2017-01-30-11-35-35-949](https://cloud.githubusercontent.com/assets/968029/22548319/e950cd06-e96b-11e6-8b6d-30dfb937f572.png)

Environment:
Bootstrap v3.3.1

Please let me know if there is any fix for this.

**Comment by CanNuhlar** [comment]
`
if (/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)) {
$(".selectpicker").attr("data-native-menu","false");
}`

Should do it. I don't have an iphone to test it though.
