### ISSUE TITLE
VoiceOver issue

### ISSUE THREAD

**Issue by remisture** [snapappointments/bootstrap-select#1626]
Hi,

In VoiceOver for iOS, scrolling through the list of option elements is not working as expected. Instead, VoiceOver reads each letter for the selected element. 

Anyone have a fix or workaround for this?

![img_8567](https://cloud.githubusercontent.com/assets/2372967/22594290/c6e7bd44-ea22-11e6-9fd9-53e76328e7ac.PNG)
![img_8568](https://cloud.githubusercontent.com/assets/2372967/22594291/c6e7dc16-ea22-11e6-8490-2ffe1c0ac769.PNG)

**Comment by NicolasCARPi** [comment]
Is this still an issue?
