### ISSUE TITLE
Active bootstrap-select Menu hovering the button instead of clicking it

### ISSUE THREAD

**Issue by Phpuserit** [snapappointments/bootstrap-select#1634]
Hello,

I need the  code necessary to update the Jquery plugin "bootstrap-select" in order to activate the select and show the list of "options" available, when i hover with the mouse on the button instead of clicking on it.

Thank You very much.

Paolo

**Comment by holtkamp** [comment]
Maybe you can use this? On the background a Bootstrap dropdown is created, so might work

https://github.com/CWSpear/bootstrap-hover-dropdown
