### ISSUE TITLE
Sintax error

### ISSUE THREAD

**Issue by daniel-lucio** [snapappointments/bootstrap-select#1640]
bootstrap-select.css:9 Uncaught SyntaxError: Unexpected token {

When using https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.css

**Comment by jonathanbull** [comment]
Also having this issue.

**Comment by jonathanbull** [comment]
Are you by any chance loading the CSS file in a script tag?
