### ISSUE TITLE
Bootstrap-select webpack /Jquery 

### ISSUE THREAD

**Issue by AngularTx** [snapappointments/bootstrap-select#1652]
In our project we are building application with angular 2.4.8 version on IE browser. No Jquery  should be done ( if any 3rd party application uses internally , we have no issues) .

I would like to know if this package can be used in our application without adding any extra jquery coding . 

Basically the issue with IE browser is that the select drop down doesnot look good . So we would like to have this package used . Demo looks cool..

**Comment by NicolasCARPi** [comment]
jQuery removal will not happen before 2.0.0.
