### ISSUE TITLE
Feature Request: New live search style: fuzzysearch 

### ISSUE THREAD

**Issue by manniL** [snapappointments/bootstrap-select#1655]
Greetings!

I've looked into bootstrap-select and I'm impressed what a mighty plugin it has become!
Anyway, a thing that I really missed was another search style, called [fuzzysearch](https://en.wikipedia.org/wiki/Approximate_string_matching). The algorithm itself [isn't very complex](https://github.com/bevacqua/fuzzysearch/blob/master/index.js), so I thought about implementing it myself, but I honestly don't know where to start ^^

Fuzzysearch might be a preference thing, but IMO this search algorithm has great impact on small and medium datasets, because you can find data much easier!

**Comment by NicolasCARPi** [comment]
See https://github.com/snapappointments/bootstrap-select/blob/d83135124b02d6293af2a8ada45df17435f5186d/docs/custom_theme/js/base.js#L80
