### ISSUE TITLE
Use livesearch with AngularJS

### ISSUE THREAD

**Issue by sam-thecoder** [snapappointments/bootstrap-select#1658]
Can I get an example on how to have livesearch box but disabled from searching so I can have AngularJS do the search?

**Comment by gamunax** [comment]
mi solution: ng-change="pedido.buscarCliente()", apply `$('.selectpicker').selectpicker('refresh');`
html:
`<select class="selectpicker" ng-init="pedido.getCliente()" ng-model="pedido.formPedido.ID_CLIENTE"  ng-options="cliente.ID as cliente.NOMBRES for cliente in pedido.clientes" data-live-search="true" ng-change="pedido.buscarCliente()">
        </select>`
js:

> vm.getCliente = function() {
				$http.get(URL.baseUrl+'pedido/dashboard/getCliente')
					.then(function(data) {
						vm.clientes = data.data;							
						 $timeout(function() {				           
				           $('.selectpicker').selectpicker('refresh');
				        });						
					})
					.catch(function(error) {
					});
			}

> vm.buscarCliente = function() {
				$('.selectpicker').selectpicker('refresh');
			}
