### ISSUE TITLE
Multiple data-tokens useless if live search style is startsWith

### ISSUE THREAD

**Issue by rishitank** [snapappointments/bootstrap-select#1659]
Hi,

I have noticed an issue with using live search and multiple space separated tokens for the data-tokens attribute for an option. I am using the latest version 1.12.2 To reproduce:
- set the dropdown to use liveSearch and liveSearchStyle set to startsWith.
- Then add a space separated string of tokens and provide that as the data-token attribute for your options. e.g. "SIN Singapore"
- Try searching using live search, it only searches for items starting with the first token in your space separated string, ignoring the others. E.g. typing "Sing" produces no results as it doesn't match the first token.

I believe that live search should respect the list of tokens as separate keywords instead of one whole keyword (this configuration would only work if liveSearchStyle was set to 'contains'), if this could be looked into that would be great, thanks.

**Comment by andrews05** [comment]
You can override the search functions. Here's what I use to achieve a "word starts with" search:
```js
$.expr.pseudos.ibegins = function (obj, index, meta) {
	var haystack = (obj.dataset.tokens || obj.textContent).toUpperCase();
	var tokens = haystack.split(' ');
	var search = meta[3].toUpperCase();
	for (var i=0; i<haystack.length; i++) {
		if (haystack[i].startsWith(search)) return true;
	}
	return haystack.startsWith(search);
};
```

**Comment by mesvil7** [comment]
Cool @andrews05 I've replaced `haystack.length` by `tokens.length` also in the if condition and it worked for me.
