### ISSUE TITLE
selectpicker not refreshing after form submit

### ISSUE THREAD

**Issue by jmaxner** [snapappointments/bootstrap-select#1668]
I have a selectpicker in a dynamic table inside of a form (can add rows, delete rows).

My form submits correctly with all data. I am passing the index of the row where the selectpicker is located back to the success function in ajax. I need the selecpicker to refresh to pick-up the new product that was just inserted into the database. I know the index of the row that was clicked, just can't figure out how to refresh the selectpicker. Any help would be greatly appreciated.

$("#frmAddProduct").on('submit', function(e){
		e.preventDefault();

		var form_data = new FormData(this);
		var post_url = $(this).attr("action");
		
		$.ajax({
			url: post_url,
			type: 'POST',
			data: form_data,
			contentType: false,
			cache: false,
            processData: false,
			mimeType:'multipart/form-data',
			success: function(data){
				var rowIdx = data;
				//console.log(rowIdx);
				$('.selectpicker').selectpicker('refresh');	
			}
		});
});`

**Comment by vidyashree09** [comment]
same issue am facing any solution??

**Comment by caseyjhol** [comment]
3. **Provide environment details.** Provide your operating system, browser(s),
   jQuery version, Bootstrap version, and bootstrap-select version.

4. **Create an isolated and reproducible test case.** Create a [reduced test
   case](http://css-tricks.com/6263-reduced-test-cases/).

5. **Include a live example.** Use [this Plunker debugging template](http://silviomoreto.github.io/bootstrap-select/playground/) to share your isolated test cases. You can also make use of [jsFiddle](http://jsfiddle.net/) or [jsBin](http://jsbin.com/).

**Comment by jeancarlos110295** [comment]
ninguna solucion que soporte
