### ISSUE TITLE
Safari performance affected by position of <select>

### ISSUE THREAD

**Issue by andrews05** [snapappointments/bootstrap-select#1682]
This is a strange issue that's taken me a while to track down. In Safari, when using livesearch with a very large select menu, it can be quite slow to focus on the search input, particularly the first time you open the menu. I discovered I can resolve this performance penalty by positioning the `<select>` _before_ the `.dropdown-toggle` button. The only side-effect is a css tweak is needed to fix the left border-radius of the button since it's no longer the first child. (Alternatively, it could be positioned before the `.bootstrap-select` wrapper, if that doesn't cause any complications)

**Comment by andrews05** [comment]
After futher experimenting, I found the performance issue was caused by some of my css selectors - ones which didn't even apply on the current page! Very odd, but I tweaked the selectors and my problem is now solved without having to change the position of the <select>.

**Comment by andrews05** [comment]
Well my css adjustments made a big difference but I find I still get a bit of lag unless I reposition the `<select>`, so I'll reopen the issue.

**Comment by holtkamp** [comment]
@andrews05 can you provide an example that demonstrates the issue? I am about to dive into the performance issues... https://jsfiddle.net/ might be useful?
