### ISSUE TITLE
Unescaped HTML for $this.data('subtext') can cause XSS

### ISSUE THREAD

**Issue by jpopxfile** [snapappointments/bootstrap-select#1688]
https://github.com/silviomoreto/bootstrap-select/blob/3af7aa47940564387b2e9b8ab82d55d3d189f685/dist/js/bootstrap-select.js#L622

As subtext is not HTML escaped, if it contains text that can be rendered as HTML, XSS can occur.

![subtext](https://cloud.githubusercontent.com/assets/9736802/24338265/f8f6e370-12de-11e7-81cf-eabac351a0c9.PNG)

A good way to fix it might be to do this:
htmlEscape($this.data('subtext'))

**Comment by hossein** [comment]
Does 1.13.6 and its sanitizer resolve this issue? Related: https://github.com/snapappointments/bootstrap-select/issues/2225 .

**Comment by caseyjhol** [comment]
Fixed in v1.13.6.
