### ISSUE TITLE
2 mobile/usabillity issues

### ISSUE THREAD

**Issue by Maaark** [snapappointments/bootstrap-select#1700]
Hello,

I found 2 issues on mobile devices on 1.12.2:

1. When you set { mobile: true } the browsers native version and the normal dropdown are showing up - I expected only the native version to show up. 
2. On desktops you can open the dropdown and close it by clicking anywhere on the page. On a mobile device you need to choose an option before the dropdown closes. 

Can these issues be solved? And if these aren't bugs, how can I solve this/

**Comment by NicolasCARPi** [comment]
Is this still an issue?
