### ISSUE TITLE
bootstrap-select is slow

### ISSUE THREAD

**Issue by Machou** [snapappointments/bootstrap-select#1709]
Hello

How to load bootstrap-select so that it is loaded faster? Because it takes 1 second before loading my select, it is relatively long.

**Comment by davidenco** [comment]
Same here. Everything else has loaded before the select, and even then it takes it 0.5 seconds to load. I only have half a dozen options in the list too!!

**Comment by phil-a** [comment]
I am having this issue as well. It is especially noticeable if you have many images or elements on the page, it seems to wait for them all to finish loading before it shows the select.

**Comment by davidenco** [comment]
I fixed the rendering delay by loading only jQuery and Bootstrap-Select in the <head> with the rest of the JS including Bootstrap below the </body>, then just after each </select>, add this:

<script type="text/javascript">$('#myselect').selectpicker('render');</script>

Now all selects load before the page has finished rendering.

**Comment by bigalnz** [comment]
I too have the same issue.

**Comment by bigalnz** [comment]
While the rendering of the selects after davidenco fix helped, now when I use the select and pick a option it is slow to close the menu.

**Comment by traycho** [comment]
Only <script type="text/javascript">$('#myselect').selectpicker('render');</script> is enough, hope we see the improvement next release

**Comment by AdamFu** [comment]
same problem.fixed by 
`$(function(){
    $(".selectpicker").selectpicker('render');
})`

**Comment by davidenco** [comment]
Or this?

`$({$(".selectpicker").selectpicker('render');});`

**Comment by avilas** [comment]
Thank you so much..!

**Comment by caseyjhol** [comment]
Note to self:

Use document.ready instead of window.load to auto-initialize bootstrap-select.

**Comment by MuraliM** [comment]
have more than 30 select boxes in my page. Each select box has around 300+ options. So we staretd using this select picker to allow user to quickly type and pick the one. However, now its making lots of performance issues and we are in trouble now.


This select box has been created as reusuable angular component and we apply selectpicker in once the view was initialized using ### ngAfterViewInit

Each of them may or may not have a initial value set
```
 ngAfterViewInit() {
  jQuery("#mySelect10").selectpicker();
  jQuery("#mySelect10").selectpicker('val', 10); // sets the value, if it is present, ex 10 is value here
}
```
I tried with but still no change. Takes more time to load the page

```
 ngAfterViewInit() {
  jQuery("#mySelect10").selectpicker('render');
  jQuery("#mySelect10").selectpicker('val', 10); // sets the value, if it is present, ex 10 is value here
}
```

In IE 11, it is even very slow. User has to wait for nearly 30 seconds to see the view/UI. 

@caseyjhol  Is there any workaround on this performance issue? The plugin looks really great, except this performance issue

I tired updated to version 1.13.10, but still no luck :(

**Comment by caseyjhol** [comment]
This change will be a part of the v1.14.0 release. This issue will be updated after it's made available.

**Comment by caseyjhol** [comment]
Released in [v1.14.0-beta](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta)!

**Comment by ubertil** [comment]
Still very slow on page with multiple selects with thousands of options

**Comment by caseyjhol** [comment]
@ubertil With v1.14.0-beta? Can you link me to an example?

**Comment by Sublime1** [comment]
Hi @caseyjhol you have this flagged as a breaking change - can you explain a little more about this please?
