### ISSUE TITLE
UL Scroll Bar remembers last position

### ISSUE THREAD

**Issue by Vismar87** [snapappointments/bootstrap-select#1724]
Hi Folks,
                     great job, the selectpicker is awesome. 
I have found a problem, although I don't know if it's intentionally designed that way. 
If I scroll down on the select  (select an option or not) and then i close it and do
$('#mySelect').selectpicker();
   $('#mySelect').selectpicker('render');
   $('#mySelect').selectpicker('refresh');  
it doesn't matter the order or the combination, the vertical scroll bar stays on the same position that I left it.
At least for me it would be ideal that it was all the way to the top.
I am using the select to pick elements and add it to a collection. Once I have added the item, I don't want it to keep on the focus once the select is open again. 
Is there a way to do that?

**Comment by NicolasCARPi** [comment]
Probably a browser issue.
