### ISSUE TITLE
Add Sejda to "Used by" section

### ISSUE THREAD

**Issue by ediweissmann** [snapappointments/bootstrap-select#1733]
We're using bootstrap-select and would like to be on your "used by" list.
Thanks for sharing your work!

---

URL: https://www.sejda.com
Logo: https://www.sejda.com/images/sejda-banner-136x40.png

**Comment by ediweissmann** [comment]
Opened pull req: https://github.com/silviomoreto/bootstrap-select/pull/1734

**Comment by caseyjhol** [comment]
Thank you for your support of bootstrap-select! Unfortunately, we are discontinuing the "used by" section.
