### ISSUE TITLE
Property to set tickicon base diferent to iconBase

### ISSUE THREAD

**Issue by emilsonPineda** [snapappointments/bootstrap-select#1742]
issue, when set iconBase to another  icons source and it not has one check icon to replace tickIcon, there is no way to conserve glyphicon like iconbase for tickicon.

example, when using flags of countries to show like icons.

solution: override source code to do thats temporaly. please provide one property to solven this issue.

**Comment by NicolasCARPi** [comment]
This will probably not be implemented.
