### ISSUE TITLE
bootstrap-select breaks BS layout by having too much text in option tag

### ISSUE THREAD

**Issue by jonasgroendahl** [snapappointments/bootstrap-select#1746]
Hello everyone,

I have encountered an issue with the bootstrap-select overflowing a panel using classic boostrap grid layout because of too long text in the option tag. I wonder if this is a bug and if so, I wonder if there's a small fix. I'd like to use bootstrap-select instead of vanilla select with "form control" because of the search and other nice features.

JSfiddle to show the problem: https://jsfiddle.net/qbnxf2zm/

I also posted on stackoverflow.

**Comment by jonasgroendahl** [comment]
I have narrowed it down to **input-group** and **selectpicke**r css conflicting since if you remove the div with the  input-group class, it becomes responsive again.

**Comment by caseyjhol** [comment]
Fixed in v1.13.7.
