### ISSUE TITLE
I can't scroll to the footer on mobile

### ISSUE THREAD

**Issue by n-osennij** [snapappointments/bootstrap-select#1755]
projet url: http://new-genpasport.igc.by/price
Steps:

1. open url from **mobile**
2. at the top of the page on `select` chouse anything 
3. after that try to scroll to the footer

**Comment by gneotel** [comment]
I have the same issue (chrome on android), after I select something if I scroll the page scrolls back on a fixed position. It does so as long as the focus is on the select. If I click outside the select and it looses focus it stops scrolling.
http://www.guide.univpm.it/guide.php?lang=lang-eng&fac=economia&aa=2017&search=Cerca
Try to select a degree programme than to scroll.
Thanks!

**Comment by Leoxxid** [comment]
You can tell me how resolved this?

**Comment by n-osennij** [comment]
@Leoxxid stop using bootstrap-select

**Comment by Leoxxid** [comment]
why?

**Comment by n-osennij** [comment]
@Leoxxid because I'm not found solution

**Comment by Leoxxid** [comment]
In @gneotel project, he haved succeed in make the select over of the footer. I needed only it, but don't know how he did.

**Comment by Leoxxid** [comment]
I just want know how @gneotel  had succeed in make the select over of the footer.

**Comment by gneotel** [comment]
I didn't find a solution yet, for now page still has same behavior...

**Comment by jjorissen52** [comment]
It only happens with the default width setting for me, which is `width: false`. A workaround is to set width to anything other than false. Hope this helps.
```
//bad
$('#facility-filter-select').selectpicker({
    width: 'false'
});

//good
$('#facility-filter-select').selectpicker({
    width: 'auto' //literally anything other than false
});
```

**Comment by gneotel** [comment]
@jjorissen52  looks like it's working.
I kinda love you :-D

**Comment by gneotel** [comment]
Just to add some info, data-width="auto" is ok, data-width="75%" is bad instead.
I did not try "fit" and "350px" (the amounts are just examples).
