### ISSUE TITLE
Vue based version of bootstrap-select

### ISSUE THREAD

**Issue by unitedworx** [snapappointments/bootstrap-select#1773]
I am wondering if there is a possibility of a vue based version of bootstrap-select dropping jquery in favour of vue. Or anything similar but not a warper. Most vue based multi select controls I came across follow the tag convention instead of the tick used in bootstrap-select.

Why a vue based version? Generally much faster, reactive in nature and much much less code compared to jquery based components

**Comment by Sjoerrdd** [comment]
I would like it! :heart_eyes:

**Comment by AmitGuptaMT** [comment]
Any update on this?

**Comment by slidenerd** [comment]
I triple this

**Comment by caseyjhol** [comment]
I'm not opposed to this, but this would be a massive undertaking. I'd be more inclined to have bootstrap-select eventually be Vanilla JS (with no dependency on Bootstrap), and then ultimately making a Vue wrapper available. Once it's possible for the select to auto-update, it'll make things even simpler (#2185).

**Comment by slidenerd** [comment]
In the meantime, if anyone is looking for a dropdown search that works with, Vue, [HERE](https://codepen.io/zupkode/pen/rowmBM) you go It is not bootstrap-select as I had some trouble getting it to work inside a modal...

**Comment by unitedworx** [comment]
Bootstrap-select in Vanilla JS and a Bootstrap-select vue JS  component would be completely different things build with a completely different approach. With the latter being faster and substiantially slimmer in actual code.

**Comment by caseyjhol** [comment]
@unitedworx I understand that, but a Vue-based bootstrap-select component would still be a ton of work and I personally don't have time to work on it at the moment (especially since SnapAppointments is using Angular). If somebody wants to tackle this, by all means go for it, and I'll lend a hand where I can.

**Comment by juniorsotto** [comment]
Look this https://www.npmjs.com/package/vue-search-select, so similar.

**Comment by unitedworx** [comment]
@juniorsotto thanks for your recommendation but vue-search-select, is nowhere near the quality level or feature set provided by bootstrap-select

**Comment by NicolasCARPi** [comment]
Closing as out of scope request. Open source developers time is unfortunately not infinite.
