### ISSUE TITLE
feature request: Custom image for each option

### ISSUE THREAD

**Issue by hulem** [snapappointments/bootstrap-select#1782]
First of all, I have to say thank you for this great library.
---------
I wanted to use this library to show a list of countries and it works fine.
Then I told myself it's nice to show country flags next to each option.
I tried to add <img> but it didn't worked. Then I checked docs but it seems that there is not such feature.

It could be nice to add this feature. Something like:
<option data-img="/images/flags/us.png">

**Comment by shailesh-daund** [comment]
Hello @hulem ,

You can use **_[Custom Content](https://silviomoreto.github.io/bootstrap-select/examples/#custom-content)_** option which allows you to add html tags for options.
