### ISSUE TITLE
Used by Php Form Builder

### ISSUE THREAD

**Issue by migliori** [snapappointments/bootstrap-select#1783]
Hi,
Thanks for your amazing Bootstrap select.
I just wanted to suggest my Php Form Builder 
![phpformbuilder-logo-txt](https://user-images.githubusercontent.com/7558100/29259382-d8b02106-80c2-11e7-8646-49dac0d4743b.png)
be added to your "used by" list:

[https://www.phpformbuilder.pro/](url)
[https://codecanyon.net/item/php-form-builder/8790160?ref=migli](url)

I'll publish a new release very soon with Bootstrap 4 - Now BS4 is the official Bootstrap latest release: will you update your plugin?

Thanks again for this great work,

Gilles

**Comment by caseyjhol** [comment]
Thank you for your support of bootstrap-select! Unfortunately, we are discontinuing the "used by" section.
