### ISSUE TITLE
Data-size doesn't work with multiples selects

### ISSUE THREAD

**Issue by dpaya** [snapappointments/bootstrap-select#1794]
When I use data-size in diferent selects in the same page the scroll auto doesn't work
This line is only added in one select

`<ul` class="dropdown-menu inner" role="listbox" aria-expanded="false" style="max-height: 517px; overflow-y: auto; min-height: `80px;">`

In the others select this is the line added

`<ul` class="dropdown-menu inner" role="listbox" `aria-expanded="false">`

The style doesn't added and the text are out of the windows

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.
