### ISSUE TITLE
New company that uses bootstrap-select

### ISSUE THREAD

**Issue by kurdtpage** [snapappointments/bootstrap-select#1804]
The next release of [DairyWindow](https://www.dairywindow.nz) will use bootstrap-select. Here is my logo:
![logo_large](https://user-images.githubusercontent.com/1308716/30271355-1c7faa18-9744-11e7-83eb-3d8bc8076685.png)

**Comment by kurdtpage** [comment]
The next version has been released and is now live.

**Comment by krahamath** [comment]
is that spam ?

**Comment by kurdtpage** [comment]
No. As stated on the bottom of the [front page](http://silviomoreto.github.io/bootstrap-select/), my company (DairyWindow) now uses Bootstrap Select

**Comment by caseyjhol** [comment]
Thank you for your support of bootstrap-select! Unfortunately, we are discontinuing the "used by" section.
