### ISSUE TITLE
Stylized multiple selection with option to remove item

### ISSUE THREAD

**Issue by marcelogarbin** [snapappointments/bootstrap-select#1805]
Hello,

Currently I use select2 and I looked for alternatives and found bootstrap-select. I liked this plugin for bootstrap integration, but I saw some examples and found no resemblance to what I would like to do.
I would like to know if it is possible to style the select as in the image below. This would help the user better identify the selected options when using multiple select and would also help remove items, in my case I have a list with more than 2 thousand items, so it would be very uncomfortable for the end user to have to search one by one by the listing, with the option to remove directly in the item would facilitate its use.

Here is an example:
![Alt Text](https://i.imgur.com/1eIipou.png)

**Comment by caseyjhol** [comment]
This is not currently an option, but will be available in a future release. Please subscribe and 👍 #565.
