### ISSUE TITLE
live search on laraval view not works

### ISSUE THREAD

**Issue by heshanmax** [snapappointments/bootstrap-select#1812]
Hi

I'm trying to get live search on larval view

 <div class="form-group {{ $errors->has('manufacture_id') ? ' has-error' : '' }} ">
       {!! Form::label('manufacture_id','Manufacturer Name: ') !!}
       {!! Form::select('manufacture_id',[''=>'Select Manufacture']+$manufactures,null,['class' => 'form-control selectpicker' , 'data-live-search'=>'true']) !!}
</div>

when  I type on search box its not giving the result.

**Comment by elieandraos** [comment]
I have the same issue, it only highlights the searched result.
