### ISSUE TITLE
Changing value when select is disabled

### ISSUE THREAD

**Issue by bigalnz** [snapappointments/bootstrap-select#1823]
Hi,

I have a dropdown that is disabled so the user can't change the value (the value is changed progmatically (jquery/javascript) in response to users answers to previous questions.

The displayed value seems to change but not the value sent to the server.

The tags look like:

<select class="selectpicker risk" id="risk" data-width="100%">

And the code to change it:

$('.selectpicker.risk').selectpicker('val', 0 );
$('.selectpicker.overallrisk').selectpicker('refresh');

Is this by design? Do I need to enable/disable between changing the value?

**Comment by brettwinters** [comment]
I think my issue is related. I'm on 1.13.2 with BS4 using multiselect with option groups. If I set the option group to 'disabled' as follows: 

![image](https://user-images.githubusercontent.com/26474006/46055641-30df2700-c177-11e8-8a9c-7098d043eb96.png)

It's correctly disabled, however when I call ..selectpicker('val') it does not list the disabled item even though it was (previously / before disable) selected. This item is also listed when the select is closed

![image](https://user-images.githubusercontent.com/26474006/46055856-21aca900-c178-11e8-9bd0-ad199ae46237.png)

**Comment by ickbinhier** [comment]
I have the same problem as @brettwinters . Is that so intentional or is that a bug?

**Comment by giero** [comment]
Same here - disabled items are listed (or counted for `selectedTextFormat: 'count>3'`) when the select is closed.
As I remember some versions ago it was working as it should.

**Comment by NicolasCARPi** [comment]
Is this still an issue?

**Comment by jdhenry08** [comment]
This seems to still be a problem in 1.13.18 (the most recent Nuget version as of this comment).

**Comment by NicolasCARPi** [comment]
Unfortunately I don't have enough access to update nuget or make new releases, please try with latest from default branch if possible.
