### ISSUE TITLE
Multi Select: Select All but 2 options and/or deselect all but 1 option

### ISSUE THREAD

**Issue by bluesun3k1** [snapappointments/bootstrap-select#1825]
Hello,

I wonder if it's possible to Select all items except two (2) and also to deselect all items except one (1).

The thing is, I have a option list which includes an option that should not be part of multi select. If that option is selected, all other options should be deselected.

There is also another option which if selected, all other options should be selected except the one option that triggers the multi select.

Thanks in advance,

**Comment by gideonapollob** [comment]
I am experiencing this as well.

###### Environment
* Windows 7
* jQuery 1.12.4
* Bootstrap 3.3.7

###### Detail:
When [Select/deselect all options](http://silviomoreto.github.io/bootstrap-select/examples/#selectdeselect-all-options) customize menu is enabled, and you press the <kbd>Select All</kbd> button, will select all option without considering `data-max-options` property of the `<optgroup>` as shown in [this jfiddle](https://jsfiddle.net/gabardelas/aq9Laaew/108864/). When the <kbd>Select All</kbd> button is pressed, is should only select one (preferrably the first `<option>` of that `<optgroup>`), as inicated by `data-max-options` property.
