### ISSUE TITLE
When using "liveSearch" option there is no screen reader accessibility anymore

### ISSUE THREAD

**Issue by hrvojegolcic** [snapappointments/bootstrap-select#1831]
If "liveSearch" is enabled then you can no longer traverse through the multiselect items because the screen reader will not read the labels and states (checked/unchecked) but rather will repeat all the time "search textbox" whenever you go thought the list of options.

This might be due to search textbox stealing the focus all the time.

**Comment by ryan-z** [comment]
I've run into this issue with JAWS 18 as well, additionally all of the examples refuse to read out in IE11.

**Comment by caseyjhol** [comment]
Fixed in v1.13.10 (if not earlier).
