### ISSUE TITLE
bootstrap-select compatibility with Jquery version 3 or more

### ISSUE THREAD

**Issue by maheshparadkar** [snapappointments/bootstrap-select#1832]
I am trying bootstrap select with Jquery latest version 3 it seems its not working properly is there any solution for that or release new version for that

**Comment by bartclaeys** [comment]
I confirm that is does work perfectly with jQuery 3x.

**Comment by beerlander** [comment]
Even the latest version of bootstrap-select is still using fn.change() and fn.click() event shorthands in its js that are deprecated in jQuery 3.x (enabling jQuery migrate plugin will point that out).

**Comment by mattfeury** [comment]
yup these functions (`.click` and `.change`) are deprecated and should probably be replaced
https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated

**Comment by garima2094** [comment]
I also tried bootstrap select with jquery3, and the Bootstrap select plugin is not working properly. is there any solution available?

**Comment by caseyjhol** [comment]
Released in [v1.13.6](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.6)!
