### ISSUE TITLE
Back button causes field to duplicate

### ISSUE THREAD

**Issue by Dion-clarity** [snapappointments/bootstrap-select#1836]
First, let me say, I really appreciate this handy widget and thank you for the work.

I have ran into several small issues while using bootstrap-select, and have solved them in some way or another, so this post is more of a reflection than an issue report:
1. When pressing back to go back to a page that has a bootstrap-select field, bootstrap-select gets initialized again causing duplicated fields.

My solution:
I added some js code to check whether there is any 'bootstrap-select' class directly following another 'bootstrap-select' class, and if so, remove the duplicated field.
      $('.bootstrap-select').each(function(bs) {
        if ($(this).next().hasClass('bootstrap-select')) {
          $(this).next().remove();
        }
      })  

2. I used bootstrap-select primarily on a country and city field for my project. The city field is a template that gets re-rendered when the country value changes. It so happens that when the city field reloads, 'bootstrap-select' defaults to hiding itself (i.e. it gets reloaded as well, but it is not displayed)

My solution:
After testing 'bootstrap-select' event hooks, adding the following in the template seems to do the trick:
     $('.selectpicker').selectpicker('refresh');

3. And, finally, as mentioned by others already, 'bootstrap-select' does not seem to be compatible with Bootstrap 4 at the moment. I've tried the patch mentioned by another user, but I couldn't get it to work.

**Comment by NicolasCARPi** [comment]
Thanks for the feedback.
