### ISSUE TITLE
Dropdowns don't work in label tag on touchscreen devices

### ISSUE THREAD

**Issue by allanjackson** [snapappointments/bootstrap-select#1842]
I'm having a problem with bootstrap-select dropdowns not being able to be closed under certain conditions.

1. Using a device that has a touchscreen (affects most browsers).
2. The dropdown allows multiple selection.
3. The dropdown is contained within a label html tag.

Here's some sample code with several examples showing when it's broken vs working right.
http://jsfiddle.net/4vme9d89

I'm using bootstrap-select version 1.12.4, and I've encountered the bug on the following platforms:
iOS: Safari and Chrome.
Android: Chrome.
Microsoft Surface Pro: Chrome and Firefox. It works fine in IE and Edge.
Windows: Chrome using developer tools to simulate a mobile device.

**Comment by allanjackson** [comment]
@silviomoreto Have you had a chance to look at this issue at all? I know it's a pretty specific situation, but it's all valid html and use-case. In this situation, the form is just completely broken/unusable since you can't get the bootstrap-select dropdown to close after opening it.

**Comment by caseyjhol** [comment]
It appears this has been fixed in v1.13.1. https://fiddle.jshell.net/caseyjhol/4vme9d89/1/show/

**Comment by allanjackson** [comment]
It does appear to be fixed now -- thanks!

**Comment by kfe908** [comment]
Problem still exists in 1.13.9 and Bootstrap 4.0.0 :-(
