### ISSUE TITLE
Dynamically select a particular option under a particular optgroup

### ISSUE THREAD

**Issue by prateekjain0402** [snapappointments/bootstrap-select#1847]
Scenario
```html
<optgroup label="Group1">
<option value="1">
<option value="2">
</optgroup>
<optgroup label="Group2">
<option value="1">
</optgroup>
```
When option is selected using
$('#selectPickerId').selectpicker('val','1');

Both the options "1" under Group 1 and Group 2 are selected. I want to select "1" under Group1 only.

Something like
$("selectPickerId").selectpicker("val","optgroup[label='Group1'] option[value='1']");

How can we select a particular option under a partcular optgroup?

**Comment by caseyjhol** [comment]
You need to use different values for each option.
