### ISSUE TITLE
dropup doesn't work if size is set and count of options < size

### ISSUE THREAD

**Issue by ConfusedVorlon** [snapappointments/bootstrap-select#1848]
0) set up a select with 4 items 
1) leave dropupAuto = true
2) make size=8
3) view select near bottom of screen

(actually any case where number of items <= size will behave like this)

expect: 
select drops up

actual:
select drops down below screen

plunk:
https://plnkr.co/edit/uxDy19ulsFuND5Zmg6vM?p=preview
(remember to make your window small so that it should dropup)

![image](https://user-images.githubusercontent.com/586910/32289011-77dd5b1a-bf2d-11e7-8d35-609fba164fb6.png)

note: you might ask why I set size = 8 when there are only 4 items. The answer is that I do want a max size (I don't like the dropdown taking up the whole screen) and the number of items varies based on the user's data.

I can tell that the issue is coming from this line:

`else if (this.options.size && this.options.size != 'auto' && this.$lis.not(notDisabled).length > this.options.size)`

as `this.$lis.not(notDisabled).length > this.options.size` is false.
I'm not capable of fixing the issue though.

**Comment by caseyjhol** [comment]
Fixed in v1.13.0+: https://plnkr.co/edit/o2W0S0LTo8UTE2MP9k1e?p=preview.
