### ISSUE TITLE
bootstrap-select is used in multiple places in one page but only working for the first one

### ISSUE THREAD

**Issue by ashfaqrafi** [snapappointments/bootstrap-select#1849]
I have used three bootstrap-select in one page in my react component, I have followed all the instructions given, but only the first one is working properly and the other ones are not showing at all, here is the code snippet:
`componentDidMount() {
    $('.select').selectpicker();
    $('.selectpicker').selectpicker({
      style: 'btn-info',
      size: 4
    });
  }
`
`<div className="custom-select">
              <p className="font-300">
                                Drill Down Select
                            </p>
              <select className="sidebar-select m-bot-1 selectpicker selectbg" onChange = 
              {this.handleGraphTypeSelect.bind(this)}>
                <option selected disabled="disabled">Drill Downs</option>
                <option value="2_AXIS">Two axis graph</option>
                <option value="MULTIPLE_AXIS">Multiple axis</option>
                <option value="LOCATION">Location</option>
              </select>
            </div>` 
the other two has the same classes and structures but different values

**Comment by ashfaqrafi** [comment]
no one to help???

**Comment by ashfaqrafi** [comment]
is there anyone who can help me out???

**Comment by MaheswariSubburathinam** [comment]
use ID instead of class name..
Example:
 $('#ddlCountry').selectpicker();

**Comment by ashfaqrafi** [comment]
does not work, only works for the first selectpicker, but other three in the same page does not get the styling and JS.

**Comment by MaheswariSubburathinam** [comment]
Definitely there is solution. Do you want to apply same styling to be applied for all then use class selector and apply. Otherwise do you want to apply separate styling for each then choose the id selector for each and apply. If it doesnt work out. Place the pieces of code for selectpicker.

**Comment by GreggOrdHume** [comment]
I have personally found that:
`$('.selectpicker').selectpicker({ style: 'btn-info', size: 4 }); }`
does not work on the current version of selectpicker. When using it in my project it did not render the selectpicker.

**Comment by MaheswariSubburathinam** [comment]
All the select(dropdown) having the class named as "selectpicker". Or the one which is first.

**Comment by caseyjhol** [comment]
> I have personally found that:
> `$('.selectpicker').selectpicker({ style: 'btn-info', size: 4 }); }`
> does not work on the current version of selectpicker. When using it in my project it did not render the selectpicker.

Not sure which version this was broken in, but this is working in the latest release.
