### ISSUE TITLE
dropdown disappears when ajax call replaces the form

### ISSUE THREAD

**Issue by MercedeX** [snapappointments/bootstrap-select#1850]
I have the following form

```
<form action="/ManagementReview/Save" class="form" id="meetingForm" method="post" novalidate="novalidate">    <fieldset>
        <legend>Meeting</legend>
        <input data-val="true" data-val-number="The field Id must be a number." data-val-required="The Id field is required." id="Id" name="Id" type="hidden" value="545">
        <div class="form-group">
            <label class="control-label" for="Title">Meeting Title</label>
            <input class="form-control" id="Title" name="Title" required="required" type="text" value="review meeting" aria-required="true">
        </div>

        <div class="form-group">
            <label class="control-label" for="Prepration">Prepration</label>
            <textarea class="form-control" cols="20" id="Prepration" name="Prepration" rows="2">none</textarea>
        </div>

        <div class="form-group">
            <label class="control-label" for="Participants_Selections">Participants</label>
            <select class="form-control selectpicker" id="Participants_Selections" multiple="multiple" name="Participants.Selections"><option value="26">Rahat Fateh (Finance Officer)</option>
<option value="365">Erik schultz (Finance Officer)</option>
<option value="449">Ranax  (Supervisor)</option>
<option value="457">Ehsan Breeze 1 (Programmer)</option>
</select>
        </div>
        <div class="form-group">
            <label class="control-label" for="Venue">Venue</label>
            <input class="form-control" id="Venue" name="Venue" type="text" value="meeting room">
        </div>

        <div class="form-group">
           <label class="control-label" for="MeetingTime">Meeting Time</label>
            <input class="form-control" data-val="true" data-val-date="The field MeetingTime must be a date." id="MeetingTime" min="1800-01-01" name="MeetingTime" type="date" value="2017-11-03" readonly="readonly">
        </div>

        <div class="form-group">
            <label class="control-label" for="Notes">Description</label>
            <textarea class="form-control" cols="20" id="Notes" name="Notes" rows="2">none so far</textarea>
        </div>
        <div class="form-group">
            <button type="submit" name="button" value="save" class="btn btn-primary" id="save"><span class="glyphicon glyphicon-plus"></span> Save Meeting</button>
            <button type="reset" id="clear" name="action" class="btn btn-warning">Clear</button>
        </div>

    </fieldset>
</form>
```

when the same form is replaced, the dropdown disappears and no error is displayed in the console.
the area whr this should be displayed appears empty.

**Comment by iyadthayyil** [comment]
How you replacing your form? can you share the JavaScript?

**Comment by GreggOrdHume** [comment]
Are you replacing the form or select options with new html? 
If thats the case you might want to re-register the selects after your ajax.

So on your ajax success after appending the html:
`$('.selectpicker').selectpicker();`

If i were you I would ajax, on success destroy the old selects, drop the html, append the new html, initialise the select.
destroy: `$('.selectpicker').selectpicker('destroy');`
initialise: `$('.selectpicker').selectpicker();`

If you are updating the options inside the selects you can probably refresh:
`$('.selectpicker')..selectpicker('refresh')`

For more info feel free to post more code or see the docs:
https://silviomoreto.github.io/bootstrap-select/methods/#selectpickerdestroy

If i were you @iyadthayyil I would close this issue. The OP hasn't not responded in ages and has probably solved this.

**Comment by LeviHassel** [comment]
I'm using bootstrap-select v1.13.0-beta with Bootstrap 4 and jQuery 3.2.1 and I just experienced this same problem. After retrieving some HTML using AJAX and adding it to the page using `$(".container").append(response);`, all dropdowns with the class `selectpicker` from the HTML response are hidden entirely.

However, by calling `$('.selectpicker').selectpicker();` after appending the new HTML, as @GreggOrdHume recommended, everything works great!!

It still seems like this is an issue that should be looked into. Maybe there's a way to automatically refresh the Select Picker whenever a new one is detected?

**Comment by caseyjhol** [comment]
@LeviHassel That's beyond the scope of bootstrap-select, and would be better handled by something like an Angular or Vue wrapper for bootstrap-select. It would simply use too many resources otherwise to constantly be checking to see if a new select element has been added to the page.
