### ISSUE TITLE
selectpicker() always applies to every select with class .selectpicker

### ISSUE THREAD

**Issue by kjkrum** [snapappointments/bootstrap-select#1855]
Using version 1.12.4.  Consider the following:

```html
<select class="fnord">
  <option value="0">Foo</option>
  <option value="1">Bar</option>
  <option value="2">Baz</option>
</select>

<select class="selectpicker">
  <option value="0">Foo</option>
  <option value="1">Bar</option>
  <option value="2">Baz</option>
</select>
```

```javascript
$(".fnord").selectpicker();
```
**Expected behavior:** Only `<select class="fnord">` is themed.

**Actual behavior:** Both `<select>` elements are themed. ([jsfiddle](https://jsfiddle.net/f3nqwhxq/))

The reverse is not true. If we run `$(".selectpicker").selectpicker();` then only `<select class="selectpicker">` is themed.

If this is not a bug, it should be better documented that `.selectpicker` is not just a convention, but actually has special meaning.  I spent half a day trying to figure out why this was theming my hidden selects:

```javascript
$(".selectpicker").filter(":visible").selectpicker();
```

**Comment by asiby** [comment]
It's because of the selectpicker class. Just remove it. The class name is not used for anything else. So don't use it.
