### ISSUE TITLE
suits and tables now uses bootstrap-select

### ISSUE THREAD

**Issue by Christopher-Jakob** [snapappointments/bootstrap-select#1868]
![st-logo-whiteonnavy-short](https://user-images.githubusercontent.com/20484139/33501631-de5d710e-d6a2-11e7-8c7a-9460290a036c.png)

link: www.suitsandtables.com

**Comment by caseyjhol** [comment]
Thank you for your support of bootstrap-select! Unfortunately, we are discontinuing the "used by" section.
