### ISSUE TITLE
Special characters case insensitive with liveSearchNormalize

### ISSUE THREAD

**Issue by Casporro** [snapappointments/bootstrap-select#1876]
Please I need avoid problems of liveSearch with special spanish characters like Ñ

**Comment by Casporro** [comment]
Really the problem is that the liveSearchNormalize is case sensitive when you write ñ or Ñ and I want and I need this to be case insensitive.

**Comment by caseyjhol** [comment]
Released in [v1.13.4](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.4)!
