### ISSUE TITLE
Bootstrap validator + mobile

### ISSUE THREAD

**Issue by mhallager** [snapappointments/bootstrap-select#1884]
When used in conjunction with Bootstrap validator and mobile switched on, a non-selection error status on form submit will cause the menu to become unselectable. This was tested on Firefox 52.1 on a desktop. This issue does not occur when "data-mobile" is not specified, defaulting to false.

`<div class="form-group">
			<label for="formState" class="control-label col-sm-3"> State*: </label>
			<div class="col-sm-9">

				<select id="formState" class="selectpicker form-control" 
				data-width="auto" data-mobile="true" 
				aria-describedby="formStateStatus"
				name="formState" 
				title="Select a State" required>
<option value="ACT">Australian Capital Territory</option>
<option value="NSW">New South Wales</option>
<option value="NT">Northern Territory</option>
<option value="QLD">Queensland</option>
<option value="SA">South Australia</option>
<option value="TAS">Tasmania</option>
<option value="VIC" selected="selected">Victoria</option>
<option value="WA">Western Australia</option></select>

			<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
			<span id="formStateStatus" class="sr-only">(success)</span>

			</div></div>`

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.
