### ISSUE TITLE
Link & logo

### ISSUE THREAD

**Issue by stefkes** [snapappointments/bootstrap-select#1886]
We're using this excellent plugin on our site [here](http://atlasail.lh/nl/zeilreizen-zeilvakanties).

Below is a logo which can point to https://atlasail.com

https://i.imgur.com/R3iEQPi.png

Thanks!

**Comment by krahamath** [comment]
Receiving spam

**Comment by caseyjhol** [comment]
Thank you for your support of bootstrap-select! Unfortunately, we are discontinuing the "used by" section.
