### ISSUE TITLE
Using removeClass() has no effect

### ISSUE THREAD

**Issue by davidenco** [snapappointments/bootstrap-select#1891]
I can add a class to my select-picker as follows:
$('#propertyType').addClass('pvForm-sp-error').selectpicker('setStyle');

However removing the same class does not work. The class is removed from the select but not from the parent element.
$('#propertyType').removeClass('pvForm-sp-error').selectpicker('setStyle');

The workaround is to manually remove the class using the following:
$('#propertyType').removeClass('pvForm-sp-error').selectpicker('setStyle').parent().removeClass('pvForm-sp-error');

Any idea why removing a class only does half the job or am I missing something?

**Comment by cwilliamson62** [comment]
I have this exact issue. Would love an answer, but your work-around got me unstuck!! Thank you!!

**Comment by alxndrep** [comment]
On 2022 and have this same issue. Thanks @davidenco, like @cwilliamson62 said, your work save me!
