### ISSUE TITLE
Property 'selectpicker' does not exist on type 'JQuery<HTMLElement>'

### ISSUE THREAD

**Issue by mikewalkerjr** [snapappointments/bootstrap-select#1896]
I have successfully imported `bootstrap-select` into my project using:

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/i18n/defaults-*.min.js"></script>

Within the document `<head>` tag. I was going to see how to modify the checkmarks within the multiple select boxes, and figured I would try to use the 

    $('.selectpicker').selectpicker('deselectAll');

Method as shown [here](https://silviomoreto.github.io/bootstrap-select/methods/). Whenever I attempt to use that bit of code, I receive an error:

    TS2339: Property 'selectpicker' does not exist on type 'JQuery<HTMLElement>'.

I have even tried installing the types definition using
 
    npm install --save-dev @types/bootstrap-select

But the issue still remains. I'm using the Visual Studio SPA template which uses ASP.NET Core template, Vue.js and Webpack.

**Comment by fskale** [comment]
Perhaps you should refer directly using the id ?
I have no problem by doing:
$(#selectpicker').selectpicker('deselectAll');

Of course you have to set the id on the picker !

**Comment by InhouseMedia** [comment]
I had the issue with webpack and the modular function that comes with it.
The jQuery version that's been used for bootstrap-select was different than the one i've implemented.
So i needed to overwrite this using imports-loader:
you need to overwrite the "this" within the factory function that is searching for "root['jQuery']".

require("!imports-loader?define=>false,exports=>false,module=>false,this=>{'jQuery': jQuery}!bootstrap-select");

i hope this will help

**Comment by davemvp** [comment]
@InhouseMedia,
Any idea how to do what you describe using the angular-cli.json file of an Angular 2+ project?

**Comment by InhouseMedia** [comment]
@davemvp sorry I don't know. maybe there is a ngx-bootstrap/select package somewhere. haven't found it yet
