### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by CharleysTante** [snapappointments/bootstrap-select#1899]
first and foremost for this great jQuery plugin

You have on your page a demo with tooltips, but if I enter in the first option-tag a titel attribute as well, I'll get this titel in the selcet field after a browser relod. It would be ver nice if you could fix it:

![bootstrap-select](https://user-images.githubusercontent.com/23652883/35034369-33713816-fb6e-11e7-83f5-119cb877a9f5.png)

**Comment by NicolasCARPi** [comment]
Option element must not have a title attribute.
