### ISSUE TITLE
space and/or new line after option content breaks formatting

### ISSUE THREAD

**Issue by PhilPJL** [snapappointments/bootstrap-select#1906]
Visual Studio 2017 15.5
IE 10
Bootstrap 3.3.7
Bootstrap select 1.12.4

Say I have this which works fine

                        <div class="col-sm-5">
                            <select name="@Html.NameFor(m => m.SelectedTriggers)"
                                    id="@Html.IdFor(m => m.SelectedTriggers)"
                                    class="form-control selectpicker"
                                    multiple="multiple"
                                    data-window-padding="[50,0,50,0]">
                                @foreach (var option in Model.LineConfiguration.FlagWinderTriggers)
                                {
                                    <option value="@option.Value" @(option.Selected ? "selected" : "")>@option.Text</option>
                                }
                            </select>
                        </div>

and do something, like a reformat which ends up with this

                                    <option value="@option.Value" @(option.Selected ? "selected" : "")>
                                        @option.Text
                                    </option>

This shows a space before the comma, and screws up the tooltip.

![image](https://user-images.githubusercontent.com/271656/35727898-a775f61c-0801-11e8-8e71-c18d1f68fc7b.png)

Adding .trim() here

          if (typeof $this.attr('title') !== 'undefined') {
            return $this.attr('title');
          } else if ($this.data('content') && that.options.showContent) {
            return $this.data('content').toString();
          } else {
            return icon + $this.html().**trim()** + subtext;
          }
        }
      }).toArray();

Fixes the issue

**Comment by caseyjhol** [comment]
Fixed in v1.13.0. See #2063.
