### ISSUE TITLE
Fix: Safari 11.0.3 Bug (Always 'bold' Text (for noneSelectedText))

### ISSUE THREAD

**Issue by mikeploeger** [snapappointments/bootstrap-select#1913]
Fix on line 526 in bootstrap-select.js:

Old:
`'<span class="filter-option pull-left"></span>&nbsp;' + `

New:
`'<span class="filter-option pull-left"></span>' + 
`
Due to this, the 'noneSelectedText' was bold in Safari.
After the fix the text looked normal like expected.

Cant reproduce the bug in Firefox, seems to be a Safari issue. (macOS)

**But anyway, the `&nbsp;` in this line is really unnecessary and should be removed.**

**Comment by caseyjhol** [comment]
What version of bootstrap-select are you using? Is this bug occurring in v1.13.0-beta? https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta

**Comment by mikeploeger** [comment]
I'm using v1.12.4.
Thank you for taking your time to commit the fix to the repo.

**Comment by caseyjhol** [comment]
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
