### ISSUE TITLE
 not working with bootstrap 3.3.7 and jquery 3.3.1

### ISSUE THREAD

**Issue by armanfeyzi** [snapappointments/bootstrap-select#1914]
i use  `bootstrap 3.3.7` and `jquery 3.3.1` but `bootstrap-select` not workin, what's problem?
see my demo at  [jsfiddle]( https://jsfiddle.net/xs8y38o6/5/).

**Comment by mkraha** [comment]
Removed your boostrap-select.js code from js file within jq331 and add boostrap-select.js bootstrap.js file in the resources then it worked.
Check it out here: https://jsfiddle.net/xs8y38o6/9/
