### ISSUE TITLE
Fork that works against Bootstrap 4?

### ISSUE THREAD

**Issue by ghost** [snapappointments/bootstrap-select#1915]
Seems like this is abandonware. Does anyone have a fork that works against Bootstrap 4.x?

**Comment by cocowalla** [comment]
Seems like you didn't bother to search ;)

The [v1.13.0-dev branch](https://github.com/silviomoreto/bootstrap-select/tree/v1.13.0-dev) added support for Bootstrap 4 just a day or two ago.

**Comment by ghost** [comment]
I did search, I didn't think to search for that. Thanks for the pointer.

**Comment by ghost** [comment]
The last commit on that branch is from 7 months ago. Can you point me to what you're talking about?

**Comment by cocowalla** [comment]
Sorry, I sent you to the wrong place - I meant [this fork](https://github.com/snapappointments/bootstrap-select). This fork is 'official', but I'm not really sure why Bootstrap 4 support is happening in a fork and not just a branch.

**Comment by ghost** [comment]
Thanks for the pointer, I never would've found that.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!

**Comment by Jogai** [comment]
The forks are confusing. This project listed the one from snapappointments as the official successor, but later @silviomoreto removed it from the readme. The official npm package seems to be taken over by snapappointments. So what is going on, and what should package users follow?

**Comment by caseyjhol** [comment]
@Jogai I've been the main developer of bootstrap-select for the past 5 years. Silvio didn't want to transfer ownership of the repo to me, so I opted to fork it and move development to snapappointments/bootstrap-select. I'll be continuing development there. If you like the plugin and would like frequent updates, mine is probably the one you want to follow. It's understandably confusing.
