### ISSUE TITLE
Cannot remove dotted outline

### ISSUE THREAD

**Issue by krystyna93** [snapappointments/bootstrap-select#1916]
I cannot for the life of me, remove that hideous dotted outline on the .bootstrap-select .dropdown-toggle:focus. I have tried using the !important rule, but that does not work at all....

Any ideas?

**Comment by Loafer19** [comment]
`
.bootstrap-select .dropdown-toggle:focus {
        outline: none !important;
    }
` - it works for me
check the CSS style order
