### ISSUE TITLE
no matches for livesearch with trailing \ in filter text

### ISSUE THREAD

**Issue by mclouden** [snapappointments/bootstrap-select#1918]
We had an issue where we were not able to livesearch/filter dropdown items whenever the input text ended with \

The data in the list is in the form of domainname\username

domainname\ will fail to have any results
domainname\a does work
\ will fail to have any result as well
e\a does work

you get the picture

what I found was in the $searchbox.on('input propertychange' event
the line: $searchBase.not(':' + that._searchStyle() + '("' + that.$searchbox.val() + '")');

When I break inside the icontains
$.expr.pseudos.icontains = function (obj, index, meta)

meta[3] will be provided as "\"\\\"" if I only entered \ which will fail to match in the includes call (fails to match "\\" - with quotes)

I am in no way a javascript expert (or fan), and a casual read of jquery 'contains' suggests that the match string does not require the enclosing quotes. So we took them out in the line

$searchBase.not(':' + that._searchStyle() + '(' + that.$searchbox.val() + ')');

I was mildly surprised/amused to see that this works, and seems to be having no negative impact.

I would ask then: is this an appropriate (correct) change to be making local, and to request that it be made in the project? Or should we instead hijack the icontains, and have it do some basic - if meta[3] starts and ends with a quote, then strip them off before the test - approach ?

Much appreciate any feedback

BTW - this is v1.10 through latest.

**Comment by caseyjhol** [comment]
There have been some significant changes to the way searching works in v1.13.0 (we no longer use pseudos). Please give the latest [v1.13.0-beta](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta) a try and let me know if the issue persists (it seemed to be working in my tests).

**Comment by mclouden** [comment]
An excellent suggestion which I should have considered first - and the behavior is as you would expect (working) in this beta version. Thank you for your quick response and for your assistance. We are still defining our toolkit for bootstrap UI development, and this package is fitting many of our needs - and with these types of improvements I expect it will find a permanent place here.

**Comment by caseyjhol** [comment]
No worries! It's a bit confusing as we're in the process of transferring the repo to another location.
