### ISSUE TITLE
not opened dropdown in Bootstrap 4.0.0

### ISSUE THREAD

**Issue by sborislav** [snapappointments/bootstrap-select#1919]
Sorry, my english is bad, but i can write report.

I use bootstrap 4.0.0 and selectpicker.
And my selectpicker not opened because you use style of Bootstrap 3.3.6
```
.open>.dropdown-menu {
    display: block;
}
```
Bootstrap 4.0.0 have't this style.
I hope I made that clear.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta. Please post any issues in that repo from now on.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
