### ISSUE TITLE
Proudly used by MasteredMonkey 

### ISSUE THREAD

**Issue by obchodniuspech** [snapappointments/bootstrap-select#1920]
Hello, 

we proudly use yours plugin in ours e-commerce platform startup from Czech Republic. Thank you guys for great work! :) 👍 

![mmlogo-01](https://user-images.githubusercontent.com/12214261/36354491-b01decbc-14d5-11e8-9ac9-ac12275a3687.png)

Link: https://www.mastered-monkey.com

Thanks for adding us :)

**Comment by caseyjhol** [comment]
Thank you for your support of bootstrap-select! Unfortunately, we are discontinuing the "used by" section.
