### ISSUE TITLE
Selectpicker is hidden how to refresh ?

### ISSUE THREAD

**Issue by Vameo** [snapappointments/bootstrap-select#1923]
Hello,
I have question because I can't resolved this problem. 
I use bootstrap-select and everything is work corectlly.
But I have some issue is : If I select option in search , results is hidden .... 
I use option <select> 
I must refresh entire page then I see my choice.  
What I do wrong ? Can someone ...
( Gif screen ) 
[http://recordit.co/WHsP5LSaOW](url)
Thank you

**Comment by caseyjhol** [comment]
What version of bootstrap-select are you using? What is your resolution? It seems like your screen is really small and there's not enough room for the menu.

**Comment by Vameo** [comment]
Hello,
I use new version : 1.12.4  No no it's only example screen with my monitror. I use 24" monitror.
Please see again : http://recordit.co/zoBM4xNT4B
Plugin works ok but i have problem I need refresh page If i want to see selected result. Selected option isn't loading.
I use this in prestashop - blocklayered

thank you

**Comment by caseyjhol** [comment]
Seems like there is a conflict somewhere - I'd be happy to investigate further if you can link me to an example. Try giving v1.13.0-beta a try as well: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta.

**Comment by Vameo** [comment]
Hello , 
Please see sample live website. Left column. Selectet filters is hidden ( select.bs-select-hidden, select.selectpicker { /* display: none!important; */}
https://goo.gl/CeMvWe

thank you

**Comment by CarlosAlexz** [comment]
I have the same problem, the DDL disappears when I change status.

Could you solve it?

**Comment by caseyjhol** [comment]
@Vameo You need to load the bootstrap-select CSS later - it's being overwritten by some of your other CSS.
