### ISSUE TITLE
Request: Is it possible to fire event on search box?

### ISSUE THREAD

**Issue by winex01** [snapappointments/bootstrap-select#1924]
I want to fire an event on search box so i can submit an ajax request, is this possible?
i already check the available events on the documentation but no event for the search box.

**Comment by running-snail-sfs** [comment]
i have same problem，slove?

**Comment by pedro-pinho** [comment]
[https://github.com/truckingsim/Ajax-Bootstrap-Select](url) this seems to solve this problem

**Comment by caseyjhol** [comment]
Please 👍 and follow #1305.
