### ISSUE TITLE
SCSS compile error - 1.13.0-beta

### ISSUE THREAD

**Issue by spyter** [snapappointments/bootstrap-select#1927]
I am having issues compiling the scss file for bootstrap-select 1.13.0-beta.

I believe line 78 needs to be border-color: $color-green-success; instead of border-color: @color-green-success;

$ instead of @

**Comment by caseyjhol** [comment]
This has been resolved in the v1.13.0-dev branch. See https://github.com/snapappointments/bootstrap-select/pull/3.
