### ISSUE TITLE
data-live-search does not close after selecting items

### ISSUE THREAD

**Issue by VicoErv** [snapappointments/bootstrap-select#1929]
data-live-search does not close when selecting items after searching (click/enter same).
there seems to be a problem with the `open` class in` .bootstrap-select`
my step to recover is to use jquery

```javascript
...
handleChange: function (event) {
   console.log (event.target.value);
   $ ('bootstrap-select'). removeClass ('open');
}
...
```

- Browser: Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)
- js files: vue.js, axios.js, jquery.js, popper.js, bootstrap.js, bootstrap-select.min.js
- css files: bootstrap.min.css, bootstrap-select.min.css

![gif](https://image.prntscr.com/image/xeYNGNX7Ssyy8hAnoUjUGQ.gif)

**Comment by caseyjhol** [comment]
What versions of Bootstrap and bootstrap-select?

**Comment by VicoErv** [comment]
Bootstrap v4.0.0
Bootstrap-select v1.12.4
is bootstrap-select not compatible with bootstrap v4 ?

it seems working normally in example using Bootstrap v3.3.6

**Comment by caseyjhol** [comment]
Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta.

**Comment by VicoErv** [comment]
thank you, ill close this issue.
