### ISSUE TITLE
bootstrap-select's data-live -search  not woking in bootstrap4

### ISSUE THREAD

**Issue by yilumengxiang** [snapappointments/bootstrap-select#1931]
when i added data-live-search="true" to "select" it worked not well.
 does it support bootstrap4 well?

**Comment by caseyjhol** [comment]
Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta. Please post any issues in that repo from now on.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
