### ISSUE TITLE
Cannot append new options to select/dropdowns if already initialized 

### ISSUE THREAD

**Issue by talesid5** [snapappointments/bootstrap-select#1932]
I want to dynamically change select options based on another select with jQuery. Working fine but not with this library.

Already posted there but no response: [bootstrap-select append new options](https://stackoverflow.com/questions/49014969/bootstrap-select-append-function-in-jquery)

The select is populated but doesn't display because of new elements.

**Comment by caseyjhol** [comment]
I posted a response on StackOverflow.

**Comment by talesid5** [comment]
Thanks
