### ISSUE TITLE
DropDownList is missing after AutoPostBack.

### ISSUE THREAD

**Issue by CarlosAlexz** [snapappointments/bootstrap-select#1935]
HI to All,

I have a problem with the selectpicker class, in my project im using a MasterPage , so the all the other pages inherit from it.
In my default ASPX i have a UpdatePanel and inside there are another two UpdatePanel, like this:

 **<div class="form-business" id="form-group-1">
        <p>
            <asp:UpdatePanel ID="upnPrincipal" runat="server">
                <ContentTemplate>
                    <asp:UpdatePanel ID="upnBuscar" runat="server" UpdateMode="Conditional">
                        <ContentTemplate>
                            <asp:Panel ID="pnlBuscar" runat="server">                              
                                <div class="form-group" id="divRazon">
                                    <asp:DropDownList ID="ddlRazon" runat="server" CssClass="form-control selectpicker" data-style="btn-warning" data-live-search="true" data-live-search-style="contains" title="Escriba Nombre De Razon Social..." data-size="10" data-live-search-normalize="true" OnSelectedIndexChanged="ddlRazon_SelectedIndexChanged" AutoPostBack="true"></asp:DropDownList>
                                </div>
                                <div class="form-group">
                                    <asp:Button ID="btnAgregarRazon" Text="Agregar Razon Social" CssClass="form-control" OnClick="btnAgregarRazon_Click" runat="server" />
                                </div>
                            </asp:Panel>
                        </ContentTemplate>
           </asp:UpdatePanel>
        </ContentTemplate>
<asp:UpdatePanel> This is another Update Panel. </asp:UpdatePanel>
    </asp:UpdatePanel>
</p>
</div>

After the DropDownList generated an AutoPostBack, the DropDownList is missing.

**Comment by vanpatrick81** [comment]
you would need to re-initialize the selectpicker. just call $('.selectpicker').selectpicker(); again on page load.

**Comment by CarlosAlexz** [comment]
Ok, Thanks for your comment,
The problem is that he lose the 'selectpicker' class, when he makes a PostBack.
