### ISSUE TITLE
Intermittent - after repopulating list in script code, dropdown doesn't update

### ISSUE THREAD

**Issue by jrichview** [snapappointments/bootstrap-select#1936]
Hi guys. This is a problem not reproducible consistently, but it does reproduce often. It's tied to a Microsoft Dynamics CRM portal page, so it's not something I can easily reproduce as a snippet. Bear with me a sec and it's pretty easy to reproduce:
1) Go to https://cityofbirminghamtest.dynamics365portals.us/ and register (you need to be logged in to do this)
2) after registering and getting logged in, click the service request map to go to that page. [https://cityofbirminghamtest.dynamics365portals.us/service-request-map/]
3) Drop down the "Request Type" filter. There should be over 220 items.  If the only item is "Any" you have reproduced the problem.

JQuery code loads the list items from an Ajax call. I have inserted console.log messages to let me know if any errors are happening. It appears that when it fails, no errors are occurring. The Ajax call successfully retrieves the results. I'm calling refresh on the control after modifying the options, so I'm not sure what else I could do about this. 

Here's the method code
[script snippet.txt](https://github.com/silviomoreto/bootstrap-select/files/1790239/script.snippet.txt)
:

**Comment by NicolasCARPi** [comment]
Website not working.

**Comment by jrichview** [comment]
Yes, well it has been three years since I posted this. So....
