### ISSUE TITLE
l10n file for Japanese

### ISSUE THREAD

**Issue by jackdeguest** [snapappointments/bootstrap-select#1937]
Although I salute the effort, the file `defaults-ja_JP.js` containing the localised content for Japanese contains inadequate translation.

Use of words like `達成` for `reach` and `限界` for limit is wrong. The former is rather used to imply an achievement and the latter for limit, but more as boundaries.
So `Limit reached ({n} item max)` should not be translated as:
`限界は達した({n}{var}最大)`
but as:
`上限(最大{n}{var}項目)に当たった`

Likewise `No results match {0}` should not be translated as:
`\'{0}\'が結果を返さない`
but as:
`\'{0}\'の結果はなし`

The use of `アイテム` for `item` is inadequate as this is used for commercial product or things one feels to have absolutely. The right word would rather be `項目`
etc...
Updated file is attached.
P.S.: I am a long-term resident in Japan, read and write Japanese fluently.
[defaults-ja_JP.txt](https://github.com/silviomoreto/bootstrap-select/files/1800010/defaults-ja_JP.txt)

**Comment by silviomoreto** [comment]
@jackdeguest can you make a pull request for that?
