### ISSUE TITLE
List and search not working

### ISSUE THREAD

**Issue by Cruyjun** [snapappointments/bootstrap-select#1940]
Hello I've followed and search for some fix but I couldn't find it.
![image](https://user-images.githubusercontent.com/6058565/37301437-77759444-2620-11e8-86b3-e803ea79f60d.png)

I've used the example from the original website 
https://silviomoreto.github.io/bootstrap-select/

I've bootstrap 4, if I change my html file to use a previous version this works:
"  rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.css"
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.js"></script>"

But using bootstrap 4 its not possible, also the search does not hide the other options. 
Can anyone help me with my problem?

**Comment by caseyjhol** [comment]
Please read the [readme](https://github.com/silviomoreto/bootstrap-select/blob/master/README.md).

Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta. Please post any issues in that repo from now on.

**Comment by Cruyjun** [comment]
Thank you ;) all working now.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
