### ISSUE TITLE
Change data-width programmatically

### ISSUE THREAD

**Issue by mistre83** [snapappointments/bootstrap-select#1941]
Hi to all,
i'm using selectpicker on my website that have a mobile version.

On desktop, i need **data-width="fit"** and on mobile i need **data-width="100%"**. Because some devices (like iPad) when are in landscape are recognized as desktop and in portrait are recognized as mobile, **how i can refresh the data width programmatically ?**

**Comment by NicolasCARPi** [comment]
Out of scope.
