### ISSUE TITLE
Option dropdownAlignRight auto doesn't work

### ISSUE THREAD

**Issue by ghost** [snapappointments/bootstrap-select#1943]
Option dropdownAlignRight=auto doesn't work!

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by vinnygambiny** [comment]
http://jsfiddle.net/q9s2rLbe/

**Comment by caseyjhol** [comment]
Broken in v1.13.0. Working correctly in v1.12.4.

**Comment by caseyjhol** [comment]
Released in [v1.13.4](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.4)!
