### ISSUE TITLE
Drag and drop list item

### ISSUE THREAD

**Issue by rfossella** [snapappointments/bootstrap-select#1944]
Hi,
This is more of question than an issue.  Is there an option or method I'm not seeing in docs that would allow one to drag (reorder) list items around?  The idea is that I have a list of items that can be multi-selected.  I would like to have ONE of these items "marked" as a default.  Not sure how this would be done using checkmarks so I thought dragging an item to the top of list would indicate this. 

Any suggestions or ideas appreciated!  Thanks for the great widget!
Rob

**Comment by Smtgr14** [comment]
There is no option to re-order items via drag and drop.
If you need to have a default, add ```selected="selected"``` to the attributes of the option like so:
```
<select class="selectpicker" multiple>
  <option selected="selected">ITEM</option>
</select>

**Comment by rfossella** [comment]
Thanks for prompt feedback!  While I'm aware of the 'selected' option, my question had more to do with setting a 'default' based on **all** the selections chosen.  e.g. list has
```
Company A
*Company B
*Company C
Company D
*Company E
```
I wanted to somehow allow user to signify that selected option 'Company C' is the default option, say, upon initial login, I want to default by logging into Company C.

In any event, you answered my question that there isn't such an option.

Thanks again!
