### ISSUE TITLE
how to triggering submit with enter key?

### ISSUE THREAD

**Issue by hisune** [snapappointments/bootstrap-select#1945]
how to triggering submit with enter key?

**Comment by Smtgr14** [comment]
Do you mean submitting the form by pressing the enter key?
Or do you mean selecting the highlighted item and closing the select menu?

For accessibility reasons, the enter key should do the latter (and does by default). 

If you really want to to do the first one, you'll need to add an event handler to the form that listens for the ```Enter``` key. The exact way to do this is outside the scope of this project/repository.

**Comment by hackeresq** [comment]
I do believe this is a bug. Normal HTML input types will submit the form when enter is pressed even if focus is still on the input. 

Here, after selecting an item from the drop down, focus remains on the bootstrap-select. When enter is pressed, the form is not submitted.

**Comment by caseyjhol** [comment]
In Internet Explorer 11, Edge, Firefox 75, and Chrome 81 on Windows 10, I'm not able to reproduce submitting the form while a native select element is focused (whether it's the element itself or an option in the menu). That is the standard behavior for an input element, however. Submitting the form while the select element is focused would be an unexpected behavior.
