### ISSUE TITLE
1 click to open a select, when another one is opened

### ISSUE THREAD

**Issue by cazacugmihai** [snapappointments/bootstrap-select#1946]
Having two select items (one after the other) and the first one opened:

```
+---------+    +---------+
| SelectA |    | SelectB |
+---------+    +---------+
| item 1  |
| item 2  |
| item 3  |
+---------+
```
is there a way to open the second one by clicking it (one click, not two)?

Thanks!

**Comment by caseyjhol** [comment]
That should already be standard behavior (unless I'm misunderstanding something).
