### ISSUE TITLE
Replace de/selectAllText with icone on select data-actions-box [enhancement with PR provided]

### ISSUE THREAD

**Issue by Pbast** [snapappointments/bootstrap-select#1947]
Hello,

To improve your great bootstrap-select, could you replace replace de/selectAllText with icone on select data-actions-box with my PR?

![multiselectwithicone](https://user-images.githubusercontent.com/7781704/38016394-26d15b4e-326f-11e8-8f17-e8ba62aabf3c.png)

Here a nice live example: https://plnkr.co/edit/OrfZu1b2sjaXbgolj4gC?p=preview

Ty

Pascal BASTIEN

**Comment by Pbast** [comment]
Here my 2 PR (sorry I didn't manage to merge my 2 PR in one)
* https://github.com/silviomoreto/bootstrap-select/pull/1948
* https://github.com/silviomoreto/bootstrap-select/pull/1949

Thxs

**Comment by Pbast** [comment]
Hello could you tell me why you are not interested by my PR? ty

**Comment by caseyjhol** [comment]
Your PRs completely overwrite the "Select All" and "Deselect All" text, providing no backwards compatibility. In addition, I plan to add support for the buttons to the template option, which will allow more advanced customization of button content. I also haven't seen a lot of interest in this feature. Also, as Bootstrap 4 no longer uses Glyphicons, I'm trying to move away from them where possible (this PR would result in two empty buttons if using Bootstrap 4). Thank you for your contribution, but until there is more support for this feature specifically, I'm not sure it fits into the scope.

Please 👍 and subscribe to #1299 for updates.
