### ISSUE TITLE
Option to fix the dropdown position ('auto', 'up' or 'down')

### ISSUE THREAD

**Issue by lucasscarduelli** [snapappointments/bootstrap-select#1953]
It's a feature!

I have a need to define the position that the dropdown is opened, today this position is auto, if have space the dropdown is opened to down else it's opened to up. But to keep the consistency of behavior in my application I need to defined that dropdown always opened to down.

It's possible?!

**Comment by lucasscarduelli** [comment]
Any news!!??

**Comment by caseyjhol** [comment]
Set `dropupAuto: false`.
