### ISSUE TITLE
Empty dropdown when i make one

### ISSUE THREAD

**Issue by Goten87** [snapappointments/bootstrap-select#1957]
i wanned to add your multi select option for my website but it is not working at all

```
<select class="form-control selectpicker" multiple name="extra[]" id="Extra">
    <option value="lvling">Leveling</option>
    <option value="farming">Farming</option>
    <option value="dungeon">Dungeon Friendly</option>
    <option value="raid">Raid Friendly</option>
</select>
```

this is my code when i go to my website and open the Select the Select dropdown is compleetly empty no data in it at all
so what am i doing wrong

i use boostrap 4
and jquery 3.2.1
also i have jquery UI installed

**Comment by MinChanSike** [comment]
I think it is because of *Bootstrap version 4*. 
By documentation - `This version currently does not support Bootstrap 4 officially.`

**Comment by caseyjhol** [comment]
Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta.

**Comment by Goten87** [comment]
To @caseyjhol Will try that tomorrow

**Comment by Goten87** [comment]
also i use
```
<optgroup class="HideAll Show1">
<option class="HideAll Show1">option 1</option>
<optgroup>
```
but i hide them on the other selects i use but all the lines stay what can i do to fix that
so that when i hide all and show 1 it will only show that and not all the other `<li>` lines as well sins i have a lot of it

**Comment by Goten87** [comment]
lol my old script is not working anymore for jquery that sucks :(

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
