### ISSUE TITLE
Bootstrap 4 and navbar dropdown issue

### ISSUE THREAD

**Issue by pavlito** [snapappointments/bootstrap-select#1959]
Having console error when using bootstrap-select in bootstrap 4 navbar.
bootstrap-select.js:1597 Uncaught TypeError: Cannot read property 'update' of null
    at Selectpicker.setMenuSize (bootstrap-select.js:1597)
    at Selectpicker.setSize (bootstrap-select.js:1611)
    at HTMLButtonElement.<anonymous> (bootstrap-select.js:1910)
    at HTMLButtonElement.dispatch (jquery-3.2.1.slim.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.2.1.slim.min.js:3)

Also seems like plugin needs style for navbar

![ss 2](https://user-images.githubusercontent.com/3610827/38805234-69e1e9de-4175-11e8-96e6-b085e10e7afa.png)

**Comment by caseyjhol** [comment]
Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta.

**Comment by pavlito** [comment]
Hey @caseyjhol thanks on feedback.
I am using this version of plugin 1.13.0-beta.

**Comment by caseyjhol** [comment]
Can you confirm you are loading the bootstrap-select CSS *after* the Bootstrap CSS? Can you include a live demo of the problem? I'm not able to recreate the issue on my end.

Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by caseyjhol** [comment]
[v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0) has officially been released.

**Comment by dinatih** [comment]
Hello @caseyjhol, please can you tell me why is there 2 repos for this plugin https://github.com/snapappointments/bootstrap-select vs this one https://github.com/silviomoreto/bootstrap-select ?

**Comment by caseyjhol** [comment]
@dinatih See my comment here: https://github.com/snapappointments/bootstrap-select/issues/12#issuecomment-382790871.

**Comment by dinatih** [comment]
@caseyjhol Alright, thank you !
