### ISSUE TITLE
jQuery migrate warning: jQuery.fn.attr('selected') might use property instead of attribute

### ISSUE THREAD

**Issue by jamie-pi** [snapappointments/bootstrap-select#1960]
We want to remove jQuery migrate from our app, but the only thing that remains is this warning:
"jQuery.fn.attr('selected') might use property instead of attribute" coming from line 622 of "bootstrap-select.js".

```
if ($opt.attr('selected') === undefined && this.$element.data('selected') === undefined) {
    titleOption.selected = true;
}
```

This is similar to this issue here: https://github.com/silviomoreto/bootstrap-select/issues/94

Is there any reason why 'attr' is used here instead of 'prop'?

**NPM packages:**
"bootstrap-select": "1.12.4"
"jquery": "3.2.1"
"jquery-migrate": "1.4.1"

**Comment by caseyjhol** [comment]
`attr` retrieves/sets the actual `selected` attribute (i.e. the defaultSelected value). This attribute determines the initial selected state of the option. `prop` retrieves/sets selected "internally." Basically, that line of code is checking to see if the option was set to be selected manually in the DOM e.g. `<option value="1" selected></option>` vs being set programmatically via JS. As it's just a warning, I'd say it's safe to be ignored.

**Comment by jamie-pi** [comment]
That makes sense. Thanks for clearing that up.
