### ISSUE TITLE
IE11 Issue - Mouse Scroll Loses Focus on Drop Down with Live Search Enabled

### ISSUE THREAD

**Issue by 15BelowStudios** [snapappointments/bootstrap-select#1963]
IE11 Issue - Mouse Scroll Loses Focus on Drop Down with Live Search Enabled

When the "Live Search is **enabled**, if you mouse scroll down and select an option,the selected option is not shown/selected and instead the "focus" goes back to the top to the search box.

When the "Live Search" is set to **disabled**, the mouse scroll works and you can select an option (works properly).

This is only in IE11 as FF and Chrome do not have this issue.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, and bootstrap-select version.

**Comment by 15BelowStudios** [comment]
This is for IE 11 only as far as my testing:
1. Select on of the first options: "Abrasions"
2. Use mouse and scroll to one of the bottom options and select/click (ear infection)
NOTE: The issue only shows up using the mouse scroll, not the arrow/menu scroll.
3. "Ear Infection" will not be selected, and the focus will jump back up to "Abrasions"

https://jsfiddle.net/eshera/zkgLnfwn/
Bootstrap: 4.1.0
Bootstrap-Select: 1.13.0

**Comment by 15BelowStudios** [comment]
You may close and/or delete this thread as I found it is indeed with IE 11 and using the :
"data-live-search-placeholder" - when removed the issue does not accure:
https://github.com/silviomoreto/bootstrap-select/issues/851

**Comment by Datta-Telukunta** [comment]
I was also having the same issue. Do we have any solution for it
