### ISSUE TITLE
Add autocomplete attributes to data-live-search

### ISSUE THREAD

**Issue by rintiobootcamp** [snapappointments/bootstrap-select#1964]
Hello, 
we get a warning in browser console when we click on the  bootstrap-select element : 
[DOM] Input elements should have autocomplete attributes (suggested: autocomplete='address-level2')

it  seem like the data-live-search input doesn't have an autocomplete attribute. 

May you fix it. 

Thanks in advence. 

Best regards.

**Comment by NicolasCARPi** [comment]
There is autocomplete `off` or `list` now.
