### ISSUE TITLE
Autofill on iOS 9 Chrome jumps to the autofilled field when select dropdown is clicked

### ISSUE THREAD

**Issue by SvetlinStaev** [snapappointments/bootstrap-select#1965]
This happens only one mobile, specifically in Chrome browser when there is a password or other field which has autofill available in the browser and when the `mobile` option is set to true to invoke the native select menu.

I have tried it on iOS 9 with Chrome here - https://www.bezplatno.net/en/classifieds/new-listing
When the category dropdown is selected the page jumps to the bottom where the autofilled password field is located. Upon deselecting the autofilled field and retrying, the dropdown opens fine.

Any ideas what might be causing it? Tried disabling the autofill, but it is not completely consistent in Chrome and doesn't solve the issue, just patches the trigger for it.

**Comment by NicolasCARPi** [comment]
Closing as corner case and too old request.
