### ISSUE TITLE
new feature: please separate it to the smaller modules

### ISSUE THREAD

**Issue by rpokrovskij** [snapappointments/bootstrap-select#1967]
Current bootstrap-select (ver. 1.14.3) size is 
44KB form bootstrap-select.min.js 
It is just too big. 

E.g. chosen size is 12kb

May be I'm naive but:
Popper.js should be utilized (as it is included into bootstrap 4).
Polyfills should be excluded (webpack manage them better).
There should be possibility to include "single-select" or "multi-select" separate. I'm interesting only in multi-select.

This is not only about load performance but more about contributing, smaller scripts are more attractive for people who can say "lets check can I add this feature by meself".

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for your input. It is indeed important to keep the size of the library as small as possible and remove cruft over time.

May I suggest you use brotli compression to bring the size of your assets down?

At the moment this is not a priority and splitting the project might IMHO make it harder to maintain.
