### ISSUE TITLE
virtual-scrolling - modal on small screens bug

### ISSUE THREAD

**Issue by iDeedz** [snapappointments/bootstrap-select#1971]
I have found a bug with the virtual-scrolling branch.

This branch solved my previous issue I had with 10 000+ select items caused dropdowns to be slow and unresponsive when searching.

My new issue is that when you have selects inside a modal on a smaller screen sizes, at the bottom of the screen the dropdown items does not display.

Looks like a padding issue or something,
![screenshot_051018_092353_am](https://user-images.githubusercontent.com/381652/39857494-e086e05a-5433-11e8-916b-3c5c619b18fa.jpg)

**Comment by caseyjhol** [comment]
The version included in the virtual-scrolling branch was pre-alpha. Please try the latest stable release here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.1 and let me know if your problems persist. Please post any issues in that repo from now on.

**Comment by iDeedz** [comment]
Thank you very much for your feedback @caseyjhol 

Seems to be working perfect, searching as well as the dropdown size issue I was having, is gone.

Much appreciated!
