### ISSUE TITLE
Freeze of Chrome Extension when closing selectpicker

### ISSUE THREAD

**Issue by penseeartificielle** [snapappointments/bootstrap-select#1973]
Hi,

 I'm developing an extension for Chrome, and there is a really annoying bug.
1) Create an extension with popup.html and popup.js
2) Fix height of popup (body) at 80px for instance
3) Change height according to list, with content coming from code (in extension you can't make the list go outside of the popup) :
```
$('#selectList').on('show.bs.select', function (e) {
    $('body').height(600);
});
```
and
```
$('#selectList').on('hide.bs.select', function (e) {
    $('body').height(175);//$('body').height(80);
});
```

The bug is : if new height is lower than 175px, every thing freezes forever and is bugged (badly responding, can still click on invisible elements, search zone not hiding...).

Does anyone have an idea why there is a limit at 175px ?

**Comment by jaredsohn** [comment]
I have recently been experiencing similar things in a Chrome extension that I am working on. FYI, upgrading bootstrap-select from v12.x to v13.1 seemed to fix it for me.

(FWIW, the popup height of the extension I'm working on is around 80 px when the dropdown is collapsed.)
