### ISSUE TITLE
addResults true does not ask me to add result.

### ISSUE THREAD

**Issue by amsterdamharu** [snapappointments/bootstrap-select#1975]
## Bug

addResults is not behaving as expected.

```
$(`[data-role="autosuggest"]`)
.selectpicker({
    liveSearch: true,
    addResults: true
  });

```

I am using latest [here](https://codepen.io/amsterdamharu/pen/erPdLL?editors=0100) but setting addResult does not seem to behave as the [documentation](https://github.com/silviomoreto/bootstrap-select/blob/master/docs/docs/options.md) says it will (When set to true, replaces 'No Results' message with prompt to add search string to select options.) Instead I'm getting `No results matched "..."`

**Comment by AndrejGajdos** [comment]
+1

**Comment by caseyjhol** [comment]
I'm not sure where you were looking, but `addResults` is not part of any current or past bootstrap-select API.

**Comment by AndrejGajdos** [comment]
@caseyjhol there is a PR #1403
