### ISSUE TITLE
Data-style not working

### ISSUE THREAD

**Issue by Saifer707** [snapappointments/bootstrap-select#1976]
As title says:

```
<select class="selectpicker" data-style="btn btn-primary btn-round" title="Single Select" data-size="7">
      <option disabled selected> Roles</option>
      <option value="1">Admin</option>
      <option value="2">User</option>
</select>
```
data-style does not give style to select. 

Furthermore, in my Angular 2+ app, i can't change dropdown's style in css.

Thanks

**Comment by eailyass** [comment]
Hi,
I have the same issue, I tried to do like documentation says:
```Hint: If you want to style the element as a form control, set style to '' and styleBase to 'form-control'.```
But the btn class remains in the style!

**Comment by NicolasCARPi** [comment]
Please try with latest version.
