### ISSUE TITLE
.selectpicker('refresh') throws an error when called while an item in live search menu is active, but its option has been programmatically removed

### ISSUE THREAD

**Issue by David-Petrov** [snapappointments/bootstrap-select#1977]
So I've been fighting with that issue for a long time now. I mean, theoretically. The practical solution was not so hard and everything seems to be working fine as of right now. 
Description of the situation: I'm using bootstrap select with live-search and really enjoy doing so. But there was that problem. I wanted to dynamically fetch the options after the input field value's length overcame 3 characters, so I don't get extreme large chunks of data loaded at once. I've done that with a listener for the `input` event on the corresponding input field of an initially empty `select.selectpicker` (with no options). If the value is greater than 3, I'm sending an ajax and marking that I've fetched the results:

        if(val.length > 3 && !sp.data('options_loaded'))
        {
            $.ajax({
                method: 'GET',
                url: '/getSelectOptions', 
                data:{
                    search: val,
                    model_class: sp.data('relation_class')
                },
                success: function(data){
                    sp.html(data);
                    sp.selectpicker('refresh');
                    sp.data('options_loaded', true);
                    self.trigger('input'); //self refers to the input, i wanted to update the search automatically, so I triggered the input event. Works fine
                }
            });
            
        }
So far everything great, it works and the newly populated search filters the matches properly. But then I decided that I wanted to dispose the fetched options for those initial 3 digits after the input length decreases below 3, so I've extended that piece of code with an else statement:

    else if(val.length <= 3 && sp.data('options_loaded'))
    {
        sp.find('option').remove();
        sp.selectpicker('refresh'); //throwing the error

        sp.data('options_loaded', false);

        e.preventDefault();
        return;
    }

And here I faced a strange error in the console: `Uncaught TypeError: Cannot read property 'classList' of undefined` on line 809. So I checked out the code and it was this part causing the error:

    if (that.activeIndex !== undefined) {
          prevActive = that.selectpicker.current.elements[that.selectpicker.current.map.newIndex[that.prevActiveIndex]];
          active = that.selectpicker.current.elements[that.selectpicker.current.map.newIndex[that.activeIndex]];
          selected = that.selectpicker.current.elements[that.selectpicker.current.map.newIndex[that.selectedIndex]];

          if (init) {
            if (that.activeIndex !== that.selectedIndex) {
              active.classList.remove('active'); //line 809
              if (active.firstChild) active.firstChild.classList.remove('active');
            }
            that.activeIndex = undefined;
          }

          if (that.activeIndex && that.activeIndex !== that.selectedIndex && selected && selected.length) {
            selected.classList.remove('active'); 
            if (selected.firstChild) selected.firstChild.classList.remove('active');
          }
        }
So I guess this appears to be a problem because the actual option that `active` element refers to has been deleted, but the plugin presumes that it should exist given the fact that the corresponding `<li>` is currently selected in the live search bar. And that error was block the further proper execution of the `.selectpicker('refresh')` event. I haven't digged up to find out the exact significance of this piece of code, but I guess it's simply stylistic as the solution was quite easy and had no further consequences. I've simply added a check like that:

        if (that.activeIndex !== that.selectedIndex && active)//line 808
and everything worked. So I wanted to share that problem with the community and the creator and I hope that this will be carefully reviewed as a presumable issue and fixed in the next release of the plugin. Thanks in advance!

**Comment by emircansancar** [comment]
I've had the same problem and solved it that way. This update needs to be done in the new version.

**Comment by caseyjhol** [comment]
See #2189. Will be fixed in next release.
