### ISSUE TITLE
Modal reopen problem

### ISSUE THREAD

**Issue by mbraidy** [snapappointments/bootstrap-select#1983]
I have a modal with some bootstrap-select in it.
The first time I launch the modal, the dropdowns are rendered properly and I can use them.  If I dismiss the modal (hide it) and reopen the modal, the dropdowns are rendered properly and then disappear after less than 1 second.

I need to refresh the whole page to get the dropdowns  to work again.

Is this a modal problem? I have no problem with other plugins or code.
Is this a setup problem?  What should I do?

Thank you

**Comment by mahmoudafer** [comment]
hello, i had a similar problem where i was using vuejs for my frontend and i had some bootstrap-select elements in a modal, whenever i open another component and then get back to the previous component, the dropdowns get empty (note that I am fetching data and populating every time. So i fixed it with this function:

```js
function select_refresh(ref, data, id, name) {
    let item_index = 1;
        $(ref).empty();
        $.each(data.data, function(index, value) {
            $(ref).append('<option value="'+ value[id] +'">' + value[name] + '</option>');
            $(ref).parent().find('div ul.inner').append(
                '<li data-original-index="'+ item_index +'">' +
                '    <a tabindex="0" class="" data-tokens="null" role="option" aria-disabled="false" aria-selected="false">' +
                '        <span class="text">' + value[name] + '</span>' +
                '        <span class="glyphicon glyphicon-ok check-mark"></span>' +
                '    </a>' +
                '</li>'
            );
            item_index++;
        });
    $('.selectpicker').selectpicker('refresh');
}
```

In the parameters:
ref is the reference to the dropdown like $("#select-id").
data is the data I'm fetching and populating (includes ID and Name).
id and name are the name of the fields, for example if i just fetched a"supplier" object in the data.. its fields are "Supplier_ID" and "Supplier_Name".

I hope this helps

**Comment by mbraidy** [comment]
Thank you mahmoudafer for your answer
However my problem is a bit different.  The options are there and no need to insert them.
I can see the options with Dev Tools in the right place, but nothing is shown.
When I launch the modal first time, it works properly.  This is what is shown:
![first-time](https://user-images.githubusercontent.com/1821891/44525463-46c57c00-a6e1-11e8-889c-56015ccafde2.png)




However when I launch the modal a second time, I get this:
![second-time](https://user-images.githubusercontent.com/1821891/44525501-678dd180-a6e1-11e8-98f1-8464a7cd26cd.png)

The drop down is not rendered even though the select/options are there.

The reason  is that the select is not inside this div

```
<div class="dropdown bootstrap-select form-select fit-width">

// ******************* SELECT TAG HERE ********************

          <button type="button" class="btn dropdown-toggle bs-placeholder btn-link"
                       data-toggle="dropdown" role="button" data-id="districtID" title="Select a district..">
                ::before
                 <div class="filter-option">
                     <div class="filter-option-inner">
                          <div class="filter-option-inner-inner">Select a district..</div>
                     </div>
                </div>
                <span class="bs-caret">
                      <span class="caret"></span>
                </span>
         </button>
        <div class="dropdown-menu open" role="combobox">
            <div class="bs-searchbox">
                <input type="text" class="form-control" autocomplete="off" role="textbox" aria-label="Search">
            </div>
            <div class="inner open" role="listbox" aria-expanded="false" tabindex="-1">
                <ul class="dropdown-menu inner "></ul>
            </div>
       </div>
</div>

```
For some odd reason, that div disappears when I dismiss the modal and launch it a second time.

**Comment by mbraidy** [comment]
Thank you mahmoudafer
I moved this issue to the main thread and closing this one
