### ISSUE TITLE
Unable to pull select IDs when class=selectpicker

### ISSUE THREAD

**Issue by atssmith** [snapappointments/bootstrap-select#1984]
Hello,

I am building a form using--among other things--Bootstrap select. I have run into a problem, though: for all select elements where I use Bootstrap Select, the element ids become undefined. This is messing with a validation piece I have.

I have provided an example below. Note that the example also has the class "dropdownVal":

     <label for="facilityPP">Point Prevalence Facility:</label>

     <select data-style="btn-outline-primary" data-dropupAuto=false class="selectpicker show-tick d- 
         block dropdownVal" name="facilityPP" id="facilityPP" required title="Choose..." >
          <CFOUTPUT QUERY="FacilitiesQry">
              <OPTION value="#FacilitiesQry.facility_ID#">#FacilitiesQry.facility_abbr#</OPTION>
          </CFOUTPUT>
     </select>

Upon submit, it passes to another page with this function:

	$(".dropdownVal").each(function() {
			isBlankSelect($(this).attr("id"))
	})
Which then goes to this:

function isBlankSelect(field)
{
	var xS=document.getElementById(field).value
 	if(document.getElementById(field).hasAttribute('required')) {
	if (xS=="") {
		nonBtInv=1;
		document.getElementById(field + "-Blank").style.display='block';
		}
}
}

Now, whenever I run this, function isBlankSelect fails at all Bootstrap Select elements. When I added
alert("the ID of this element is " + $(this).attr("id") + ".") to the .dropdown function, I discovered that the id of all elements was "undefined".

I have tried adding $(".selectpicker").selectpicker(), refresh, and render to the page, without effect.

Thanks for your help!

**Comment by caseyjhol** [comment]
bootstrap-select doesn't do anything to change the ID of the original select element, so I'm not sure what would be causing that particular issue. Is it possible it's related to another plugin you're using? 

Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by atssmith** [comment]
Could you explain more what you mean by being related to another plugin?

I know it at least has something to do with bootstrap select, because all I have to do is remove the class "selectpicker" and the problem is solved.

I will create a live demo later in the day.

**Comment by rmarzocchi84** [comment]
I encountered the same problem.. 

I have a select input form defined as disabled
` <select disabled id="via-list" class="selectpicker show-tick form-control" data-live-search="true" onChange="getCivico(this.value);" required>`

and a radion button 

`<div class="form-group">
					<label for="nome">Text of uestion?</label> <font color="red">*</font><br>
					<label class="radio-inline"><input type="radio" name="georef" id="civico">Option 1</label>
					<label class="radio-inline"><input type="radio" name="georef" id="mappa">Option 2</label>
					<label class="radio-inline"><input type="radio" name="georef" id="coord">Option 3</label>
				</div>
`
Normally I use a javascript function to enable the selectpicker input of my form: 


`(function ($) {
    'use strict';
    $('[type="radio"][id="civico"]').on('change', function () {
        if ($(this).is(':checked')) {
            $('#via-list').removeAttr('disabled');
            $('#civico-list').removeAttr('disabled');
            $('#lat').attr('readonly', true);
            $('#lon').attr('readonly', true);
            $('#lat').val('');
            $('#lon').val('');
            $("#mapid").off("onclick");
            	mymap.off('click', onMapClick);
            return true;
        }
    });    
}(jQuery));`


but it seems do not recognize the "id" of my selectpicker input

**Comment by rmarzocchi84** [comment]
Here my example:

[https://codepen.io/rmarzocchi84/pen/QVQyVK](https://codepen.io/rmarzocchi84/pen/QVQyVK)

**Comment by caseyjhol** [comment]
@rmarzocchi84 In your example, your select element doesn't have an ID. Also, you need to call `selectpicker('refresh')`. Please read the documentation: https://developer.snapappointments.com/bootstrap-select/methods/#selectpickerrefresh

**Comment by rmarzocchi84** [comment]
Thanks @caseyjhol  for your reply. I updated the example and it works. I think the updated example can be useful for further users.
