### ISSUE TITLE
How I can remove the current selection back to default value or placeholder?

### ISSUE THREAD

**Issue by Matias-Carazzo** [snapappointments/bootstrap-select#1985]
Hi, not sure if it is a bug or a new feature.

Just want to know how I can remove the current selection back to the default value or the placeholder?

Im using the select to select different values in a report filter and I want to give the option to final users to remove all the filters. So I need to remove the selected value on the select lists.

Thanks

**Comment by mahmoudzadah** [comment]
+1

**Comment by caseyjhol** [comment]
Please 👍 and follow #1449.
