### ISSUE TITLE
Bootstrap select handle huge entries 

### ISSUE THREAD

**Issue by KarthikKasiram** [snapappointments/bootstrap-select#1987]
Hello Experts, 

I am using bootstrap-select (Version 1.12.2) in my JSP page and the requirement is to load  ~100000 entries in the dropdown dynamically using ajax javascript calls  (And I have 5 to 6 such dropdowns on the same page). I understand that if we load such huge data the browser becomes unresponsive and breaks and I also went through eariler issues reported for this #1229 . Is there a way to achieve this functionality using latest version? 
Any other alternative suggestions are also welcome :) 
TIA

**Comment by dedeparisg** [comment]
Hello,
I've the same problem.

**Comment by caseyjhol** [comment]
Using the latest version should solve this problem. The latest version is available here: https://github.com/snapappointments/bootstrap-select. Development has moved there.
