### ISSUE TITLE
intermittent issues concerning function scroll()

### ISSUE THREAD

**Issue by MarkClouden** [snapappointments/bootstrap-select#1990]
recently updated to 1.13.1 in order to resolve a search issue (Thanks!), but have come across one more small item.

I am hard-pressed to describe this one - it concerns this code

var size = that.selectpicker.current.elements.length;
        var chunks = [];
        **var chunkSize = Math.ceil(that.sizeInfo.menuInnerHeight / that.sizeInfo.liHeight * 1.5); // number of options in a chunk**
        var chunkCount = Math.round(size / chunkSize) || 1; // number of chunks
        var currentChunk = undefined;

Specifically, that we see that.sizeInfo.menuInnerHeight being a negative number in some odd scenarios (knockout is in-play here, so i dont know if i could contrive a valid scenario to describe). I also am not sure where that.sizeInfo.menuInnerHeight comes from, why it could be negative, if it should never be, or any of that. All I know is that we do see it, and we have required a change to defend against that situation by simply setting the chunkSize to 1 and allowing the code to continue on its way. This is working to resolve the issue for us.

Thank you

**Comment by caseyjhol** [comment]
Fixed in v1.13.6 - see #2198.
