### ISSUE TITLE
Vertical scrolling no longer works correctly after changing select option font size

### ISSUE THREAD

**Issue by gcafengui** [snapappointments/bootstrap-select#1992]
When changing the font size of the select option the vertical scrolling no longer works correctly. For example, if you change the font size in the option tag to 16px and you vertically scroll down a list of 20 options by using the down arrow key you will see it does not scroll down properly after 10 items or so....also when selecting an option and then clicking the dropdown...the selected option is not in the proper scrolling position.

**Comment by gcafengui** [comment]
v1.13.1 breaks vertical scrolling with bootstrap 3. Reverted back to v1.12.4 and all is well.

**Comment by caseyjhol** [comment]
There have been a lot of improvements in scrolling since v1.13.1. I'm going to assume this has been fixed since then, but if anybody is still experiencing this problem and can provide an example I'd be happy to take a look.

**Comment by lauracabre** [comment]
Hi, I downloaded 1.13.14 but I am still having this particular issue. If I reduce the font of the data within the dropdown, the issue disappears.
