### ISSUE TITLE
About bootstrap 4 support

### ISSUE THREAD

**Issue by AnnoyingTechnology** [snapappointments/bootstrap-select#1993]
Hello,

Do you have an approximate release date for a bootstrap 4 compatible version ?
In the README you talk about help, how could someone help on that subject ?

Love this extension by the way :+1: 

Thanks !

**Comment by Tooluloope** [comment]
Yes, I seriously just knew about this and fell in love with it, only to find out that its incompatible with bootstrap 4.1. That's really sad. 
I'll love it if you could help with this

**Comment by caseyjhol** [comment]
Bootstrap 4 support is available with the latest release, v1.13.1, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.1. Please post any issues in that repo from now on. I have moved development there.

**Comment by AnnoyingTechnology** [comment]
Great ! Thank you
