### ISSUE TITLE
not showing options

### ISSUE THREAD

**Issue by zoigecyb** [snapappointments/bootstrap-select#1997]
hello. 
option list is empty. but in code i can see <ul> list.
native select 
```
<select id="mysel" class="selectpicker"
<option value="5">someopt</option>
<option value="423">anotheropt</option>
</select>
```

and also in ul list there are no option values, it converts them to indexes.

**Comment by jerzy-dudzic** [comment]
I have similar problem. First open works fine, the next ones don't.
It seems that the **div.dropdown-menu** doesn't get the **open** class. If I add this manually then the entries are shown.

EDIT: And it turned out to by caused by another jQuery plugin.

**Comment by zoigecyb** [comment]
In my case it triggers open class, but the list i see is one empty line.

**Comment by Kitsunemimii** [comment]
I have the same problem that my options aren't shown.  (version 1.12.3)

I only have jQuery, popper and bootstrap implemented.

The searchbar is shown and I can type in the options that should be there and they get selected but the whole option list isn't shown at all

**Comment by jerzy-dudzic** [comment]
I was not able to fix the issue myself. I ended up using this plugin instead: http://davidstutz.de/bootstrap-multiselect/)

**Comment by Kitsunemimii** [comment]
Thanks for the tip!

This plugin is working but it's not as nice to use as other one, because it's converting the selectbox into a dropdown with radio buttons. You have to click the text or radio button.

**Comment by dtr4x** [comment]
Here is a jsfiddle basic example

https://jsfiddle.net/aq9Laaew/100740/

**Comment by zoigecyb** [comment]
the problem exactly as in david-dd4 example.

**Comment by Azuryu** [comment]
Same Problem here. I'm using Bootstrap v4.1.3 with jQuery 3.3.1. Reason seems to be that there's missing some CSS in Bootstrap v4.1.3 that was there on earlier versions:

```
.open>.dropdown-menu {
    display: block;
}
```
Adding this myself makes the invisible options visible for me. It looks ugly though but that's probably caused by my own CSS.

**Comment by caseyjhol** [comment]
Only versions v1.13.0+ of bootstrap-select are compatible with Bootstrap 4.
