### ISSUE TITLE
data-live-search and multiple, missed the selected first active item after selected another item

### ISSUE THREAD

**Issue by spairy** [snapappointments/bootstrap-select#1999]
This is my html code[1.13.1]:

`<select class="selectpicker" multiple data-live-search="true">`
`  <option data-tokens="ketchup mustard">Hot Dog, Fries and a Soda</option>`
`  <option data-tokens="mustard">Burger, Shake and a Smile</option>`
`  <option data-tokens="frosting">Sugar, Spice and all things nice</option>`
`</select>`

when I keydown with "s", the item "<option data-tokens="ketchup mustard">Hot Dog, Fries and a Soda</option>" is active with blue backgroud. Then I click it to select it marked with "√". After I click other item and marked "√", the first selected item lost its  "√".

**Comment by caseyjhol** [comment]
Released in [v1.13.2](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.2)!
