### ISSUE TITLE
Selectpicker Option Rendering Issue on IE 11.4 

### ISSUE THREAD

**Issue by deborahpoulsen** [snapappointments/bootstrap-select#2004]
This is only happening on IE 11.4. When I click on the selectpicker to see the options, I can see all the options for 1 second. After that, all the options disappear; however, when I hover over them, they appear again. I was wondering if there is a way to prevent this from happening? Thanks!
![image](https://user-images.githubusercontent.com/41598456/43108178-64740f5a-8e95-11e8-886f-36f6705e62b4.png)

**Comment by caseyjhol** [comment]
Can you link me to a live example?
