### ISSUE TITLE
Bootstrap 4.1 Support

### ISSUE THREAD

**Issue by amit996** [snapappointments/bootstrap-select#2006]
Will it ever support Bootstrap 4?

**Comment by slidenerd** [comment]
1.13.1 as the author claims already supports bootstrap 4

**Comment by okonkole** [comment]
Hi everyone,

I'm also looking forward to using "bootstrap-select" in the lastest bootstrap version (4.1.3).

The last version of bootstrap-select I found in the repository in 1.12.4... @slidenerd , where did you get this 1.13.1 version ?

Thx

**Comment by Picpool** [comment]
Hi, i try also to make it woks with Bootstrap 4.1.3 is there a workaround or an update ?
thanks

**Comment by kinoli** [comment]
It works fine with 1.13, except I can't get liveSearch to work.

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css">
```

**Comment by Picpool** [comment]
thanks a lot, liveSearch works fine !

**Comment by GregObleshchuk** [comment]
I have it working on 4.1.2 or bootstrap but the dropdowns don't open first time.  I click once nothing then click it again and it works fine.  Does anyone else have this issue?

**Comment by caseyjhol** [comment]
You can now find v1.13.0+ in this repository. See https://github.com/snapappointments/bootstrap-select/releases.
