### ISSUE TITLE
Feature: Add custom button to action box 

### ISSUE THREAD

**Issue by jeffreymeng** [snapappointments/bootstrap-select#2007]
It would be great if there was an api to add more buttons to the action box. You would be able to use the api to add a button with custom attributes(such as id) that let you attach handlers and perform an action when the button is clicked.

Possible use case: Instead of only having the `select all` and `select none` options you could add a `select defaults` option to a multiple select.

**Comment by caseyjhol** [comment]
Duplicate of #1299.
