### ISSUE TITLE
Is there a way to auto-size the width of the control to the content

### ISSUE THREAD

**Issue by Sicos1977** [snapappointments/bootstrap-select#2055]
I'm using version 1.13.

Is there a way to make the width of the control auto-size to the content that is in it?
I used to make this work with previous version by just changing these lines in the css file.

.bootstrap-select:not([class*="col-"]):not([class*="form-control"]):not(.input-group-btn) {
  width: 220px;
}

to...

.bootstrap-select:not([class*="col-"]):not([class*="form-control"]):not(.input-group-btn) {
  width: auto;
}

But if I do that now I just end up with a very width control that is much wider then the width of the widest content.

**Comment by caseyjhol** [comment]
See the width option:
https://developer.snapappointments.com/bootstrap-select/options/
https://developer.snapappointments.com/bootstrap-select/examples/#width
