### ISSUE TITLE
No proper rendering in a modal when launched a second time

### ISSUE THREAD

**Issue by mbraidy** [snapappointments/bootstrap-select#2057]
I have a modal with some bootstrap-select in it.
The first time I launch the modal, the dropdowns are rendered properly and I can use them. If I dismiss the modal (hide it) and reopen the modal, the dropdowns are rendered properly and then disappear after less than 1 second.

I need to refresh the whole page to get the dropdowns to work again.

I can see the options with Dev Tools in the right place, but nothing is shown.
When I launch the modal first time, this is what is shown:
![first-time](https://user-images.githubusercontent.com/1821891/44525463-46c57c00-a6e1-11e8-889c-56015ccafde2.png)

It works fine!

However when I launch the modal a second time, I get this:
![second-time](https://user-images.githubusercontent.com/1821891/44525501-678dd180-a6e1-11e8-98f1-8464a7cd26cd.png)

The drop down is not rendered even though the select/options are there.

The reason  is that the select is not inside this div

```
<div class="dropdown bootstrap-select form-select fit-width">

// ******************* SELECT TAG HERE ********************

          <button type="button" class="btn dropdown-toggle bs-placeholder btn-link"
                       data-toggle="dropdown" role="button" data-id="districtID" title="Select a district..">
                ::before
                 <div class="filter-option">
                     <div class="filter-option-inner">
                          <div class="filter-option-inner-inner">Select a district..</div>
                     </div>
                </div>
                <span class="bs-caret">
                      <span class="caret"></span>
                </span>
         </button>
        <div class="dropdown-menu open" role="combobox">
            <div class="bs-searchbox">
                <input type="text" class="form-control" autocomplete="off" role="textbox" aria-label="Search">
            </div>
            <div class="inner open" role="listbox" aria-expanded="false" tabindex="-1">
                <ul class="dropdown-menu inner "></ul>
            </div>
       </div>
</div>

```
For some odd reason, that div disappears when I dismiss the modal and launch it a second time.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.
