### ISSUE TITLE
IOS native dropdown not working.

### ISSUE THREAD

**Issue by logicsdrive** [snapappointments/bootstrap-select#2059]
IOS native dropdown not working with bootstrap 4 and this beta version of selectpicker. Native dropdown flashes and then hide we can't select any option on mobile.

**Comment by caseyjhol** [comment]
What version of iOS are you using? What web browser?

**Comment by logicsdrive** [comment]
IOS v 11.4.1
Browser Safari

**Comment by logicsdrive** [comment]
@caseyjhol any update?

**Comment by caseyjhol** [comment]
Seems to be a duplicate of #1828.
