### ISSUE TITLE
Elements in an input group below a selectpicker have a higher z-index, causing them to appear above the opened menu

### ISSUE THREAD

**Issue by BI7PRK** [snapappointments/bootstrap-select#2078]
![default](https://user-images.githubusercontent.com/24989210/44649595-edc65280-aa16-11e8-8947-e7baa2f27e17.png)

I have tried to rewrite,
 it has not been solved.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, **Bootstrap version, bootstrap-select version, and specific browser and OS details**.

**Comment by TomKrakott** [comment]
Since 1.13.0, when you place the select in input-group, you've got this case : 
https://jsfiddle.net/Thanaucy/6v01gfrs/
Work in 1.12.4

**Comment by bazineta** [comment]
Have this issue as well. @caseyjhol, if you've got a pointer on where to look, I can take a stab at it.

**Comment by bazineta** [comment]
@caseyjhol Just trying to move the ball forward here; it seems that the issue I'm seeing stems from line 23 of `bootstrap-select.less`:
```
z-index: 1;
```
If I comment that out, my issue seems to go away without breaking anything else, at least so far as I can see at the moment. The purpose of that particular z-index is at present unclear to me, but it's not as if that's saying much, really...the set of things that are unclear to me is, regretfully, quite large.

**Comment by caseyjhol** [comment]
@bazineta That was first introduced in commit 9dfbe558a9be51747fa85574adddd910fc6683bd when support for HTML5 validation was added. Originally, the select was inserted *after* the button, which is why z-index needed to be set on the button. Since commit 303eb95811fd07345e09c61aab929def00c8a30e, though, where support for pseudo class styling was added, setting the z-index there has been unnecessary (as the select element is now *before* the button). Thanks for catching that! Will get this out in the next release.

**Comment by caseyjhol** [comment]
This issue mostly stems from the fact that since v1.13.0-beta, the `input-group-btn` class is no longer automatically applied to the `.bootstrap-select` div (as styling is automatically inherited).

**Comment by caseyjhol** [comment]
Released in [v1.13.6](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.6)!
