### ISSUE TITLE
check mark hidden in Internet explorer 11 while selecting in multiselect select picker

### ISSUE THREAD

**Issue by rahulsomkunwar** [snapappointments/bootstrap-select#2080]

**Comment by caseyjhol** [comment]
It seems to be working for me: https://developer.snapappointments.com/bootstrap-select/examples/#multiple-select-boxes. Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by rahulsomkunwar** [comment]
It was an issue with the checkbox icon I was using, I have found a workaround,
Thanks for the prompt reply.
