### ISSUE TITLE
CDNJS not automatically updating after release

### ISSUE THREAD

**Issue by holtkamp** [snapappointments/bootstrap-select#2083]
Is CDNJS version updated automatically?

~20 hours after `1.13.2` was tagged, it is (still) not available at CDNJS https://cdnjs.com/libraries/bootstrap-select
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/bootstrap-select

As a results, these URLs result in a `HTTP 404`:
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/bootstrap-select.js
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/bootstrap-select.min.js

This guide describes how this can be configured: https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

**Comment by holtkamp** [comment]
Mmm, when looking a bit closer at https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/bootstrap-select/package.json, it seems it **is** properly configured, will wait a bit longer then 😄

**Comment by caseyjhol** [comment]
Yea, not sure what the delay is here. Will contact the devs.

**Comment by MartinKolarik** [comment]
Alternatively there's https://www.jsdelivr.com/package/npm/bootstrap-select which has no delay at all.

**Comment by holtkamp** [comment]
Issue at CDNJS for monitoring purposes: https://github.com/cdnjs/cdnjs/issues/12928, can people upvote that issue to get their attention?

**Comment by caseyjhol** [comment]
v1.13.2 is now available!

**Comment by holtkamp** [comment]
Nice, kudos for the persistence to get this resolved. 

While trying to understand https://github.com/cdnjs/cdnjs/issues/12928#issuecomment-425324453, will the next bump in the release number be "processed" automatically again?

**Comment by caseyjhol** [comment]
It should be processed automatically, yes. I don't foresee a change in file structure until v1.14.0 at the earliest, and even then it seems like adding files doesn't cause any issues, only removing files.

**Comment by holtkamp** [comment]
Fingers crossed for `1.13.3` 🤞 

Let's see when
https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.3

lands at
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.3/js/bootstrap-select.min.js

**Comment by holtkamp** [comment]
@caseyjhol thinks this issue can/needs to be re-opened...

**Comment by caseyjhol** [comment]
Waiting for the CDNJS team to take care of this. In the meantime (and in future releases until I'm confident they have resolved the issue), I'm recommending jsDelivr: https://www.jsdelivr.com/package/npm/bootstrap-select?path=dist.

**Comment by caseyjhol** [comment]
It looks like v1.13.3 is available now.

**Comment by caseyjhol** [comment]
It looks like v1.13.3 was committed to the repo about 20 minutes after its release, but for some reason didn't show up as available until today: https://github.com/cdnjs/cdnjs/commit/be1ce9576048ecbc4d39ef0076dbf7fd9bd27f30.

**Comment by caseyjhol** [comment]
Apparently they were having issues with their auto-update script that have been resolved.

**Comment by holtkamp** [comment]
Again fingers crossed for `1.13.4` and `1.13.5` 🤞

Let's see when
https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.4
https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.5

lands at
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.4/js/bootstrap-select.min.js
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.5/js/bootstrap-select.min.js

Seems no commit has been done yet: https://github.com/cdnjs/cdnjs/search?o=desc&q=bootstrap-select&s=committer-date&type=Commits

**Comment by holtkamp** [comment]
Both releases have reached CDNJS 👍 :

https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.4/js/bootstrap-select.min.js
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.5/js/bootstrap-select.min.js

This seems to be done by @PeterDaveHello manually using https://github.com/cdnjs/cdnjs/commit/a36bdef0b37c5fbd8a1014fb7a10d8a631c31366

Next release we should still keep an eye out whether the auto-update process properly detects the new release.

**Comment by caseyjhol** [comment]
@holtkamp Thanks for taking care of this. I'm hoping the CDNJS team can get this figured out, as I prefer it to jsDelivr, but I think I'll have to start recommending that with the next release unless I hear anything promising from the CDNJS team.

**Comment by PeterDaveHello** [comment]
I believe the auto-update detects all the updates, the reason why the bot didn't add it, is because of the change of the directory/file structure, that needs manual reviews, sorry for the delays, as I'm mostly the only one runs the project, and there are some projects not like this one to have good structure, which needs manual reviews to confirm the diffs. We don't have a project whitelist mechanism to skip the review yet, I'm trying to do my best to get the review done faster.
