### ISSUE TITLE
How to get current new selected value for multiple select

### ISSUE THREAD

**Issue by snd1890** [snapappointments/bootstrap-select#2088]
$('#year').on('change', function(e) {
               console.log($('#year').val()); //get all selected value
               console.log(e.target.value); //get first selected value
}
i have also try "changed.bs.select" but not get my result please guid me how to get current new selected value

**Comment by caseyjhol** [comment]
```js
$('#mySelect').on('changed.bs.select', function (e, clickedIndex, isSelected, previousValue) {
  console.log( $(this).find('option').eq(clickedIndex) );
});
```
