### ISSUE TITLE
Tooltip Implemantation

### ISSUE THREAD

**Issue by Bruskyer** [snapappointments/bootstrap-select#2090]
Hi
Im using bootstrap and bootstrap select with dynamic data (from web service, like country list) also I use liveseach everything is ok but I need to add tooltip with same text when move mouse over each item but I can't I only made it for static option "value" or option title "text" how is it possible to implement this feature.
regards
thanks

**Comment by caseyjhol** [comment]
If using the latest version, something like:

```js
$('#number').on('shown.bs.select', function () {
  $($(this).data('selectpicker').selectpicker.current.elements).attr('title', 'New Title').tooltip();
});
```

In the future, please ask questions like this on Stackoverflow. This one has already been answer for v1.12.4: https://stackoverflow.com/questions/31270151/silviomoreto-bootstrap-select-tooltip-on-options.

**Comment by Bruskyer** [comment]
thanks a lot for reply now its working with one static text that defined ('title', 'New Title') for all item
$('selectpicker').selectpicker.current.elements).text()
put all item texts in tooltip! but when move the mouse the value also should change with in tooltip(only for its value)
https://cdn1.imggmi.com/uploads/2018/9/7/21093ba294817db8cb4cf968e467fe64-full.png
what is the wrong?
above link method also not working :(
regards, thanks
