### ISSUE TITLE
Cant disable dropupAuto

### ISSUE THREAD

**Issue by vktrwlt** [snapappointments/bootstrap-select#2093]
I am using Boostrap-select 1.13.1 with Bootstrap 4 and I am trying to disable the dropupAuto functionality.

I try passing in as dropupAuto= "false" as an attribute and also set it to false in the constructor, but its it not turning it off. 

Not sure why I cant disable dropup

Here is an example

[https://codepen.io/vtsang/pen/wErxgL](https://codepen.io/vtsang/pen/wErxgL)

**Comment by caseyjhol** [comment]
Via JS, it needs to be a boolean (so `false` instead of `"false"`). Via data attribute, you need to use `data-dropup-auto="false"`.
