### ISSUE TITLE
CDN not working

### ISSUE THREAD

**Issue by michaelBielang** [snapappointments/bootstrap-select#2096]
These are not available:

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/css/bootstrap-select.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/bootstrap-select.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/i18n/defaults-*.min.js"></script>

**Comment by caseyjhol** [comment]
Working with CDNJS to see if we can get this resolved. See #2083. In the meantime, you can use https://www.jsdelivr.com/package/npm/bootstrap-select.

**Comment by Pyvonix** [comment]
I confirm the CDN specified in the document desn't work. 
Thank for the alternative link.
