### ISSUE TITLE
Cannot read property 'display' of undefined

### ISSUE THREAD

**Issue by iscorporacion** [snapappointments/bootstrap-select#2097]
a few days ago I'm reporting this error in the console, Cannot read property 'display' of undefined at e (bootstrap-select.js:2727)

**Comment by caseyjhol** [comment]
Duplicate of #2086. Please search next time.

**Comment by AkhirahStrong** [comment]
This didn't answer my question either, and by your response, this doesn't seem to be a friendly and understanding platform to as questions, and I have been researching btw.

**Comment by caseyjhol** [comment]
@ahkyhabib What's your question? For this particular issue you're responding to, there was already a recently created issue with a nearly identical title. It's hard enough as is to respond to every issue, made harder when people don't search beforehand and create duplicate issues. If you've searched and haven't found anything, go ahead and create a new issue.
