### ISSUE TITLE
How to give a custom order with MULTISELECT

### ISSUE THREAD

**Issue by Picpool** [snapappointments/bootstrap-select#2099]
Hi,

Is it possible to have a custom order diffent with the multipleselect
thanks

**Comment by caseyjhol** [comment]
Can you elaborate or give an example?

**Comment by Picpool** [comment]
Well when i use multiselection the order is the one of the select value, what i need is to define the order of the item selected.

**Comment by caseyjhol** [comment]
Closing this in favor of #2119.
