### ISSUE TITLE
Getting value problem

### ISSUE THREAD

**Issue by ndmuratsahin** [snapappointments/bootstrap-select#2100]
Hi,
Sometimes I get the null value from selectpicker. I always get the successfull result, If I put a delay between setting value and displaying data'. On the other hand  I tried "render" method instead of "refresh". But the result didn't changed. What should I do? 
 
   $('#gateway').val(data.GatewayID);                
   $('#gateway').selectpicker("refresh");                    
   console.log(data.GatewayID);
   console.log($('#gateway').val());

Successfull output of console: 
    1
    1 

Sometimes I get null value. The output of console:
    1
     null

**Comment by caseyjhol** [comment]
`.val()` is a native jQuery method. If you're running into issues retrieving the value after it has been set, that sounds like a jQuery issue.

Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.
