### ISSUE TITLE
angular 5 bootstrap-select: selectpicker is not a function

### ISSUE THREAD

**Issue by ad-el** [snapappointments/bootstrap-select#2102]
Please look at
https://stackoverflow.com/questions/52331371/angular-5-bootstrap-select-selectpicker-is-not-a-function
where I described the issue.

Also if I add to style.css a line:
@import "~bootstrap-select/dist/css/bootstrap-select.css";
then select element is not visible.

**Comment by vigamage** [comment]
any updates on this?
