### ISSUE TITLE
Bottom elements in drop drown are disappear if you have more the 599 elements

### ISSUE THREAD

**Issue by pusidroid** [snapappointments/bootstrap-select#2108]
Hi,

i have a long list of options, which seem to be failing to show the last few elements.
When you scrolling down or stepping by the keyboard and you are getting close to the last few elements the list is just disappears.  I checked the li elements in the html and it contain elements from the first option again. And top and bottom margin is set to the default as it would jumped around and wanted to start to scroll from beginning again. However the drop down itself is blank

I tried in different scenarios. It depends on what is the container of the select. Which probably overrides some features.

here is my jsfiddle for it. hope its good enough
http://jsfiddle.net/pusidroid/q15bcL8z/

1. Chrome Version 69.0.3497.100 (Official Build) (64-bit). 
 if i add     -webkit-appearance: menulist: to the container in my server however this not helps on jsfiddle

2. the add moz/ms appearenace: menulist did not helps in firefox or edge. So same problem

Thank you, .
as this is my first report, i hope it`s good enough to explain what (i think) the problem
r

**Comment by caseyjhol** [comment]
All of options appear to show properly in the example you've linked. In any case, you're loading two versions of Bootstrap, as well as two versions of bootstrap-select (it's not clear which version of Bootstrap you're intending to use, check the "resources" menu on the left). Please clean up your example (and ensure you're loading Popper if you're intending to use Bootstrap 4+) and let me know if the issue persists.

**Comment by pusidroid** [comment]
new js fiddle 
http://jsfiddle.net/q15bcL8z/15/

First of all thanks for your information.
Now i changed the css and js includes. 
Still. When you scroll the second (lower option) to 599 its ok As you click on down scrollbar arrow or scroll a bit more, everything disappear so the last item cant be selected. If you scroll up again , list comes back without last element.
Now interesting things:  i checked this jsfiddle on chrome and firefox
-on chrome
if the drop down drops up because of space limitation it works fine.
If you lock the data-size to 5 or 10 still works fine.
If there is now data size and it uses all spaces doesn`t work. 
-firefox
if you check the same jsfiddle link in ff both going mental at if you want to select the last item.
if you set data-size for them both works.

Please let me know if you find the same issues as me. Even if not. Because its more interesting than
Thank You

**Comment by caseyjhol** [comment]
I was able to replicate the issue when visiting the HTTPS version of your demo. However, you're still loading two sets of JS/CSS. After removing the JS and CSS from the resources menu in the left column, the issue no longer persisted.

**Comment by pusidroid** [comment]
Oh good thank you. At least you did see what i saw.
But at this point i dont understand where do i use duplicated js/css imports

i have in the fiddle in this order. I dont see any duplicate in these.
bootstrap css
jquery js
popper js
bootstrap js

bootstrap-select css
bootstrap-select js

thank you

**Comment by caseyjhol** [comment]
Click on Resources in the left column. You are loading bootstrap and bootstrap-select files. You are also including them in the body, so the files are being included twice.

![image](https://user-images.githubusercontent.com/2874325/47325137-b42d5480-d61f-11e8-8aa3-d03161d62c43.png)
