### ISSUE TITLE
The height of the select doesn't auto-size with multi-line options

### ISSUE THREAD

**Issue by fdj184** [snapappointments/bootstrap-select#2109]
Hi,

Here's the jsfiddle with Bootstrap 3.3.7 and bootstrap-select **1.12.4**.
Depending on the content, the height of the select will auto-size.
http://jsfiddle.net/WayneHsu/2eopu534/5/

And here's the jsfiddle with Bootstrap 3.3.7 and bootstrap-select **1.13.2**.
The text is out of the control and won't auto-size either.
http://jsfiddle.net/WayneHsu/ebnq48a1/1/

Is this a bug or how I should I fix it?
I'd appreciate for any help.

**Comment by gtguybrush** [comment]
same here. just make a question even on stackoverflow: 
https://stackoverflow.com/questions/52831049/bootstrap-select-does-not-wrap-text-with-bootstrap-4

hope you will find a solution soon

**Comment by jadamec** [comment]
Hopefully will be fixed asap. Thanks!

**Comment by caseyjhol** [comment]
Released in [v1.13.7](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.7)!
