### ISSUE TITLE
In multiselect, a highlighted option gets selected if you click on another option

### ISSUE THREAD

**Issue by patcmds** [snapappointments/bootstrap-select#2112]
Steps to reproduce:
- Have a multi select dropdown
- Click on field
- Use down arrow to highlight first option
- Now, while the first option is highlighted, click on a different option. Both the highlighted option as well as the one you clicked will get selected.

This can be seen in your own example: https://developer.snapappointments.com/bootstrap-select/examples/#multiple-select-boxes

**Comment by caseyjhol** [comment]
Duplicate of #2101.
