### ISSUE TITLE
Insert window.open in <option>

### ISSUE THREAD

**Issue by Machou** [snapappointments/bootstrap-select#2113]
hi

possible to insert an option to open link in <option>, or how can i insert this in an option :

```
<select>
    <option onclick="myFunction(url)">Link 1</option>
    <option onclick="myFunction(url)">Link 2</option>
</select>

<script>
function myFunction() {
    window.open("+.url.+");
}
</script>
```

**Comment by caseyjhol** [comment]
Your best bet would be to use an event listener, like changed.bs.select (https://developer.snapappointments.com/bootstrap-select/options/#events).
