### ISSUE TITLE
[Bootstrap 4] attribute required not work with jquery validate

### ISSUE THREAD

**Issue by yaelahan** [snapappointments/bootstrap-select#2115]
![image](https://user-images.githubusercontent.com/35204891/46923577-ca497c80-d043-11e8-9d31-42bc14c5351b.png)

the pict capture when form was validate
* left pict = addClass selectpicker and attribute required
* right pict (normal) = attribute required

here is the code :
```
<div class="col-sm-6 col-md-6">
	<div class="form-group mb-4" id="select-container">
                 <label class="form-label">Position</label>
                 <select name="position" class="form-control selectpicker" title="-- Position --" required>
                          <option value="someValue">Option Here</option>
                 </select>
	</div>
</div>
<div class="col-sm-6 col-md-6">
	<div class="form-group mb-4">
		<label class="form-label">Employment</label>
		<input name="employment" type="text" placeholder="Employment" class="form-control" required>
	</div>
</div>
```

I serach before in this repo, stackoverflow, and other site but i cant resolve this yet
Thanks for your help/answer

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by yaelahan** [comment]
sorry for my mistake. This is the live demo 
https://jsfiddle.net/mw8b0hrv/

detail: 
- Bootstrap v4.1.3
- jQuery v3.2.1
- jQuery Validation Plugin - v1.17.0

**Comment by caseyjhol** [comment]
What problem is your demo demonstrating? Also, the jQuery validation plugin is not being loaded in your example and bootstrap-select is being loaded *before* Bootstrap (and the word `function` is misspelled, although that shouldn't be affecting anything).

**Comment by yaelahan** [comment]
sory i forgot to save yesterday, link has been updated

**Comment by caseyjhol** [comment]
Can you elaborate a bit on how to recreate the issue? Even when removing the `selectpicker` class (so it's a regular select element), clicking submit doesn't show the error for the select element. Disabling jQuery validate and using HTML5 validation works as expected though (both with *and* without the `selectpicker` class). That implies to me it might be an issue with jQuery validate.

**Comment by yaelahan** [comment]
Ok, I think an issue came from jquery validate. thanks for your help
