### ISSUE TITLE
Memory leak: getPlacement resize & scroll 

### ISSUE THREAD

**Issue by WizardCM** [snapappointments/bootstrap-select#2118]
https://github.com/snapappointments/bootstrap-select/blob/fecf38196946c9f3809fe7f41f55cd7768605832/js/bootstrap-select.js#L1803

These event hooks are not namespaced (so I can't clean them up myself), and are never removed by Bootstrap Select itself. The more times you create and destroy Bootstrap Select, the more stack up.

**Comment by caseyjhol** [comment]
Released in [v1.13.4](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.4)!
