### ISSUE TITLE
FR: Add SASS version to NuGet

### ISSUE THREAD

**Issue by ddelella** [snapappointments/bootstrap-select#2122]
SASS and LESS appear to be part of the source code.  Is there any chance to get a new NuGet package for bootstrap-select-sass?  This would download the SASS files in the appropriate folder structure and have the dependency on bootstrap.sass which contains the latest version 4.x.  Right now we have to include the code manually and it does make updates easy.   Thanks!

**Comment by NicolasCARPi** [comment]
Not a priority. Feel free to make your own unofficial one.
