### ISSUE TITLE
Problem with scrollbar

### ISSUE THREAD

**Issue by Machou** [snapappointments/bootstrap-select#2124]
Hi

I use this code :

```
<select title="Genres" class="selectpicker show-menu-arrow show-tick" data-live-search="true" data-size="10" data-style="select-filtres" data-width="170px" onchange="window.location=this.value;">
	<option value="/films/" title="Tous les Genres">Tous les Genres</option>
	<option value="/films/" title="Genre 1">Genre 1</option>
	<option value="/films/" title="Genre 2">Genre 2</option>
	<option value="/films/" title="Genre 3">Genre 3</option>
	<option value="/films/" title="Genre 4">Genre 4</option>
	<option value="/films/" title="Genre 5">Genre 5</option>
	<option value="/films/" title="Genre 6">Genre 6</option>
	<option value="/films/" title="Genre 7">Genre 7</option>
</select>
```

But i have this scrollbar, how to disable it ? (i use latest version of bootstrap select & bootstrap)

https://i.imgur.com/ELdlZN0.jpg

**Comment by caseyjhol** [comment]
This seems like it's probably an issue with your CSS. Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by Machou** [comment]
Hum i try my problem on CodePen, i don't have the bug.

I don't know how to find the problem. I think it's a problem with CSS. But i don't know where lol.

I search.

of i find the problem. it's :

`.show {
    display: inline-block !important;
}`
