### ISSUE TITLE
Reenable old select box layout in Bootstrap 4

### ISSUE THREAD

**Issue by saitho** [snapappointments/bootstrap-select#2128]
With v1.13.0 (#2061) the select box for Bootstrap 4 redesigned and the `.bs-caret` was removed.
I saw that the old layout is still available for Boostrap 3.

We've customized the CSS on the .bs-caret class and added a background to the caret area which is not possible anymore with this change. Is there any possibility of adding a new setting that allows us to keep using `.bs-caret` with Bootstrap 4?

Thanks!

**Comment by NicolasCARPi** [comment]
Closing as out of scope request.
