### ISSUE TITLE
Change language on the fly

### ISSUE THREAD

**Issue by biroplane** [snapappointments/bootstrap-select#2131]
I'm using i18next to translate my application. 
it works quite good with everything except this plugin.

I can set the default language when it starts but cannot change it on the fly (i've already checked that it worked for everything else)
Before posting this issue, here's the things i've been trying:

- Refresh the selectpicker
- Render again the selectpicker
- Destroy the sp and render again (actually working with some magic tricks)
- Set the language by `selectpicker({language:'IT'})`
- Set the language by `selectpicker({locale:'IT'})`

The main problem is with the placeholder. it won't rendere or refresh when i fire the changeLanguage method...

**Comment by NicolasCARPi** [comment]
Closing as wontfix.
