### ISSUE TITLE
Dropdown skipped on tab - tabindex bug in Safari

### ISSUE THREAD

**Issue by RolandBende** [snapappointments/bootstrap-select#2134]
## Bootstrap select dropdown skipped on keyboard tab press in Mac Safari desktop browser

[Video](https://res.cloudinary.com/bwebdesign/video/upload/v1541097122/bootstrap_select_tabindex_bug_in_safari.mov
)

I've tried to add tabindex numbers to the original form select element - did not resolved it.

**Comment by RolandBende** [comment]
You can test the form here with Safari:
[LINK](https://partner.privathus.hu/partner-regisztracio)

**Comment by caseyjhol** [comment]
Duplicate of #478.
