### ISSUE TITLE
Select flashes when open

### ISSUE THREAD

**Issue by mytdragon** [snapappointments/bootstrap-select#2139]
Hello,

when I open a select that have a scroll bar in and when I scrolled in the page, the select will flashes and won't be useable untill I click next to (for chrome, see gif). On firefox and safari, it will flashes 2-3 seconds then we can use it. 

![nov-07-2018 07-53-24](https://user-images.githubusercontent.com/31501596/48115237-87558000-e262-11e8-9afb-c03d1abf83ec.gif)

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by mytdragon** [comment]
Hello, sorry for the inconvenient, the problem was me. I used the 1.13.1 and when I tried to do live demo, I had not the problem. I looked the version and I had not the latest (1.13.3), now I don't have the problem anymore.
