### ISSUE TITLE
Default option for live search?

### ISSUE THREAD

**Issue by joelft** [snapappointments/bootstrap-select#2142]
I have a select with live search enabled.

Is it possible to define a default option for the case that the user's input does not match any entry?

for example:
```html
<select class="form-control selectpicker" data-live-search="true">
  <option> Customer Inc </option>
  ...
  <option> Customer LLC </option>
  <option> New Customer </option
</select>
```

In the above case, assuming the user's search input does not match any entry, I would like it to show the "New Customer" option. Is this possible?

Thanks

**Comment by Amosar** [comment]
Did you found a way to implement that?
I've tried to inject an html link into `data-none-results-text` without success.
Bootstrap-select return this error
```
Uncaught TypeError: Cannot read property 'firstChild' of undefined
    at Selectpicker.setSelected (bootstrap-select.js?0cf8:2191)
```

**Comment by joelft** [comment]
I did not find a way, unfortunately. If this ever gets resolved, great, but for now I just put a link next to it which pops up a bootstrap modal.

**Comment by caseyjhol** [comment]
Please 👍 and follow #990.
