### ISSUE TITLE
dynamically create another bootstrap-select, it doesn't show! why?

### ISSUE THREAD

**Issue by autumn3015** [snapappointments/bootstrap-select#2143]
the first one is ok.
using js like  $(this).parent().before($node)  to create another bootstrap-select,didn't work.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.
