### ISSUE TITLE
Cannot read property 'menuInnerHeight' of undefined

### ISSUE THREAD

**Issue by comgenius** [snapappointments/bootstrap-select#2145]
Version of bootstrap "3.3.7"
Version of bootstrap-select "1.13.3"

I am not exactly sure why this error occurs

`bootstrap-select.js:2727 Uncaught TypeError: Cannot read property 'menuInnerHeight' of undefined
    at i (bootstrap-select.js:2727)
    at u.createView (bootstrap-select.js:2727)
    at HTMLInputElement.<anonymous> (bootstrap-select.js:2727)
    at HTMLInputElement.dispatch (jquery.min.js?v=1472465470:3)
    at HTMLInputElement.r.handle (jquery.min.js?v=1472465470:3)
    at Object.trigger (jquery.min.js?v=1472465470:3)
    at Object.a.event.trigger (jquery-migrate-1.4.1.min.js?v=1472435034:2)
    at HTMLInputElement.<anonymous> (jquery.min.js?v=1472465470:3)
    at Function.each (jquery.min.js?v=1472465470:2)
    at a.fn.init.each (jquery.min.js?v=1472465470:2)`

**Comment by comgenius** [comment]
I just saw this at dist/js/bootstrap-select.js at line 880
`chunkSize = Math.ceil(that.sizeInfo.menuInnerHeight / that.sizeInfo.liHeight * 1.5);`

The `that.sizeInfo.menuInnerHeight` was not defined before it was used.
Please check this out. I really need your help. Am hooked

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by comgenius** [comment]
Sorry I was not able to create a live demo of the problem but chrome gave me the line at  dist/js/bootstrap-select.js at line 880. Please can you help me look into it.

**Comment by caseyjhol** [comment]
Sorry - if you can't replicate the issue, then I can't replicate the issue, which makes it impossible to troubleshoot.

**Comment by tangkhaiphuong** [comment]
@caseyjhol @comgenius I found this issue caused by the auto-fill for search input.

https://github.com/snapappointments/bootstrap-select/blob/309324656069ebace3a087a683418db9e7840e38/js/bootstrap-select.js#L2487

**Comment by comgenius** [comment]
@tangkhaiphuong Please what is the fix to the issue?

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.
