### ISSUE TITLE
Add placeholder option / deprecate title option

### ISSUE THREAD

**Issue by caseyjhol** [snapappointments/bootstrap-select#2147]
A new option - `placeholder` will function the same as `title` does currently. `placeholder` will be available and `title` will be deprecated in the next minor release.

`title` will be removed in the next major release. The `title` option will then behave as it would be expected (a tooltip with the title text will be displayed when hovered over).

Addresses #977.

**Comment by caseyjhol** [comment]
This change will be a part of the v1.14.0 release. This issue will be updated after it's made available.

**Comment by caseyjhol** [comment]
Released in [v1.14.0-beta](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta)!

**Comment by vukasinpetrovic** [comment]
Hi @caseyjhol,
I tried adding placeholder to option elements, but it is not displayed. Instead whole text of options is shown when it's selected. I'm using regular single select, not the multiple one.
