### ISSUE TITLE
Select disappears

### ISSUE THREAD

**Issue by joshkpeterson** [snapappointments/bootstrap-select#2149]
I'm having the same issue as people on this SO: https://stackoverflow.com/questions/45121378/bootstrap-select-selectpicker-disappears

I'm trying to integrate bootstrap-select into a backbone app with a bunch of other dependencies, and the <select> is hidden once it renders with nothing in its place.

I've tried updating jquery and bootstrap to the latest, same behavior.

**Comment by Xefiron** [comment]
Did you load the Poppers.js plugin when you switched to Bootstrap 4?

**Comment by caseyjhol** [comment]
Ensure you are:

- including jQuery *before* Bootstrap and bootstrap-select
- including all bootstrap-select files *after* all Bootstrap files

If you're still having issues, include an example of your code and I'll investigate further.
