### ISSUE TITLE
Live search discards the first typed character

### ISSUE THREAD

**Issue by kdolan** [snapappointments/bootstrap-select#2150]
### Description
When a live search enabled bootstrap select is focused (but not yet open) and a character is typed the select expands but discards the typed character. The expected result is the typed character expands the select and populates the search field with that character.

### Versions
Browser/OS: Chrome Version 71.0.3578.30/Windows 10

### Steps to Reproduce
1. Tab to a live search enabled select
2. Type a single character

Actual Result: The select opens.
Expected Result: The select opens and the character that was typed is displayed in the search field.

### Examples
Code Pen: https://codepen.io/kdolan1/pen/xQdNyg

Can Also be Reproduced Here: https://developer.snapappointments.com/bootstrap-select/examples/#live-search. Try typing "b" in this example

**Comment by Mrsssswan** [comment]
i have the same problem.

**Comment by caseyjhol** [comment]
Released in [v1.13.6](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.6)!
