### ISSUE TITLE
This plugins broken when the version of IE below 10 

### ISSUE THREAD

**Issue by Jed5** [snapappointments/bootstrap-select#2151]
When I use it which version is 1.13.2  in IE8 or 9, 
IE console shows 1 errors: 
Unable to get undefined or null referenced property "toggle" in bootstrap-select.js (30,3)
IE8 and 9 isn't compatible with Element.classList. so how to use it in IE 8 and 9? can you give some suggestions

Thanks

**Comment by bazineta** [comment]
Bootstrap 4 doesn't support IE8 or 9 either, so if you're moving to the 1.3 version for BS4 support, there's probably more things you're going to run into.

**Comment by caseyjhol** [comment]
I'll need to add a classList polyfill at some point (which can then be removed in v2), but for now, check out https://github.com/eligrey/classList.js/.

**Comment by caseyjhol** [comment]
Released in [v1.13.4](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.4)!
