### ISSUE TITLE
Icon as static title, approach, alternatives?

### ISSUE THREAD

**Issue by bazineta** [snapappointments/bootstrap-select#2157]
While our typical usage of this plugin is as your run of the mill select replacement, we find the live search to make it a fantastic context-specific search box (in one case, we've got a tree created by d3, and use bootstrap-select with the live search as a quick filter for the tree nodes; works great).

In such cases, all we really want is just a magnifying glass as the title, and we achieve that by setting the title to the Unicode value of the magnifying glass in our icon font, set the width to fit, the selectedTextFormat to static, and the style option such that the button will use the correct font family for the icon.

This works well, but feels a bit more convoluted than perhaps it should. I'm curious if there's something more obvious that I'm missing, or if I could contribute to this in some way, for example, allowing the title option to be a function rather than the `null | string` choice that exist now.

**Comment by NicolasCARPi** [comment]
Please feel free to contribute via a PR.
