### ISSUE TITLE
z-index not working as intended

### ISSUE THREAD

**Issue by leider** [snapappointments/bootstrap-select#2158]
Currently the z-index for the menu should be set to 1060.

the resulting snippet from css is: 

```
.bootstrap-select.bs-container .dropdown-menu {
  z-index: 1060;
}
```

unfortunately the required class `bs-container` is not present in the surrounding element.

I suppose the generation has changed somewhen during bs4 adaption.

**Comment by caseyjhol** [comment]
The `bs-container` class is only used when the `container` option is set.

**Comment by leider** [comment]
I don’t have it set. Sorry.

**Comment by caseyjhol** [comment]
If you can provide me an example of z-index not behaving as expected (as outlined in the contributing guidelines), I'd be happy to investigate further.

**Comment by leider** [comment]
I can provide more information:
In my first comment I was not very clear. So here re-stated:

My expectation is that the menu always has a z-index of 1060.
My finding is that it does not.

The css shows that .bs-container is required for the menu to have a z-index of 1060

If this is a feature, everything is fine. but this way a normal menu might be partially hidden if ```options.container===false```

**Comment by leider** [comment]
I have a screenshot of your demosite where you can see the behaviour. the top menu entry is behind the navb not in front of it:
![image](https://user-images.githubusercontent.com/450708/50041459-bdea9b80-0055-11e9-8362-f1ff96b68125.png)
I guess that makes it really visible. :)

And now you need to decide if it working as specified or not. 

Cheers,
Andreas

**Comment by deadrightdove** [comment]
Hi @caseyjhol . I see this was closed, but I have the same issue with the latest bootstrap-select & bootstrap. Just checking what the fix here was? Cheers
