### ISSUE TITLE
noneSelectedText utf-8 charachter 

### ISSUE THREAD

**Issue by fabercs** [snapappointments/bootstrap-select#2161]
My problem is,
```
 $(".m_selectpicker").selectpicker({
            noneSelectedText: '<span>Tümü</span>' // or noneSelectedText:'Tümü'
 })
```
this renders to 

`<button type="button" class="btn dropdown-toggle bs-placeholder btn-light" data-toggle="dropdown" role="button" data-id="" title="T�m�" aria-expanded="false"><div class="filter-option"><div class="filter-option-inner"><span>T�m�</span></div></div>&nbsp;<span class="bs-caret"><span class="caret"></span></span></button>`

![capture](https://user-images.githubusercontent.com/407149/49871534-8e564c00-fe27-11e8-8cb9-0cffa420d13a.JPG)

It does not render utf-8 char althougy page includes `<meta charset="utf-8" />`.

Bootstrap version is _"bootstrap": "^4.1.3"_
Bootstrap-select version is _"bootstrap-select": "1.13.0-beta"_

What might be the problem?

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.
