### ISSUE TITLE
Sub options display separately instead of as 1 list

### ISSUE THREAD

**Issue by pbrf01** [snapappointments/bootstrap-select#2166]
In my bootstrap-select box I have categories that each have sub-type options.  Initially, the categories are all visible and all sub-types are disabled/hidden.  The user selects one category (e.g. dog), then the appropriate sub-types appear (e.g. beagle, collie), and the user can select any they want.  In previous versions of bootstrap-select the sub options would appear as a single list under one TYPE header.  Now if there are 3 sub-types, you see 3 TYPE sections each with 1 sub type.

Ideally the sub types would appear as a single list under one `TYPE` heading.  Otherwise the list quickly becomes unusable with many options.

Plunker:  https://plnkr.co/edit/Lw9XMKwXk7hbNSBxZapE?p=preview

To reproduce in the plunker:
1. Select a category (e.g. dog)
2. View the list and you'll see `Dog` checked, with 4 `TYPE` sections below it, rather than 1 `TYPE` list with 4 options.

Tested with:
Chrome 70.0, Firefox 52.5
Bootstrap-select 1.13.5
Bootstrap 4.1.3
Jquery 2.2.4

**Comment by caseyjhol** [comment]
Works correctly in v1.13.3 (issue introduced in v1.13.4/5).

Another test case courtesy of @Thodor12: https://jsfiddle.net/Thodor12/1xc6ek3s/3/

**Comment by caseyjhol** [comment]
Released in [v1.13.6](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.6)!
