### ISSUE TITLE
page reload on selecting a value

### ISSUE THREAD

**Issue by luki06** [snapappointments/bootstrap-select#2168]
am using boostrap-select in electron project and after i select a value it redirect to an empty page,still didn't add any event for it,here is my code
 `  <select id="choose_pro" data-size="10"  class="selectpicker form-control" data-live-search="true" title="Selectiona un articulo">
                                                                <option   data-tokens="ketchup mustard">Mustard</option>
                                                                <option  data-tokens="mustard">Ketchup</option>
                                                                <option  data-tokens="frosting">Barbecue</option>
                                                              </select>    `
thanks.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.
