### ISSUE TITLE
Disabled optgroup + hideDisabled causes the optgroup to split up

### ISSUE THREAD

**Issue by Thodor12** [snapappointments/bootstrap-select#2170]
I found an issue if you disable and re-enable an optgroup using hideDisabled.
As soon as it's re-enabled and refreshed the optgroup options will all be split up with different optgroup headers.

Reduced test case: https://jsfiddle.net/Thodor12/1xc6ek3s/3/

**Comment by Thodor12** [comment]
It seems the same issue is described in here:
#2166 Sub options display separately instead of as 1 list

**Comment by caseyjhol** [comment]
Closing in favor of #2166.
