### ISSUE TITLE
Multiselect selected flag didn't show when use bootstrap4

### ISSUE THREAD

**Issue by HuAaron** [snapappointments/bootstrap-select#2172]
Multiselect selected flag didn't show when use bootstrap4

When use bootstrap 3, the multi-select is ok. 
![image](https://user-images.githubusercontent.com/28371968/50767849-625ca800-12b9-11e9-855b-a95fc1eea342.png)

But when use bootstrap 4, the flag doesn't appear when selected. 
![image](https://user-images.githubusercontent.com/28371968/50767865-72748780-12b9-11e9-8417-7f8ab45ca1e8.png)

Check from the source. It use glyphicon class but this appears removed in bootstrap 4.

**Comment by Thodor12** [comment]
Bootstrap 4 dropped support for glyphicons, you have to manually add glyphicons to your project or switch to something else like fontawesome.

![2019-01-09 12_17_46-window](https://user-images.githubusercontent.com/14359461/50896399-2d5f6b00-1409-11e9-8383-a23ee467c267.png)

**Comment by HuAaron** [comment]
Yes, I add font awesome and set iconBase option to font awesome and it works.
