### ISSUE TITLE
Octal escape causes build issues

### ISSUE THREAD

**Issue by floribon** [snapappointments/bootstrap-select#2179]
Hi, about the octal scape `\0` in the following line

https://github.com/snapappointments/bootstrap-select/blob/31d765b641f95fb559d2ca86b829a54612e23ffc/less/bootstrap-select.less#L16

This is causing issues with my webpack build because it tries to insert that into a template string, which causes the following error:

```
Octal escape sequences are not allowed in template strings
```

Is the comment about IE9 about the specified width, or the use of this character? What problem is being solved by its presence and is there any alternative?

Thanks

**Comment by NicolasCARPi** [comment]
See: https://github.com/snapappointments/bootstrap-select/issues/1122
