### ISSUE TITLE
is-invalid not work in vue

### ISSUE THREAD

**Issue by arisdevx** [snapappointments/bootstrap-select#2180]
`<select class="selectpicker" v-bind="{'is-invalid': error}">`
`<span class="invalid-feedback"> error </ span>`

doesn't work when using vue, because the is-invalid class appears in `<select>` not in the parent of this plugins `<div class="dropdown">`

"invalid-feedback" will appear under "is-invalid".

**Comment by caseyjhol** [comment]
You need to call `$('.selectpicker').selectpicker('refresh')` after updating the class. See #2164 for tips on using bootstrap-select with Vue.

**Comment by arisdevx** [comment]
it's work, but...

first click: is-invalid not appear
second click: is-invalid appear in the class.

so I have to double click then it works.
