### ISSUE TITLE
Thumbnail option does not work in Bootstrap 4.x

### ISSUE THREAD

**Issue by ddelella** [snapappointments/bootstrap-select#2181]
Bootstrap Version: 4.2.1
bootstrap-select Version: 1.13.5
jQuery Version: 3.3.1
Browser: Chrome 71.0.3578.98, Edge 41.16299.820.0
Operating System: Windows 10 (1709) - 16.299.904

I started by using the example referenced at this URL:
https://thdoan.github.io/bootstrap-select/examples.html

That example uses an older version of bootstrap-select, jQuery, and Bootstrap.  I created a working jsfiddle example using the code on that page.  I then proceed to update the scripts.  Changing to jQuery 3.3.1 did not change the result.  Upgrading to the latest bootstrap-select and Bootstrap causes the drop down to be display but with no thumbnail.

https://jsfiddle.net/ddelella/xqygf86n/9/

**Comment by caseyjhol** [comment]
bootstrap-select doesn't have a thumbnail option. The version you linked appears to be a modified version of bootstrap-select.

**Comment by ZaLiTHkA** [comment]
I've just been caught out by the same thing.. I need to allow a user to select one image from a list, and I liked the idea of using a styled select list with image thumbnails.

@caseyjhol, I've searched the issues and PRs and I don't see anything about this, so just in case I missed it, is there any plan to add (or explicitly *not* add) such a feature to `bootstrap-select`?

at the time of writing this, @thdoan's fork is "19 commits ahead, 518 commits behind snapappointments:master", so if I can rebase/adapt those changes into this project, would you be willing to accept a PR for this?

> FWIW, it seems the fork in question was created after commit 7940829d5fd80fd66659fdbdabb16fd0e47aa2ac.
