### ISSUE TITLE
Dropdown Not Opening When Data Contains Accent Characters

### ISSUE THREAD

**Issue by Marshall-George** [snapappointments/bootstrap-select#2182]
We're using bootstrap-select for a multi-select checkbox list in our project.  The project supports multiple languages, and we're finding that when set to French the dropdown list does not open.

We use our own language resources for the translations, and in this case we have two words that have the accented e character that is common in the French language.

English:

Downloaded
Ordered

French:

Téléchargé
Commandé

What I am observing is that there isn't any sort of event firing when I click on the dropdown, so the 'show' class isn't being added to any of the controls.  This doesn't happen when English is selected - the dropdown opens as expected.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.
