### ISSUE TITLE
Dropdown listbox margin bottom leaves an empty white area

### ISSUE THREAD

**Issue by kriit24** [snapappointments/bootstrap-select#2183]
Element: div.dropdown-menu div[role="listbox"] ul.dropdown-menu
Data over 10000 (also maybe with less) in listbox
Some problem with calculated margin-bottom
[Print screen](https://www.dropbox.com/s/zzvasuqfv1rao3x/2019-01-23_07h49_25.png?dl=0)

**Comment by carlosmerida** [comment]
Hi,
I have the same problem.
when initially the dropdown has enough elements to show the scroll:
![image](https://user-images.githubusercontent.com/47460417/52574752-3931b900-2e1d-11e9-9b37-4c177bd18159.png)
later if the content is changed, even if the refresh method is invoked, the margin-bottom leaves all that empty space:
![image](https://user-images.githubusercontent.com/47460417/52575028-cbd25800-2e1d-11e9-9ac2-248129d1bfa5.png)

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by hamidmayeli** [comment]
Hi @caseyjhol 

I have used this plugin in a few projects and I have this issue only in one of them. The only difference that I can think of between them is that the faulty project has an iframe including the plugin. However, I tried to replicate the issue in a test scenario but I failed. (I tried to load the plugin in an iframe in another project and it worked fine.)
