### ISSUE TITLE
Firefox shows mulitiple selects

### ISSUE THREAD

**Issue by shamiradjaku** [snapappointments/bootstrap-select#2184]
Firefox renders multiple selects even on the examples [page](https://developer.snapappointments.com/bootstrap-select/examples/).

I see similar behaviour when using version 1.13.5  it in my code.

This  only happens on Firefox.

My Firefox version is 64.0.2 (64-bit) Windows

![image](https://user-images.githubusercontent.com/3898201/51599697-2d2a9980-1ef8-11e9-8ff2-53507cb21320.png)

**Comment by caseyjhol** [comment]
Looks like the bootstrap-select CSS isn't loading for you for some reason - perhaps AdBlock? It's working correctly for me (Firefox 64.0.2 64-bit Windows).
