### ISSUE TITLE
Feature request: refresh automatically

### ISSUE THREAD

**Issue by esamo** [snapappointments/bootstrap-select#2185]
Need for this comes frequently so I thought I'll note it here.
Would be great to have a config option that will bind listeners and automatically call refresh function when either options change or disabled attribute changes, obviously secured against throttling.

**Comment by Hypher** [comment]
I had to deal with that on a project, it's pretty easy with MutationObserver:
```js
// define anywhere globally in the plugin:
var mutationObserver = new MutationObserver(function(mutationList) {
        for(var i=0; i<mutationList.length; i++) {
	        var mutation = mutationList[i];
	        if(mutation.type == 'childList' || mutation.type == 'attributes' && mutation.attributeName == 'disabled') {
		        $(mutation.target).closest('select').selectpicker('refresh');
	        }
        }
    });

// in the init function (for each select):
mutationObserver.observe(this.$element[0], {attributes: true, childList: true});
```

Feel free to throttle the function as you said, and to add other attributes than "disabled" (that was the only one I was interested in, I don't know if bootstrap-select is using other attributes).

Also, I don't know the requiered compatibility of bootstrap but MutationObserver does not work on IE10- https://caniuse.com/#feat=mutationobserver

**Comment by caseyjhol** [comment]
Closing in favor of #1360. Please 👍 to vote and subscribe 🔉 for updates.
