### ISSUE TITLE
"Cannot read property '0' of undefined" when dropupAuto is false and the select is at the bottom of the page

### ISSUE THREAD

**Issue by realunreals** [snapappointments/bootstrap-select#2198]
I found 2 bugs about refresh and when I enable optgroup.

1) When I use data-dropup-auto="false" tag and when the select is on the bottom of the page I can not refresh.
2) When I disable optgroup it is working but when I enable optgroup creating many group.

Please check bugs: http://jsfiddle.net/hza0t6L9/1/

**Comment by caseyjhol** [comment]
Your second issue is known: #2166.

**Comment by caseyjhol** [comment]
Released in [v1.13.6](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.6)!
