### ISSUE TITLE
Live search and multiple

### ISSUE THREAD

**Issue by DjovDev** [snapappointments/bootstrap-select#2200]
Hi,

I have a populated select box with a list of brands. I want to make it multi-selectable but also searchable.

I have for example

- Brand A
- Brand AB
- Brand ABC

1. I type in "A"
2. I select "Brand ABC"
3. "Brand ABC" is selected as value for the element, however, "Brand A" (always first option) also gets a checkbox next to it.

Has anybody faced similar issues? This is on 1.13.2

**Comment by DjovDev** [comment]
It apears to happen as soon as any value was typed, for example A, which corresponds with something within the select box.

In this example, if I type "Z" and try to recreate the issue, it does not occur.

**Comment by caseyjhol** [comment]
Please upgrade to v1.13.5 and see if the issue persists.

**Comment by DjovDev** [comment]
Hey,

I just did and it seems to be working better. I will test it in the coming days, thanks a lot!
