### ISSUE TITLE
dropdown truncates its length (bootstrap panels)

### ISSUE THREAD

**Issue by themindfactory** [snapappointments/bootstrap-select#2201]
not so much a bug but I am using this with bootstrap collapse-able panels, and when the drop down happens it will only show itself within the current panel, if the panel is very short, then the drop down gets cut off, I would rather the dropdown just show itself fully on the screen and only cut itself off at the top and bottom of the physical screen.

I have gone threw all the settings and can not find one that does this.....

Anyone help?

Thanks!
Example it opened itself upwards and truncated the 1-13 selections:

![image](https://user-images.githubusercontent.com/8609129/52983585-c6df4c80-33b9-11e9-9b39-3812cab522fb.png)

**Comment by caseyjhol** [comment]
Try the `container` option. https://developer.snapappointments.com/bootstrap-select/examples/#container
