### ISSUE TITLE
data-live-search, data-size and dropupAuto with Bootstrap 4

### ISSUE THREAD

**Issue by jvjc** [snapappointments/bootstrap-select#2202]
When use the options liveSearch and dataSize with Bootstrap 4 and the dropdown changes to dropup, when you type in the live search input the dropup does not update the position and keeps "floating".

boostrap 4.1.3
popper 1.12.9
jQuery 3.2.1
boostrap-select 1.13.5

1. Open the dropdown.
2. Type something to reduce the choices.
3. The dropup stay away from the dropdown button.

| With data-size = 5 | - | Without data-size |
| ------------- | - | ------------- |
| ![data-size](https://media.giphy.com/media/3s279Fl4sEybFhFsb0/giphy.gif) |   | ![without-data-size](https://media.giphy.com/media/24lp9VuMyiPi7Ty1V3/giphy.gif)  |

[Plunker](https://embed.plnkr.co/EhJegBf9NcGethvkF7lZ/)

[Maybe needs a setMenuSize?](https://github.com/snapappointments/bootstrap-select/blob/66510fe594c91ccfab6721d48558ff8d0b69f4f9/js/bootstrap-select.js#L1836)

Cheers and thanks!

**Comment by caseyjhol** [comment]
Released in [v1.13.6](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.6)!
