### ISSUE TITLE
Weirdly duplicated select elements

### ISSUE THREAD

**Issue by tholkashen** [snapappointments/bootstrap-select#2205]
When I initialized selectpicker two same dropdown button shown in modal. But there was only one select element.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by RodolVelasco** [comment]
Having same issue. This happened to me when using this class "selectpicker form-control select2" for the select element.

**Comment by lcsqlpete** [comment]
I'm experiencing duplicate select elements in the following circumstances.

Bootstrap 3.3.7
bootstrap-select v 1.13.16
Chrome browser Version 81.0.4044.122 (Official Build) (64-bit)

This happens within a bootstrap modal.  I have two tables, one which is hidden and has a row including a selectpicker which acts as a template, and another working table where the user can click a button to add a row.

When the user adds a row, the html of the row in the template table is prepended to the working table and I refresh the selectpicker in the working table (if I don't refresh, no options appear).  I then see two selectpickers, one below the other.  The top one displays the options when clicked, the bottom displays nothing when clicked.

Attached is a file that illustrates the issue (it's a .txt file).  After opening the file, click the Open Modal button, then click the plus sign icon to see the issue.

[DuplicateSelectBug.txt](https://github.com/snapappointments/bootstrap-select/files/4555341/DuplicateSelectBug.txt)
