### ISSUE TITLE
Map file for minified js version does not work correctly

### ISSUE THREAD

**Issue by esamo** [snapappointments/bootstrap-select#2206]
Due to this issue #2203, I had to use bootstrap-select.js file directly, as with the minified version and map file in use, Chrome was showing wrong line in the error stack trace.

Screenshots showing wrong mapping can be found below.

![image 1](https://user-images.githubusercontent.com/6228442/53505923-2f62b380-3ab5-11e9-91aa-cf444ccac385.png)
![image](https://user-images.githubusercontent.com/6228442/53505924-2f62b380-3ab5-11e9-9da1-32ce2edab77c.png)

While using the full js directly, proper error line was displayed:

![image 2](https://user-images.githubusercontent.com/6228442/53506018-65079c80-3ab5-11e9-9082-2b94937c3bea.png)

---

Bootstrap-select v1.13.3
Chrome v72.0.3626.119

**Comment by caseyjhol** [comment]
Released in [v1.13.6](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.6)!

**Comment by esamo** [comment]
Guys this is still broken in v1.13.6 and possibly v1.13.7 too.
Instead of proper line as here #2231 , minified version with map points to line 3054 which translates to empty file upon click.
