### ISSUE TITLE
With animsition, redirecting to /undefined when option is selected

### ISSUE THREAD

**Issue by vitorregisrr** [snapappointments/bootstrap-select#2208]
Hey! I have a simple select-picker:

          
   ```
<select name="nome" id="nome" class="select-picker form-control" data-live-search="true">
          <option selected disabled>Selecione um cliente</option>
           <option value="a"> Angelica Rodrigues</option>
           <option value="a"> Carlos Santos</option>
           <option value="a"> Debora Goettems</option>
           <option value="a"> Ricardo Goettems</option>
           <option value="a"> Vitor Régis</option>
      </select>
```

And i'm simply starting select-picker in the end of the doc.
`$('.select-picker').selectpicker();`

I'm using **bootstrap 4.1 and jquery 3.2.1**
In a isolated test case it's working correctly, i'm searching for a few hours and i just dont have idea why is that ocurring.

I've already tryied to create my on prevent redirecting but it's not working.
```
$('a[role="option"]').click(function(e) {
  e.preventDefault();
  e.stopPropagation()
});
```
But when i click on a option, its redirect to /undefined. Anyone knows why?
![error](https://user-images.githubusercontent.com/9900252/53603512-7a9dc480-3b90-11e9-9dca-6c4e490270a4.gif)

**Comment by caseyjhol** [comment]
What browser? What version of bootstrap-select? If you inspect the elements in the menu, is the `href` attribute somehow set on the `<a>` elements?

**Comment by vitorregisrr** [comment]
Version: 1.13.5
Browser: Chrome
Has HREF Property: No, there isnt that propert.

**Comment by caseyjhol** [comment]
What's different between your isolated test case and your actual usage? Are you using using a framework like Angular, Ember, or Vue?

**Comment by vitorregisrr** [comment]
No. I just tryied an isolated case because the rules of opening an issue asked to try it.

**Comment by caseyjhol** [comment]
And it works correctly if bootstrap-select is disabled? Without a way to view a demo of the issue, I won't be able to help.

**Comment by ilkerkocatepe** [comment]
Hi Casey,
I have a problem like this, I checked all of my files and i can't find something wrong. Most probably an other js file causing this problem.
I can give a demo link for you. Could you look it for the solution?
Thanks a lot...

Link: [click](https://vamosapp.site/isletme/testselect.php)

**Comment by caseyjhol** [comment]
@ilkerkocatepe It has to do with something else you're loading. As a test, try just adding:

```html
<a>Click Here</a>
```

If you click that link, the page redirects to undefined. That is not normal behavior. Also, unrelated, but you have an open `<script>` tag at the end of your document without a closing one to follow.

---

Looks like it's being caused by animsition:

```js
$(".animsition").animsition({
    ...
    linkElement: 'a:not([target="_blank"]):not([href^="#"]):not([class^="chosen-single"])',
    ...
});
```

I bet if you change it to:
```js
linkElement: 'a[href]:not([target="_blank"]):not([href^="#"]):not([class^="chosen-single"])'
```
it'll fix your problem.

or
```js
      transition: function (url) {
        if (url) window.location.href = url;
      }
```

**Comment by ilkerkocatepe** [comment]
I'm so happy that. It fixed my problem. Thank you. Best regards.
