### ISSUE TITLE
dropdown items not showing, but they have values

### ISSUE THREAD

**Issue by ghardy2k** [snapappointments/bootstrap-select#2209]
i am having a weird issue with dropdown items not showing when the dropdown is clicked. i even re-populate the dropdown when the control is clicked.  i have console messages letting me know that happened.   the dropdown items don't show, but the tags are filled in if i look at the page source...the hundreds of options that get loaded up simple don't "dropdown".

my bootstrap-select is sitting inside a bootstrap datatable, which is inside a bootstrap tab.   i have tried moving the select out of other containing tags, but that didn't help. but if i refresh the page, it is fine (usually).

MVC 5 web app, dot net 4.6.1
bootstrap-select 1.13.5
bootstrap 4.3.1
jquery 3.3.1
datatables 1.10.15
chrome 72
visual studio 2017

here is a copy of my page.   i don't know if stuff is loading up in the right order...that's the only thing i can think of that might cause this.

--- edit - got rid of this, because it is irrelevant.

**Comment by caseyjhol** [comment]
It sounds like you might not be loading the correct CSS? Could you link me to a demo?

**Comment by ghardy2k** [comment]
https://plnkr.co/edit/YwTL7Yep5EdhMLazOKSV

i did my best to setup this plunker.   long story short, i see all those values in the select, but it won't show when i drop it down.   this is happening on the certification tab, with a select called "program".   I suspect it coulld be datatables.js, moment.js, or the tabs that is doing it.

![capture](https://user-images.githubusercontent.com/12464998/53841693-0f266f00-3f63-11e9-8d50-32f6a67f743b.PNG)
![capture2](https://user-images.githubusercontent.com/12464998/53841694-0f266f00-3f63-11e9-8272-f3ac2a233661.PNG)

**Comment by ghardy2k** [comment]
note above, that in the browser debugger, i see all these option values.   i did a page source, and all i see there is the select with no options.

--
  | <select class=" bootstrap-select form-control "
  | id="program" name="program"
  | data-container="body"
  | data-live-search="true"
  | title="Search..."
  | data-hide-disabled="true"></select>



so i am not familiar enough with debugging javascript to figure out why i see it in developer mode in the browser, but not in the page source itself.  weird. 

if i decide to refresh the page, then i get stuff in there...
![capture3](https://user-images.githubusercontent.com/12464998/53842705-d9cf5080-3f65-11e9-8d30-d6f533858c66.PNG)

**Comment by caseyjhol** [comment]
Yes, that select is on the page, but the elements of bootstrap-select are appended dynamically (assuming your select has more than 600 options in it).

In any case, looking at your Plunkr, you're loading jQuery *after* Bootstrap, and you're also not loading Popper.js, which is a requirement of Bootstrap 4.

Changing that seems to fix your issue: https://plnkr.co/edit/jI3Oqy3jSI4unzu2R2RE?p=preview.

**Comment by ghardy2k** [comment]
thanks for your help!  i did change the order of stuff loading up.  looked at network tab in debugger, and verified scripts loading up the way they should, including the umd version of popper.  the same problem exists, but i can safely assume this problem isn't the dropdown, but my lack of understanding on debugging web stuff.   thanks again i'll keep digging.

**Comment by anyderre** [comment]
for the one facing this issue with bootsrap-select ensure that your jquery is selected before the loading the bootstrap select. 
`    
    <script
      src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"
    ></script>
<script
      src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"
    ></script>
`
That order is important to ensure that the options values to show.
