### ISSUE TITLE
Button DropDown-Toggle Style Issue

### ISSUE THREAD

**Issue by yuri1994** [snapappointments/bootstrap-select#2213]
I try to use select picker with last version 1.13.5 and bootstrap version 4+.  The problem where i have is:
![image](https://user-images.githubusercontent.com/22602195/53730127-ab774580-3e7f-11e9-9f4c-dfc9512c93b5.png)

the button and selected option is not in same position. how can i fix it?

**Comment by caseyjhol** [comment]
What is your doctype set to?

**Comment by yuri1994** [comment]
yep, when i set doctype in every single page it's work, the strange is in that, i have doctype in master page where is extended in other child pages, but in this way they didn't get the doctype. in my case i use php laravel with blade templates. How ever, it's work. Thanks!

**Comment by caseyjhol** [comment]
Released in [v1.13.7](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.7)!
