### ISSUE TITLE
BUG: Emtpy list element doesn't work when 'data-content' attribute is used

### ISSUE THREAD

**Issue by wittich** [snapappointments/bootstrap-select#2218]
## Bug reports

When `<option>` contain the `data-content` attribute the emtpy "bs-title-option" element doesn't work and the first option with `data-content` attribute is selected as default.

Workaround is to add manully an empty option element which contains content data attribute:

`<option class="bs-title-option" value="" data-content=""></option>`

_____________
_bootstrap-select version 1.13.2_

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details. Also, try the latest version to see if the issue persists.

**Comment by wittich** [comment]
Sorry should have done that before. Can't reproduce the bug in jsFiddle, their everting just works as aspeced: https://jsfiddle.net/wittich/m8wsq9k0/

Pls close the issue
