### ISSUE TITLE
js folder missing in bower_components/bootstrap-select/dist with v1.13.6

### ISSUE THREAD

**Issue by troymolsberry** [snapappointments/bootstrap-select#2220]
bower installing 1.13.6 and no longer bower_components/bootstrap-select/dist/js folder containing javascript code.

to reproduce:
1. bower install bootstrap-select
2. ls bower_components/bootstrap-select/dist

css

expected result:
css
js

js folder containing javascript

**Comment by zipper** [comment]
Since this is critical bug, is there any chance of making bugfix release just for this asap? Since it is already fixed in https://github.com/snapappointments/bootstrap-select/commit/79e4a9e4b1a054336527601d4d620a25862978f2, it should not be a problem.

**Comment by caseyjhol** [comment]
Hoping to have this out today.

**Comment by caseyjhol** [comment]
Released in [v1.13.7](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.7)!

**Comment by zipper** [comment]
Awesome, thank you very much!
