### ISSUE TITLE
Selecting option by typing is not working correctly in 1.13.6

### ISSUE THREAD

**Issue by Jogai** [snapappointments/bootstrap-select#2226]
Test Case: https://codepen.io/jogai/pen/LazgKb

- Open the browser console
- Open the first select
- Start typing "November" (in this setup its actually enough to type just 1 alphabetic character)

Issue:

November is so far down the list that its not visible, so users cant see what they're doing. (and console is throwing an error)

Edit: seems to be a regression from 1.13.5 and is a single issue

**Comment by caseyjhol** [comment]
Looks like `element.focus()` accidentally got swapped with `element.trigger('focus')` when removing the jQuery shorthand (even though the element is native).

**Comment by Jogai** [comment]
Thanks, good to see the 'next release' label on this one.

**Comment by caseyjhol** [comment]
Released in [v1.13.7](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.7)!

**Comment by Jogai** [comment]
It might have something to do with how I instantiate this, but if the select is accessed with a tab typing still doesnt scroll the right option into the view. 

Also the window padding is not respected on select with custom content (or should I make another issue for that?)
