### ISSUE TITLE
Change event is fired when I need to deselect option [Single-Option]

### ISSUE THREAD

**Issue by IWGDevelop** [snapappointments/bootstrap-select#2227]
Hi,

I have a problem with a single-option Bootstrap-select. In previous versions I clear the selected option with [selectpicker('val', '')](https://developer.snapappointments.com/bootstrap-select/methods/#selectpickerval) method.

Now, with 1.13.6 version, when I need to clear the selected option, and I call `$('#SelectPickerId').selectpicker('val', '');` and the event `onChange` is Fired, but I not need this.

So, I try to use [DeselectAll method](https://developer.snapappointments.com/bootstrap-select/methods/#selectpickerdeselectall) but this not works with Single-Option bootstrap-select.

How can I deselect the selected option in my case.

Thanks

**Comment by caseyjhol** [comment]
See #2046.
