### ISSUE TITLE
[Question] Is it possible to stop scrolling to top when hitting the bottom?

### ISSUE THREAD

**Issue by kylephp** [snapappointments/bootstrap-select#2230]
Hi @caseyjhol,
When using the up and down arrow key to navigate the items, it scrolls to the top when hitting the bottom and vice versa.
Is there any way to stop this behaviour or it's designed that way?
![bootstrap-select](https://user-images.githubusercontent.com/7766055/54274952-f8fc5c80-45bb-11e9-9879-2d442f2ae540.gif)

**Comment by caseyjhol** [comment]
Not currently possible. Any reason specifically you don't want that? In the demo you posted your select has some custom styling which is why it's not scrolling all the way to the bottom.

**Comment by kylephp** [comment]
@caseyjhol not really a issue but in my case, I wanted to use the arrow down key to navigate to the last item (forget the custom styling issue, it's solved in https://github.com/snapappointments/bootstrap-select/issues/2229)
