### ISSUE TITLE
Every 'refresh' appends a new span.check-mark

### ISSUE THREAD

**Issue by lcampanari** [snapappointments/bootstrap-select#2232]
Hello! The method 'refresh' appends a new `span.check-mark` to every `li.dropdown-menu  > a` when using the attribute `multiple`.

Steps to reproduce:

1. Set up a `select` using the `multiple` attribute;
2. Initialize bootstrap-select;
3. Count `.bootstrap-select li:first-child > a > .check-mark`
4. Refresh bootstrap-select;
5. Repeat 3.

Reduced test case: https://codepen.io/campanari/pen/OqvrRv?editors=1011

For now I modified the function Selectpicker.prototype.createLi as follows:

<pre><code>
if ((that.options.showTick || that.multiple) <b>&& elementTemplates.a.getElementsByClassName('check-mark').length < 1</b>) {
        checkMark = elementTemplates.span.cloneNode(false);
        checkMark.className = iconBase + ' ' + that.options.tickIcon + ' check-mark';
        elementTemplates.a.appendChild(checkMark);
      }
</code></pre>

Would this solve this issue without causing any other problems?

Thanks!

**Comment by caseyjhol** [comment]
Good catch. That fix won't cause any issues. I'll work on something more robust and make it available in the next release.

**Comment by caseyjhol** [comment]
Released in [v1.13.9](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.9)!
