### ISSUE TITLE
server-side error: HTMLSelectElement is not defined

### ISSUE THREAD

**Issue by MarcGodard** [snapappointments/bootstrap-select#2233]
I have been getting this error since 1.13.6:

`error: HTMLSelectElement is not defined`

I have no idea why, or how, but I use a type of webpack and server side rendering. So I assume in one of those the error is created (if no one else is getting this issue).

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

**Comment by MarcGodard** [comment]
This setup is very complicated. There is no reduced test case. I can make a public repo that others can try the newer version to see it. The problem is that its part of Server Side Rendering and it being compiled with a package manager to reproduce. I could dig further in, but I will just wait till others see the issue with other similar systems if a repo is not good enough.

**Comment by caseyjhol** [comment]
So you're only getting that error server side?

**Comment by MarcGodard** [comment]
It really just needs a `if (HTMLSelectElement) HTMLSelectElement ...`

**Comment by caseyjhol** [comment]
Definitely that would fix the error. Just wanted to make sure I didn't need to come up with a new way to do the `selectedOptions` polyfill. I thought maybe you were using some weird browser where HTMLSelectElement wasn't available immediately/at all.

**Comment by MarcGodard** [comment]
@caseyjhol I am not 100% sure if that is the case (where its not yet available), but sounds like the case. Let me know when I can update and test again. If you need more help, I should have time in a week to dig deeper. I do like this project and have been using it for a long time.

**Comment by caseyjhol** [comment]
Released in [v1.13.9](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.9)!

**Comment by MarcGodard** [comment]
Thanks for trying, now I get another error (Just updating this one package) and still breaks everything. I will dig deeper soon, still works 100% with version 1.13.5. Big deadline then I will be happy to make a PR

**Comment by caseyjhol** [comment]
@MarcGodard What error are you getting now?

**Comment by MarcGodard** [comment]
@caseyjhol unfortunately the error isn't descriptive. It would require some deep probing.

`error: Mixed dependency cycle detected`

However, the older version still works 100%.

**Comment by caseyjhol** [comment]
@MarcGodard For what it's worth, this polyfill will be removed in v1.14.0, so if you're still having problems hopefully that will fix it.
