### ISSUE TITLE
position bootstrap-select behind input field

### ISSUE THREAD

**Issue by bardware** [snapappointments/bootstrap-select#2234]
Hi,

in my production code I'm still on bootstrap-select-1.10.0 and I only recently understood this repo was move from silviomoreto to snapappointments.
I replaced my bootstrap-select js and css files with the files from the new version 1.13.7 and saw my page does not look the same.
I set up a [demo](https://bardware.github.io/bsselect/index-1.10.0.htm). bootstrap-select nicely appears right behind an input field. This is how it's supposed to look. I use it in production to show a dropdown with various currency names after a field to input an amount.
The second [sample](https://bardware.github.io/bsselect/index-1.13.7.htm) is the exact same page but with your version 1.13.7. The bootstrap-select box is not rendered behind the input but below.

What is the corrrect way to place a bootstrap-select behind an input field?

Thanks for you effort,
Bernhard

**Comment by caseyjhol** [comment]
Released in [v1.13.9](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.9)!

**Comment by bardware** [comment]
Thanks for the fix.
Sorry to come back so late. 
I updated my [sample](https://bardware.github.io/bsselect/index-1.13.10.htm) . The thin I notoice is, the dropdown has a very large width. Much wider than the input.
Is there a possibility to correct this?
