### ISSUE TITLE
Mobile native menu

### ISSUE THREAD

**Issue by denisenkor** [snapappointments/bootstrap-select#2235]
After update bootstrapselect from 1.13.6 to 1.13.7 or 1.13.8 method $ ('selectpicker'). selectpicker ('mobile')   has not work. Native menu not showing.

On 1.13.6 work fine.

**Comment by caseyjhol** [comment]
Released in [v1.13.9](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.9)!

**Comment by icanul-mcr** [comment]
I have the same issue but in version Bootstrap-select v1.13.18
