### ISSUE TITLE
Keep the display value unchanged

### ISSUE THREAD

**Issue by jdzhang1221** [snapappointments/bootstrap-select#2237]
Hello！
I am using the bootstrap package of version 4.3.1.
How do I keep the display value of the drop-down box unchanged when I select multiple drop-downs? Not a splicing of drop-down items, nor a display of the number of choices, but a fixed value is always displayed.

**Comment by caseyjhol** [comment]
Set `selectedTextFormat` to 'static' and set the select title to whatever you want displayed.
