### ISSUE TITLE
Bootsrap-select get autoselected first option

### ISSUE THREAD

**Issue by wazyquinin** [snapappointments/bootstrap-select#2246]
Bootstrap-select get autoselected first option when mutiple options in enable and live search in search is enabled

test Case:

seach something in input filed like a or e ; select 3 rd option;this will automatically select first option also
![selectpickerIssue](https://user-images.githubusercontent.com/851904/55154987-2fb9a180-517c-11e9-8ff5-27a859912198.gif)

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

**Comment by wazyquinin** [comment]
Fixed After updated to New Version !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
Thank You very very very very very very very much
