### ISSUE TITLE
Is it possible to use the search and dynamically load the options via ajax fro the server?

### ISSUE THREAD

**Issue by ppazos** [snapappointments/bootstrap-select#2250]
Current examples show a search filtering out options in the select, but can't find an example of actually populating the options using the search data and getting matching results from the server. Thanks.

**Comment by caseyjhol** [comment]
Please 👍 and follow #899. See https://github.com/snapappointments/bootstrap-select/issues/2081#issuecomment-416647772 for a workaround in the meantime.
