### ISSUE TITLE
bug: hideDisabled and selectedTextFormat: count not working correctly if disabled options are selected

### ISSUE THREAD

**Issue by giero** [snapappointments/bootstrap-select#2253]
Hello,

since version 1.13.4 `hideDisabled` option doesn't work as should. Hidden positions from dropdown menu are hidden, but they are still visible (or counted if `selectedTextFormat` option is set to count them) on dropdown button.

examples - click 'Hide selected' button and toggle bootstrap-select menu:
1.13.3 - works: https://jsfiddle.net/8tLzwdjy/
1.13.4 - doesn't work: https://jsfiddle.net/6ntzyhu8/
1.13.9 - still doesn't work: https://jsfiddle.net/2aLzdjg0/

**Comment by caseyjhol** [comment]
jQuery's [.val()](http://api.jquery.com/val/) doesn't take into account disabled options, so we need to use getSelectValues in `togglePlaceholder`, and update that function accordingly so it doesn't count disabled options, making it a closer recreation of .val() (which is what `togglePlaceholder` was using before to check if there were any options selected). This will be available in the next release.

**Comment by caseyjhol** [comment]
Released in [v1.13.10](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.10)!
