### ISSUE TITLE
selected option styling is not updated if .selectpicker('val', x) is called while dropdown menu is open

### ISSUE THREAD

**Issue by rbonomo** [snapappointments/bootstrap-select#2256]
Reproduce:
Select some options in the dropdown. In on-change event call .selectpicker('val', someOptionValue). The checkmarks are not updated.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

**Comment by rbonomo** [comment]
Will update this issue with requested content later. Opened a PR for this issue.

**Comment by caseyjhol** [comment]
After looking at your PR, I see what you mean.

**Comment by caseyjhol** [comment]
Released in [v1.13.10](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.10)!
