### ISSUE TITLE
menu size doesn't update when virtualScroll is disabled while the menu is open

### ISSUE THREAD

**Issue by alvaro-marting** [snapappointments/bootstrap-select#2258]
Hello, I have found that when handling a big workload (525+ items in the select, when we have optgroups and accounting for them, and 599+ without optgroups)the size of the select does not refresh properly.
This happens only when the selector has been opened prior to filtering or disabling the items we dont want to see.

This has been tested both in Firefox and Chrome latest versions.

1. Open the jsFiddle: http://jsfiddle.net/amarting/L8ny9qp6/41/
2. Open all selectors before 10 seconds pass (There is a setTimeout with a dummy function that disables every optgroup and options with the _disabled_ class apart from 2 that have the class _notDisabled_)
3. Watch as the one in the left has an appropiate size and the other 2 allow scrolling through an empty list. This is because the margin-bottom stays the same as if there has been no change in the list of items.

I only glimpsed the source code of the library, so this is a wild wild guess that almost surely is wrong, but maybe getComputedStyle or jquery.css are called before the task of rendering the items is finished? Maybe a callback is needed with a big workload? 

P.D: My workaround about this consisted of destroying and recreating the selectpicker, as the problem lies when refreshing, even though I don't think that would be ideal.

Thank you for this awesome library! Keep up the good work.

**Comment by caseyjhol** [comment]
What's happening: the menu has a large number of options, auto-enabling virtualScroll. Most of the options are then hidden after a timeout, disabling virtualScroll, but the "spacer" margin on the menu isn't reset.

**Comment by caseyjhol** [comment]
Released in [v1.13.10](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.10)!
