### ISSUE TITLE
Desired width of dropdown menu breaks after resizing window, but only if there are many options inside the select (reproducible).

### ISSUE THREAD

**Issue by giro83** [snapappointments/bootstrap-select#2266]
https://jsfiddle.net/m1ab2k35/

1) Open up and run the fiddle.
2) Test both select boxes. The width of the dropdown menu, in both cases, is the same as the select box (which is my intent here).
3) Make the results panel in jsfiddle much larger by dragging the vertical panel divider towards the left. Note the select boxes automatically resize.
4) Now test both select boxes again. The one with 4 elements will continue to work as expected (IMO). The one with 100 elements will have an unexpectedly smaller width.
5) If you start over and do the opposite test (shrink the results panel by moving the vertical divider to the right), you get the opposite issue.

I noticed this after an upgrade from v1.12.4. This did not happen there.

Also attaching screenshots post-repro.

![Screenshot 2019-04-26 at 11 25 28](https://user-images.githubusercontent.com/20286572/56801725-19077880-6816-11e9-9ff5-fa133cfecba7.png)

![Screenshot 2019-04-26 at 11 25 10](https://user-images.githubusercontent.com/20286572/56801728-1dcc2c80-6816-11e9-825b-d3e6bfea177c.png)

**Comment by giro83** [comment]
A workaround seems doing a .selectpicker('refresh') after the window changes.

**Comment by caseyjhol** [comment]
Released in [v1.13.11](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.11)!
