### ISSUE TITLE
min-width add outside checks in setWidth

### ISSUE THREAD

**Issue by cwolcott** [snapappointments/bootstrap-select#2271]
This issue currently exists in 1.13.10 on line 2018.
I have 70 items in my list,  the maximum item length is 40 characters.

The if clause on line 2014 is true and it is recalculating the totalMenuWidth and assigning it the css min-width.  But my element has data-width="fit".

I have currently comment out line 2018 for the time being to have it show properly.

**Comment by caseyjhol** [comment]
Menu width calculation has been updated in v1.13.11. Please check it out and let me know if your issue persists. If so, please link me to an example.
