### ISSUE TITLE
Class bs-placeholder is no longer set on "default" values in 1.13.10

### ISSUE THREAD

**Issue by Amunak** [snapappointments/bootstrap-select#2272]
Somewhere between 1.13.9 and 1.13.10 the `bs-placeholder` class is no longer set on non-multiple selects. I suspect [this change](https://github.com/snapappointments/bootstrap-select/compare/v1.13.9...v1.13.10#diff-ff31d80eb2d28b06752ee372aa065210R1631) to be the culprit.

I need to style the "default" values differently. My selects looked like this in 1.13.9 (all have the "default" / "initial" value, the first one is a multi-select with nothing selected):

![image](https://user-images.githubusercontent.com/781546/57328687-5cb18a80-7112-11e9-950d-a6424dff043e.png)

Now in 1.13.10 they look like this:

![image](https://user-images.githubusercontent.com/781546/57328745-87034800-7112-11e9-9648-c076babbdf52.png)

I'm not sure whether this is a bug or if it's intended, but I could really use a way to differentiate the "default" values from the user-selected ones.

Or maybe I'm going wrong about this and don't understand how it's supposed to work? x)

**Comment by caseyjhol** [comment]
I wasn't able to reproduce this issue. Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

**Comment by Amunak** [comment]
Sorry @caseyjhol I didn't get back earlier. Compare [this Plunk](https://plnkr.co/edit/ZxzGIRfCo95ancn4xw86?p=preview) that's on top of v 1.13.9 and [this one](https://plnkr.co/edit/1tRhnhRS6zcVaj6zhi5R?p=preview) that's on top of v1.13.12.

Basically before when you had (I assume?) empty `value` set, the option (when selected) would be "grayed out" as if it was a "default"/empty option. That's very desirable, IMO, and it disappeared between the versions.

I assume that it's some kind of side effect of how it was written previously, but it was a nice feature. Ideally we could set this style independent of the `value` perhaps with data attributes or somehting.

**Comment by caseyjhol** [comment]
@Amunak Thanks for the demos. This fix will be available in the next release.

**Comment by caseyjhol** [comment]
Released in [v1.13.13](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.13)!

**Comment by ex1st** [comment]
Hi @caseyjhol, this fix broke "getSelectValues" if a selected item placed in a "optgroup".
