### ISSUE TITLE
"precompiled bootstrap" link is broken in README

### ISSUE THREAD

**Issue by alex-jitbit** [snapappointments/bootstrap-select#2273]
The link (for those not using bootstrap) that points to "https://getbootstrap.com/docs/3.3/customize/?id=7830063837006f6fc84f" is broken and redirects to builder homepage. Please either update the link or list which components do I need exactly.

**Comment by caseyjhol** [comment]
Looks like it should be updated to https://getbootstrap.com/docs/3.4/customize/?id=7830063837006f6fc84f

**Comment by Khlyl** [comment]
شكرا

**Comment by caseyjhol** [comment]
Released in [v1.13.12](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.12)!
