### ISSUE TITLE
Bug: Event duplication on refresh

### ISSUE THREAD

**Issue by ArneKlein** [snapappointments/bootstrap-select#2275]
When using selectpicker('refresh') the click events on the $button are always added, if the html of the select tag has been changed. This leads to a performance degradation, especially for large dropdowns. 

A workaround for this bug is to destroy the selectpicker before refreshing it.

As shown in Firefox before refresh:
![image](https://user-images.githubusercontent.com/5556282/57623988-3caa1d00-7591-11e9-81bd-cd83f10b64f5.png)

Refresh with the following code:
`
var dropdown = $('#dropdown');
dropdown.html('');
dropdown.selectpicker('refresh');
`

![image](https://user-images.githubusercontent.com/5556282/57624172-ade9d000-7591-11e9-91dd-f777f903d84a.png)

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

**Comment by ArneKlein** [comment]
https://next.plnkr.co/edit/YTeEz4zQAKLyZC2Q

- Bootstrap 4.1.0
- Bootstrap-Select 1.13.11
- All browsers in all operating systems

**Comment by caseyjhol** [comment]
Looks like the click listener in the `checkDisabled` function is the source.

**Comment by caseyjhol** [comment]
Released in [v1.13.12](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.12)!
