### ISSUE TITLE
Weird rendering bug when skeleton.css is used

### ISSUE THREAD

**Issue by DeepSpace2** [snapappointments/bootstrap-select#2276]
I managed to reproduce it in both Chrome 74.0.3729.131 and Edge 44.17763.1.0: https://plnkr.co/edit/JNFbyIuzJMcLDipH4wim

Open the two selects and scroll all the way to the bottom. All of the first select's options (580) render with no issues. 

However, the second select's options (600) not all render. All the options after "app 565" are blank. If we type "600" in the search field then that option can still be selected.

If we comment out

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css" />

(line 6 in plnkr) then the issue is gone.

**Comment by caseyjhol** [comment]
skeleton.css is adding a 1rem bottom margin to li elements, which is throwing off the height calculation for virtualScroll. virtualScroll is enabled by default for selects with 600 or more options. You can either set `virtualScroll: false` or override the 1rem bottom margin on li elements.

**Comment by DeepSpace2** [comment]
@caseyjhol Awesome detective work
