### ISSUE TITLE
bootstrap select (in multi select mode) does not respect col width

### ISSUE THREAD

**Issue by vincentkeizer** [snapappointments/bootstrap-select#2279]
When all the selected titles combined are wider than the bootstrap col, the col gets wider and pushes the following cols to a new row.

In the example below, both selects are in one row, and both in a col.
In my opinion, both cols should have a equal width and the selected titles should be cut of when the maximum width (the width of the col) is reached.
![image](https://user-images.githubusercontent.com/3955202/57696367-ea303580-7650-11e9-8c49-871e2a4d99f1.png)

Reproduction steps:
- Add a multiple select with class "form-control" to a col in a row with multiple cols.
- initialize selectpicker for this select
- Select multiple options from the select, so that the width of all titles combined  are wider than the col.
- The select will not respect the width of the col and it will push the following cols to a new row.

It did work as I expected in version 1.3.5, but due to css changes to the "filter-option" class, it no longer works as expected.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

**Comment by NicolasCARPi** [comment]
Closing for no response from OP.
