### ISSUE TITLE
Bootstrap 4 and navbar data-live-search="true" does not go to the search field

### ISSUE THREAD

**Issue by oarque** [snapappointments/bootstrap-select#2280]
Here's is a demo of the problem:

The navbar select doesn't work but the body's select yes:

[]https://plnkr.co/edit/aIGT2Bj9LllhXoYr5QUq?p=preview

**Comment by florian-callewaert** [comment]
Here is a work around to focus the input when showing the selectpicker :
```
$(fieldSearch).on('shown.bs.select', () => {
        // add focus on input
        $('button[data-id=' + fieldSearchId + '] + div input').focus();
});
```
