### ISSUE TITLE
The dropdown value is not updating after unbind and bind the selectpicker again

### ISSUE THREAD

**Issue by mukeshthe93** [snapappointments/bootstrap-select#2281]
# Description
The selectpicker title is not updating after unbind the "selectpicker" using "off"  jquery method and binding it again using 'on' jquery method. After binding, the selectpicker value is not reflecting on title. But it is reflecting correct value when i am calling "$("#ID").val();"

Query: How can I update the title value of selectpicker. I have to unbind the selectpicker ID when user starts scrolling the page and bind it with a button click. 

The issue is seen in Bootstrap-select v1.12.4. I have also attached the sample code in ".txt" format. 

# Reproduction steps: 
Kindly change the attached file extension to ".html" from ".txt" and follow the below steps to reproduce the issue.
> 1. Launch the page in the browser
> 2. Click on dropdown and select a value. It is working
> 3. Click on "Click TO disable" button to disable the selectpicker
> 4. Click on "Click TO enable" button to enable the selectpicker
 > 5. Click on dropdown and select a value. It is selecting the value but it is not reflecting on Title.
> Hence Issue reproduced.
> 6. I am able to change using below command. 
$('#btnPropTxtStyle').selectpicker('val', '')

[dropDown.txt](https://github.com/snapappointments/bootstrap-select/files/3187672/dropDown.txt)

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.
