### ISSUE TITLE
bootstrap-select throws javascript error with jquery slim

### ISSUE THREAD

**Issue by kingmotley** [snapappointments/bootstrap-select#2285]
bootstrap-select's default behavior when you have a data-max-options attribute and you select too many items is to throw up a message and then fade it out, however, jquery slim does not contain the .fadeOut function, so it throws a javascript error.

Documentation should be updated to note that the full jquery is required, or the fadeOut function removed or reworked.

**Comment by caseyjhol** [comment]
Released in [v1.13.11](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.11)!
