### ISSUE TITLE
Button at bottom of the dropdown.

### ISSUE THREAD

**Issue by vikkya** [snapappointments/bootstrap-select#2287]
Hi,

Is there any option like `data-live-search="true"`  for button at end of the dropdown. 

Here is the sample screenshot for what i'm trying to explain.

![select-buttob](https://user-images.githubusercontent.com/26187350/58412791-d7782080-8094-11e9-8390-c15ce08f0cb1.png)

Thanks.

**Comment by bjufre** [comment]
@vikkya Any news on this?

**Comment by caseyjhol** [comment]
It's not currently documented, but I think `doneButton` and `doneButtonText` should do what you're asking.

**Comment by caseyjhol** [comment]
Closing in favor of #1996. Please 👍 to vote and subscribe 🔉 for updates.
