### ISSUE TITLE
calling refresh after dynamically adding an option breaks automatic sizing of drop-down menu

### ISSUE THREAD

**Issue by MarkusHaak** [snapappointments/bootstrap-select#2288]
Hi,
I have a select picker to which I am dynamically adding options. After calling `$('.selectpicker').selectpicker('refresh');` to update the content, the drop-down menu is no longer updating its height when scrolling on the website. Before calling refresh, the drop-down menu automatically rescales to show as many selectable options as possible, but this behaviour seems to be broken when calling refresh manually. It still flips between drop-up and drop-down though, depending on the amount of space that is available above or beneath, but the height is fixed, no matter if more space is available or parts of the menu are cut-off due to missing space.
I tried to add options without calling refresh and the issue doesn't occur. Of course I won't see the added option then, so this is not really a solution to my problem.

I am using 
firefox 67.0 (64-Bit) on iOS 10.12.6
bootstrap-select 1.13.10
bootstrap 4.1.3
popper 1.14.7

Thank you very much in advance,
Markus

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with your link.
