### ISSUE TITLE
Multiple ticks in optgroup with data-max-options defined as "1"

### ISSUE THREAD

**Issue by adamkalis** [snapappointments/bootstrap-select#2289]
Starting from` v1.13.9`, `optgroup` with `data-max-options="1"` doesn't work as expected.

In [this example](https://jsfiddle.net/w5ktyhrp/2/), with bootstrap v3.3.6 and bootstrap-select v1.13.9, when you click from top to bottom all the options in the popup menu, the ticks don't work as expected. It looks like a UI issue, as when the menu is closed and opened again then it shows the right selection.

The expected behavior can be seen in [this example](https://jsfiddle.net/dxbfsmqo/), with bootstrap v3.3.6 and bootstrap-select v1.13.8.

I've created also [this example](https://next.plnkr.co/edit/JdSVBzXWYk0esyLo) with bootstrap v4 and boostrap-select v1.13.10.

Unfortunately I wasn't able to check it in more depth, a quick guess is that the issue is related to the changes for issue #2126.

I've tested the examples above on both firefox and chromium in a linux distribution.

**Comment by leanec** [comment]
Same problem with Bootstrap v3.4.1 andd Bootstrap-select v1.13.10

**Comment by Merlingilb** [comment]
Please fix this!
Bootstrap-select is such a good tool if there wasn't that issue

**Comment by Merlingilb** [comment]
same problem with bootstrap v4.3.1 and bootstrap-select v1.13.8

**Comment by Merlingilb** [comment]
glad to hear that

**Comment by caseyjhol** [comment]
Released in [v1.13.11](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.11)!
