### ISSUE TITLE
Creating a vanilla JS version

### ISSUE THREAD

**Issue by fabiochelly** [snapappointments/bootstrap-select#2291]
Is it possible to create a Vanilla JS version? It would be a lot faster and as Bootstrap 5 will be pure Vanilla, it would be important  to follow the flow.

Is there a lot of work to convert this plugin to a simple JS object? I can help.

**Comment by caseyjhol** [comment]
It's certainly possible. Right now, most of our limitations come from our attempt to support versions of IE < 11. See https://github.com/snapappointments/bootstrap-select/issues/2228#issuecomment-476328158 for more info.

**Comment by fabiochelly** [comment]
I tried to understand your code but it is huge. I have a lot of experience converting jquery code to Vanilla JS but can you point out the parts that need to be translated?
Will it be an ES6 version using new "class {...}" implementation?

**Comment by NicolasCARPi** [comment]
Closing as duplicate of #2228
