### ISSUE TITLE
Selected values that are disabled are shown in the button

### ISSUE THREAD

**Issue by incodemode** [snapappointments/bootstrap-select#2292]
I filter the possible options with disabled but if the user has selected anything and then those options are set to disabled, when I refresh the button text does not change.
Even if I click on a enabled option it just adds the selection but does not remove the disabled selection.

**Comment by incodemode** [comment]
Fixed it by changing the source code to this:
```
  //if (!HTMLSelectElement.prototype.hasOwnProperty('selectedOptions')) { 
  // comment of the if so always customly selects
    Object.defineProperty(HTMLSelectElement.prototype, 'selectedOptions', {
      get: function () {
        return this.querySelectorAll(':checked:not(:disabled)'); // added the not disabled part
      }
    });
  //}
```

**Comment by caseyjhol** [comment]
If you don't want to show disabled options that are selected in the button, set `hideDisabled: true` or `data-hide-disabled="true"`. If you don't want to enable that, but still don't want to show disabled options in the button, a better alternative would be to actually update the select's value to not include the disabled options.
