### ISSUE TITLE
selectpicker without jquery for the future

### ISSUE THREAD

**Issue by danielchirinos** [snapappointments/bootstrap-select#2295]
in the future there will be a version that does not incorporate jquery? I'm trying to do all my code with native JS and I've come across that by calling the selectpicker () I have to do it by Jquery forced.

**Comment by caseyjhol** [comment]
Please 👍 and follow #2291. We're targeting a native JS version in v3.0.0.

**Comment by fabiochelly** [comment]
I tried to understand your code but it is very complicated. I have a lot of experience converting jquery code to Vanilla JS but can you point out the parts that need to be translated?
Will it be an ES6 version with the new "class {...}" kind of code?
