### ISSUE TITLE
How to pass data attribute for option

### ISSUE THREAD

**Issue by betagoo** [snapappointments/bootstrap-select#2296]
I have select filed.
I add some data attributes for option tags.
For example: data-imageurl, data-pageurl.
How to pass this attributes to generated selectpicker dropdown-menu list (LI) element?

**Comment by Kowal0** [comment]
You can try doing it via data-content attribute https://stackoverflow.com/questions/21873370/bootstrap-select-data-attributes

**Comment by mehmetalidumlu** [comment]
Hi @betagoo ,
I have same problem and solved it like this;

HTML

```
<select class="selectpicker" name="ranking-type">
                    <option value="1" data-srv="a" selected>a</option>
                    <option value="2" data-srv="b">b</option>
                    <option value="3" data-srv="c">c</option>
                    <option value="4" data-srv="d">d</option>
                    <option value="5" data-srv="e">e</option>
                    <option value="6" data-srv="f">f</option>
                    <option value="7" data-srv="g">g</option>
                </select>
```

Solution;

`$('select[name="ranking-type"] option[value="' + $('select[name="ranking-type"]').selectpicker('val') + '"]').data('srv')`

**Comment by ctf0** [comment]
@mehmetalidumlu another way could be

```js
let slctor = 'select[name="ranking-type"]'

$(slctor).on('changed.bs.select', function (e, clickedIndex, isSelected, previousValue) {
    let data = $(`${slctor} option`).eq(clickedIndex).data('srv')
})
```

**Comment by SDKiller** [comment]
As an ugly workaround it is also possible to pass some data via `class` attribute of select options (https://developer.snapappointments.com/bootstrap-select/examples/#style-individual-options).

Here is my case - I had to pass company_id:
```
<select name="shops">
    <option class="company_id_1" value="1">Shop 1</option>
    <option class="company_id_1" value="2">Shop 2</option>
    <option class="company_id_2" value="2">Shop 3</option>
</select>
```

The generated html is as follows:
```
<li class="selected">
    <a role="option" class="dropdown-item company_id_1">
        <span class="text">Shop 1</span>
    </a>
</li>
<li>
    <a role="option" class="dropdown-item company_id_1">
        <span class="text">Shop 2</span>
    </a>
</li>
<li>
    <a role="option" class="dropdown-item company_id_2"">   
        <span class="text">Shop 3</span>
    </a>
</li>
```

**Comment by umutilbas** [comment]
Getting selectpicker options attribute data with JQ as short as this :

$('#select_picker_id option:selected').attr('data-attr-name');

**Comment by zdilby** [comment]
@ctf0 just use $(this) is more short

`$(this).children('option').eq(clickedIndex).data('srv');`
