### ISSUE TITLE
Is it impossible to change the default character?

### ISSUE THREAD

**Issue by TechnicalSuwako** [snapappointments/bootstrap-select#2302]
There is "何もが選択した" when not selected.
Because it is funny Japanese, I would definitely like to change it, but once I put "noneSelectedText", I will not change it at all.
![Screenshot_20190708_111440](https://user-images.githubusercontent.com/15627184/60778345-adc11780-a171-11e9-9461-1c1ae8f5ca58.png)
　　　↓
![Screenshot_20190708_111546](https://user-images.githubusercontent.com/15627184/60778368-bfa2ba80-a171-11e9-8b51-713c4595cf66.png)

Thank you.

**Comment by giero** [comment]
@TechnicalSuwako In HTML you should use `data-none-selected-text` - not `noneSelectedText` (as you used `data-live-search="true"`) :)

**Comment by TechnicalSuwako** [comment]
助かったーー
Thank you!
