### ISSUE TITLE
V1.13.10 Selecting non existing option by code breaks the selection

### ISSUE THREAD

**Issue by Jaroost** [snapappointments/bootstrap-select#2303]
In Version 1.13.10

Here the bug:

When you select a non existing option by code in select, it breaks the selection by hand:

Here a [code pen](https://codepen.io/anon/pen/WqYama?editors=1111) of the issue.

Here the  v1.13.9 [code pen](https://codepen.io/anon/pen/YoRdVM?editors=1111) working

**Comment by giero** [comment]
This bug was also reported here: https://github.com/snapappointments/bootstrap-select/issues/2263

**Comment by caseyjhol** [comment]
Duplicate of #2263.
