### ISSUE TITLE
Bootstrap-Select is available on PageCDN

### ISSUE THREAD

**Issue by praisedpk** [snapappointments/bootstrap-select#2306]
PageCDN uses **brotli-11** compression that reduces bootstrap-select files' size by a few more KBs compared to other CDNs. In addition, **immutable caching** is enabled by default to optimize content delivery aggressively. [Bootstrap Select CDN](https://pagecdn.com/lib/bootstrap-select) on PageCDN.
	
    2.32 KB  bootstrap-select.min.css
    13.70 KB bootstrap-select.min.js

Thanks.

**Comment by caseyjhol** [comment]
It looks like the homepage URL, as well as the project description are both incorrect/outdated. Where are you pulling that information from?

**Comment by praisedpk** [comment]
Updated the description, as well as the homepage URL. Thanks for pointing out the discrepancy.
