### ISSUE TITLE
Using of search="true" and width="auto" together

### ISSUE THREAD

**Issue by CharleysTante** [snapappointments/bootstrap-select#2309]
If I use data-live-search="true" and data-width="auto" together I will get a proper result in Firefox, but not in Chrome. In Chrome, the top item of the select box is smaller than the text it contains for the top item. At least if the text 40 or more characters. In Firefox the width correctly fits to the text.

Is there any way to fix this?

jQuery: 3.4.1
Bootstrap: 3.4.1
Bootstrap-Select: 1.13.9

In Chrom (V. 75.0.3770.142):
![Bootstrap_Select_Chrom](https://user-images.githubusercontent.com/23652883/61443675-457ced80-a94a-11e9-867e-6c6a16d8f1d1.png)

In Firefox (V. 60.8.0esr):
![Bootstra_Select_Firefox](https://user-images.githubusercontent.com/23652883/61444147-1f0b8200-a94b-11e9-9552-870906b5b31a.png)

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version (ensure you're trying with the latest release)
- specific browser and OS details.
