### ISSUE TITLE
i hive a problem about 'nothing select'

### ISSUE THREAD

**Issue by LongStockingPipi** [snapappointments/bootstrap-select#2310]
The data of this component has been loaded in. I tried to select one, normal, and then another, and an error would be reported. After debugging the code, I found that the value of e. t.value was a strange string, and the format was:?String: XXX?, where XXX is the normal value, may I ask what is the situation?
Add that anomalies occur at intervals, one normal and one abnormal

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.
