### ISSUE TITLE
Require Popper + Unexpected token

### ISSUE THREAD

**Issue by AlissonRS** [snapappointments/bootstrap-select#2311]
First, I add the bootstrap select script:

`<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>`

Then I get this message: "Bootstrap's dropdowns require Popper.js", which makes sense. Then I add popper using a CDN:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/popper.min.js"></script>`

But then Popper throws an error: **"Unexpected token export"**.

Then I found [in this SO thread](https://stackoverflow.com/a/48498096/2263507) that I should be using the UMD version:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js"></script>`

But then I start getting this message again: **"Bootstrap's dropdowns require Popper.js"**

What am I missing?

**Comment by Kowal0** [comment]
Are you including popper.js after bootstrap? You should first import jquery, then popper, then bootstrap and finally bootstrap-select.

**Comment by caseyjhol** [comment]
The correct order to load the JS files:

- jQuery
- Popper.js
- Bootstrap
- bootstrap-select

**Comment by aibrahim2020** [comment]
@caseyjhol 
How can apply that order in the master.site
