### ISSUE TITLE
How to add options dynamically in bootstrap 4 version

### ISSUE THREAD

**Issue by dropways** [snapappointments/bootstrap-select#2312]
Hi,

Thank you for sharing bootstrap-select with the community.

I'm using the 1.13.9 version with bootstrap 4.

How to add dynamically data inside dropdown menu. 

like this type
http://www.marcorpsa.com/ee/t1161.jq1.html
bootstrap-select 1.13.6  and above not working.

![Add options dynamically](https://user-images.githubusercontent.com/38377336/61787543-9f3f5500-ae2d-11e9-9c6f-9140cf45665f.gif)

**Comment by caseyjhol** [comment]
Similar to #990. Please subscribe and 👍 #990 for updates.
