### ISSUE TITLE
Selectpicker not being removed when clicking outside selectpicker

### ISSUE THREAD

**Issue by itsjithinv** [snapappointments/bootstrap-select#2313]
## Selectpicker not being removed when clicking outside select picker

I am using Vue JS with select-picker (v1.13.10). When I initializing select picker without options, it shows the popup but after clicking outside of the select box or somewhere in the body, select-picker doesn't close.

```
<select id="departments" class="form-control selectpicker" name="departments[]"
 multiple="multiple" title="Select departments" data-dropup-auto="false"  
data-selected-text-format="count > 2" data-live-search="true"  
data-allow-clear="true" v-model="selectedDepartments">
     <option v-for="department in departments" :value="department.id">
                  {{ department.name }}
     </option>
</select>

// Here I'm initializing like follows

 $('#departments').selectpicker();

```
Please look at the following screenshot.

![Screenshot 2019-07-31 at 3 44 41 PM](https://user-images.githubusercontent.com/31924948/62204627-3b77d780-b3ab-11e9-9ccc-9ba72440945d.png)

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.
