### ISSUE TITLE
Bootstrap select dropdown gets distorted when used with slick slider

### ISSUE THREAD

**Issue by adityasharma7** [snapappointments/bootstrap-select#2314]
When using [Bootstrap select](https://github.com/snapappointments/bootstrap-select) dropdown with the [slick](https://github.com/kenwheeler/slick) slider, it gets distorted.

Here is the [link](https://jsfiddle.net/iamaditya/01ncvrbj/) to jsfiddle. 

Does anyone have any solution for this?

Thanks in advance

====================================================================

###### `[  paste your jsfiddle link here  ]`  

https://jsfiddle.net/iamaditya/01ncvrbj/

====================================================================

#### Steps to reproduce the problem
Click on the select box it gets distorted.
![image](https://user-images.githubusercontent.com/15027245/62695669-69d16480-b9f4-11e9-921d-5bdaec747964.png)
 

====================================================================

#### What is the expected behaviour?
Without Slick:
![image](https://user-images.githubusercontent.com/15027245/62695983-1c092c00-b9f5-11e9-8e71-043de52f7ee3.png)

====================================================================

#### What is observed behaviour?
With Slick:
![image](https://user-images.githubusercontent.com/15027245/62695856-cfbdec00-b9f4-11e9-84d0-890142afeb71.png)

====================================================================

**Comment by caseyjhol** [comment]
You need to set `container: 'body'` or `data-container="body"`. https://developer.snapappointments.com/bootstrap-select/examples/#container

**Comment by adityasharma7** [comment]
Thanks @caseyjhol :)
