### ISSUE TITLE
Background color is different from the rest of the bootstrap inputs

### ISSUE THREAD

**Issue by ppazos** [snapappointments/bootstrap-select#2315]
All bootstrap inputs have a white background and a thin light grey border. Bootstrap-select selects are all grey, making the selects to be different than the rest of the inputs on all our forms.

Is there any way to make the bootstrap-select selects to have the same style as the rest of the bootstrap inputs?

**Comment by FELITH** [comment]
I have this issue as well, looking for the resolution
[https://i.imgur.com/DLNnEO4.png](https://i.imgur.com/DLNnEO4.png)

**Comment by ppazos** [comment]
I needed to add the data-style="form-control" to the select picker, then on the CSS:

```
.bootstrap-select > .btn.form-control {
  border: 1px solid #ced4da !important;
}
```

But the library doesn't offer bootstrap compatible look and feel, I think it should since it is "bootstrap" :)

**Comment by caseyjhol** [comment]
bootstrap-select by default uses Bootstrap dropdown styling...if you want normal form field styling, do:

```js
$.fn.selectpicker.Constructor.DEFAULTS.styleBase = 'form-control';
$.fn.selectpicker.Constructor.DEFAULTS.style = '';
```

**Comment by ppazos** [comment]
@caseyjhol in bootstrap 4 the style is not applied and the select is different from the rest of the inputs, as mentioned on the initial issue

**Comment by caseyjhol** [comment]
@ppazos It seems to be working for me: https://plnkr.co/edit/8zawv5a0xiVw3dneIC2W?p=preview.
