### ISSUE TITLE
bsSelect 1.13.10 no focus on the select with data-live-search="true" on Validation

### ISSUE THREAD

**Issue by DidierBe** [snapappointments/bootstrap-select#2317]
Hello

After my update from 1.12.4 to 1.13.10 for better performance in large dropdowns (you did a great job for that), i've been stuck for hours on the fact that my validator doesn't work anymore in a specific case : when using the data-live-search="true" option.

If you delete the data-live-search="true" from the select and also uses 1.13.10 there is no problem, so it is really depending on the data-live-search="true" option integration.

My impression is that the way the focus is placed on the new bs-select is causing the problem. If you click on the select and then away from the select, the message appears.

The code to test, is available on Plunker at following url :
https://plnkr.co/edit/wIfSBRwGUiLUUDZrNl1b?p=preview
or as text
https://github.com/DidierBe/MyCode/blob/master/Issue-bsSelectFocus

Please help :-)

![bootstrap-select-1 12 4](https://user-images.githubusercontent.com/54440512/63595176-940c5000-c5b8-11e9-8f65-692c4cb85900.png)
![bootstrap-select-1 13 10](https://user-images.githubusercontent.com/54440512/63595177-940c5000-c5b8-11e9-9c48-ec491091e60d.png)

**Comment by caseyjhol** [comment]
It looks like native browser validation is working, so the core issue has something to do with the validation plugin you're using. Obviously it was working with bootstrap-select v1.12.4, though, so it's definitely caused by a change in the bootstrap-select code.

**Comment by caseyjhol** [comment]
The reason this is happening in v1.13.0+ is the `select` element has been moved *after* the search's `input` element to allow for easier error styling (previously it was before). Presumably, the validator plugin you're using only works on the first form element in the form-group. There are a couple ways you could handle it.

1. The search's input has `role="combobox"`, so specify that it shouldn't be included:
```js
$.fn.validator.Constructor.INPUT_SELECTOR = ':input:not([type="hidden"], [type="submit"], [type="reset"], [role="combobox"], button)';
```
2. The documentation says:
> By default, the validator will only validate fields that are present when the plugin is initialized.

So simply move validator.js before bootstrap-select.js, so when it's initialized the `input` element won't yet exist on the page, allowing it to target only the `select` element.

The only way to "fix" this with bootstrap-select, that I can see, is by altering the searchbox template to include the attribute `data-validate="false"`. At some point, once custom templates are better supported, this might be an option you could use without altering the code. For now, though, I'd recommend going with option 2 for simplicity.
