### ISSUE TITLE
Extra CSS code is conflicting with default Bootstrap button colors

### ISSUE THREAD

**Issue by jahaganiev** [snapappointments/bootstrap-select#2318]
Hey folks, having an issue with some predefined CSS color code in the library while the live demo doesn't include that CSS code and that's why it doesn't have there.

Here is example code:

```
.bootstrap-select>.dropdown-toggle.bs-placeholder, .bootstrap-select>.dropdown-toggle.bs-placeholder:active, .bootstrap-select>.dropdown-toggle.bs-placeholder:focus, .bootstrap-select>.dropdown-toggle.bs-placeholder:hover {
    color: #999;
}

```

Here a screenshot of the issue:
https://www.dropbox.com/s/u2q73bqzafi9i7c/Screenshot%202019-08-24%2018.10.13.png?dl=0

As you can see from the above screenshot the issue appears on both button styles default and outline styles.

We are not overriding any CSS, below the screenshot shows that it comes from the library:
https://www.dropbox.com/s/mgkccq6su6glysx/Screenshot%202019-08-24%2018.12.15.png?dl=0

The issue can be solved early by removing those lines of code but it's not good solution as each update we have to remove the code manually.

Any suggestion would much appreciated.

Thanks a lot!

**Comment by jahaganiev** [comment]
if the above mentioned extra code will be removed, I believe the below example code won't be needed also:

https://www.dropbox.com/s/xq8s6bcgfd51hf5/Screenshot%202019-08-24%2018.22.50.png?dl=0

**Comment by caseyjhol** [comment]
None of your screenshots are working now. Please try uploading them directly to your Github comment.

**Comment by jahaganiev** [comment]
> None of your screenshots are working now. Please try uploading them directly to your Github comment.

Awee by mistake I've recently deleted all the archived screenshots on the dropbox - will reverse back tomorrow and update you. Thanks a lot for the reply.

**Comment by jahaganiev** [comment]
> None of your screenshots are working now. Please try uploading them directly to your Github comment.

Restored all deleted files, please have a look and let me know if you have any questions. Thanks.

**Comment by caseyjhol** [comment]
In case the images get removed from Dropbox again, here they are:

1. ![image](https://user-images.githubusercontent.com/2874325/65379388-692f1d80-dc84-11e9-916c-778ea636775c.png)
2. ![image](https://user-images.githubusercontent.com/2874325/65379389-6c2a0e00-dc84-11e9-990c-a2c0757f8852.png)
3. ![image](https://user-images.githubusercontent.com/2874325/65379391-6fbd9500-dc84-11e9-8407-83b0ef2064a0.png)

**Comment by caseyjhol** [comment]
@jahaganiev Can you link me to a live example of this issue?

**Comment by matthewhegarty** [comment]
I resolved the issue I was having by specifying a style:
```html
<select class="selectpicker" data-style="btn-light">
```

**Comment by caseyjhol** [comment]
Good to hear! I'm still not entirely sure what your issue was (or, rather, what was causing it), as the text color *should* have been white with 50% opacity if the button had the btn-primary class. In any case, I'll close this for now.
