### ISSUE TITLE
Resizing issue on window height change

### ISSUE THREAD

**Issue by thorst** [snapappointments/bootstrap-select#2322]
Very simple code markup:
https://jsfiddle.net/thorst/f8u67jp2/10/

View code output:
https://jsfiddle.net/thorst/f8u67jp2/10/show

The issue is simple, when you mess with window height the dropdown gets really wide, has a tendency to go offscreen, and cannot recover without a refresh.

To reproduce:

1. Open https://jsfiddle.net/thorst/f8u67jp2/7/show
2. Make the window not full screen
3. Expand dropdown
4. Drag the bottom of the window up until you see the drop down pop up a couple pixels, this occurs when the window is around 268px tall (sometimes under certain circumstances itll happen before 268)
5. From now on, no matter how you resize the window, the width of the drop down will stay the same

Using chrome on desktop

**Comment by caseyjhol** [comment]
Seems related to #2266.

**Comment by securedsigningsupport** [comment]
the latest version 1.13.12 still has this issue. #2266 fixed width issue but not height issue here.
a walkaround is to add refresh on show.bs.select event
