### ISSUE TITLE
Privacy error on website

### ISSUE THREAD

**Issue by robbaker292** [snapappointments/bootstrap-select#2325]
When visiting the website at `https://developer.snapappointments.com/bootstrap-select/examples/` I get the following error in Chrome `NET::ERR_CERT_DATE_INVALID`.

Firefox reports the certificate expired at 19/09/2019 13:34 (presumably UTC)

**Comment by caseyjhol** [comment]
Working on getting this updated ASAP.

**Comment by caseyjhol** [comment]
Fixed.
