### ISSUE TITLE
Disable dropupAuto from defaults or from data-attribute not working

### ISSUE THREAD

**Issue by 7iomka** [snapappointments/bootstrap-select#2331]
Demo with latest version of this plugin
Scroll to the end of page.
https://codepen.io/7iomka/pen/NWKQOjX?editors=1010

I need to disable global for all instances of plugin dropupAuto.
From documentation, I need to put data-dropup-auto="false" for each instance. It's overhead.
Ok. I go to override defaults. Defaults seems to be changed, but without any effect.

Why?
How to fix that?

**Comment by caseyjhol** [comment]
Duplicate of #2262.
