### ISSUE TITLE
Showing select box next to each other on MsEdge

### ISSUE THREAD

**Issue by MenAtWeb** [snapappointments/bootstrap-select#2336]
I've searched everywhere but no luck to find a solution.

The issue is showing the select box next to each other on MsEdge browser though everything is good with Google Chrome.

This is how it looks on Chrome.
![Capture1](https://user-images.githubusercontent.com/56418633/66617476-0399d580-ec21-11e9-8896-2ef84f58693b.PNG)

And, this is how it looks on Edge.
![Capture2](https://user-images.githubusercontent.com/56418633/66617524-2deb9300-ec21-11e9-9986-ce748338d262.PNG)

In my JS I have this:
`$('#myList').selectpicker({  
         noneSelectedText: 'Choose one or more types'
    });`

In my HTML, I have this:
![Capture3](https://user-images.githubusercontent.com/56418633/66618292-50cb7680-ec24-11e9-9f21-eea7e57acf4b.PNG)
I've tried both load options dynamically and write the options statically. But, neither is working. I am wondering if any of you have a solution to this issue.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

**Comment by MenAtWeb** [comment]
I've later found that it was conflicting with jquery-steps. The issue is solved after I've moved the select input box out of the step wizard form. It would be great if there's a way to resolve such conflicting issue. Thank you.

**Comment by caseyjhol** [comment]
@MenAtWeb Without seeing an example or having any of the other information I mentioned in my previous message, I'm unable to determine if this is something that could be fixed from within bootstrap-select or not. If you can get me an example I'd be happy to take a look.
