### ISSUE TITLE
data-size="false" issue

### ISSUE THREAD

**Issue by Otokiru** [snapappointments/bootstrap-select#2339]
According to the documentation, "When set to false, the menu will always show all items."

However, when i tried using data-size="false", none of my options are actually showing.
Was it meant to be like that or it is a bug?

Here's the edited Playground replica: [https://plnkr.co/edit/tdBnTzkSaS4mEolMWmiB?p=preview](https://plnkr.co/edit/tdBnTzkSaS4mEolMWmiB?p=preview)
-1st multiple select is working fine as data-size="5".
-2nd multiple select is not showing any options as data-size="false".

What I'm trying to archive is to show all my options and set the height base on HTML attribute "size". So basically, is to always show the menu. Not sure if its possible in the current release.

**Comment by Otokiru** [comment]
Adding more info:
-Bootstrap version: 4.1.0
-bootstrap-select version: 1.13.12
-specific browser and OS details: 
Chrome (Version 77.0.3865.120 (Official Build) (64-bit)
Win 10 Pro 64-bit (Build 18362)

**Comment by caseyjhol** [comment]
Released in [v1.13.13](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.13)!
