### ISSUE TITLE
Text color in search box is white, cannot change it to black

### ISSUE THREAD

**Issue by tofiqjutt** [snapappointments/bootstrap-select#2343]
![image](https://user-images.githubusercontent.com/43275829/67220809-4efd7200-f3df-11e9-889d-a0457f91f461.png)

I am using black dashboard pro by creative tim and when I try to use snapappointments select, the text color in searchbox is white and I cannot change it to black

**Comment by caseyjhol** [comment]
This is an issue with the theme you're using and is not caused by bootstrap-select.
