### ISSUE TITLE
Toggler button is invalid HTML

### ISSUE THREAD

**Issue by ghost** [snapappointments/bootstrap-select#2350]
Hi,

Why does the project use a `<button type="button">` as toggler button with many `<div>` inside? It's invalid html in validator: [https://validator.w3.org/nu](https://validator.w3.org/nu).

Would not it be more interesting to replace the `<button  type="button">` with a `<div>`  tag ? Or maybe replace `<div>` tags inside with `<span>` tags...

![button](https://user-images.githubusercontent.com/57239073/67992091-c29f4a80-fc3b-11e9-8caa-7907f11776ef.PNG)

**Comment by caseyjhol** [comment]
Please follow #2376.
