### ISSUE TITLE
<select> is too small, I end up with a blank

### ISSUE THREAD

**Issue by Machou** [snapappointments/bootstrap-select#2355]
Hello,

When the <select> is too small, I end up with a blank at the end of the list.

How to correct this problem? (except to increase the length)

See Screenshot : https://i.imgur.com/88PfCkJ.jpg

Sincerely

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.
