### ISSUE TITLE
Uncaught TypeError: $(...).selectpicker is not a function

### ISSUE THREAD

**Issue by marsalans** [snapappointments/bootstrap-select#2357]
Hi, i'm, getting **Uncaught TypeError: $(...).selectpicker is not a function**

```
VM906:5 Uncaught TypeError: $(...).selectpicker is not a function
    at HTMLDocument.eval (eval at <anonymous> (jquery.min.js:2), <anonymous>:5:26)
    at i (jquery.min.js:2)
    at Object.add [as done] (jquery.min.js:2)
    at n.fn.init.n.fn.ready (jquery.min.js:2)
    at eval (eval at <anonymous> (jquery.min.js:2), <anonymous>:4:13)
    at eval (<anonymous>)
    at jquery.min.js:2
    at Function.globalEval (jquery.min.js:2)
    at Ha (jquery.min.js:3)
    at n.fn.init.append (jquery.min.js:3)
```

I'm using:
- BSB Admin Admin Template
- Jquery v1.12.4
- Bootstrap v3.3.6
- Bootstrap Select v1.13.11
- Browser: Chrome: Version 77.0.3865.75 (Official Build) (64-bit)

I added **selectpicker** class and initilize with **$('select.selectpicker').selectpicker();**

My HTML:

```
<div class="row clearfix">

<div class="col-md-3 m-sm-4">
<select class="selectpicker show-tick form-control show-menu-arrow">
<option>Enabled</option>
<option>Disabled</option>
</select>
</div>

<div class="col-md-3 m-sm-4">
<select class="selectpicker show-tick form-control">
<option>Active</option>
<option>Expired</option>
<option>Upcoming Expiry</option>
<option>Expiring Today</option>
<option>New Unactivated</option>
</select>
</div>

<div class="col-md-3 m-sm-4">
<select class="selectpicker show-tick form-control">
<option>Verified</option>
<option>Unverified</option>
</select>
</div>

<div class="col-md-3 m-sm-4">
<select class="selectpicker show-tick form-control">
<option>2mb</option>
<option>3mb</option>
</select>
</div>

</div><!--ROW1:END-->
```

After adding class and initializing my select drop-downs are not shown and gives error, and when i comment initialize error is gone but dropdowns still not displayed, removing selectpicker class display dropdowns.

Before Adding selectpicker class and initializing:

![selkect0](https://user-images.githubusercontent.com/36761603/69349299-542d3580-0c99-11ea-8c8b-3723defddbeb.PNG)

After adding selectpicker only:

![selkect02](https://user-images.githubusercontent.com/36761603/69349373-72933100-0c99-11ea-82b4-dad7eb0200cc.PNG)

After adding selectpicker and initializing:

![selkect1](https://user-images.githubusercontent.com/36761603/69349406-80e14d00-0c99-11ea-979c-4ec528bb5225.PNG)

**Comment by caseyjhol** [comment]
It sounds like it might be an issue with the order you're loading your JS. Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with your link.
