### ISSUE TITLE
bootstrap-select in col causes near col-auto breaking to newline

### ISSUE THREAD

**Issue by fabiomosti** [snapappointments/bootstrap-select#2358]
hello,
I have an issue when I put the bootstrap-select in a col (auto width) because if the text inside the select is longer than the available space, the near col-auto goes to newline, you can see the issue here:
![image](https://user-images.githubusercontent.com/53529766/69352982-140c8980-0c7e-11ea-998a-b629cc5d864e.png)

the code is:
![image](https://user-images.githubusercontent.com/53529766/69353492-dd833e80-0c7e-11ea-9009-a3eedf01ca56.png)

(sorry I can't figure out how to paste the HTML code, for the "insert code" button does not render it)

if I select a shorter item, the bootstrap-select works fine:

![image](https://user-images.githubusercontent.com/53529766/69353207-6baaf500-0c7e-11ea-85a1-552c9fce600a.png)

any suggestion?

**Comment by 01e9** [comment]
My col-auto is always the same size _(no text, only buttons with icons)_ so I ”fixed” the select column with

```html
<div class="col" style="max-width: calc(100% - 7.6em)"></div>
<div class="col-auto"></div>
```

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.
