### ISSUE TITLE
"Select All" and "Unselect All" Change

### ISSUE THREAD

**Issue by GokhanKR** [snapappointments/bootstrap-select#2359]
I want change "select all" and "unselect all" text with own title, but I'm not found anything on docs.

**Comment by hndcrftd** [comment]
It IS in the documentation, on page https://developer.snapappointments.com/bootstrap-select/options/

You have 2 options:
1. Setting defaults for all instances of bootstrap-select:
After loading the select-bootstrap JS file, place the following JS lines RIGHT AFTER, not on document ready event
Basically, you want the selectpicker library loaded, but before it starts initializing select elements. Which is not MY preferred way.

```
$.fn.selectpicker.Constructor.DEFAULTS.deselectAllText = 'Whatever You Want';
$.fn.selectpicker.Constructor.DEFAULTS.selectAllText = 'Whatever You Want';
```

then when selectpicker runs and initializes all elements that have "selectpicker" class, these will be the button captions

If you are initializing selectpicker manually and you want to apply the defaults globally, the above JS lines CAN go into your on document ready event. Which is MY preferred way

2. You are initializing selectpicker manually, then in your call, place these in the options object, i.e.:

`$('select').selectpicker({deselectAllText: 'Whatever You Want', selectAllText: 'Whatever You Want'});`
