### ISSUE TITLE
countSelectedText not working when only 1 item is selected

### ISSUE THREAD

**Issue by cbrianball** [snapappointments/bootstrap-select#2367]
I have tried setting `countSelectedText` to both a string template as well as a function.
I've also tried setting `selectedTextFormat` to both `count` and `count > 0`.

It works fine if I select more than 1 item, but if I only select 1, I just see that item's text (which in my case doesn't look good since I use a template for each item).

I can understand the default of `selectedTextFormat: "count"` only showing the `countSelectedText` value if more than 1 is selected, but at the very least, I would expect "count>0" to work where it shows my `countSelectedText` template if only one item is selected.

I've narrowed down the issue to one line of code:
https://github.com/snapappointments/bootstrap-select/blob/2c39162d5e4f6584350e14cfdfe3811f27d50afd/js/bootstrap-select.js#L1664

Here's a quick reproduction of the issue (I kept it as simple as possible, even opting to use the default `countSelectText` (and not defining my own).

http://jsfiddle.net/k2ph0vcm/

**Comment by mikemix** [comment]
Still doesn't work.

**Comment by mirko77** [comment]
I have the same issue

**Comment by NicolasCARPi** [comment]
Fixed in beta3 version.
