### ISSUE TITLE
Resize / Scroll listeners added each time select is clicked

### ISSUE THREAD

**Issue by michaelsweeney** [snapappointments/bootstrap-select#2371]
Each time a bootstrap select is clicked, two event listeners are added to the window: resize, and scroll. 

From the bootstrap select [Examples](https://developer.snapappointments.com/bootstrap-select/examples/) page: After clicking one of the selects eight times, you get sixteen listeners: 
![Capture](https://user-images.githubusercontent.com/30322631/71939411-87ac1c80-3180-11ea-954e-4d79e07869d1.JPG)

Live, simplified example here:

https://michaelsweeney.github.io/bootstrap-select-resize-scroll/

As might be expected, calling 'destroy' on the selects doesn't remove them, nor does manually removing the select. This might not be an issue for small projects, but I'm working on a single-page app designed to stay open for relatively long periods of time, with dynamically-created selects each having several hundred options, and I'm concerned about potential memory leaks and/or bloat.

Is there any way to remove these references periodically -- or ideally, not duplicate them in the first place?

**Comment by caseyjhol** [comment]
Looks like this was actually a Bootstrap issue that was fixed in Bootstrap v4.4.0. Not sure which issue/commit specifically.
