### ISSUE TITLE
Problem with quotes in options value

### ISSUE THREAD

**Issue by luisgaldos** [snapappointments/bootstrap-select#2377]
> Problem with quotes in options value
>
> First of all, congrats for doing a very good job customizing HTML5 controls and making it easier to use.
> Now I have a problem when I get the values of a bootstrap-select picker when it has quotes or some special character. I have also tried with the escape function, but when I call to the $("#my_id").val() function, some values are not complete; they are only a part of the string.
>
> 1. Create a select picker with many options and set a string with special characters as their value, use the escape() js function if desired,  the result be the same.
> 2. Call to the $("#selectID").val() function and check returned array. Probably some of the values are not complete.
>
## Thanks in advance!

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.
