### ISSUE TITLE
Dropdown-menu empty after showing a modal dialog

### ISSUE THREAD

**Issue by alex6m59** [snapappointments/bootstrap-select#2378]
Hello,

My selectpicker works well but as soon as i bring a modal dialog, the dropdown menu stay empty.

Steps:
1) Display dropdownmenu in the main page => OK
2) Display modal dialog then close it => OK
3) Display again the dropdownmenu => OK

Now if i don't do the 1st step, the 3rd step will show an empty dropdown menu.
1) DO NOT Display dropdownmenu in the main page
2) Display modal dialog then close it => OK
3) Display again the dropdownmenu => NOK, the dropdown is empty.

I use a JS function to show modal dialog.

It seems there is an accident with the management of the modal dialog.

Here is my configuration :
Bootstrap 4.3.1
Bootstrap select 1.13.12
Firefox 72.0.1 or Chrome 79.0

Now here is a simple example :
Edit: my example was not public, here is the public one: https://embed.plnkr.co/hkk1uJ/

**Comment by alex6m59** [comment]
Finally i decided to manage modal dialogs differently.
I don't append the html code of dialog on the button click.
The html code of dialog is already in the body, and i change the tag values in JS function.

When it's done like this, there is no problem of dropdown menu anymore.

Here is the solution:
https://embed.plnkr.co/9sQmwj/

**Comment by caseyjhol** [comment]
This is just an issue with the way you're appending the modal (innerHTML). See https://stackoverflow.com/a/595825/1922696. Since you're using jQuery anyway, I'd recommend `$('body').append()` instead.
