### ISSUE TITLE
Hidden options make keyboard navigation pretty hard

### ISSUE THREAD

**Issue by giRobert** [snapappointments/bootstrap-select#2379]
Hello,

when you hide a option and try to navigation through the option by using arrow up and down key on your keyboard the index seems to struggle since the option still exists but is hidden.

can you fix the index? it should not trigger hidden options.

here you can test it easy: https://jsfiddle.net/L92jz7ec/

but please dont remove the hidden options. this could break other functions.

**Comment by caseyjhol** [comment]
Fixed in v1.13.13.

**Comment by giRobert** [comment]
not really.. i tried v1.13.16.

https://jsfiddle.net/9z8mxtge/

reproduce it by clicking mustard and use key down. you need to press key twice to go to the other visible element.

**Comment by caseyjhol** [comment]
In your example, you're hiding the option with `class="hidden"`. This isn't supported. Simply add the `hidden` attribute instead.

**Comment by giRobert** [comment]
how do I do so?

**Comment by caseyjhol** [comment]
Instead of adding `class="hidden"` to each option, just add `hidden`.

**Comment by giRobert** [comment]
ok this works. thx. didnt knew its valid html.

thanks for caring!
