### ISSUE TITLE
Shading behind options when scrolling through select

### ISSUE THREAD

**Issue by rfischman** [snapappointments/bootstrap-select#2382]
Is there a way to change the color shading that appears in the dropdown menu when scrolling over the options? 

For example, on Safari, selects are natively rendered such that the options are highlighted blue when scrolling through the list.  However, as soon as I apply the selectpicker class, my background is white and the highlight is no longer visible.

**Comment by caseyjhol** [comment]
You can change the background color using CSS: `.dropdown-item:focus, .dropdown-item:hover`.
