### ISSUE TITLE
Dropdown menu is over select

### ISSUE THREAD

**Issue by pdias** [snapappointments/bootstrap-select#2383]
I created this select:

```
<select class="selectpicker" data-container="body" data-size="5" data-width="100%" data-style="btn btn-light btn-square">
     <option disabled>AAAAAA</option>
     <option disabled>BBBBBBB</option>
</select>
```

The select is inside a table-responsive, for that i use **"data-container="body"** .
The dropdown menu is over the select. I use BS 4.4

![1111](https://user-images.githubusercontent.com/1615884/73077583-5c336c80-3eb8-11ea-86cd-f3fbecb56b22.PNG)

Thanks.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.
