### ISSUE TITLE
🤔 No option for width of dropdown?

### ISSUE THREAD

**Issue by mikeploeger** [snapappointments/bootstrap-select#2387]
Does bootstrap-select offer a width attribute for the content (If you open the select picker)?

Everything I can find is that bootstrap-select offers a data-width="" attribute for the width of the select field. (Before you open it)

In my case the content of the selectpicker is larger than the available width and now it makes my website scrollable horizontally (after opening it), what I don't want.

This feature should already be built in? But I can't find it?

Any help is highly appreciated!

**Comment by mikeploeger** [comment]
Fix: Use dropdownAlignRight: 'auto'

**Comment by NANAARUN** [comment]
still need this 
No option for width of dropdown?
