### ISSUE TITLE
browser freezes when one option is deselected in multiple mode

### ISSUE THREAD

**Issue by arzoni1** [snapappointments/bootstrap-select#2389]
I have big list in select and when I deselect one option by clicking again on the selected option the browser freezes

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.
