### ISSUE TITLE
setStyle fails if newElement.parentNode is a document fragment

### ISSUE THREAD

**Issue by Mobe91** [snapappointments/bootstrap-select#2391]
With version 1.13.12 and Bootstrap 3, `setStyle` fails if `newElement.parentNode` is a document fragment because `classList` is undefined in this case. This used to not be a problem with version 1.13.5.

Also, the call to `buildData()` in `refresh()` should come before `render()` like it is done in `init()`.

**Comment by caseyjhol** [comment]
Released in [v1.13.16](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.16)!
