### ISSUE TITLE
virtual scroll sometimes jumps to first chunk instead of showing last chunk

### ISSUE THREAD

**Issue by Mobe91** [snapappointments/bootstrap-select#2395]
Due to imprecisions in scrollTop vs data position computation, the computation of the currentChunk does not yield a match in some cases. The fallback is to show the first chunk. This results in an empty menu because the current scrollTop and the first chunk margins do not match in this case.

**Comment by BT-aestebanez** [comment]
I reported the same issue in my comment here:
https://github.com/snapappointments/bootstrap-select/issues/2401
it includes a video of the error

**Comment by caseyjhol** [comment]
Seems like this issue has been resolved.
