### ISSUE TITLE
Selectpicker doesn't work just for one select

### ISSUE THREAD

**Issue by fabienwnklr** [snapappointments/bootstrap-select#2398]
Hi, i use bootstrap-select into modal,

so i itinialize this with $('.selectpicker').selectpicker();

on 3 select, 2 working good but 1 do not,

### Here the select does not work open :( ###
![image](https://user-images.githubusercontent.com/49644785/74842149-328c2a80-532a-11ea-8221-a8cbcf164ac0.png)

but all others work

![image](https://user-images.githubusercontent.com/49644785/74842214-4e8fcc00-532a-11ea-9afa-237f1d04b355.png)

It's all because of me. I am sure..!, many thanks :)

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.
