### ISSUE TITLE
data-live-search="true" not working

### ISSUE THREAD

**Issue by syan1992** [snapappointments/bootstrap-select#2399]

**Comment by fabienwnklr** [comment]
More details ? @syan1992

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.
