### ISSUE TITLE
drop down list opens only for the first generated selectpicker

### ISSUE THREAD

**Issue by iliya-hajjar** [snapappointments/bootstrap-select#2404]
I'm using javascirpt to generate selectpickers and the problem is, after generating more that one selectpicker the dropdown list works only for the first one, doesn't matter if you click on the nth selectpicker drop down list opens only for the first selectpicker. Below is the javascript code to generate fields:
```
var newElement = $(selector).clone(true);
    newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
        var name = $(this).attr('name');
        if(name) {
            var new_name = name.replace(name, name+'_'+Uuidv4());
            var id = 'id_' + new_name;
            $(this).attr({'name': new_name, 'id': id}).val('');
        }
    });
    $(selector).after(newElement);
    var conditionRow = $('.table-generate:not(:last)');
    conditionRow.find('.btn.add-form-row')
    .removeClass('btn-success').addClass('btn-danger')
    .removeClass('add-form-row').addClass('remove-form-row')
    .html('-');
```

and here is the first field in html:
```
<select data-width="150px" class="selectpicker" data-live-search="true" data-style="btn-primary btn-round" required title="Tag" name="register_tag" id="id_register_tag">
            {% for tag in tags_name %}
                <option id="{{ tag }}" value="{{ tag }}">{{ tag }}</option>
            {% endfor %}
  </select>
```

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.
