### ISSUE TITLE
 data-live-search="true" not working when using data-container="body"

### ISSUE THREAD

**Issue by rosaricla** [snapappointments/bootstrap-select#2405]
Dear All,

I have been facing some trouble to active the search box with data-live-search="true" when data-container option is set to body. The search box appears but the width is really small and when you start to write the input the first characters do not even appear in the search box. The container is the header of a datatable.

Example of what I obtain when I click the button:
![Captura de pantalla de 2020-03-02 16-35-19](https://user-images.githubusercontent.com/26365784/75690842-d4edcb80-5ca3-11ea-867c-68ba3c7bc32a.png)

Example of what I obtain when I write "chromo" in the search box:
![Captura de pantalla de 2020-03-02 16-31-20](https://user-images.githubusercontent.com/26365784/75690728-a3750000-5ca3-11ea-8a8c-c60599baa3ef.png)

My code is the following:
`<select class="selectpicker" data-none-selected-text="Filter" data-live-search="true" data-width="75%" data-container="body" multiple>
                              <option value="chr1" class="options">Chr 1</option>';
                              <option value="chr2" class="options">Chr 2</option>';
                           </select>`

(If I remove data-container="body" then it is working but is hidden the dropdown) Example:
![Captura de pantalla de 2020-03-02 16-36-41](https://user-images.githubusercontent.com/26365784/75691000-05ce0080-5ca4-11ea-81c7-57d5c3f6984e.png)

I have tried adding this CSS options but the problem continue...
`  .bootstrap-select-searchbox {
        width: 100%;
        margin: 0;
        padding:0;
        text-align: center;`

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.
