### ISSUE TITLE
dropdown stick out of the viewport

### ISSUE THREAD

**Issue by Th3M3** [snapappointments/bootstrap-select#2408]
Hi there,

I am using bootstrap v3.4.1 and included the selectpicker into a `table` cell, `data-container` is set to `body`.

When the selectpicker's button is partly scolled out of view, then the dropout appears on a wrong x-position (outside of viewport).

Any idea how to fix this (without switching to bootstrap v4)?

![dropdown2](https://user-images.githubusercontent.com/28313514/76670052-d31ee480-658e-11ea-8c57-b6510496704d.gif)

Plunker:
https://plnkr.co/edit/sniGnsewezearurI

**Comment by caseyjhol** [comment]
Add:

```js
$.fn.selectpicker.Constructor.DEFAULTS.dropdownAlignRight = 'auto';
```
to your JS. Or, set `data-dropdown-align-right="auto"` on your select. This option will be enabled by default in v2.0.0.
