### ISSUE TITLE
noneSelectedText is not working

### ISSUE THREAD

**Issue by MAXiDROME** [snapappointments/bootstrap-select#2410]
I have selectpicker with this config:
    $('.selectpicker').selectpicker({
        selectedTextFormat:'count > 2',
        noneSelectedText:'Show All',
    });
But I have the "Nothing selected" label on page load. If I change the values of selectpicker and then unselect all, the label is correct.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.
