### ISSUE TITLE
selectpicker on select with class w-100 leads to unexpected behavior

### ISSUE THREAD

**Issue by phylogram** [snapappointments/bootstrap-select#2411]
calling selectpicker on selects with class w-100 and width not 'auto' or 'fill' leads to unexpected behavior (see screenshot)
![strange-full-width-dropdown-issue](https://user-images.githubusercontent.com/29863702/77160723-44d3c280-6aa8-11ea-9a3c-2622cf72f5c2.png)

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.
