### ISSUE TITLE
When dropdown is opened, it is causing other elements to move instead of displaying over the top

### ISSUE THREAD

**Issue by terryaney** [snapappointments/bootstrap-select#2418]
Before posting, please see [guidelines for contributing](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md). If you're submitting a bug report, see below.

jQuery - 3.3.1
Bootstrap-select 1.13.9
Bootstrap - 4.3.1

I am using card-columns css based on card-columns displayed on Bootstrap site.  However, you can remove that css and the problem exists.

1 Card Problem - http://jsfiddle.net/mfn4hsq8/ - when you drop down the select, the submit button moves.

![image](https://user-images.githubusercontent.com/6237247/78379832-9ac06400-7598-11ea-8fa4-c896902217be.png)

(when dropped down)

![image](https://user-images.githubusercontent.com/6237247/78379870-aad84380-7598-11ea-8835-f180077df9a0.png)

2 Card Problem - http://jsfiddle.net/zsfqhrju/1/ - when you dropdown either select, the second 'card' moves underneath the first card and the submit button moves.

Is there some css or data attributes I can assign to help out with that?

If I don't use bootstrap-select the button doesn't move.  To simulate this...

1) Remove bootstrap-select class from `<div class="dropdown bootstrap-select show-tick form-control iAuthStatus1">`
2) Remove selectpicker from `<select name="iAuthStatus1" id="iAuthStatus1" class="form-control selectpicker show-tick iAuthStatus1">`

Then re-run.  Yes, the dropdown now looks ugly ;) But the button doesn't move when dropped down.

![image](https://user-images.githubusercontent.com/6237247/78380028-de1ad280-7598-11ea-99e1-befc4ab5cc86.png)

**Comment by caseyjhol** [comment]
Not sure why it's doing that...probably something to do with flexbox. In the meantime, setting `data-container="body"` on your select should solve your problem.

**Comment by caseyjhol** [comment]
This is being caused by `.card-columns` - specifically the `column-count` property. This is an issue inherent to Bootstrap's dropdown itself, rather than something specific to bootstrap-select: http://jsfiddle.net/caseyjhol/gd3ajuer/7/.

**Comment by caseyjhol** [comment]
It doesn't seem like there's anything we can do about this. As it's being caused by Bootstrap's card-columns class, you'll want to report it to them (or try asking on Stackoverflow first). Here is a similar issue: https://stackoverflow.com/questions/23259901/css-column-count-elements-jumping-across-columns.
