### ISSUE TITLE
selectAll causing Bootstrap error

### ISSUE THREAD

**Issue by lcsqlpete** [snapappointments/bootstrap-select#2420]
I'm issuing a call to the selectAll method which is causing a Bootstrap error.  

Javascript:

`$(function () {
    $('#exchangereason').selectpicker()
    $('#exchangereason').selectpicker('selectAll');
});`

HTML:

`<select id="exchangereason" class="selectpicker" name="ExchangeReason[]" multiple data-style="" data-style-base="form-control" data-actions-box="true">`

Console log:

Uncaught TypeError: Cannot read property 'length' of undefined
    at J.changeAll (bootstrap-select.js:2590)
    at J.selectAll (bootstrap-select.js:2616)
    at HTMLSelectElement.<anonymous> (bootstrap-select.js:2991)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at n.fn.init.Q [as selectpicker] (bootstrap-select.js:2963)
    at HTMLDocument.<anonymous> (reports.js:4)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.

**Comment by lcsqlpete** [comment]
[SelectAll Bug.txt](https://github.com/snapappointments/bootstrap-select/files/4513046/SelectAll.Bug.txt)

This file illustrates the problem. It's actually html even though the extension is .txt.  Load the file in your browser and check the js console to the error.

**Comment by caseyjhol** [comment]
This is fixed in the latest version: https://plnkr.co/edit/OZV3yp99C6XlSwbo.
