### ISSUE TITLE
Live Search Issue When Using Arrow Up or Down After Searching

### ISSUE THREAD

**Issue by jayden-arrai** [snapappointments/bootstrap-select#2421]
Two jsfiddle's explains the issue and how to replicate it.
1. https://jsfiddle.net/ds3zLvue/3/ - This shows 2 issues, it doesn't scroll down 1 item, and a javascript error can occur.
2. https://jsfiddle.net/ds3zLvue/4/ - This one has `data-virtual-scroll="true"` added to the select box and doesn't have the issues from 3.

Instructions:
1. Open the dropdown.
2. Using the arrow keys up and down works fine.
3. Type in `testing`.
4. Using the arrow keys is messed up. If you click the arrow down key 3 times and then click the arrow up key 2 times you will get a javascript error.
5. You don't need to do this item as jsfiddle 4 already has it done.

**Comment by caseyjhol** [comment]
This appears to be fixed in the latest release.
