### ISSUE TITLE
Is this being supported?

### ISSUE THREAD

**Issue by lcsqlpete** [snapappointments/bootstrap-select#2426]
I don't see any responses to issues going back quite some time.  Is this plugin actively supported?  It's the best select plugin I've found but I have several issues which are preventing me from using it

**Comment by caseyjhol** [comment]
Yes, this is still being supported. I've been swamped with another project these past few months, but I'm planning to start tackling issues and features at a greater pace in the coming weeks. Which issues specifically are preventing you from using it?

**Comment by lcsqlpete** [comment]
Great thanks Casey.  This is definitely the best select plugin out there.
Most of my selects are working just fine, just a couple that have issues
and they can stay as plain vanilla selects until the issues are resolved.

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*
