### ISSUE TITLE
Incorrect auto-dropup positioning when scrolling.

### ISSUE THREAD

**Issue by marcinhordziej** [snapappointments/bootstrap-select#2431]
I found annoying bug with auto dropup positioning when scrolling. I found it on my site but the same thing happens on official demo page but it's less visible (because of CSS differences).

When you click the select button and dropdown opens down everything is fine. You can scroll up and down and both .dropup class, dropdown height and inline positioning changes at the same time.

But when you click the select button and dropdown opens up there is strange issue. When scrolling .dropup class and dropdown height changes at different breakpoints then dropdown position. It calculates the height of the dropdown to bottom edge of view but it's top.

Same issue happens on the demo page.

Link:
https://developer.snapappointments.com/bootstrap-select/examples/

Bootstrap version
4.3.1

Bootstrap Select version
1.13.9

Link:
https://nobuhomes.pl/

Bootstrap version
4.1.3

Bootstrap Select version
1.13.12

OS: Windows 7, Windows 10, macOS

Browser: Firefox, Chrome, Edge, Internet Explorer, Opera, Safari
I've uploaded the issue here:
[YouTube Video](https://youtu.be/EOYzEdoy-4Y)

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.

**Comment by marcinhordziej** [comment]
Updated

It happens also on preconfigured Plunker on every browser and OS.

**Comment by caseyjhol** [comment]
Is there a specific example on that page I should be focusing on? Everything appears to be functioning normally as far as I can tell.

**Comment by marcinhordziej** [comment]
Yes, check the video on YouTube. Same thing happens on Plunker and Demo Page.

One more video made on Plunker:
https://youtu.be/xh8iTpHV27A

Look at the dropup class.

**Comment by caseyjhol** [comment]
Ah, I see what's happening. Popper's positioning is taking precedence, so occasionally the dropup class is being ignored (and vice versa).

**Comment by marcinhordziej** [comment]
It's not occasionally, it's happens all the time but on some styles it's less visible. On mine it's very visible. Is it possible to fix it?

**Comment by caseyjhol** [comment]
When I say occasional, I mean that there are times when the menu's dropup class is being obeyed and thus behaving normally. I'm not sure if this is fixable yet. In the meantime, on your select element, adding `data-display="static"` should work for you. This disables Popper and uses bootstrap-select's built-in menu positioning.

**Comment by caseyjhol** [comment]
Looks like this is essentially a duplicate of #2262. Closing this in favor of that issue. Please 👍 to vote and subscribe 🔉 for updates.
