### ISSUE TITLE
Populating multiple select with array doesn't keep array order

### ISSUE THREAD

**Issue by FSeixasPT** [snapappointments/bootstrap-select#2434]
I'm using bootstrap-select to create a dropdown menu where users can select up to 3 options, initialized like so:

```
$('#PItypeSelect').selectpicker({
    maxOptions: 3,
});
```

Let's say this is the HTML:

```
 <select id='PItypeSelect' multiple>
     <option>A</option>
     <option>B</option>
     <option>C</option>
     <option>D</option>
     <option>E</option>
 </select>
```

And now I'd like to set the selected options from an array, for example `type = ['B','A','C']`, but no matter what I try, it always ends up being displayed as A, B, C instead of B, A, C.

Neither

`$('#PItypeSelect').selectpicker('val', type);`

nor

```
$('#PItypeSelect').val(type);
$('#PItypeSelect').selectpicker('refresh');
```

work. Is there any way to do this? Maybe iterate the array and add the options one by one?

**Comment by FSeixasPT** [comment]
Temporary workaround is to call

`$('.filter-option-inner-inner').text(type.join(', '));`

after setting the value, changing the displayed text. Feels too hacky though.

**Comment by caseyjhol** [comment]
Duplicate of #2119. Please 👍 to vote and subscribe 🔉 for updates.

**Comment by FSeixasPT** [comment]
It's related but not exactly the same. I managed to get a vector with the correct user-selection order (also in a hacky way...), but what I'm looking for is the reverse - I have a vector with a certain order and I'd like to populate the select with that order. 👍'd anyway.
