### ISSUE TITLE
hasOwnProperty is not a function

### ISSUE THREAD

**Issue by billclinton8** [snapappointments/bootstrap-select#2438]
html:
<select #DataCombobox [attr.data-live-search]="true"  ..... ></select>

 for (var dataAttr in dataAttributes) {
		           if (dataAttributes.hasOwnProperty(dataAttr) && $.inArray(dataAttr, DISALLOWED_ATTRIBUTES) !== -1) {
              delete dataAttributes[dataAttr];
            }
			
          }

My HTML reports hasownproperty is not a function in the following JS

**Comment by caseyjhol** [comment]
Duplicate of #2430.
