### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Constructor' of undefined

### ISSUE THREAD

**Issue by gavinju** [snapappointments/bootstrap-select#2439]
When I upgraded from 1.13.12 to the 1.13.14 version, some errors occurred：
“Uncaught TypeError: Cannot read property 'Constructor' of undefined”

I found there is  new code in 1.13.14：
// get Bootstrap's keydown event handler for either Bootstrap 4 or Bootstrap 3
var bootstrapKeydown = $.fn.dropdown.Constructor._dataApiKeydownHandler || $.fn.dropdown.Constructor.prototype.keydown;

Please help me, how to solve this problem？
thank you very much！

Bootstrap version
4.3.1

JQuery version
3.4.1

Bootstrap-Select version
1.13.14

OS: Windows 10, macOS

**Comment by caseyjhol** [comment]
Released in [v1.13.15](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.15)!

**Comment by Skillnter** [comment]
using 1.13.18 facing the same issue 👎

**Comment by CollectionAgency** [comment]
Error still occuring.

**Comment by RamonaBarbieru** [comment]
Just downloaded the last release and the error is still there. Fixed by put the js link at the bottom of the page.

**Comment by TheGP** [comment]
Its caused by bootstrap js(with draggable js) loading after bootstrap-select js

**Comment by offlineC** [comment]
Try include the bootstrap js script (as what I've used from [here ](https://getbootstrap.com/docs/4.6/getting-started/introduction/) for bootstrap v4.6). Or use the respective versions that come with the boostrap css's version.

I tried including the bootstrap script and the issue is fixed.

**Comment by manager-wiseTech** [comment]
Try to use bootstrap [4.6.0](https://getbootstrap.com/docs/4.6/getting-started/introduction/) and try to load bootstrap base files before SELECT  plugin js and CSS files.

**Comment by kinglion580** [comment]
### reminder：remember Bootstrap’s dropdown.js component.
```html
<script type="text/javascript" src="{% static 'js/dropdown.js' %}"></script>
```

**Comment by shirgans** [comment]
I'm using Bootstrap 5.1 and loading it before the select plugin. Still, got that issue... any solution?

**Comment by shirgans** [comment]
I managed to fix that after taking the exact version as [in here](https://plnkr.co/edit/AA74u8B1DeJ1J6DB?open=lib%2Fscript.js&preview)

**Comment by nurmuhammet-ali** [comment]
> I managed to fix that after taking the exact version as [in here](https://plnkr.co/edit/AA74u8B1DeJ1J6DB?open=lib%2Fscript.js&preview)

Thank you my man

**Comment by iheblhbib** [comment]
> I managed to fix that after taking the exact version as [in here](https://plnkr.co/edit/AA74u8B1DeJ1J6DB?open=lib%2Fscript.js&preview)

thanks man

**Comment by jthomp** [comment]
> I managed to fix that after taking the exact version as [in here](https://plnkr.co/edit/AA74u8B1DeJ1J6DB?open=lib%2Fscript.js&preview)

Fixed this for me, as well. Thanks!

**Comment by RenrevZ** [comment]
> I managed to fix that after taking the exact version as [in here](https://plnkr.co/edit/AA74u8B1DeJ1J6DB?open=lib%2Fscript.js&preview)

damn 2022 and this is still the solution

**Comment by Symness** [comment]
> I managed to fix that after taking the exact version as [in here](https://plnkr.co/edit/AA74u8B1DeJ1J6DB?open=lib%2Fscript.js&preview)

Thanks !

**Comment by andrewsemchism** [comment]
> I managed to fix that after taking the exact version as [in here](https://plnkr.co/edit/AA74u8B1DeJ1J6DB?open=lib%2Fscript.js&preview)

Worked for me. Thanks.

**Comment by isackblue** [comment]
> I managed to fix that after taking the exact version as [in here](https://plnkr.co/edit/AA74u8B1DeJ1J6DB?open=lib%2Fscript.js&preview)

Excelent!! Working here with Bootstrap 5.20

**Comment by ekane3** [comment]
> I managed to fix that after taking the exact version as [in here](https://plnkr.co/edit/AA74u8B1DeJ1J6DB?open=lib%2Fscript.js&preview)

Thanks very much for your answer, i spent roughly a couple of hours looking for a good cdn solution

**Comment by iankucera** [comment]
I can confirm this is fixed by latest bootstrap-select beta2 or beta3
https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js

**Comment by muhismail015** [comment]
> I can confirm this is fixed by latest bootstrap-select beta2 or beta3 https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js

its works, thanks!!

**Comment by mithunkottayi** [comment]
It's working, thanks

**Comment by wliontb** [comment]
> I can confirm this is fixed by latest bootstrap-select beta2 or beta3 https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js

Thks

**Comment by gxcplcto** [comment]
In Bootstrap 5.3 I am getting this error:

Uncaught TypeError: can't access property "Constructor", $.fn.dropdown is undefined
    <anonymous> bootstrap-select.js:3133
    <anonymous> bootstrap-select.js:3152
    <anonymous> bootstrap-select.js:21
    <anonymous> bootstrap-select.js:23

 I am trying to implement the Live Search.

Other scripts that I am using are:
```
<script src="<cms:show k_site_link />assets/js/jquery-3.0.0.js"></script>
<script src="<cms:show k_site_link />assets/js/popper.js"></script>
<script src="<cms:show k_site_link />assets/js/bootstrap.js"></script>
<script src="<cms:show k_site_link />assets/js/Chart.js"></script>
<script src="<cms:show k_site_link />assets/js/bootstrap-select.js"></script>
```
and they are in the same sequence as mentioned above.

**Comment by maulidailham** [comment]
the beta version didnt include search functionality!

**Comment by kriit24** [comment]
does not worked for me. Bootstrap v5.0.0-beta3
edit: also does not work with Bootstrap v5.3.2

**Comment by Mike-A-Qian** [comment]
> I can confirm this is fixed by latest bootstrap-select beta2 or beta3我可以确认这已通过最新的 bootstrap-select beta2 或 beta3 修复 https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js

thanks

**Comment by dudugsx** [comment]
> I managed to fix that after taking the exact version as [in here](https://plnkr.co/edit/AA74u8B1DeJ1J6DB?open=lib%2Fscript.js&preview)

Thank you, it worked for me. 
bootstrap 5.1.0 and bootstrap-select 1.14.0-beta3

**Comment by baij45** [comment]
> I managed to fix that after taking the exact version as [in here](https://plnkr.co/edit/AA74u8B1DeJ1J6DB?open=lib%2Fscript.js&preview)

相当有用
