### ISSUE TITLE
Problem with refresh and selected item

### ISSUE THREAD

**Issue by ts1985** [snapappointments/bootstrap-select#2445]
In 1.13.10 it works. But I updated the version to 1.13.15 and since then there is a problem.
I change the list and I also selected an option in the changed list. After that I call refresh and the list is also updated. But it shows that there is nothing selected. (but when you open it you can see that something is selected)
If you call refresh 2 times, it will be displayed correctly.

Bootstrap 4.1.0
Bootstrap-Select 1.13.15
All browsers in all operating systems

https://plnkr.co/edit/cBeMQjFADuzzvcJH

**Comment by caseyjhol** [comment]
Looks like this is fixed in the upcoming release, which should be out today.

**Comment by caseyjhol** [comment]
Released in [v1.13.16](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.16)!
