### ISSUE TITLE
Dropdown empty 

### ISSUE THREAD

**Issue by HakimGhanem** [snapappointments/bootstrap-select#2447]
Hello, I have an issue with the dropdown

`                <select class="selectpicker" name="iselectlibellemarque" id="iselectlibellemarque" title="Sélectionnez une marque" style="width: 210px;" data-live-search="true" data-actions-box="true" multiple></select></br>

<script>
select_marque = document.getElementById( 'iselectlibellemarque' );
    for( i in Object.keys(lib_pk_marque_dict) ) {
        select_marque.add( new Option( libelle_marques[i] ) );
    };
</script>
`

I am deploying a Flask application into an Azure Cloud environment, some people see all my options (150+) but some of them have no options. I don't know why. I tried to fix it with browser options but all the users have last versions of Chrome or Firefox. How can I fix that?

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.
