### ISSUE TITLE
Why the selectpicker's display shows none?

### ISSUE THREAD

**Issue by liusming** [snapappointments/bootstrap-select#2449]
Hi,

I following the getting start including CDN and download locally with the very simple code as example. However, nothing shows there!

When I dived into the code, I found the attribute to "selectpicker" class was "Display: none"? I am wondering what wrong with it or there is any misunderstanding? Would you kindly advise?

**Comment by caseyjhol** [comment]
It sounds like you're only loading the CSS and not including bootstrap-select.js.

**Comment by liusming** [comment]
CDN seems method seems not working. Then I install to locally and still has error in javascript.
bootstrap-select.js:350 Uncaught TypeError: Cannot read property 'valHooks' of undefined
    at bootstrap-select.js:350
    at bootstrap-select.js:3152
    at bootstrap-select.js:21
    at bootstrap-select.js:23

**Comment by caseyjhol** [comment]
Are you loading jQuery before Bootstrap and bootstrap-select? You can see the CDN is working here: https://plnkr.co/edit/mUIJB7xQwaSfjFeX.

**Comment by mfalconi-perle** [comment]
I am having the same issue, console shows no errors. using latest version of bootstrap-select with bootstrap 4. All my bootstrap dependencies are loaded as they are used across our whole site, however when using bootstrap select all my selects end up being hidden

**Comment by jOHAN-bIRD** [comment]
When loading the select (whether inside a modal or on the main page), insert this call after the HTML:

$('.selectpicker').selectpicker('render');

This way it will render the selects again.
