### ISSUE TITLE
Duplicate selectpicker after refresh

### ISSUE THREAD

**Issue by lcsqlpete** [snapappointments/bootstrap-select#2451]
OSX 10.14.6
Bootstrap 3.3.7
bootstrap-select v1.13.16
Chrome Version 81.0.4044.122 (Official Build) (64-bit)
Example https://plnkr.co/edit/Nxqtaesbgh6rKvZb

To run the example:
Click the Open Modal button
In the modal, click the plus sign icon
2 selectpickers appear.

The js for the plus sign icon, copies the <tr> from add-template-table to default-products-table and refreshes the selectpicker in default-products-table.  Without the refresh, only 1 selectpicker appears but it is empty.

I found a similar issue but it was recently closed without a resolution.

**Comment by caseyjhol** [comment]
You need to prevent auto-initialization by removing the selectpicker class, and by not calling `.selectpicker()` until after the row has been cloned. You're copying everything inside your template, including the already styled bootstrap-select elements. When `selectpicker()` is triggered again, there's no way for bootstrap-select to know the select element is already styled properly (as all of the data associated with the original selectpicker was stripped out when using `html()`, so it creates a new menu and a new button.

See: https://plnkr.co/edit/ykBpFOcf6Gmh5MfO.

**Comment by lcsqlpete** [comment]
Thanks, that worked.

**Comment by kasra-my** [comment]
This is a shame it still hasn't been fixed in 2022!
BTW, the following worked for me, so I hope this can help someone else as well:


          var refName = $.trim( $('#ref_name').val() );

         $.ajax({
                    method: 'POST',
                    url: "{{ route('myroute') }}",
                    data: {
                        'name' : refName,
                        _token: '{{ csrf_token() }}'
                    },
                    success: function(results){

/*  ---------------------------     Here is the main part ------------------------------*/
                        $('#my-selectpicker').selectpicker("destroy");

                        // remove all options of the select element
                        $('#my-selectpicker option').each(function() {
                            $(this).remove();
                        });

                        $.each(results, function( index, value ) {
                            $('#reference').append('<option value="' + value.id + '">' + value.name + '</option>');
                        });

                        $('#my-selectpicker').addClass('selectpicker').selectpicker("render");

/*  ---------------------------     Here is the main part ------------------------------*/
                    },
                   error: function(jqXHR, textStatus, errorThrown) {
                        console.log(JSON.stringify(jqXHR));
                        console.log("AJAX error: " + textStatus + ' : ' + errorThrown);
                    }
           });

**Comment by yeamusic21** [comment]
@kasra-my This concept of destroying the selectpicker and then rebuilding the selectpicker is the only method that's worked for me. Thanks for sharing! :-D
