### ISSUE TITLE
Keyboard input for 11,22,33 etc

### ISSUE THREAD

**Issue by crazyhor77** [snapappointments/bootstrap-select#2453]
Have come across an issue with keyboard entry when numbers are the values and you type the same number twice.

For instance a select with values 1 to 40.

When you type 1, option 1 is selected, but type 1 again for 11, nothing is selected.

It works fine when the second number is different, ie. 14, 23 or 36.

But you can't select 11, 22 or 33 via the keyboard.

I don't report bugs often, so please let me know if any further explanation is required.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.

**Comment by crazyhor77** [comment]
thanks casey.

i reproduced by simply removing the option text on the basic example with no live search.  as you can see, typing 22 while it is active only selects 20, likewise with 11 and 33.

interestingly, it works fine with the live search dropdown.

[https://plnkr.co/edit/JgRpxRWfDZGmgiHE](https://plnkr.co/edit/JgRpxRWfDZGmgiHE)

**Comment by caseyjhol** [comment]
I see what you're talking about. That is by design (it matches native select behavior).

- Press 2: 2 is selected
- Press 2 again: 20 is selected
- Press 2 again: 21 is selected
- Press 2 again: 22 is selected
