### ISSUE TITLE
Autofocus doesn't work with Bootstrap 3

### ISSUE THREAD

**Issue by carstenfuchs** [snapappointments/bootstrap-select#2454]
Please consider the attached test case:

[bs-select-autofocus.html.txt](https://github.com/snapappointments/bootstrap-select/files/4575646/bs-select-autofocus.html.txt)

  - If bootstrap-select is not activated, the select control gets the autofocus as intended.
  - If activated, the control lacks the (auto-)focus (but works properly otherwise).

If I read earlier issues correctly, the autofocus attribute of the select element should be taken to the styled control?

Firefox 75.0 on Ubuntu 18.04 LTS.

**Comment by caseyjhol** [comment]
Autofocus only works on page load. Since the bootstrap-select element obviously can't be added until after page load, this doesn't work. An easy fix will just be to check if the element is focused on init, and if so, focus the button.

**Comment by caseyjhol** [comment]
Since you're manually calling `selectpicker()` anyway, a workaround in the meantime is:

```js
      var focusedElement = document.activeElement;

      $('select').selectpicker();

      if (focusedElement.autofocus === true) {
        focusedElement.focus();
      }
```

**Comment by carstenfuchs** [comment]
When I searched before filing the issue, I had found #435 and thought that code like this was already included?
Many thanks for posting the work-around, it works very well!

**Comment by caseyjhol** [comment]
It was meant to be included. The `autofocus` attribute is added to the button, and it sometimes works (depending on when the plugin is called). It' just not very consistent (at least in Chrome).

**Comment by NicolasCARPi** [comment]
No more bootstrap 3 support.
