### ISSUE TITLE
selectpicker('refresh') seems to be ignoring options passed programmatically before

### ISSUE THREAD

**Issue by heppa** [snapappointments/bootstrap-select#2456]
Hi there...

I programmatically create the selectpicker via 

```
$('#myselect').selectpicker({
  liveSearch: true,
  actionsBox: true,
  selectedTextFormat: 'count',
  selectAllText: 'Select all',
  deselectAllText: 'Deselect all',
  countSelectedText: '{0} of {1} items selected'
})
```

Now, I need to dynamically add and remove options. After doing that, since bootstrap-select does not automatically update the list, I need to call 

`selectpicker('refresh'). `

However, when I do that, my previous options are being ignored. Do I really have to destroy and "regenerate" the whole select with the same options again?

Many thanks!

BR,
Alex

**Comment by heppa** [comment]
Just for your information: When I add the selectpicker class to the select element, and then call the selectpicker function with options and then call selectpicker('refresh'), it works with the options remaining...

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.

**Comment by heppa** [comment]
Hi Casey,

sorry for not having respected the contributing guidelines and thanks for getting back to me.

This is the situation I was talking about:
https://plnkr.co/edit/KNOlwyQKbUkHnYyJ

However, in this simpler scenario it's not reproducible, so I guess it's related to my webpack setup together with some deep interactions back and forth, I will have to investigate further in my code... Sorry for having wasted your time!

BR
Alex

**Comment by WiznooDev** [comment]
Hi,
I have the same problem to refresh options list after a post ajax success.
I've tried plnkr link solution, but it's not working in my case.
I'd like to change list from another argument used in post ajax to get new list.
My ajax query is working and returning a JSON result.
I'm using bootstrap-selectpicker in a custom wordpress plugin.
- Jquery is enqueue from wordpress hook. v1.12.4
- Popper 1.14.7
- Bootstrap 4.3.1
- bootstrap-bundle 4.4.1
- bootstrap-select 1.13.6

**Comment by caseyjhol** [comment]
@WiznooDev Unfortunately, if you can't reproduce it, I can't fix it. If you can link me to an example of your issue (using the latest version of bootstrap-select) I can take a look.

**Comment by WiznooDev** [comment]
@caseyjhol Thanks for your response.

1. I create my custom plugin wordpress with boilerplate generator https://wppb.me/
2. I add a custom shortcode for front end with add_shortcode()
3. I enqueue necessary css and js with wp_enqueue
    wp_register_script( 'popper-js', 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js', ['jquery'], NULL, true );
wp_enqueue_script( 'popper-js' );
		
wp_register_style( 'bootstrap-css', 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css', false, NULL, 'all' );
wp_enqueue_style( 'bootstrap-css' );

wp_register_script( 'bootstrap-js', 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js', ['jquery'], NULL, true );
wp_enqueue_script( 'bootstrap-js' );

wp_enqueue_script( 'jquery-ui-core');
wp_enqueue_script( 'jquery-ui-datepicker' );
wp_enqueue_script( 'jquery-ui-sortable' );

wp_enqueue_style( 'jquery-ui-datepicker-style' , '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css');
		
		
wp_register_style( 'bootstrap-css-select', '//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.16/css/bootstrap-select.min.css', false, NULL, 'all' );
wp_enqueue_style( 'bootstrap-css-select' );

wp_register_script( 'bootstrap-js-bundle', 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js', ['jquery'], NULL, true );
wp_enqueue_script( 'bootstrap-js-bundle' );
wp_register_script( 'bootstrap-js-select', '//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.16/js/bootstrap-select.min.js', ['jquery'], NULL, true );
wp_enqueue_script( 'bootstrap-js-select' );
		
wp_enqueue_script( $this->plugin_name.'-sort-table', plugin_dir_url( __FILE__ ) . 'js/sort-table.js', array( 'jquery' ), $this->version, false );

4. In DOM, I populate options in select lists with a php array loop, when I tried to render front end, it seems ok. Lists are filled, search is available.

5. I added JS to get value of first list on change with changed.bs.select event and send an ajax post query to get a JSON containing second list options. On ajax success, I'd like to empty second select list and load on it JSON to recreate options. So in first time I tried to empty second list but it's not working.

jQuery('.selectpicker').on('changed.bs.select', function (event, clickedIndex, isSelected, previousValue)
	{
		var data = {
			list:jQuery(this).parent().attr('data-name'),
			field: jQuery(this).attr('id'),
			value: this.value,
			action : 'change_options',
		};
		
		jQuery.post(ajaxurl, data, function(response) {
			 console.log(response);
			 console.log(data);
			 
			 switch(data.list)
			 {
			 	case 'type':
			 		var row_index = data.field.replace(data.list,'');
			 		jQuery('#product'+row_index).empty();

Do I've to used the other ajax function to work on success case?

BR

**Comment by artemmm312** [comment]
Here's what to do after adding/removing, adding various options, properties, attributes, etc. Two lines of code after these steps:
$('#myselect').selectpicker('destroy');
$('#myselect').selectpicker('render');

**Comment by mrunalpittalia** [comment]
Hey @artemmm312 ,

doing destroy & render shows updated options, but removes attached working events like, changed.bs.select , etc...

**Comment by Masisoft** [comment]
After destroy class .selectpicker will be removed: try to add class selectpicker to your select element ID before render 

$('#myselect').selectpicker('destroy');
$('#myselect').addClass( "selectpicker" );
$('.selectpicker').selectpicker('render');

**Comment by jagger-extremity** [comment]
@caseyjhol https://jqcode.space/questions/continuing-to-reference-outdated-json-data-even-after-refreshing-the-page-instead-of-utilizing-the-most-recent-version
