### ISSUE TITLE
Deprecate title option for individual options

### ISSUE THREAD

**Issue by caseyjhol** [snapappointments/bootstrap-select#2458]
This would allow for options to have normal "title" functionality, with support for tooltips. Of course, it needs to be replaced with a more aptly named attribute.

I'm leaning toward `data-selected-text` and `data-selected-html`. Thoughts?

**Comment by hossein** [comment]
This would (re-)enable displaying rich HTML for the selected item; I'm a fan.

I have no comment regarding the naming; I guess one of them will html-escape the input and the other one would sanitize the passed html?

**Comment by james-yun** [comment]
How do you get "title" placeholder functionality in 1.13.17? 
In 1.13.16, this would show a placeholder when no option is selected.
`<select class="selectpicker" title="Quantity">`

**Comment by caseyjhol** [comment]
@james-yun This appears to still be working correctly in v1.13.17. If it's not, please open a new issue with a link to your reduced test case.

**Comment by caseyjhol** [comment]
The `placeholder` option was added in https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta and existing `title` functionality has been deprecated.
