### ISSUE TITLE
Bad display using Symfony 5, Twig 2.12.5, Bootstrap 4 and bootstrap-select

### ISSUE THREAD

**Issue by dubitoph** [snapappointments/bootstrap-select#2460]
I'm using Symfony 5, Twig 2.12.5, Bootstrap 4 and bootstrap-select.
When I try to use bootstrap-select on my select inputs, I have this kind of display.
![Capture](https://user-images.githubusercontent.com/47710530/81560332-7e7ec680-9391-11ea-8d03-b37b6b32a8c1.JPG).

In js : 

```
...
import 'bootstrap';
...
import selectpicker from 'bootstrap-select';
...
jQuery( document ).ready( function( $ ){

  $('select').selectpicker();
...
});
```

In the formType : 

```
...
$builder
...
      ->add('seatsNumber', ChoiceType::class, [
                                                      'placeholder' => 'choose.number.seats.placeholder',
                                                      'choices' => [
                                                                      '1.seat.choice' => 1,
                                                                      '2.seats.choice' => 2,
                                                                      '3.seats.choice' => 3,
                                                                      '4.seats.choice' => 4,
                                                                      '5.seats.choice' => 5,
                                                                      '6.seats.choice' => 6,
                                                                      '7.seats.choice' => 7,
                                                                      '8.seats.choice' => 8,
                                                                      '9.seats.choice' => 9,
                                                                      '10.seats.choice' => 10
                                                                     ],
                                                      'label' => 'seats.number.label'
                                                    ]
                 )
...
```

In the Twig view : 

```
...
{{ form_start(form, { 'attr': { 'id': 'form' }}) }}
   <fieldset class="form-group">
...
   {{ form_row(form.seatsNumber) }}
...
```

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.

**Comment by dubitoph** [comment]
Impossible for me to give a link because it isn't a website in production. However, I gave a screenshot.

Bootstrap version : 4.4.1
bootstrap-select version : 1.13.17
Browser : Google Chrome and FireFox
OS : Windows 7

**Comment by caseyjhol** [comment]
Could you view source on the page and include the output HTML in a Plunker? If I can't reproduce it, I can't fix it.

**Comment by thomascrepain** [comment]
I encountered the same effect (Symfony 5.0, Twig 3.0.3, Bootstrap  4.5 & Bootstrap-select 1.13.17), and could reproduce this behaviour in Plunker once I removed this line from the code.

`<link rel="stylesheet" href="css/bootstrap-select.css">`

The CSS in not automatically loaded within the last version of Symfony/Encore/...

Work-around is to manually import the CSS in your SCSS file:
`@import "../node_modules/bootstrap-select/sass/bootstrap-select";`

Live example: https://plnkr.co/edit/WvTaHS907LAs9zHq

@dubitoph You might want to check with your CSS if the effect is the same.

**Comment by PiroozMB** [comment]
I can confirm the bug with the css not being loaded in symfony 5.1 bootstrap 4.5 and selectpicker .
adding @import "../node_modules/bootstrap-select/sass/bootstrap-select"; in my app.scss doesn't help for me. When I put the below code I cannot see the options of the select like in the below screenshot. Instead I get an empty list. 
`<select class="selectpicker">
                    <option>Mustard</option>
                    <option>Ketchup</option>
                    <option>Barbecue</option>
</select>`
![image](https://user-images.githubusercontent.com/34473887/87393554-a3b8cc80-c5ae-11ea-9fd1-8abb8409a4f6.png)
