### ISSUE TITLE
Make a title without "multiple"

### ISSUE THREAD

**Issue by Machou** [snapappointments/bootstrap-select#2463]
Hello

I noticed that to put a title in the <select> you have to put the attribute "multiple" in it.

Is it possible to put the title without the multiple choice?

Regards

**Comment by caseyjhol** [comment]
Yes, by default, if you set the `title` attribute on a select that's not multiple, a blank option will automatically be added for you. Keep in mind starting in v1.14.0, using `title` for this purpose will be deprecated, and you'll want to use `placeholder` instead.
