### ISSUE TITLE
title attribute does not work in 1.13.17 (Safari)

### ISSUE THREAD

**Issue by james-yun** [snapappointments/bootstrap-select#2464]
In 1.13.16, the title attribute gave a placeholder when no option is selected.
This functionality does not work in 1.13.17

`<select class="selectpicker form-control" id="number" title="Select a number"></select>`

This should show `Select a number` when no option is selected.

Test case: https://plnkr.co/edit/eStCUygC40HAM52x

**Comment by caseyjhol** [comment]
This is working for me in Chrome 81 and Firefox 76 on Windows. What browser/OS are you using?

![image](https://user-images.githubusercontent.com/2874325/82505130-3dd22c00-9aba-11ea-8e3c-45089983bbd6.png)

**Comment by james-yun** [comment]
I'm getting this bug on MacOS, Safari 13.1.
<img width="558" alt="Screen Shot 2020-05-20 at 6 54 52 PM" src="https://user-images.githubusercontent.com/35581036/82505323-64e52980-9acb-11ea-8dc9-5e01d59d1499.png">
Interestingly, it works fine on my Chrome in MacOS.

**Comment by caseyjhol** [comment]
Released in [v1.13.18](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.18)!
