### ISSUE TITLE
In modal forms is not display

### ISSUE THREAD

**Issue by nabizadeh84** [snapappointments/bootstrap-select#2465]
when i use selectpicker class for select tag in a modal form.
the select tag does not show and it is hidden.
actually its display is none

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.
