### ISSUE TITLE
Exception for optgroup with custom class

### ISSUE THREAD

**Issue by latuszek** [snapappointments/bootstrap-select#2468]
When using optgroup with a CSS class bootstrap-select throws exception:
`Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.`.  This is located in `bootstrap-select-1cf542156a0f4ebaf63f57774dc5e56a.js:731:77)` in 1.13.14 release.

The source of the issue is this line:
`if (typeof classes !== 'undefined' && classes !== '') a.classList.add.apply(a.classList, classes.split(' '));`
And the `classes` var here has 2 spaces when custom class is added to the `optgroup` element (`classes` var is equal to `opt  my-class`).

**Comment by latuszek** [comment]
For my local copy of bootstrap-select I've replaced mentioned line with:
`if (typeof classes !== 'undefined' && classes !== '') a.classList.add.apply(a.classList, classes.replace(/[ ]+/g, ' ').split(' '));`.

But proper fix should also deal with the source of added second space.

**Comment by caseyjhol** [comment]
Fixed in v1.13.16: #2442.

**Comment by latuszek** [comment]
Sorry for duplicate @caseyjhol. I've believed I had downloaded the latest release. The official website should be updated then - it points to 1.13.14 version ;) 
https://developer.snapappointments.com/bootstrap-select/
