### ISSUE TITLE
Shift-Tab key not working in 1.13.17

### ISSUE THREAD

**Issue by rjaros** [snapappointments/bootstrap-select#2469]
Since version 1.13.17 backward tab with Shift-Tab key is not working anymore in Chrome and Firefox.
This issue has something to do with jQuery version as well, because it works fine in this default playground https://developer.snapappointments.com/bootstrap-select/playground/ with jQuery 3.2, but stops working if you change jQuery to version >= 3.4.x.

Two samples with jsfiddle:
https://jsfiddle.net/gfyumt2k/ (1.13.17, Shift-Tab not working)
https://jsfiddle.net/zpxsvo4a/ (1.13.16, Shift-Tab is working)

**Comment by caseyjhol** [comment]
Related: https://github.com/snapappointments/bootstrap-select/issues/1212#issuecomment-629252986

**Comment by rjaros** [comment]
Thx for fixing. Any ETA on the next release?

**Comment by caseyjhol** [comment]
Released in [v1.13.18](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.18)!
