### ISSUE TITLE
data-live-search showing Chinese hint while no result found

### ISSUE THREAD

**Issue by corelus** [snapappointments/bootstrap-select#2472]
A bug is a _demonstrable problem_ that is caused by the code in the repository.

Guidelines for bug reports:

1. **Use the GitHub issue search.** Check if the issue has already been
   reported.

2. **Check if the issue has been fixed.** Try to reproduce it using the
   latest `master` or development branch in the repository.

3. **Provide environment details.** Provide your operating system, browser(s),
   jQuery version, Bootstrap version, and bootstrap-select version.

4. **Create an isolated and reproducible test case.** Create a reduced test
   case and include a link to a live example. Use [this Plunker debugging template](https://developer.snapappointments.com/bootstrap-select/playground/) to share your isolated test cases.

**Comment by corelus** [comment]
Any explanation!? Mr. Caseyjohl?
you can at least leave a comment why did you closed this issue?

**Comment by caseyjhol** [comment]
This is a duplicate of another issue you created. This one provides no information.
