### ISSUE TITLE
With multiple selects, cannot select options with keyboard after using mouse to select options

### ISSUE THREAD

**Issue by pvictor** [snapappointments/bootstrap-select#2474]
Hello,

Problem: With `multiple="true"` we can select option with keyboard, but if we click on an option with mouse, then selection with keyboard doesn't work anymore.

Tested with bootstrap-select-1.13.17 on Chrome and Firefox.

Here a playground: https://plnkr.co/edit/u7ohgCl2jVWxDy1B

To reproduce:
* open picker
* keyboard: type "a" then enter -> "A" is selected
* keyboard: type "b" then enter -> "B" is selected
* mouse: click on any option -> selected
* keyboard: can't select an option (except if picker is closed and reopened)

Thanks for your work!

**Comment by caseyjhol** [comment]
Introduced by the fix for #663.

**Comment by caseyjhol** [comment]
Released in [v1.13.18](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.18)!
