### ISSUE TITLE
Dropdown listbox with an empty white area when lists are over 600 options

### ISSUE THREAD

**Issue by Regenbogenkii** [snapappointments/bootstrap-select#2478]
I use 
Bootstrap-select v1.13.2
Bootstrap v3.3.6
Angular 6
I test with different amount of data and it seems like data option up to 600 everything is fine but when I render data option over 600 then an empty big white space is displayed. Also when I scroll down the window scroll bar I get infinity height of the option box.
![bug](https://user-images.githubusercontent.com/32223809/83877388-a846c580-a764-11ea-9634-bdfff64a802f.png)

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.
