### ISSUE TITLE
Is this a heavyweight component?

### ISSUE THREAD

**Issue by SoftCircuits** [snapappointments/bootstrap-select#2480]
Quick question: I like the look and feel of this for multiselect dropdowns. But I'm trying to limit the amount of stuff I pull into my project so I'm looking for lighter weight components.

If I download the ZIP file, I see it contains 336 files in 29 folders. Do you document anywhere how many files are in the NuGet package, or how many files are required to run this component?

I have jQuery and Bootstrap 4. I'd like to know how many other files will be added to my project.

**Comment by caseyjhol** [comment]
See https://github.com/snapappointments/bootstrap-select#quick-start.

If you're already using jQuery and Bootstrap 4, then you only need bootstrap-select.min.js and bootstrap-select.min.css (and any language files). The contents of the dist folder should be all that are included in the NuGet package: https://github.com/snapappointments/bootstrap-select/tree/v1.13.0-dev/dist.
