### ISSUE TITLE
This change will be a part of the v1.14.0 release. This issue will be updated after it's made available.

### ISSUE THREAD

**Issue by PankajS3** [snapappointments/bootstrap-select#2484]
This change will be a part of the v1.14.0 release. This issue will be updated after it's made available. 

###how to call a function while clicking the cancel option..
I'm new to angularjs.. thanks for help in advance
Demos:
- Bootstrap 4: https://plnkr.co/edit/c2XDSXipVnbMkjaM
- Bootstrap 3: https://plnkr.co/edit/2OcOGhfmBxRpbDh2

_Originally posted by @caseyjhol in https://github.com/snapappointments/bootstrap-select/issues/1449#issuecomment-619287092_

**Comment by vivek-kandhvar** [comment]
This is such a useful feature! Any idea when will 1.14.0 release?

**Comment by caseyjhol** [comment]
v1.14.0 is dependent on #899. I'll try to get that feature as stable as possible and most likely release a v1.14.0-alpha first, as it needs more testing prior to release.
