### ISSUE TITLE
Unable to disable select element from JavaScript

### ISSUE THREAD

**Issue by SoftCircuits** [snapappointments/bootstrap-select#2485]
I found several articles about disabling `<option>` elements but not the `<select>` element.

I'm enabling or disabling my `<select>` element like this:

    $('#customers').prop('disabled', mode != 1);

But after I apply bootstrap-select (to allow multiple selections), this no longer works. The enabled or disabled state of the element does not change.

**Comment by SoftCircuits** [comment]
I see now I can do the following as a workaround.

    $('#customers').prop('disabled', mode != 1);
    $('#customers').selectpicker('refresh');

**Comment by caseyjhol** [comment]
There is an example of this exact functionality in the documentation: https://developer.snapappointments.com/bootstrap-select/methods/#selectpickerrefresh.

In v2.0.0, once we have dropped support for IE < 11, we can implement MutationObserver to auto-detect changes.

**Comment by SoftCircuits** [comment]
I would have guessed the easier approach is to just add a *disable* and/or *enable* method. But it's working. Thanks.

**Comment by caseyjhol** [comment]
I'd rather have as few proprietary functions as possible. You can chain the functions too:

```js
$('#customers').prop('disabled', mode != 1).selectpicker('refresh');
```
