### ISSUE TITLE
The cancel option provided in 1.13.16 with data-allow-clear i can't find that in the new version .

### ISSUE THREAD

**Issue by PankajS3** [snapappointments/bootstrap-select#2486]
I want an option with which when i deselect all options then i can call back a function or introduction of a button or something input field so as to add an extra functionality from our side.

As we'll bind to that button then.

It'd be really useful, as of right now for single selecting options nothing seems much useful while deselecting and then showing changes doubly binded in front and back. Coz that doesn't show. 

Please if there is already such feature do tell me about it !!

**Comment by caseyjhol** [comment]
Sorry - can you elaborate a bit?

**Comment by PankajS3** [comment]
The cancel option indicated after the data-allow-clear does only change the front-end but i'm unable to attach any event or function to trigger change in backend after the cancel is clicked

![Capture](https://user-images.githubusercontent.com/61134495/85276103-ec450480-b49e-11ea-8f83-542c430f2e7e.PNG)


I want to attach a function or an event(**I've tried from the docs**) when the cancel option is clicked !

**Comment by PankajS3** [comment]
> Sorry - can you elaborate a bit?

Please can you give me a response or suggestion it's really important

**Comment by ChristianVermeulen** [comment]
@PankajS3 If this is still applicable.... I don't think that ever made it to Master.
https://github.com/snapappointments/bootstrap-select/pull/536 was created but closed without merge. Later https://github.com/snapappointments/bootstrap-select/pull/682 was created and has been waiting for merge since 2014.

**Comment by caseyjhol** [comment]
This feature is in v1.14 (currently in beta).
