### ISSUE TITLE
Need to align-items: center for Icons

### ISSUE THREAD

**Issue by harnishdesign** [snapappointments/bootstrap-select#2487]
I was last time use Bootstrap-select **v1.13.9**. and, I was used [currency flag](https://github.com/transferwise/currency-flags) as data-icon and it was show proper vertical align center there. 

but, Now, I was use latest Bootstrap-select **v1.13.17**. & It was not proper vertical align center. because, You have removed **`align-items: center !important;`** and **`display: flex !important;`** css from  **`.filter-option-inner-inner`** and **`.dropdown-menu li a`** in latest version. I think, it must need to align items center when we are use images as data-icon for proper display.

### Old Version v1.13.9 - This does show proper.
```
.bootstrap-select .dropdown-toggle .filter-option-inner-inner {
  overflow: hidden;
  -ms-flex-align: center !important;
  align-items: center !important;
  display: -ms-flexbox !important;
  display: flex !important;
}
.bootstrap-select .dropdown-menu li a {
  cursor: pointer;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
  -ms-flex-align: center !important;
  align-items: center !important;
  display: -ms-flexbox !important;
  display: flex !important;
}
```

### Latest Version v1.13.17  - This does not show proper.
```
.bootstrap-select .dropdown-toggle .filter-option-inner-inner {
  overflow: hidden;
}
.bootstrap-select .dropdown-menu li a {
  cursor: pointer;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
}
```

I don't know. On what basis have you removed it in the latest version it css. **but, I think, It must to align items center when we are use images as data icon.** Please check below screenshot for proper understand.

### with Old Version - Icon image does proper vertical align center
![old-bs](https://user-images.githubusercontent.com/2634085/85203437-8126f100-b32b-11ea-8718-740e93afe602.jpg)       

### with Latest Version - Icon image does not vertical align center
![latest-bootstrap-select](https://user-images.githubusercontent.com/2634085/85203453-9ac83880-b32b-11ea-94dc-86f60052a63b.jpg)

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.

**Comment by harnishdesign** [comment]
Here, This is simply css issue. I have already describe in my question. this issue does in latest bootstrap-select version. I have already described above. Which was old css are perfect. but, you have removed it css from latest bootstrap-select version. I think, which is not need to remove. Hope, You are understand.
