### ISSUE TITLE
Action for select or deselect an option

### ISSUE THREAD

**Issue by mnu-nasir** [snapappointments/bootstrap-select#2489]
I am using the select box in my ASP.NET MVC project. I have select box where multiple item can be selected. Now I want to perform an action upon **select an option or deselect an option** from the select box. 

I need jquery function for that operation. Can anyone help me how to do that.

Another question is, how can I get the value of a specific index

**Comment by PankajS3** [comment]
yaa same problem here couldn't bind with any event or function while deselecting !

**Comment by caseyjhol** [comment]
https://developer.snapappointments.com/bootstrap-select/options/#events.

```js
$('#mySelect').on('changed.bs.select', function (e, clickedIndex, isSelected, previousValue) {
  console.log(this.options[clickedIndex].value);
});
```
