### ISSUE TITLE
Search for element with and without German "Umlauts"

### ISSUE THREAD

**Issue by codafish-gmbh** [snapappointments/bootstrap-select#2492]
In one of our selection lists, city names like "Köln" or "München" are stored. When a user searches for "Kö" or "Mü", the expected result is displayed. 

<img width="252" alt="kö" src="https://user-images.githubusercontent.com/2080312/85890148-196e1b80-b7ed-11ea-8767-faf0a9f0a27d.png">

However, we would also like to see "Köln" when entering "Ko" or "München" when entering "Mu". Is there any way to configure the component to do this?

<img width="236" alt="ko" src="https://user-images.githubusercontent.com/2080312/85890153-1bd07580-b7ed-11ea-9f8c-6fa0dc7dc4e6.png">

Thank you very much for your help!!!

**Comment by caseyjhol** [comment]
https://developer.snapappointments.com/bootstrap-select/options/.

Set `liveSearchNormalize` to true.
