### ISSUE TITLE
[Bug] Does not work with Admin Lte 

### ISSUE THREAD

**Issue by davidbuckleyni** [snapappointments/bootstrap-select#2497]
Hi no mater what I try and do I cannot get your control to work with the last version of admin lte it just shows items but it doesnt allow me to drop down the control is just disabled in nature im using bootstrap select country as I need to show flags in my system. 

Admin lte system
https://adminlte.io/themes/AdminLTE/index2.html

even if you can identify what might be wrong so I can use it in this admin template would be great.
 
    <div class="form-group">
        <label>Flag</label>
        <select class="selectpicker countrypicker" data-flag="true"></select>
        <input asp-for="Flag" class="form-control" />
        <span asp-validation-for="Flag" class="text-danger"></span>
    </div>

Any Idea why when I do this as you say to do in the documentation it would show up as follows its very annoying as you controls are way cooler than select to which admin lte uses by default.

![image](https://user-images.githubusercontent.com/5619229/87254047-9f3dc800-c477-11ea-9c22-d91e4cfb196a.png)

**Comment by davidbuckleyni** [comment]
I tried this suggestion here 

    $(document).ready(function() {
       $('.selectpicker').selectpicker({
        style: 'btn-default',
        size: false
      });
    });

But still did not work

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.

**Comment by NicolasCARPi** [comment]
Closing as no answer from OP.
