### ISSUE TITLE
Bootstrap 3 standard dropdown not accessible on reopening

### ISSUE THREAD

**Issue by sdoebroessy** [snapappointments/bootstrap-select#2502]
The available options are only read out by the screenreader when first accessing the dropdown and stepping through. On the second visit or after calling refresh the dropdown is not usable with a screenreader any more, even if the visual highlighting is correct.

Testet with NVDA in Chrome. Version used: bootstrap-select.1.13.14 and bootstrap 3 by adding a basic dopdown to the tests/bootstrap3.html
```

<select class="selectpicker">
                <option>Mustard</option>
                <option>Ketchup</option>
                <option>Relish</option>
            </select>
```

**Comment by sdoebroessy** [comment]
For me changing         
`$this.trigger('focus');`
in Line 2942 of v1.13.18 to 
`that.$menuInner.trigger('focus');`
solved the issue.

When opening drowdown with arrow keys the $this is revering to the button.btn.dropdown-toggle instead of the listbox. While using tab has sets the focus correctly.

**Comment by NicolasCARPi** [comment]
No more bootstrap 3 support.
