### ISSUE TITLE
Bootstrap 5 support

### ISSUE THREAD

**Issue by pchaganti** [snapappointments/bootstrap-select#2505]
Trying to instantiate a new bootstrap select when using BS5 gives this error. I realize BS5 is still alpha but this is something to keep an eye on. Hopefully it is a simple fix in the constructor.

```
TypeError: undefined is not an object (evaluating 'C.dropdown._menu=C.$menu[0]')
```

thanks

**Comment by caseyjhol** [comment]
Looks like this has to do with Bootstrap 5 dropping jQuery, so some of the variables/methods will have to be accessed differently.

https://plnkr.co/edit/w2MkWyZCEoa4KJ3W

**Comment by AnnoyingTechnology** [comment]
@caseyjhol are there any plans to support Bootstrap 5 ?

**Comment by AnnoyingTechnology** [comment]
> I definitely want to support Bootstrap 5 and offer a version without jQuery as a dependency. I've already begun removing jQuery code and replacing it with native JS where possible. It'll be much easier to support/maintain once IE < 11 support is dropped, since we won't be as limited and will be able to remove most of the polyfills. I'm thinking that might be a more realistic goal for bootstrap-select v3.0.0, though.

_Originally posted by @caseyjhol in https://github.com/snapappointments/bootstrap-select/issues/2228#issuecomment-476328158_

**Comment by caseyjhol** [comment]
Making this the thread to discuss Bootstrap 5 support.

**Comment by ghost** [comment]
Do you plan add suopport bootstrap 5?

**Comment by AnnoyingTechnology** [comment]
Please do not spam the maintainer. 
It's better practice to react to the original question (thumbs) if you want to manifest an interest. 

![Screenshot from 2020-12-23 12-07-42](https://user-images.githubusercontent.com/5336824/102990346-7c7c0900-4517-11eb-83b8-7fe9fbe958f1.png)

**Comment by ldcxtu** [comment]
bootstrap 5 needs you

**Comment by ldcxtu** [comment]
There was an issue retrieving Bootstrap's version. Ensure Bootstrap is being loaded before bootstrap-select and there is no namespace collision. If loading Bootstrap asynchronously, the version may need to be manually specified via $.fn.selectpicker.Constructor.BootstrapVersion. TypeError: Cannot read property 'Constructor' of undefined
    at S.fn.init.Plugin [as selectpicker] (bootstrap-select.js:3413)

**Comment by Machou** [comment]
i have migrated my website to BS5, any chance to get an update of BS Select to support ?

**Comment by caseyjhol** [comment]
Yes, I'm working on this. https://github.com/twbs/bootstrap/issues/30267 is causing me some issues currently, as I can't add a click listener to the button.

**Comment by samihoda** [comment]
Eagerly awaiting BS5 support!

**Comment by vlatro** [comment]
I would also really like bootstrap 5 support. Had to disable the bootstrap-select for now :(

**Comment by Gritmatch** [comment]
Same here!

**Comment by cal-zone** [comment]
Commenting to subscribe to notifications ("watch") this issue.

Apologies if there is some other way to do so, but I couldn't figure it out.

**Comment by CaFlow** [comment]
Eagerly waiting for  bootstrap 5 support. Had to also disable the bootstrap-select :(

**Comment by luciminea** [comment]
Hi guys !

Untill the new version is out, you can use the CSS for the Bootstrap 5 version and the JS for the 4.6. That will ensure the bootstrap-select is working.

I've just tested that ! Hope it helps you.

**Comment by chrisvanmeer** [comment]
> Hi guys !
> 
> Untill the new version is out, you can use the CSS for the Bootstrap 5 version and the JS for the 4.6. That will ensure the bootstrap-select is working.
> 
> I've just tested that ! Hope it helps you.

For me that breaks my navbar dropdowns.

**Comment by luciminea** [comment]
> 
> 
> > Hi guys !
> > Untill the new version is out, you can use the CSS for the Bootstrap 5 version and the JS for the 4.6. That will ensure the bootstrap-select is working.
> > I've just tested that ! Hope it helps you.
> 
> For me that breaks my navbar dropdowns.

Yeap, some things will happen as the JS will no longer match the CSS. I'm not using too much of the Bootstrap JS, or dynamic elements, only the grid and general CSS. I preffer to build my own responsive navigation and modals.

**Comment by caseyjhol** [comment]
This is close, but I'm unable to add click events on the button until twbs/bootstrap#30267 is resolved.

**Comment by DJScias** [comment]
Seems a PR (https://github.com/twbs/bootstrap/pull/33442) fixing it has been merged, so that's good news at least.

**Comment by caseyjhol** [comment]
Released in [v1.14.0-beta2](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta2)! jQuery is still required. You must use Bootstrap v5.0.0-beta3 or later.

**Comment by Machou** [comment]
Yeah thanks you !!

**Comment by Joshdw** [comment]
> 
> 
> Released in [v1.14.0-beta2](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta2)! jQuery is still required.

Hey Casey, just some small fix to support BS5's modal:

1162: change to
```
'<button type="button" class="btn-close" aria-hidden="true"></button>' +
```

Simply change class from `close` to `btn-close` and remove `&times;`

Cheers thanks for fixing it for BS5!

**Comment by Machou** [comment]
> 
> 
> Released in [v1.14.0-beta2](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta2)! jQuery is still required.

Sorry, but don't work with bootstrap 5 :(

**Comment by chrisvanmeer** [comment]
> Sorry, but don't work with bootstrap 5 :(

Doesn’t seem to work for me either.

**Comment by caseyjhol** [comment]
Can you link me to an example of it not working? Ensure you are using Bootstrap v5.0.0-beta3. Versions prior to that will not work.

**Comment by Joshdw** [comment]
Definitely works for me, on bs5 beta 3.

Also can confirm the ajax plugin / addon also works :)

**Comment by chrisvanmeer** [comment]
> Ensure you are using Bootstrap v5.0.0-beta3. Versions prior to that will not work.

I still had beta1, upgrading to beta3 fixed it! Thanks, you're a life saver!

**Comment by Machou** [comment]
Yes : https://codepen.io/Machou/pen/dyNMGEm

**CSS**

Bootstrap 5 - beta 3
bootstrap-select 1.14.0 - beta 2

**JavaScript**

popper.js 2.9.1
jQuery 2.6.0
Bootstrap 5 - beta 3
bootstrap-select 1.14.0 - beta 2

**Comment by Joshdw** [comment]
> 
> 
> Yes : https://codepen.io/Machou/pen/dyNMGEm
> 
> **CSS**
> 
> Bootstrap 5 - beta 3
> bootstrap-select 1.14.0 - beta 2
> 
> **JavaScript**
> 
> popper.js 2.9.1
> jQuery 2.6.0
> Bootstrap 5 - beta 3
> bootstrap-select 1.14.0 - beta 2

Why does your Pen use BS5 Beta 2?
![image](https://user-images.githubusercontent.com/8297214/112737277-32108b00-8f51-11eb-9982-22521a581d78.png)

Beta 3 is needed

**Comment by Machou** [comment]
How god, ok, now good , thanks =)

**Comment by leonbotros** [comment]
I'm getting a `bootstrap is undefined error` in https://github.com/snapappointments/bootstrap-select/blob/v1.14-dev/js/bootstrap-select.js#L601. I must be doing something wrong. On versions:

```
"bootstrap": "^5.0.0-beta3",
"bootstrap-select": "1.14.0-beta2"
```

Anyone have an idea?
Edit: fixed with: `const bootstrap = window.bootstrap = require('bootstrap');`

**Comment by cedricbonhomme** [comment]
![Screenshot_20210329_224012](https://user-images.githubusercontent.com/465400/112897316-fd2a4280-90ce-11eb-90a5-f4386787aec5.png)

It does not work.

I am not using jQuery and I've tested with document.getElementsByClassName and document.getElementById.

My dependencies are:

```json
  "dependencies": {
    "@popperjs/core": "^2.9.1",
    "bootstrap": "^5.0.0-beta3",
    "bootstrap-select": "^1.14.0-beta2",
    "fork-awesome": "^1.1.7",
    "moment": "^2.29.1"
  },
```

**Comment by Joshdw** [comment]
> I am not using jQuery

That's because Bootstrap-select still needs jQuery, even though BS5 doesn't.

![image](https://user-images.githubusercontent.com/8297214/112898396-b17c9680-90d8-11eb-8a00-62aafedcb403.png)

**Comment by cedricbonhomme** [comment]
> > I am not using jQuery
> 
> That's because Bootstrap-select still needs jQuery, even though BS5 doesn't.
> 
> ![image](https://user-images.githubusercontent.com/8297214/112898396-b17c9680-90d8-11eb-8a00-62aafedcb403.png)

OK, thank you!

**Comment by kursadcayir** [comment]
Hi, 
`<select class="selectpicker" data-title="select Title"> 
        <option title="t1" value="1">OPTION1</option>
        <option title="t2" value="2">OPTION2</option>
        <option title="t3" value="3">OPTION3</option>
        <option title="t4" value="4">OPTION4</option>
    </select>`
I created that HTML and put it on my screen, until now I am using selectpicker with bootstrap5 with no problem but this not work  like the explanation in the docs about title option.
Thanks in advance

**Comment by dugi07** [comment]
Hi guys,
Have anyone have error like my ? 
![obraz](https://user-images.githubusercontent.com/55851818/118483143-f8b8f800-b715-11eb-8cc8-ad1d66d0ae61.png)

Bootstrap 5.0.1
bootstrap-select-1.14.0-beta2
jquery-3.3.1

**Comment by jbs7** [comment]
Hi, I found that Select Picker Search is not taking any input
I'm using BSv5 with Bootstrap-select v1.14.0-beta2
Everything is fine except that I cannot type in the search input box...

**Comment by RodrigoCanoM** [comment]
Error max-option
Bootstrap 5 v5.0.1
Bootstrap - select v1.14.0-beta2
jquery-3.5.1
Error Max-Options 2, selected 3
![image](https://user-images.githubusercontent.com/71818543/120082518-c8813a00-c0c3-11eb-97f2-65c175c9e61f.png)

**Comment by sjamestasc** [comment]
There seems to be an issue with optgroups in v1.14.0-beta2

addOptgroup takes an index and the selectOtions

It is called from the loop for ( var len = selectOptions.length, i = startIndex; i < len; i++ ) {...

Rather than passing the loop variable as an index like this...
 addOptgroup.call( this, i, selectOptions );

...it is called like this...
 addOptgroup.call( this, startIndex, selectOptions );

...so if there are N optgroups in the raw select, the selectpicker will end up with N copies of optgroup[0], although it seems to get the optgroup label correct because I think item is scoped in the for loop and used in addOptgroup.

The above change was enough to fix it for us, although I am not sure if there are any knock-on effects from the change.  It seems like it would be better to pass "item" to the addOptgroup function, or use 
    var config = {display: htmlEscape( dataGetter( optgroup, 'label' ) ),
instead of 
    var config = {display: htmlEscape( dataGetter( item, 'label' ) ),

I suspect this is a coding style choice I am not equipped to comment on though.

Other than this, it works great with BS5 from what we have seen.

**Comment by luciminea** [comment]
> 
> 
> There seems to be an issue with optgroups in v1.14.0-beta2
> 
> addOptgroup takes an index and the selectOtions
> 
> It is called from the loop for ( var len = selectOptions.length, i = startIndex; i < len; i++ ) {...
> 
> Rather than passing the loop variable as an index like this...
> addOptgroup.call( this, i, selectOptions );
> 
> ...it is called like this...
> addOptgroup.call( this, startIndex, selectOptions );
> 
> ...so if there are N optgroups in the raw select, the selectpicker will end up with N copies of optgroup[0], although it seems to get the optgroup label correct because I think item is scoped in the for loop and used in addOptgroup.
> 
> The above change was enough to fix it for us, although I am not sure if there are any knock-on effects from the change. It seems like it would be better to pass "item" to the addOptgroup function, or use
> var config = {display: htmlEscape( dataGetter( optgroup, 'label' ) ),
> instead of
> var config = {display: htmlEscape( dataGetter( item, 'label' ) ),
> 
> I suspect this is a coding style choice I am not equipped to comment on though.
> 
> Other than this, it works great with BS5 from what we have seen.

Can you provide a file with those modifications ? Or a few instruction on how to modify the source .js ?

**Comment by sjamestasc** [comment]
[bootstrap-select.txt](https://github.com/snapappointments/bootstrap-select/files/6693985/bootstrap-select.txt)

See lines 1771 and 1772

**Comment by chrisvanmeer** [comment]
I would be interested in that too, just yeaterday I found the same “bug” with optgroups

**Comment by luciminea** [comment]
> 
> 
> [bootstrap-select.txt](https://github.com/snapappointments/bootstrap-select/files/6693985/bootstrap-select.txt)
> 
> See lines 1771 and 1772

I've opened it with Dreamweaver and for me it was line1718, but I've figured it out. I'm a programmer, but I don't do much work on JS, so I couldn't figure it out no matter how bad I've tried. I'm currently working ,like on the clock, on a project and I couldn't get pass this. I owe you a great deal, thanks again.

Here's the minified JS, for whomever needs it.
[bootstrap-select.min.1.txt](https://github.com/snapappointments/bootstrap-select/files/6694132/bootstrap-select.min.1.txt)

Just change the extension to .js and you're good to go. Like sjamestasc said, don't know all the implications of this change, but I guess we'll figure it out.

**Comment by chrisvanmeer** [comment]
> [bootstrap-select.txt](https://github.com/snapappointments/bootstrap-select/files/6693985/bootstrap-select.txt)
> 
> See lines 1771 and 1772

That did the trick, thanks a lot!

**Comment by liamkeily** [comment]
As demonstrated here https://jsfiddle.net/p1gosxe8/2/ i was having some issues getting bootstrap-select working with Bootstrap 5.

To get it working correctly i had to:

1. Include specific dev branch in package.json (because the latest fixes are not tagged up, see `git diff v1.14-dev v1.14.0-beta2`):

```
"bootstrap-select": "snapappointments/bootstrap-select#v1.14-dev",
```

2 Include bootstrap and bootstrap-select like this:

```
const bootstrap = window.bootstrap = require('bootstrap'); // without this bootstrap-select crashes with `undefined bootstrap`
require('bootstrap-select/js/bootstrap-select'); // we have to manually require the working js file
```

By default the [package.json](https://github.com/snapappointments/bootstrap-select/blob/v1.14-dev/package.json#L4) tells node to use `dist/js/bootstrap-select.js`, but this file is broken (perhaps out of date?). Manually requiring the `js/bootstrap-select.js` gets around this.

**Comment by luis-fss** [comment]
> Released in [v1.14.0-beta2](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta2)! jQuery is still required. You must use Bootstrap v5.0.0-beta3 or later.

bootstrap-select v1.14.0-beta2 does not show drop-down options using keyboard navigation (no mouse click) with Bootstrap v5.1.3: https://plnkr.co/edit/53lQjla5NiVGPuL0?preview
Works on Bootstrap v5.0.2

Oh, sorry! There is already an issue about this: #2665

**Comment by Kondzolko** [comment]
Hello everyone and want to say thank you for your js library, I'm not sure if I'm on the right place but I would like to report one 1 bug with groups selectpicker.

Options for groups generated from the first group.

So if we will have options like this
```
<optgroup label="Fruit">
  <option>Apple</option>
  <option>Orange</option>
</optgroup>

<optgroup label="Vegetable">
  <option>Corn</option>
  <option>Carrot</option>
</optgroup>
   
```
We will don't see options 'Corn' and 'Carrot'.

https://plnkr.co/edit/vZ9xghMuDhHFJKMc?preview

I Will be appreciative if somebody can take a look at that, I also will try to see if I can fix this problem and will share with you a solution if I will find it.

Thanks

**Comment by Kondzolko** [comment]
> Hello everyone and want to say thank you for your js library, I'm not sure if I'm on the right place but I would like to report one 1 bug with groups selectpicker.
> 
> Options for groups generated from the first group.
> 
> So if we will have options like this
> 
> ```
> <optgroup label="Fruit">
>   <option>Apple</option>
>   <option>Orange</option>
> </optgroup>
> 
> <optgroup label="Vegetable">
>   <option>Corn</option>
>   <option>Carrot</option>
> </optgroup>
>    
> ```
> 
> We will don't see options 'Corn' and 'Carrot'.
> 
> https://plnkr.co/edit/vZ9xghMuDhHFJKMc?preview
> 
> I Will be appreciative if somebody can take a look at that, I also will try to see if I can fix this problem and will share with you a solution if I will find it.
> 
> Thanks


I found where is the problem.
For Some reason we all the time sent index 0 'StartIndex'

the problem in line 1770 in this code
`addOptgroup.call(this, startIndex, selectOptions);`

please replace to
`addOptgroup.call(this, i, selectOptions);`

An example of code you can find here:
https://plnkr.co/edit/amuqKRkRe829UEVC?preview

**Comment by farhadmammadli** [comment]
For anyone looking for cdn hosted file with fix applied (tested with bootstrap 5.0.1):
https://cdn.jsdelivr.net/gh/farhadmammadli/bootstrap-select@main/js/bootstrap-select.min.js
(thanks to @sjamestasc)

**Comment by kibblewhite** [comment]
> For anyone looking for cdn hosted file with fix applied (tested with bootstrap 5.0.1): https://cdn.jsdelivr.net/gh/farhadmammadli/bootstrap-select@main/js/bootstrap-select.min.js (thanks to @sjamestasc)

That is working for me, thanks.

**Comment by fabienwnklr** [comment]
Hi , any progress on version 1.14 stable ? Thanks 😄

**Comment by kinglion580** [comment]
### reminder：remember Bootstrap’s dropdown.js component.
```html
<script type="text/javascript" src="{% static 'js/dropdown.js' %}"></script>
```

**Comment by NicolasCARPi** [comment]
@fabienwnklr I'm working on it yes.

**Comment by cspeer** [comment]
Hi @NicolasCARPi any chance we can speed things up a little? I know this probably isn't your main concern right now, but apparently a lot of people depend on it. I'm willing to throw in a 100 Euro donation and maybe someone else would like to chip in as well?

**Comment by NicolasCARPi** [comment]
Hello @cspeer, you're correct, it's not my main concern, but it's still on my radar. The thing is that I started hacking the code and removing old IE hacks so code gets more fluid and easier to grasp/fix bugs, but @caseyjhol wanted to keep IE support for the time being (and he is right, as it's a breaking change). I really want to push for more frequent updates, to keep the ball rolling, but I'm not in charge here, see https://github.com/snapappointments/bootstrap-select/issues/2228#issuecomment-1008733497.

Maybe @caseyjhol can reconsider releasing a beta even without the fix he's working on? (after all, it is a BETA).

If money is burning your hand, know that [donations are appreciated](https://liberapay.com/NicolasCARPi) ;)

But I can't ensure anything, as I don't have all the cards in hand.

**Comment by therealsujitk** [comment]
@cspeer just thought I'd let you know, I use both bootstrap 5 and 4 together, 5 for most of my site, 4 only for bootstrap-select and it seems to work perfectly. I tried the beta version with bootstrap 5 but it had bugs that would've affected users if I had pushed it to production, so I decided to use the stable version with bootstrap 4 instead. Node.js allows you to use multiple versions of the same package.

**Comment by cspeer** [comment]
@NicolasCARPi Thanks for the speedy reply. I'd definitely be in favour of releasing a new beta ;) but for the time being, is there a dev branch that I could try? I didn't find one.

@therealsujitk Interesting idea. But if I'm understanding correctly, you'd use bs4 instead of bs5 on pages that require bs-select, right? I don't think that would work for me though, as the rest of the site very much depends on bs5. Switching to bs4 just on that one page, would break functionality, I'm afraid. Thanks though!

**Comment by therealsujitk** [comment]
> But if I'm understanding correctly, you'd use bs4 instead of bs5 on pages that require bs-select, right?

Basically bootstrap 5 CSS + bootstrap 5 JS + bootstrap 4 JS (In that order). In our case, we have a single page. This might have conflicts, not sure, but in our case it didn't.

Bootstrap 5 is imported [here](https://github.com/vatz88/FFCSonTheGo/blob/master/src/js/attacher.js) and Bootstrap 4 JS is imported [here](https://github.com/vatz88/FFCSonTheGo/blob/master/src/js/course-panel.js#L16).

**Comment by fabienwnklr** [comment]
sorry to insist.. but any progress ? :) i can contribute if necessary.. good luck :)

**Comment by hmtpandya** [comment]
@caseyjhol Is there any progress or update on Bootstrap 5 support? Can you please help with this?

**Comment by luanmarangon** [comment]
> Para quem procura arquivo cdn hospedado com correção aplicada (testado com bootstrap 5.0.1): https://cdn.jsdelivr.net/gh/farhadmammadli/bootstrap-select@main/js/bootstrap-select.min.js (obrigado para@sjamestasc)

Thank you, working perfectly for me

**Comment by wings77** [comment]
este es un selec2 sin ajax se ve bien en boostrap5
![image](https://user-images.githubusercontent.com/30241218/236497428-e58d2f18-935e-4a89-acea-dc656337e293.png)

este es un select5 con ajax, con bootstrap5 pierde el stilo y se reusa a ser responsive de resto funciona bien el buscado y lo demas

![image](https://user-images.githubusercontent.com/30241218/236497848-ab98e13d-49d7-4d2e-b194-e674feb4336f.png)

se desborda del navegador

![image](https://user-images.githubusercontent.com/30241218/236498257-1d1e238e-9237-43a2-9cbc-e00c9b36ca4d.png)

**Comment by steven7mwesigwa** [comment]
@caseyjhol It **isn't** working for me using Bootstrap v5.2.2 and jQuery v3.6.1

The dropdown list doesn't show.

DEMO LINK: https://jsfiddle.net/theAccountant/baf17pys/3/

```
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"> -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.2/css/bootstrap.min.css">
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" /> -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/2.0.0-beta1/css/bootstrap-select.min.css" />
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.2/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/2.0.0-beta1/js/bootstrap-select.min.js"></script>
```

**Comment by chadwtkns** [comment]
@steven7mwesigwa did you ever get this working?

**Comment by Madlhawa** [comment]
Just checking in to see if there's any update on bootstrap5 support.

**Comment by cb-eli** [comment]
> @caseyjhol It **isn't** working for me using Bootstrap v5.2.2 and jQuery v3.6.1
> 
> The dropdown list doesn't show.
> 
> DEMO LINK: https://jsfiddle.net/theAccountant/baf17pys/3/
> 
> ```
> 
> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.2/css/bootstrap.min.css">
> 
> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/2.0.0-beta1/css/bootstrap-select.min.css" />
> 
> <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
> 
> <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.2/js/bootstrap.min.js"></script>
> 
> <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/2.0.0-beta1/js/bootstrap-select.min.js"></script>
> ```

I have the same problem, Does anyone know how to make it work?

**Comment by gian1200** [comment]
You should use [v1.14.0-beta3](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta3)

**Comment by nwalters512** [comment]
It's highly misleading that the README states "Now with Bootstrap 5 support" despite the `latest` tag on `npm`, all of the "version" badges on the README, and the [latest release highlighted by GitHub](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.18) not supporting this. Is there any chance of getting an official 1.14.0 version published?

**Comment by NicolasCARPi** [comment]
@nwalters512 It's unlikely this project will see another release. I've switched to https://tom-select.js.org/ with my project.

**Comment by liamkeily** [comment]
I switched to https://github.com/Choices-js/Choices

**Comment by mattymatty76** [comment]
Have you tried this version? 
bootstrap-select-v1.14.0-gamma1
[https://gist.github.com/mattymatty76/c996d3b77f298b2ec133be59992df9d4](https://gist.github.com/mattymatty76/c996d3b77f298b2ec133be59992df9d4)

**Comment by buzz100** [comment]
> I switched to https://github.com/Choices-js/Choices

I think switching to another solution is the right thing todo, as I believe this project is very dead and has been for a long time.
Even if the beta fixs the issue, theirs a good chance that it will break with future bootstraps and never be fixed.

If I am wrong and the project is not dead, then could you please let me know the current status of the project?

Even if this is abandoned, it a big undertaking to create and maintain code like this for free, so I would like to thank the author for their work.

**Comment by arlenreyb** [comment]
It's a real shame if this is dead, because as far as I can tell, it's the only multi-select on the entire internet that has the 
`data-selected-text-format="count > 3"`
option, and actually displays all the choices on one line without disrupting the layout.

Every other multi-select I've seen uses badges or buttons, and seemingly doesn't care about the use case of more than 4 things being selected at once.

My use case is a multiselect with 50+ options, and by default they are all selected. It's used as a filter, and by default the setting is "all options shown." If I were to use any of the alternatives, like Choices, Select2, Tom Select, or Slim Select, I would have 50+ little badges pushing my layout down several lines. Per each instance. 

I'll stick with bootstrap-select, and hope for the best. If I had an indication the dev was around and still interested in working on this awesome plugin, I'd absolutely throw my wallet at him.

**Comment by BadPixxel** [comment]
Hi,

I've used this one: https://github.com/PERBILITY/bootstrap-select/tree/bootstrap5-upgrade 

Works fine for me! Bootstrap 5.3
