### ISSUE TITLE
Placeholder doesn't work when the first option is disabled

### ISSUE THREAD

**Issue by highstrike** [snapappointments/bootstrap-select#2507]
Similar to #1839 

I have a simple select, when the 1st option is disabled the placeholder doesn't work and the select is initialized with the first non-disabled option.

this behavior can be seen here -> https://plnkr.co/edit/9QZaeAY7Yh1JxnA8

the first select has the first option disabled so it doesn't show the placeholder and selects the next available value
the 2nd select works as expected

I am on bootstrap 4.5.0, running bootstrap-select version 1.13.18 with jquery 3.5.1 on chrome on both macos catalina and windows 10

**Comment by caseyjhol** [comment]
Released in [v1.14.0-beta](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta)!

**Comment by highstrike** [comment]
Thanks for the fix, problem is I don't even remember the project where I've had this problem 😅

**Comment by warrenspence** [comment]
Ran into this same issue myself today.

I'm using v1.13.18 but I tried out the fix and it didn't work in my case because I'm using option groups.

With the fix, I believe the `'select > *:not(:disabled)'` selector should be `'option:not(:disabled)'` instead.
