### ISSUE TITLE
bootstrap-select.min.js: Uncaught TypeError: z is undefined

### ISSUE THREAD

**Issue by JohnyVB** [snapappointments/bootstrap-select#2509]
hi, i am trying to use bootstrap-select in a project with angular, i did a multiple selectpicker; in the layout it works perfectly for me but when I pass it to angular it shows me this error in the console and does not display the options: 
Uncaught TypeError: z is undefined
    select 1.13.14 / dist / js / bootstrap-select.min.js: 8
    select 1.13.14 / dist / js / bootstrap-select.min.js: 8
    select 1.13.14 / dist / js / bootstrap-select.min.js: 8
    select 1.13.14 / dist / js / bootstrap-select.min.js: 8
bootstrap-select.js: 350: 4
    <anonymous> bootstrap-select.js: 350
    <anonymous> bootstrap-select.js: 3152
    <anonymous> bootstrap-select.min.js: 8
    <anonymous> bootstrap-select.min.js: 8

I thank you for a prompt solution, greetings

**Comment by caseyjhol** [comment]
Can you try with bootstrap-select v1.13.18 and see if the issue persists?

**Comment by JohnyVB** [comment]
OK I will try it

**Comment by JohnyVB** [comment]
I already tried it with this version: bootstrap-select v1.13.18,
the selector that applies the class: "selectpicker" changes the display property: none

"select.selectpicker {
    display: none! important; "

**Comment by caseyjhol** [comment]
Hrmm...well I can't do anything more unless you're able to provide me with an example.

Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

**Comment by dpikt** [comment]
Hi, I got the same error, turns out it's because I didn't have jquery loaded before the script ran. The unminified build gives a more helpful message: `$ is undefined`.
