### ISSUE TITLE
input-group dropdowns layout wrong in Bootstrap 3.4.1

### ISSUE THREAD

**Issue by geogan** [snapappointments/bootstrap-select#2513]
Our system has a "date picker" combination widget which uses two input-group bootstrap-select dropdowns for day and month and then an input box for year. This was working fine using (Bootstrap 3.4.1 / Bootstrap-select 1.12.4). We are not updating to Bootstrap 4 in system right now - only can use latest 3.1.4.

I tried to upgrade Bootstrap-select to latest version (Bootstrap 3.4.1 / Bootstrap-select 1.13.18) to fix broken functionality on iPhone.... but now I found the day/month dropdowns don't behave the same..... the CARAT is on top of the numbers instead of to the right of them like it used to be. I don't know how to fix this.

p.s my code has extra CSS to make entire widget on one line but I have left out all my CSS

I have examples here of before (Bootstrap 3.4.1 / Bootstrap-select 1.12.4):
[https://plnkr.co/plunk/iSwxe3ZuTlqLjx8B](https://plnkr.co/plunk/iSwxe3ZuTlqLjx8B)

And after (Bootstrap 3.4.1 / Bootstrap-select 1.13.18):
[https://plnkr.co/plunk/doZ47SX2rYqWw8Fs](https://plnkr.co/plunk/doZ47SX2rYqWw8Fs)

**Comment by NicolasCARPi** [comment]
We no longer support bootstrap 3.
