### ISSUE TITLE
关于搜索框的位置建议

### ISSUE THREAD

**Issue by WangJincheng4869** [snapappointments/bootstrap-select#2525]
**Is your feature request related to a problem? Please describe.**
1、目前的搜索框是在选项里，这个样子比较浪费空间，并且也不美观。
2、展开与收起加入动画效果不唯是锦上添花
**Describe the solution you'd like**
希望可以直接把搜索框放在下拉上，如下图：
![image](https://user-images.githubusercontent.com/41162158/94221397-98264200-ff1d-11ea-8cea-0807f0e04e95.png)

**Describe alternatives you've considered**
我曾经尝试修改css的方式实现这个方案，但是失败了，因为搜索框的宽度是由选项的宽度决定的
**Additional context**
![image](https://user-images.githubusercontent.com/41162158/94221564-f2270780-ff1d-11ea-8427-62ecfd1c3b10.png)

![QQ录屏20200925105822 00_00_00-00_00_30](https://user-images.githubusercontent.com/41162158/94221929-a9bc1980-ff1e-11ea-9805-3f974deb9189.gif)

**Comment by caseyjhol** [comment]
Having the option of moving the input outside of the menu is something I've been wanting to do for a while. This feature would be covered by #990. Please 👍 to vote and subscribe 🔉 for updates.
