### ISSUE TITLE
Not rendering properly on rails 6 with bootstrap 4

### ISSUE THREAD

**Issue by sebastienb** [snapappointments/bootstrap-select#2527]
This is how it renders for me on a rails 6 with bootstrap 4 project. 
I think it's detecting the that I'm using bootstrap 4 but not sure why its not working.

![CleanShot 2020-09-26 at 12 44 21](https://user-images.githubusercontent.com/2538981/94345850-d479a100-fff6-11ea-84df-cee7a28f461d.png)

My html
```
<select class="selectpicker" multiple data-selected-text-format="count > 3" data-live-search="true">
  <option>Mustard</option>
  <option>Ketchup</option>
  <option>Relish</option>
  <option>Onions</option>
</select>
```

**Comment by bjgaynor** [comment]
@sebastienb Did you get this working yet?  I ran into the same issue and it turns out I wasn't importing the CSS properly.  Let me know if you're still working on it and post your application.css or application.css.scss and I bet I could give you a hand with this.

**Comment by caseyjhol** [comment]
Agreed - this looks like a CSS issue.
