### ISSUE TITLE
How to add it to nextjs ? 

### ISSUE THREAD

**Issue by pikooli** [snapappointments/bootstrap-select#2532]
**Is your feature request related to a problem? Please describe.**
Hi i try to do a pet project with react and nextjs, i use bootstrap and come across this libary.
It look cool and i would like to test it, but when i "npm install bootstrap-select" it get installed but i cannot use the className : 

```
<select className="selectpicker">
  <option>Mustard</option>
  <option>Ketchup</option>
  <option>Barbecue</option>
</select>
```

this give me the default select menu. 

how can i make this work ? 

**Describe alternatives you've considered**
Should i use an import ? or something like this ?

**Comment by NicolasCARPi** [comment]
Sorry we cannot provide such support.
