### ISSUE TITLE
CSS Rendering problem with iOS 14.2

### ISSUE THREAD

**Issue by depontimatteo** [snapappointments/bootstrap-select#2539]
Just updated iPhones with new iOS 14.2 and the css rendering of the dropdown menu is broken.

### Environment

* iPhone X, iPhone SE
* iOS 14.2
* Safari iOS Browser

### Code

Actually we are using `bootstrap-select` version 1.13.14

The code is (in a jinja2 template, so we have some placeholders):

```
    <select class="selectpicker prenotamicloud-bordo-{{ page_background_classes }}" data-width="fit" id="lang_id_p" name="lang_id_p">
      <option value="it" {% if locale|string == "it" %} selected="selected" {% endif %} data-content='<span class="fa fa-globe"></span> Italiano'>Italiano</option>
      <option value="en" {% if locale|string == "en" %} selected="selected" {% endif %} data-content='<span class="fa fa-globe"></span> English'>English</option>
    </select>
```

### Examples

* iOS 14.1 (yesterday)

![2020-11-06 09 05 08](https://user-images.githubusercontent.com/37115585/98341481-31fa0800-200f-11eb-8991-5cf34cfa89f5.jpg)

* iOS 14.2 (today, just updated)

![2020-11-06 09 06 08](https://user-images.githubusercontent.com/37115585/98341567-5229c700-200f-11eb-9083-e78cd02cc26b.jpg)

**Comment by depontimatteo** [comment]
Fixed with max-height values in css files:

```
.bootstrap-select > .btn {
  max-height: 37px !important;
}
.bootstrap-select > .btn > .filter-option {
  max-height: 25px !important;
}
```

Obviously edited `lass` and `sass` source files as below and recompiled with `grunt build-css`:

```
.bootstrap-select {
[...]
  & > .btn {
    max-height: 37px !important;
  }
  & > .btn > .filter-option {
    max-height: 25px !important;
  }
[...]
}
```

this is the output in the broken environment (Safari on new iOS 14.2)

![photo_2020-11-06 11 51 25](https://user-images.githubusercontent.com/37115585/98358102-7f35a400-2026-11eb-95aa-bc2d2f3c0201.jpeg)

Many thanks to my colleague @arualluna for the good job done!

**Comment by arualluna** [comment]
> good

thanks to you!
