### ISSUE TITLE
Cannot use selectOnTab

### ISSUE THREAD

**Issue by tranquangchau** [snapappointments/bootstrap-select#2548]
bootstrap-select@1.13.14
bootstrap@4.5.3
jquery-3.5.1.slim.min.js

Demo here
https://js.do/code/535940

enter in select can't open the dropdown, 
how to open the dropdown if want use enter

**Comment by caseyjhol** [comment]
It's working for me in that demo. `selectOnTab` allows the tab key to select the highlighted option.
