### ISSUE TITLE
virtualScroll has a BUG

### ISSUE THREAD

**Issue by wowton** [snapappointments/bootstrap-select#2554]
When ```virtualScroll``` is enabled, drag the scroll bar to the bottom with the mouse, a blank page appears in the drop-down box, and ```currentChunk``` becomes 0 instead of the last one.

**Comment by caseyjhol** [comment]
What version? Which browser? If this is Firefox only, it sounds like the same as #2524.

**Comment by wowton** [comment]
Sorry, just now saw your comment. It happened in Chrome. 
Environment:
windows: 10
Chrome:  87.0.4280.88
bootstrap-select: 1.13.18

**Comment by Schw2iizer** [comment]
Yes, this happens in Chrome. I created #2524. Any updates?
https://github.com/snapappointments/bootstrap-select/issues/2554#:~:text=as-,%232524.

**Comment by caseyjhol** [comment]
Closing in favor of #2524.
