### ISSUE TITLE
Documentation Issue for Select/Deselect All Option

### ISSUE THREAD

**Issue by ViVe-IT** [snapappointments/bootstrap-select#2556]
Just a small issue, in your documentation example for "Select/deselect all options", the attribute is given as: 
"**multiple** data-actions-box="true"" instead of "data-actions-box="true"" (the "multiple" needs to be removed to work properly)

(Thanks for creating and maintaining this!!! :) )

**Comment by caseyjhol** [comment]
Currently, actionsBox only works when `multiple` is true, as it's not possible to select more than one option without it. Can you elaborate a bit?

**Comment by ViVe-IT** [comment]
This is in combination with Django as a Backend, if I use the snippet directly from the documentation:
<select class="selectpicker" **multiple** data-actions-box="true">
I get an error that attributes have to be given in the form of attribute=xyz, so if I remove the multiple part it works fine, is it possible that this is just an error in the documentation?

**Comment by caseyjhol** [comment]
`multiple` is really just shorthand. Try setting `multiple=""` or `multiple="true"`.

**Comment by ViVe-IT** [comment]
Will do, thanks!
(odd that it's working though without it set explicitly)
