### ISSUE TITLE
$lis

### ISSUE THREAD

**Issue by CharleysTante** [snapappointments/bootstrap-select#2561]
From bootstrap-select 1.12.4 to 1.13.0 you've actually removed the property $lis. I used it for tooltips like this post:
https://stackoverflow.com/questions/47669038/#answer-47716261

As of version 1.13.0, how can I get access to the data that was previously stored in the $lis property? Thanks

**Comment by caseyjhol** [comment]
`$('#select').data('selectpicker').selectpicker.main.elements` returns an array of li elements that you can use.
