### ISSUE TITLE
Consider a call for maintainers

### ISSUE THREAD

**Issue by mrlife** [snapappointments/bootstrap-select#2567]
Open source software is a boon for software developers around the world. It also takes a lot of effort to maintain a repository. Please consider recruiting some maintainers to help keep the ball rolling.

e.g.  https://github.com/selectize/selectize.js/issues/752

cc @caseyjhol @brockholzer

**Comment by NicolasCARPi** [comment]
@caseyjhol I would be willing to help with issue triage (and closing the old ones) and pr review.

**Comment by caseyjhol** [comment]
@NicolasCARPi That's great - thank you! That's definitely what I need the most help with currently. Here is a pre-written message you can use on bug reports that are missing requirements. I'll try to get you access to close/label tickets soon. In the meantime you can just tag me in a comment if you think it should be closed.

Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with:

- your link
- Bootstrap version
- bootstrap-select version
- specific browser and OS details.

If you're not using the latest version of bootstrap-select, please try that as well.

**Comment by NicolasCARPi** [comment]
@caseyjhol I'm glad you accept my proposition. I think I'll start by modifying the issue template to include the required details so at least new issues have that, it seems to be a generic template as of now. I'll then gradually go over the existing issues with the close hammer at hand.

I think for a repo of this size we can aim for 100 open issues and 10 open PR. PR should be merged or closed after 30 days max ideally.

Cheers,
~Nico

**Comment by caseyjhol** [comment]
@NicolasCARPi The bug issue template is customized for bootstrap-select currently, but many people choose to ignore it anyway. It could definitely be improved, though. I think perhaps short and sweet would be better to ensure people actually read through it.

**Comment by caseyjhol** [comment]
@NicolasCARPi Also, before merging in any PRs you think look good, please flag me first so I can review. Thanks!

**Comment by NicolasCARPi** [comment]
Well, this is weird, I got the invitation email, get on the invitation page, click Accept, first I get an error that my browser did something wrong, second time I get a 404, and now it tells me Invitation is invalid....  ¯\_(ツ)_/¯

I'll try later...

edit: opened a support ticket for it. Maybe I'll need to decline and you'll need to invite again.

**Comment by NicolasCARPi** [comment]
@caseyjhol I have declined the invitation (as it is not working), could you kindly make a new one (so I stop pinging you and can actually close stuff myself)?

Cheers,
~Nico

**Comment by NicolasCARPi** [comment]
@caseyjhol Thanks for the invitation, this time it worked. But it seems it is only "view" rights, which doesn't mean a lot for a public repository. The idea was that I would have rights to label and close issues, so I can be an effective help, do you think you can extend rights like so?
