### ISSUE TITLE
Show Multiple Selected at Start

### ISSUE THREAD

**Issue by bratchan** [snapappointments/bootstrap-select#2569]
I have a Large list of countries that are dynamically built. Some I have getting selected at the start, but it will only show the LAST one selected. I could be just doing something wrong not sure. Could be something simple I missed.

Code I'm using to add the selected attribute.
```
 for(var i = 0; i < filters.length; i++){
      console.log(filters[i]);
      $("#country").val(filters[i]).find("option[value='" + filters[i] +"']").attr('selected', true);      
    }

  $("select").selectpicker('refresh');
```

Image: Shows that only one is selected with the box and console.log shows what all should be selected. 
![image](https://user-images.githubusercontent.com/6539577/106763121-8445c780-6604-11eb-82ef-4495ca3b4970.png)

Image: Shows that in the select that they are selected
![image](https://user-images.githubusercontent.com/6539577/106763349-ba834700-6604-11eb-9617-685353cd6cd4.png)

**Code Versions**
Bootstrap v4.0.0
Bootstrap-select v1.13.14

**Comment by qant** [comment]
Why no one read the docs...

https://developer.snapappointments.com/bootstrap-select/methods/

> This is different to calling val() directly on the select element. If you call val() on the element directly, the bootstrap-select ui will not refresh (as the change event only fires from user interaction). You will have to call the ui refresh method yourself.

I hope it help

**Comment by sameerdhoot** [comment]
The documentation does show correct method for updating multiple values.

https://developer.snapappointments.com/bootstrap-select/methods/#selectpickerval

In your case you should simply do this

`$("select").selectpicker('val', filters);`

This is assuming that filters is an array with strings (country names) in them.
