### ISSUE TITLE
data-width="auto" not working

### ISSUE THREAD

**Issue by perriard** [snapappointments/bootstrap-select#2574]
It sets the width to the viewport-width. I have tried both in the context I need it (in a flexbox) and as the only child in <body>, so the containing element doesn't affect it.

**Comment by qant** [comment]
> It sets the width to the viewport-width. I have tried both in the context I need it (in a flexbox) and as the only child in , so the containing element doesn't affect it.

Any codepen with bug in place (where all your css) to see the fact if is really not working will help. Improve you question. please.

**Comment by perriard** [comment]
I used the cdn v. @1.13.14 from the quick start documentation - updating to the latest fixed my problem. :-)

**Comment by ctml91** [comment]
Still occurs in latest if you do not set the live search to be enabled.

```html
<div class="col-md-4 mb-2">
        <select id="select_item" name="select_item" class="selectpicker form-control form-control-sm" title="Select item">
        </select>
</div>
```
```js
var group = $('<optgroup label="Example Group" />');
var option1 = new Option("Test1", "test1");
var option2 = new Option("Test2", "test2");
$(group).append(option1);
$(group).append(option2);
$("#select_item").append(group);
$('#select_item').selectpicker({
dropupAuto: false
});
```
Results in the width being explicitly set on the dropdown, extending off the screen. Setting `data-width="auto"` has no effect. Adding `data-live-search="true"` resolves the issue. 

```html
<div class="col-md-4 mb-2">
        <select id="select_item" name="select_item" class="selectpicker form-control form-control-sm" title="Select item">
        </select>
</div>
```
