### ISSUE TITLE
Cannot read property 'Constructor' of undefined - bootstrap 5

### ISSUE THREAD

**Issue by Alchan86** [snapappointments/bootstrap-select#2575]
I have problem with select picker (bootstrap-select) on bootstrap 5 - I'm getting error: Cannot read property 'Constructor' of undefined. With bootstrap 4 select picker works fine.

Order of scripts is:

jquery-3.5.1.min.js
popper.min.js
bootstrap.min.js
bootstrap-select.min.js

Thanks for help,

**Comment by caseyjhol** [comment]
Bootstrap 5 is not yet supported. See https://github.com/snapappointments/bootstrap-select/issues/2505.

**Comment by tiennt03** [comment]
When will bs5 support? I am needing it :(

**Comment by kriit24** [comment]
same here

**Comment by mattymatty76** [comment]
try this maybe works

[https://gist.github.com/mattymatty76/c996d3b77f298b2ec133be59992df9d4](https://gist.github.com/mattymatty76/c996d3b77f298b2ec133be59992df9d4)
