### ISSUE TITLE
Using "allowClear" doesn't update the value

### ISSUE THREAD

**Issue by joelstein** [snapappointments/bootstrap-select#2578]
The new "allowClear" button doesn't update the value, though it does update the visual select element.

Environment details: Mac OS 11.2.1, Brave 1.20.108, jQuery 3.5.1, Bootstrap 4.6.0, bootstrap-select 1.14.0-beta.

Example which shows bug in action: https://plnkr.co/edit/XDJrlaaDguYig2sl

Related: #1449

**Comment by caseyjhol** [comment]
The value _is_ actually updating, but it's not triggering the change event.

**Comment by joelstein** [comment]
Ah, thanks, I wasn’t sure. I put together a pull request which seems to work for me, but I didn’t fully understand the code...

**Comment by joelstein** [comment]
Perfecto! Thank you so much.

**Comment by caseyjhol** [comment]
Released in [v1.14.0-beta2](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta2)!
