### ISSUE TITLE
optgroup with bootsrap 5

### ISSUE THREAD

**Issue by ay1man4** [snapappointments/bootstrap-select#2592]
Hello,

I faced below unexpected behavior in **bootstrap-select v1.14.0-beta2** with bootstrap 5.0 beta-3.

1. If optgroup is used, selected option will be repeated multiple times (same count of optgroups).
2. If option is used with optgroup, for example to show default selected option, then list will disappear.

I've created sample codepen to illustrate the issue:

[bootstrap-select optgroup issue](https://codepen.io/absi_ayman/pen/VwPjERV)

Thanks

**Comment by leonbotros** [comment]
Can confirm, I have this issue as well on `bootstrap 5.0.0-beta3` and `bootstrap-select 1.14.0-beta2`.

**Comment by caseyjhol** [comment]
Same as #2607 (which will be resolved in the next release).

**Comment by Raketten1963** [comment]
I am unable to find anything newer than mentioned 1.14.0 beta 2 on jsdelivr, am I missing something?

**Comment by Abhijeet1520** [comment]
This issue seems to be resolved in 1.14.0-beta3
you can upgrade the package to `https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js`
and it should work fine
