### ISSUE TITLE
Selection arrow does not appear in the right place

### ISSUE THREAD

**Issue by mrobe** [snapappointments/bootstrap-select#2595]
When I use bootstrap-select in a modal window, the selection arrow appears squished against the right-hand edge, like this:

![Screen Shot 2021-04-03 at 15 01 41](https://user-images.githubusercontent.com/8442575/113470292-76d77d00-948f-11eb-9c3a-6ebb79d81b3c.png)

I'm using Bootstrap 4.5.0, jQuery 3.5.1, popper 1.16, and bootstrap-select 1.13.14 in Safari 13.1.2 on macOS 10.13.6.

Am I doing something wrong, or is there some kind of work-around to fix this, i.e., to move the selection arrow so that it appears as it does in the bootstrap-select docs?

**Comment by caseyjhol** [comment]
Can you try with v1.13.18? If that still doesn't fix it, can you try with v1.14.0-beta2?

**Comment by mrobe** [comment]
Thanks for your message. I tried both versions, but I don't see any change.

**Comment by mrobe** [comment]
Update: I found and fixed the problem.

There was some stray CSS in my SCSS file:

```
.dropdown-toggle::after {
  display: block;
  position: absolute;
  top: 50%;
  right: 0;
  transform: translateY(-50%);
}
```

This was interacting with bootstrap-select. I removed it, recompiled, and now everything looks fine.

Thanks again for helping with this.
