### ISSUE TITLE
Release of 1.14 on CDN

### ISSUE THREAD

**Issue by mrlife** [snapappointments/bootstrap-select#2599]
Hi, is it possible to release 1.14 on jsdelivr/cdnjs now or does it need to wait for post-beta?

**Comment by caseyjhol** [comment]
It's already available on jsdelivr: https://www.jsdelivr.com/package/npm/bootstrap-select?version=1.14.0-beta2.

**Comment by mrlife** [comment]
Thank you. I didn't realize how the pre-release versions are there but latest official release is displayed initially as the latest available.

Now that I know how to check, cdnjs also has v2.0.0-beta1. I assume it's too early to start using that one but looking forward to it. This is a great product. Thanks again.
