### ISSUE TITLE
Multiple ticks in multiple select with data-max-options defined as "1"

### ISSUE THREAD

**Issue by dhqcz** [snapappointments/bootstrap-select#2609]
I have the same issue as has been reported here: https://github.com/snapappointments/bootstrap-select/issues/2289

Select with attribute "multiple" and "data-max-options='1'" is buggy, it allows to select more than 1 item.

It was fixed in v1.13.11, but in v1.14.0-beta2 it is again here. :(

**Comment by praveensoniofficial** [comment]
Try this out. It works.

`$(document).ready(
            function() {
                $('#offering').selectpicker({
                    maxOptions:2
                });
            }
        );`

**Comment by dhqcz** [comment]
Yes, more than 1 works normally (it does not matter if it is set via javascript or in html attributes). 
But in previous versions, `data-max-options="1"` with `multiple` attribute was working perfect.
Benefit of this usage that user can see a placeholder "Choose an option..." instead of first value of selectbox.

**Comment by FurbyX92** [comment]
I made this change and works.

![image](https://user-images.githubusercontent.com/6842430/146432037-6ea3aac9-6f3d-4edb-823a-966b9a8a121f.png)

**Comment by NicolasCARPi** [comment]
Thank you @FurbyX92, I have tried your fix and it looks good so I commited the proposed change on the `dev` branch.

**Comment by Kondzolko** [comment]
I fixed this problem this way

added `that.setSelected(clickedData, false);`
```
 if (maxOptionsArr[2]) {
      maxTxt = maxTxt.replace('{var}', maxOptionsArr[2][maxOptions > 1 ? 0 : 1]);
      maxTxtGrp = maxTxtGrp.replace('{var}', maxOptionsArr[2][maxOptionsGrp > 1 ? 0 : 1]);
  }

  option.selected = false;
  that.setSelected(clickedData, false); // it will replace the last "check icon" to false if it over the limit
```
