### ISSUE TITLE
Ability to create Option

### ISSUE THREAD

**Issue by rajezz** [snapappointments/bootstrap-select#2612]
### Description

- There will be a situation where the user needs to create new options apart from just selecting the provided set. The best scenario would be adding Tag where the user should have the flexibility to add new options (_say by clicking a button_).

- So, in this mode, when the user starts entering the value in the input field, a button stating **_Create One_** should show up and clicking it should create an option with that name

_**Refer below screenshot**_

![image](https://user-images.githubusercontent.com/35561689/120057742-1ca80200-c063-11eb-9b02-c4dff81cc302.png)

**Comment by PsyBooty** [comment]
any update on that?
In addition to a prepopulated menu of options, dynamically create new options from text input by the user in the search box.

**Comment by cocowalla** [comment]
I think this is a dupe of #2563

**Comment by NicolasCARPi** [comment]
Closing as duplicate, thanks @cocowalla
