### ISSUE TITLE
Dropdown menu is not displayed

### ISSUE THREAD

**Issue by toprakmurat** [snapappointments/bootstrap-select#2615]
I develop a website in Flask. I could not understand why dropdown menu is not displayed on my website ?

**Comment by NicolasCARPi** [comment]
Hello,

Please follow the issue template: https://github.com/snapappointments/bootstrap-select/blob/v1.14-dev/.github/ISSUE_TEMPLATE/bug_report.md

It is there for a reason, how do you expect us to find the issue if you give absolutely zero information about it?

Side note: users can self-assign labels now??

**Comment by NicolasCARPi** [comment]
Closing as user did not respect the format nor provided requested information.
