### ISSUE TITLE
i18n - Using the language files on the version 1.13.14?

### ISSUE THREAD

**Issue by leonardoayres** [snapappointments/bootstrap-select#2632]
Hello,

I'm using the latest stable version (1.13.14) and trying to use the languages files for content translation, but no success so far.

I've tried to set "data-lang" and "data-language" in the **select** tag, but this is ignored completely and to get thing worse, the default language for the version that i've downloaded is "NL".

The i18n feature is available? If yes, how to use it?

All the best.

**Comment by NicolasCARPi** [comment]
It should work AFAIK, no reasons why NL would be the default one. IMHO this is more an issue on your side and not a bug in the app. Try using latest version, emptying browser cache, and other things. Unless you find a reproducible bug on the latest version, no support can be provided to help you troubleshoot such issues.
