### ISSUE TITLE
Support for older bootstrap versions broken in Bootstrap 1.14.0-beta2

### ISSUE THREAD

**Issue by SharkWipf** [snapappointments/bootstrap-select#2639]
Commit 36b7aff67d58689bfa2fdd2b8ebc6f96d1884f17, while adding Bootstrap 5 support, breaks support for older previously-supported versions.
Specifically I've tested with Bootstrap 3.4.1 (still listed as supported in the docs), simply updating to the latest bootstrap-select results in: 
```
bootstrap-select.js:601 Uncaught ReferenceError: bootstrap is not defined
    at bootstrap-select.js:601
    at bootstrap-select.js:3563
```
Is this a deliberate deprecation of old versions, or is this an unintentional bug?

**Comment by NicolasCARPi** [comment]
Hello, given that bootstrap 3 is end-of-life since July 2019 and no longer receives updates, I think this project should remove the compatibility from the docs.

**Comment by SharkWipf** [comment]
Honestly, agreed.
That said, currently the only thing breaking support as far as I can tell is the assumption that `bootstrap.Dropdown` exists, and [only in one location](https://github.com/snapappointments/bootstrap-select/blob/v1.14-dev/js/bootstrap-select.js#L601).
While I agree official _support_ would be better off dropped, simply changing that line seems to be the only change needed to keep it _working_ without further effort.
Especially since v1.14 brings some pretty massive performance improvements in some cases, and beta1 doesn't seem to work, it would be nice to at least have a version that's still useable.

I removed the `bootstrap.Dropdown` check on that line entirely on my end and it seems to be working perfectly fine for my Bootstrap version now, as far as I can tell. Simply changing this line to not assume `bootstrap` is defined seems like it'd be a complete fix of this issue.

**Comment by NicolasCARPi** [comment]
I guess you'll have to use your fork then as I don't want to remove it as it might break other setups and I have no clear way to test this.

I also started removing bootstrap3 references and will make it clear that bootstrap 3 is no longer officially supported.
