### ISSUE TITLE
Dropdown not openning on click

### ISSUE THREAD

**Issue by brokieb** [snapappointments/bootstrap-select#2644]
Hey, on click to initialized select, i cant see dropdowns.
I download 
https://github.com/snapappointments/bootstrap-select/blob/v1.14-dev/tests/bootstrap5.html 
and i see the same.

**Comment by NicolasCARPi** [comment]
You need to provide more information about your environment.

**Comment by brokieb** [comment]
Here is link for test page 
https://brokieb.pl/cm/test.html#
When i paste code to codepen everythink work correctly .. Here code: 
https://codepen.io/damian-woniak/pen/PomvYeN

**Comment by NicolasCARPi** [comment]
Look into your console, you'll see the error. Closing as not reproducible on codepen and we do not provide free support.
