### ISSUE TITLE
snapappointments.com is down looks like we need new bootstrap based select picker

### ISSUE THREAD

**Issue by kriit24** [snapappointments/bootstrap-select#2655]
A bug is a _demonstrable problem_ that is caused by the code in the repository.

Guidelines for bug reports:

1. **Use the GitHub issue search.** Check if the issue has already been
   reported.

2. **Check if the issue has been fixed.** Try to reproduce it using the
   latest `master` or development branch in the repository.

3. **Provide environment details.** Provide your operating system, browser(s),
   jQuery version, Bootstrap version, and bootstrap-select version.

4. **Create an isolated and reproducible test case.** Create a reduced test
   case and include a link to a live example. Use [this Plunker debugging template](https://developer.snapappointments.com/bootstrap-select/playground/) to share your isolated test cases.

**Comment by NicolasCARPi** [comment]
No it's not down (anymore) and once I'm done rewriting [apidoc](https://github.com/apidoc/apidoc) I'll probably give some love to this project. I have write access to the repo but difficulties communicating with the owner, who doesn't reply to my questions regarding this repo. So I guess I'll just start merging things myself, and cleanup things. But I won't be able to make new releases.

I wonder if it would be reasonable to start from scratch without jQuery and bootstrap 5 support only, and typescript, and not one single 3500+ lines file of JS.... Maybe I'll rather do that. We'll see.

**Comment by NicolasCARPi** [comment]
I'm now actively working on this library.

**Comment by caseyjhol** [comment]
Yes breaking up the source into modules would be great.
