### ISSUE TITLE
Clearable selection on single select

### ISSUE THREAD

**Issue by chrisidakwo** [snapappointments/bootstrap-select#2657]
I have a use case where a user can decide to deselect an already selected option in order to leave the select element without a selected value, I've looked around and it appears this plugin doesn't supports something like that.

Currently, the way I achieve it is to always have the first value empty, so it serves as something like a placeholder. However, it'll be great if the plugin has such feature in-built. Almost like the select2 plugin.

1. So here, I have a list of options
![Screenshot from 2021-09-20 07-32-11](https://user-images.githubusercontent.com/29854560/133964346-b9786762-cb52-4fa8-98ef-2c9c49c51c64.png)

2. And then, I select one
![Screenshot from 2021-09-20 07-32-30](https://user-images.githubusercontent.com/29854560/133964376-d7bae7c2-5996-4d69-8145-8b5f2af8e498.png)

3. How do I go back or cancel the selection? My current implementation is to use an empty option. Like the first option in the screenshot below:
![Screenshot from 2021-09-20 07-41-18](https://user-images.githubusercontent.com/29854560/133964583-0ced91bf-f18c-4d7b-aca9-3cde8967277a.png)

4. And when selected, it looks like a placeholder
![Screenshot from 2021-09-20 07-41-43](https://user-images.githubusercontent.com/29854560/133964654-76bf8d75-7732-45aa-ab5b-88a6c1a21cb9.png)

5. However, this would be great to have:

![Screenshot from 2021-09-20 07-45-58](https://user-images.githubusercontent.com/29854560/133965005-a8822105-bf92-4e8b-820a-f367bc12d521.png)

**Comment by chrisidakwo** [comment]
I think I should mention that I know there's a `.selectpicker('refresh')` method. However, this doesn't really work out of the box because one would still have to manually place the icon in the select button and then write an on-click function that deselects the selected option before calling this refresh method to reset the UI. It'll be best if the plugin provided this out-of-the-box.

**Comment by NicolasCARPi** [comment]
Can't you use `data-showtick=true`? On my select it allows to select and unselect by clicking it again. You can see it live here https://demo.elabftw.net/experiments.php in the Tags field on top of screen, middle.

**Comment by caseyjhol** [comment]
This is a duplicate of https://github.com/snapappointments/bootstrap-select/issues/1449 and is available in v1.14.x.
