### ISSUE TITLE
Ajax search get multiple calls

### ISSUE THREAD

**Issue by adaniello** [snapappointments/bootstrap-select#2659]
Hi,
i'm trying to use Ajax/JSON data source support as in https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta.

No problem if i use `source.data` property with an ajax call, but when i try to use `source.search` i get a very strange issue: typing 1 character, selectpicker posts only one ajax call; typing 2 characters, selectpicker posts 2 ajax call; from 3 characters posts so much ajax call, lower is result greather is number of calls (eg. with only two items in result, selectpicker post also 21 ajax call repeating more time result).

This is my JS code:
```
$(function () {
    $('#test').selectpicker({
        source: {
            data: function (callback) {
                $.ajax({
                    method: 'POST',
                    url: 'test_selectpicker.php',
                    dataType: 'json'
                }).then((response) => callback(response.data))
            },
            search: function (callback, page, searchTerm) {
                let data = { page, search: searchTerm };
                $.ajax({
                    method: 'POST',
                    url: 'test_selectpicker.php', 
                    data,
                    dataType: 'json'
                }).then((response) => callback(response.data))
            }
        }
    });
});
```

Thanks

**Comment by adaniello** [comment]
After some debug, i found that `fetchData()` is the problem, because it is called many times.

There's a a logical issue (i think) in this block https://github.com/snapappointments/bootstrap-select/blob/e2425ed01f279aad75d4155d807de4911ea95a02/js/bootstrap-select.js#L1463-L1471

I tried to comment and works fine!

Another issue found exploring code: https://github.com/snapappointments/bootstrap-select/blob/e2425ed01f279aad75d4155d807de4911ea95a02/js/bootstrap-select.js#L1011-L1027 this block code is repeated two times.

Thanks

**Comment by NicolasCARPi** [comment]
Thank you for looking into it, indeed it seems weird that this code is repeated two times!

**Comment by adaniello** [comment]
Hi, this is what happens: when i press only one character bootstrap-select calls ajax request once; with two characters, **twice**; when i press third character, bootstrap-select calls ajax request **40 times!** 

![Bootstrap-Select-Ajax-Test](https://user-images.githubusercontent.com/242423/137515501-31829002-2c16-4f94-b9da-893452c64f5d.gif)

My code is very simple:
```
$(function () {
    $('#test').selectpicker({
        source: {
            search: function (callback, page, searchTerm) {
                let data = { page, search: searchTerm };
                $.ajax({
                    method: 'POST',
                    url: 'test_selectpicker.php',
                    data,
                    dataType: 'json'
                }).then((response) => callback(response.data))
            }
        }
    });
});
```

Anyone can help me to fix this issue?
Thanks

**Comment by caseyjhol** [comment]
Investigating. Looks like this is only happening if the number of options is less than or equal to `chunkSize` (which defaults to 40). In most of my testing I was using larger data sets, which is how this got overlooked. Hoping to have a fix soon.
