### ISSUE TITLE
Sass deprecation warning

### ISSUE THREAD

**Issue by senchden** [snapappointments/bootstrap-select#2668]
Newer versions of the `sass` compiler deprecate the usage of slash character for division. Here is an example of the usage in your code :     https://github.com/snapappointments/bootstrap-select/blob/v1.14-dev/sass/bootstrap-select.scss#L26
This causes deprecation warning in projects where your sass files are being imported into other files. Since `libsass` and `node-sass` and are being deprecated (https://sass-lang.com/blog/libsass-is-deprecated), and `sass` compiler is recommended to use now, this might cause an issue in the future. See the related issue in the bootstrap project: https://github.com/twbs/bootstrap/issues/34051

**Comment by NicolasCARPi** [comment]
Yes, but this will have a lower priority than the current outstanding bugs. Thanks for the report.

**Comment by senchden** [comment]
No problem. Will you accept a pull request if I make one?

**Comment by NicolasCARPi** [comment]
Sure!
