### ISSUE TITLE
Selector for Options

### ISSUE THREAD

**Issue by Kondzolko** [snapappointments/bootstrap-select#2672]
Hello everyone and want to say thank you for your js library, I'm not sure if I'm on the right place but I would like to report one 1 bug with groups selectpicker.

Options for groups generated from the first group.

So if we will have options like this
```
<optgroup label="Fruit">
  <option>Apple</option>
  <option>Orange</option>
</optgroup>

<optgroup label="Vegetable">
  <option>Corn</option>
  <option>Carrot</option>
</optgroup>
   
```
We will don't see options 'Corn' and 'Carrot'.

https://plnkr.co/edit/vZ9xghMuDhHFJKMc?preview

I Will be appreciative if somebody can take a look at that, I also will try to see if I can fix this problem and will share with you a solution if I will find it.

Thanks

_Originally posted by @Kondzolko in https://github.com/snapappointments/bootstrap-select/issues/2505#issuecomment-952400062_

**Comment by Kondzolko** [comment]
I found where is the problem.
For Some reason we all the time sent index 0 'StartIndex'

the problem in line 1770 in this code
`addOptgroup.call(this, startIndex, selectOptions);`

please replace to
`addOptgroup.call(this, i, selectOptions);`

An example of code you can find here:
https://plnkr.co/edit/amuqKRkRe829UEVC?preview

**Comment by ghost** [comment]
Hi,

You can use [this workaround](https://github.com/snapappointments/bootstrap-select/issues/2675).

Regards

**Comment by caseyjhol** [comment]
Duplicate of #2607.
