### ISSUE TITLE
How do I integrate it with bootstrap5?

### ISSUE THREAD

**Issue by ablaszkiewicz** [snapappointments/bootstrap-select#2673]
I have an app running bootstrap 5.0.2 and wanted to use this multiselect.
As my app uses npm, I typed `npm install bootstrap-select` as docs suggested.
Then I added a `select` with `selectpicker` class into my HTML but it doesn't seem to work. Do I need to take some additional actions?

**Comment by ablaszkiewicz** [comment]
(I have jquery installed via link and it is before bootstrap-select. Console says `There was an issue retrieving Bootstrap's version. Ensure Bootstrap is being loaded before bootstrap-select and there is no namespace collision. If loading Bootstrap asynchronously, the version may need to be manually specified via...`

Tried to manually put "5" into `...Constructor.BootstrapVersion = "5"`. Doesn't work either

**Comment by NicolasCARPi** [comment]
It seems your issue is with loading bootstrap before bootstrap select. This is not a bootstrap-select issue, closing.
