### ISSUE TITLE
Using title on options for alternative text doesn't work

### ISSUE THREAD

**Issue by webair-studio** [snapappointments/bootstrap-select#2674]
https://developer.snapappointments.com/bootstrap-select/examples/#selected-text
Don't work for 1.14beta version

**Comment by NicolasCARPi** [comment]
I can confirm this bug (https://github.com/snapappointments/bootstrap-select/commit/397dc20491b7150c28105398d7ba13daceb5b8e0).

@caseyjhol Could you point me where in the code this would be?

**Comment by fabienwnklr** [comment]
@NicolasCARPi hi, i'm not sure to 100% but i think it's due to modification of `getSelectedOptions` function , that returning an object without the `title` property. I think it’s a good lead...

**Comment by NicolasCARPi** [comment]
I think I fixed it but I'm not sure if it's the correct way to do it...

~~~diff
diff --git a/js/bootstrap-select.js b/js/bootstrap-select.js
index 84db030..809bfd9 100644
--- a/js/bootstrap-select.js
+++ b/js/bootstrap-select.js
@@ -805,6 +805,10 @@
           value = option.style.cssText;
           break;

+        case 'title':
+          value = option.title;
+          break;
+
         case 'content':
         case 'tokens':
         case 'subtext':
@@ -1668,6 +1672,7 @@
           config.inlineStyle = inlineStyle;

           config.text = dataGetter(item, 'text');
+          config.title = dataGetter(item, 'title');
           config.content = dataGetter(item, 'content');
           config.tokens = dataGetter(item, 'tokens');
           config.subtext = dataGetter(item, 'subtext');

~~~

(still getting familiar with the codebase...)

**Comment by fabienwnklr** [comment]
I think too. Make a pull request :)

**Comment by NicolasCARPi** [comment]
@fabienwnklr https://github.com/snapappointments/bootstrap-select/pull/2689
