### ISSUE TITLE
Optgroups not working at all

### ISSUE THREAD

**Issue by amigian74** [snapappointments/bootstrap-select#2675]
Hi,

I am currently converting our products from Bootstrap 4 to Bootstrap 5. For this I use the latest version of bootstrap-select (1-14-0beta). Unfortunately there are still problems with optgroups:

Only the options from the first optgroup are displayed and processed here. The selection of the options is hardly possible, for example if you open the select and close it again immediately, the selection afterwards is empty.

I hope this litte example will show the problems:

https://jsfiddle.net/amigian74/pghjytvu/16/

Thx and greetings Steven

**Comment by ghost** [comment]
Hi,

You can install the ` v1.14-dev` branch to fix this problem ([this commit](https://github.com/snapappointments/bootstrap-select/commit/0562177a98535f80452d3b7d6d92143627f6c582#diff-eca1e0510b5a8b4008f5f3296b930bb43428760a66b4695fc69655d2f05ae5b0) corrected the problem).  No release is available at the moment.

Add this in your `package.json` file:
```json
{

	"dependencies": {
		"bootstrap-select": "github:snapappointments/bootstrap-select#v1.14-dev"
	}
}
```

Regards

**Comment by amigian74** [comment]
I'm already using v1.14.0-beta2

**Comment by ghost** [comment]
> I'm already using v1.14.0-beta2

It's not the tag `v1.14.0-beta2` but the BRANCH `v1.14-dev`. That's not the same 😉

**Comment by caseyjhol** [comment]
Duplicate of #2607.
