### ISSUE TITLE
[DEV] Branching issues

### ISSUE THREAD

**Issue by NicolasCARPi** [snapappointments/bootstrap-select#2682]
@caseyjhol I'm not a big fan of using versions in branches (that's what tags are for). I would suggest switching to this:

- `master` branch contains latest published version (and is default)
- `dev` branch is the target for PR and contains yet to be published commits

What do you think?

**Comment by caseyjhol** [comment]
I'm okay with that. I switched to versioned branches to match how Bootstrap was doing it a few years ago (they've since changed). My only concern with not having the dev branch be default is the increased possibility that users attempt PRs off of the wrong branch (increasing chances of manual intervention).

**Comment by NicolasCARPi** [comment]
> that users attempt PRs off of the wrong branch

That's not an issue, we can have an action/bot that closes PR targeted on master automatically with a link to the contributing document.

I'll make that change then.

**Comment by NicolasCARPi** [comment]
@caseyjhol You'll need to make the change as Admin rights are required to change the default branch name. See [doc](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch).

**Comment by caseyjhol** [comment]
@NicolasCARPi I renamed the branch to `main` instead of `master` to keep in line with the new Git recommendations. The branch names are still a bit inconsistent at the moment since technically "main" is not the latest published release, but instead is technically the development branch.

**Comment by NicolasCARPi** [comment]
![2021-11-28-174239_498x384_scrot](https://user-images.githubusercontent.com/3043706/143777424-9624d09b-46b1-4906-9250-cf61bce2b92d.png)

pretty nifty :)
