### ISSUE TITLE
Mouse click cannot trigger the drop-down list

### ISSUE THREAD

**Issue by WindySeasons** [snapappointments/bootstrap-select#2687]
I meet a problem.
In my project, i make a single select drop-down list like this .

```
<select multiple class="selectpicker">
          <option>X86</option>
          <option >X64</option>
          <option >ARM64</option>
</select>
```

![image](https://user-images.githubusercontent.com/36540655/144823140-f446159f-5741-4d91-aacc-33333aa93b77.png)
but the mouse click cannot trigger the drop-down list.

But  I can press the key board to use it;
![image](https://user-images.githubusercontent.com/36540655/144823895-2edda664-1440-4155-8339-3a8da0afaf92.png)

No problem when I preview it with html file，but when i run it on asp.net ,It has the problem I described above；

**Comment by NicolasCARPi** [comment]
> No problem when I preview it with html file，but when i run it on asp.net

This looks like a problem on your side then, not in this library. Feel free to comment if you can find a reproducible bug and I'll reopen if there's somthing we can do about it. Make sure to try the latest code from `main` branch, too.
