### ISSUE TITLE
Fix `main` value in package.json after removing the dist/ directory

### ISSUE THREAD

**Issue by greenfork** [snapappointments/bootstrap-select#2702]
In the recent commits the dist/ directory was removed, so the following line is not correct anymore:

https://github.com/snapappointments/bootstrap-select/blob/225ca0a9f092941d78d54ed449354655f258e5dd/package.json#L4

In my project which I use with Webpack I do `require('bootstrap-select/js/bootstrap-select.js');`, hopefully this is the correct file to require.

**Comment by NicolasCARPi** [comment]
Hello,

This file is present in the npm archive, so I believe it is the correct value for the main key of the package.json.

**Comment by greenfork** [comment]
Okay, I think then the problem is that I use the latest master version, in my package.json:
```
"bootstrap-select": "git+https://github.com/snapappointments/bootstrap-select.git#225ca0a9f092941d78d54ed449354655f258e5dd"
```

Will be waiting for the next release then for the time being. Thanks!
