### ISSUE TITLE
Floating label support

### ISSUE THREAD

**Issue by AgentSmith0** [snapappointments/bootstrap-select#2723]
**Is your feature request related to a problem? Please describe.**
It would be very useful to get floating labels like this: https://getbootstrap.com/docs/5.1/forms/floating-labels/#selects

**Describe the solution you'd like**
Floating labels support.

**Comment by javothemes** [comment]
Yes, it will look great.

<img width="460" alt="image" src="https://user-images.githubusercontent.com/28474304/190040814-24ed60dd-cd40-4a9e-af91-0dfea678ce5f.png">

We created one by some css.

But it's not really floating label as Boostrap 5.2 is not also supported floating labe on form-select. They support only input, textarea. 

I hope you have this feature. Then great!

**Comment by AgentSmith0** [comment]
When will a new version of bootstrap-select with https://github.com/snapappointments/bootstrap-select/pull/2784 released.

**Comment by AgentSmith0** [comment]
Closing, because fixed in dev branch.
