### ISSUE TITLE
Live-search bug when selectpicker part of a modal

### ISSUE THREAD

**Issue by PercyDwn** [snapappointments/bootstrap-select#2739]
I have a selectpicker with live-search that is part of a modal. The search-field is displayed, but it can not get focus. Clicking on it has no effect.

* Using bootstrap-select@1.14.0-beta3
Instead using the stable version is no option, as the beta version contains an important fix for optgroups.
* Using jquery-3.6.0
* Using bootstrap@5.1.3
* Tested in Firefox, Safari and Chrome

Demo: https://jsfiddle.net/PercyDwn/pnsq1tx4/1/

![grafik](https://user-images.githubusercontent.com/33127695/166969825-56f8d8c4-4b4a-44c7-b80b-373016a1c82c.png)

**Comment by deawx** [comment]
u can use container option

`$('#selectpicker').selectpicker({
 container: '#modal'
});`

demo : [https://jsbin.com/goteren/edit?html,js,output](https://jsbin.com/goteren/edit?html,js,output)

**Comment by NicolasCARPi** [comment]
Thank you @deawx for providing a solution to @PercyDwn.
