### ISSUE TITLE
Clear all items and add new items

### ISSUE THREAD

**Issue by cwolcott** [snapappointments/bootstrap-select#2740]
- In **1.14.0-beta2** I could clear the selectpicker and add new options, but in **1.14.0-beta3** the list does not clear.

Using bootstrap-select@1.14.0-beta3
Using jquery-3.6.0
Using bootstrap@5.1.3
Tested in Chrome

[StackBlitz Example](https://stackblitz.com/edit/bootstrap-select-issue?devToolsHeight=33&file=index.html)
Includes **1.14.0-beta3**, to see it work change the source the **1.14.0-beta2**

**Comment by yankarinRG** [comment]
Related: https://github.com/snapappointments/bootstrap-select/issues/2724

**Comment by NicolasCARPi** [comment]
Closing as duplicate then. Thanks @yankarinRG .

**Comment by jfsv** [comment]
$('#grafSeleccionado').selectpicker('destroy').empty().addClass('selectpicker').append(Departamentos).selectpicker('render');
esto me funciono con:
bootstrap-select@1.14.0-beta3
jquery-3.6.0
bootstrap@5.2
