### ISSUE TITLE
How to Lazy Load with Webpack

### ISSUE THREAD

**Issue by tamb** [snapappointments/bootstrap-select#2743]
I'm attempting to create a factory function that will return instances of `bootstap-select`.  I'm trying to lazy load the library and I'm getting this issue:
`TypeError: $(...).selectpicker is not a function`

```js
function create(selector, options){
  return import("bootstrap-select/dist/css/bootstrap-select.min.css").then(() => {
    return import("bootstrap-select").then(module => {
      // $.fn.selectpicker.Constructor.BootstrapVersion = '4';
      window.$.selectpicker = module.default;
      const defaultOptions = {
        style: '',
        styleBase: 'form-control',
        dropupAuto: false,
        static: true,
        size: 6,
        tickIcon: 'fal fa-times-circle'
      };

      options = {
        ...defaultOptions,
        ...options
      };
      return $(selector).selectpicker(options);
    }).catch(console.error);
  }).catch(console.error);
}
```

There should definitely be some clear documentation on doing this.  There are a bunch of loading benefits and this simplifies creating instances greatly.

**Comment by NicolasCARPi** [comment]
If you manage to make it work, please make a PR documenting the process. Right now we'll just classify it as: not possible.
