### ISSUE TITLE
bootstrap is not defined

### ISSUE THREAD

**Issue by applyACS** [snapappointments/bootstrap-select#2750]
![image](https://user-images.githubusercontent.com/13115651/171826963-f280e0dc-3f8b-42ce-868b-ee57a0820791.png)

I am getting bootstrap is not defined error here.
I am using bootstrap 5 and it is loaded before this

**Comment by NicolasCARPi** [comment]
fixed by https://github.com/snapappointments/bootstrap-select/pull/2736 ?

**Comment by applyACS** [comment]
cool. waiting for the merge
