### ISSUE TITLE
Refresh function adds items to the list

### ISSUE THREAD

**Issue by SoftCircuits** [snapappointments/bootstrap-select#2753]
I have markup and JavaScript similar to the following.

``` html
<select class="selectpicker" multiple>
  <option value="1">Mustard</option>
  <option value="2">Ketchup</option>
  <option value="3">Barbecue</option>
</select>
```

``` javascript 
$('button').on('click', function () {
  var select = $('select');
  select.val([ 1, 3 ]);
  select.selectpicker('refresh');
});
```

It selects the selected items in the list and then refreshes the Bootstrap-select component.

This was working in an older version of the component. But now it re-adds everything in the list. So if there are three items, there will be six after running this code.

I've created a CodePen to demonstrate:

https://codepen.io/softcircuits/pen/gOvEXJV?editors=1111

**UPDATE:**

This is happening with v1.14.0-beta3. It does not happen with v1.13.14.

**Comment by NicolasCARPi** [comment]
Closing as duplicate of https://github.com/snapappointments/bootstrap-select/issues/2712
