### ISSUE TITLE
 cannot use jsmin.php on v1.14.0-beta3 

### ISSUE THREAD

**Issue by dcarbunescu** [snapappointments/bootstrap-select#2769]
Douglas Crockford's JSMin
Windows 10, Jquery 3.6.0, Bootstrap 5.2.0,  Bootstrap-select v1.14.0-beta3

**Comment by NicolasCARPi** [comment]
Oh you mean that stuff from 10 years ago is not working? https://github.com/rgrove/jsmin-php

Seriously....
