### ISSUE TITLE
Bootstrap doesn't allow more than one instance per element. Bound instance: bs.dropdown.

### ISSUE THREAD

**Issue by AgentSmith0** [snapappointments/bootstrap-select#2782]
I am using bootstrap-select v1.14.0-beta3 with bootstrap 5.2.0. When I use a selectpicker and interact with it, I get the following error message:
`Bootstrap doesn't allow more than one instance per element. Bound instance: bs.dropdown.`

**Comment by NicolasCARPi** [comment]
You might be trying to bind it several times to an element. Looks more like a correctly handled user error rather than a bug in the lib to me.

**Comment by AgentSmith0** [comment]
I figured out that you can't assign bootstrap's custom tooltips to dropdown toggles. I fixed this by excluding dropdowns from the tooltip selector.
