### ISSUE TITLE
Build version of 1.14.0-beta3?

### ISSUE THREAD

**Issue by kikosoft** [snapappointments/bootstrap-select#2785]
I'm just a simple user, but for a new project I'm already using Bootstrap 5. Being on BS5 also means it makes sense to use the latest beta version of bootstrap-select. That would be:

[https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta3](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta3)

Regrettably 1.14.0-beta3 only comes with the source code. I could spent an afternoon trying to find out how to convert this into a build version, but it would save me a lot of time if the build version was there, just like it is with 1.14.0-beta2. 

Creating a build version is probably very simple for someone doing this every day, but that's not me. Sorry for that. Staying on 1.14.0-beta2 for now.

**Comment by NicolasCARPi** [comment]
You mean a minified version, right?

Try this:

~~~
git clone https://github.com/snapappointments/bootstrap-select/
cd bootstrap-select
npm i
./node_modules/.bin/grunt
~~~

You'll find the files in `dist/` folder.

**Comment by kikosoft** [comment]
Yes, that did work. Thank you.

**Comment by AgentSmith0** [comment]
I also struggled at building bootstrap-select from source, could you please add the instructions to the README file or to the documentation? This would be very helpful to others. Thanks!

**Comment by kikosoft** [comment]
Here is the [dist](https://github.com/snapappointments/bootstrap-select/files/9945453/dist.zip) folder I made with the instructions from [NicolasCARPi](https://github.com/NicolasCARPi). It contains the two files you need:

```
dist/css/bootstrap-select.min.css
dist/js/bootstrap-select.min.js
```

and the other files in that directory.

**Comment by AgentSmith0** [comment]
Thanks, I was already able to build it after reading the instructions here, but I propose to make the instructions easier to find for people who don't know how to build bootstrap-select from source.
