### ISSUE TITLE
refresh bugs

### ISSUE THREAD

**Issue by EternityTeam** [snapappointments/bootstrap-select#2786]
In normal use, the refresh method has some problems.
v1.14.0-beta3
[test.zip](https://github.com/snapappointments/bootstrap-select/files/9542803/test.zip)

**Comment by NicolasCARPi** [comment]
Yes. Please make sure to search for an existing report before creating a new issue, and rather than providing a zip file, use code snippets or online code editors to provide a use case. Closing as dupe of #2724.
