### ISSUE TITLE
v1.14.0-beta3 file without "dist" directory

### ISSUE THREAD

**Issue by Tirguy** [snapappointments/bootstrap-select#2832]
Just a question : is it possible to have a full archive with file that we can use directly in our web pages ? 
v1.14.0-beta2 has this directory... Why this new version do not have one ? 

Thank's for all & your work,

Thierry

**Comment by caseyjhol** [comment]
You can build the dist directory using `grunt build`, or you can use something like CDNJS or JsDelivr. It's best practice to not include built files in the source repo.
