### ISSUE TITLE
bootstrap-select@1.14.0-beta3 not working with Bootstrap 5.3.2

### ISSUE THREAD

**Issue by frankzhangxd** [snapappointments/bootstrap-select#2846]
no dropdown shows when you click the select.

https://jsfiddle.net/fzhang_dgc/95r0a46j/1/

**Comment by Shielsy** [comment]
Is there any version of bootstrap-select that is compatible with 5.3.2?

**Comment by mattymatty76** [comment]
I don't know if in your case it will work, but you can try...

[https://gist.github.com/mattymatty76/c996d3b77f298b2ec133be59992df9d4](https://gist.github.com/mattymatty76/c996d3b77f298b2ec133be59992df9d4)

remember that if you have a list very long, change virtualScroll: 600 to virtualScroll: 1000000,
and change, up to you, pipe separator | to one you prefer ,

**Comment by MadCode1982** [comment]
> no dropdown shows when you click the select.
> 
> https://jsfiddle.net/fzhang_dgc/95r0a46j/1/

There is an error using bootstrap.min.js 
![image](https://github.com/snapappointments/bootstrap-select/assets/67041064/60307d9a-7fe6-419c-baac-f671f3844e2a)

Use bootstrap.bundle.min.js instead of bootstrap.min.js

**Comment by caseyjhol** [comment]
@MadCode1982 Is correct - you need to use bundle to ensure Popper is included.
