### ISSUE TITLE
Bootstrap Floating labels broken

### ISSUE THREAD

**Issue by Kitthaven** [snapappointments/bootstrap-select#2869]
I have been using Bootstrap Select for a while for a project that I recently took a break from. Upon returning I found that the floating labels I had set up were broken and just wouldn't work properly. I'm unsure why as I haven't upgraded or downgraded Bootstrap or BS Select versions.. see the screenshots for what's happening. I know this is a long shot as this project isn't really receiving updates but would anyone have an idea for how I could fix it? I am using the latest BS Select and Bootstrap 5.3.3.

Floating labels and the Bootstrap col attribute both seem broken (for me)

![2024-03-30 21_24_06-Bean Pets - Opera](https://github.com/snapappointments/bootstrap-select/assets/50052152/73492d0c-7d13-4497-926d-10e397441ef7)
![2024-03-30 21_24_30-Bean Pets - Opera](https://github.com/snapappointments/bootstrap-select/assets/50052152/d129b312-30d3-4fdd-a6c1-6c0e4b14ef04)
![2024-03-30 21_28_37-Bean Pets - Opera](https://github.com/snapappointments/bootstrap-select/assets/50052152/98968d26-0502-4699-b720-6aeb54a7fe87)

They all use the col-sm class and used to take up all available space automatically but now the spacing is all weird and I have no idea why. I really love Bootstrap Select, for the image thumbnails especially, and I don't know of any alternatives if I can't fix this :x 

Thank you!

For code reference, in case I'm messing up classes somewhere, this is how my dropdowns are built. The floating labels work with the class 'form-select' but you can't use both that class and 'selectpicker' so I'm lost.

```
<div class='col-sm form-floating p-1'>
<select class='selectpicker show-tick' data-live-search='true' id='options' name='options' aria-label='options'>
<option value='option1'>Option 1</option>
<option value='option2'>Option 2</option>
</select>
<label for='options'>Option 1</label>
</div>
```

**Comment by gumbarros** [comment]
+1 Hoping for a solution too

**Comment by Kitthaven** [comment]
> +1 Hoping for a solution too

I managed to actually find the solution. You need to add the 'form-control' class to the select element with the 'selectpicker' class and that fixed it. Unsure why I needed to add it seemingly out of nowhere but I assume it's an update that happened to Bootstrap lol.

**Comment by gumbarros** [comment]
@Kitthaven  I will deeply appreciate if you send me a snippet of your `form-floating` + bootstrap-select working :). I'm using a combination of `form-select`, `form-control` and it's not working.

**Comment by Kitthaven** [comment]
> @Kitthaven I will deeply appreciate if you send me a snippet of your `form-floating` + bootstrap-select working :)

![2024-04-20 20_06_49-Bean Pets - Opera](https://github.com/snapappointments/bootstrap-select/assets/50052152/16a470b9-5702-4f3e-8a59-a3386a99d70b)

\<div class='col-sm form-floating p-1'>
\<select class='selectpicker show-tick form-control' data-live-search='true' id='body' name='body' aria-label='Custom pet body selection'>
\<option>Options, etc\</option>
\</select>
\<label for='body'>Body Style\</label>
\</div>

**Comment by gumbarros** [comment]
Thank you very much, have a nice weekend.

**Comment by gumbarros** [comment]
It's not working with the exact markup, do you have any customizations at CSS or JS? What version of bootstrap-select are you using?

![image](https://github.com/snapappointments/bootstrap-select/assets/52143624/4651f476-9725-4944-9b51-bd5fbbf35409)

**Comment by gumbarros** [comment]
@Kitthaven sorry for the ping, can you F12 the computed HTML after running `$(".selectpicker").selectpicker()`? I'm in a deadline and really need this fixed :(

**Comment by Kitthaven** [comment]
![2024-04-21 18_25_18-Bean Pets - Opera](https://github.com/snapappointments/bootstrap-select/assets/50052152/dcbf3795-21cc-4f52-aebe-6c3fd8d7737e)

**Comment by Kitthaven** [comment]
> It's not working with the exact markup, do you have any customizations at CSS or JS? What version of bootstrap-select are you using?
> 
> ![image](https://private-user-images.githubusercontent.com/52143624/324201840-4651f476-9725-4944-9b51-bd5fbbf35409.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MjA4NjYsIm5iZiI6MTcxMzcyMDU2NiwicGF0aCI6Ii81MjE0MzYyNC8zMjQyMDE4NDAtNDY1MWY0NzYtOTcyNS00OTQ0LTliNTEtYmQ1ZmJiZjM1NDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE3MjkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YzFkMDljNWM1ODdkZDk4OGQyZjZlMjk3YzU0Y2ZjZmEyNzZlZGJiMjAyM2U4M2JkMTBiMGNlYTJiYWQ4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2zyszVJjFJp_YweoDuZXoXVskauGUQXW4n8V9A3WUc8)

I am using the latest Bootstrap Select and the latest Bootstrap. In your picture it looks like it's working btw. I couldn't find a way to directly include it in the Bootstrap Select dropdown so I changed the colour of the dropdown to match the Bootstrap form-control background.

![2024-04-21 18_32_09-Bean Pets - Opera](https://github.com/snapappointments/bootstrap-select/assets/50052152/1fecf61d-ad29-4c49-b45e-5d35ffe6ce52)

It isn't perfect by any means but it works how I want it to so I don't mind it
