### ISSUE TITLE
iPad Keyboard Issue

### ISSUE THREAD

**Issue by clcarver** [snapappointments/bootstrap-select#444]
Hello, my first time here so please forgive me if I have missed anything as far as an answer to this question/bug?

I have noticed that when using the live-data-search feature on the iPad, the keyboard will close automatically after the user enters a letter. They have to touch the input field again to enter the next letter and so on until they touch a value.

Is this normal behavior or is there a way to keep the keyboard visible while the user is typing in the search field?

This is reproducible on your demo page.

**Comment by mattherick** [comment]
is there something new about this topic? is there already provided a fix?

**Comment by imuller** [comment]
Still no fix?

**Comment by caseyjhol** [comment]
This appears to be fixed in iOS 12 (possibly earlier).
