### ISSUE TITLE
tab key skips selectpicker inputs on Mac

### ISSUE THREAD

**Issue by gitsocko** [snapappointments/bootstrap-select#478]
Safari 6.1.1, Mac: using the tab key ignores (skips) all .selectpicker inputs.  Works fine in Firefox 27 and Chrome 32.  To test, try using the tab key in the bootstrap-select demo in Safari.

**Comment by alexandtheweb** [comment]
Same here. Still valid on Safari 8.0 on Mac Yosemite

**Comment by uiuxdeveloper** [comment]
Still an issue here

**Comment by Martinomagnifico** [comment]
Still an issue on Safari (9.1). Also on Safari Tech Preview (9.1.1).

**Comment by jchernan** [comment]
I had the same issue, and it seems you need to enable tab access in Safari as described [here](http://stackoverflow.com/a/1914496/1091724).

**Comment by elsurudo** [comment]
@jchernan But we can't rely on users having this enabled. Furthermore, tab works just fine in Safari for regular form fields.

Has anyone found a better workaround?

**Comment by caseyjhol** [comment]
Released in [v1.13.17](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.17)!
