### ISSUE TITLE
Issue with data-selected-text-format

### ISSUE THREAD

**Issue by vssaran2006** [snapappointments/bootstrap-select#732]
Hi ,

Am using data-selected-text-format to display the selected items in the select dropdown. 
I added a reset option and divider and then the list of product items . 
I want to count the product items only and not the reset option. But bootstrap select taking reset also and counting that . Basically i wanted to have an option to not to count an item in the list . 

So i added a new data attribute 
data-donotcount 
and changed the bootstrap select framework code to filter this out .

UI code :
option class="reset" data-do-not-count="true" value="reset">Reset</option

Framework code
version : 1.5.4
line no :253 
this.$element.find('option:not([data-divider="true"]):not([data- do-not-count="true"]):not([data-hidden="true"])'  and it is working fine . 

Please review this and let me know your thoughts on this .

**Comment by caseyjhol** [comment]
I think a separate button would maybe make more sense (something like #2287 or #1996). If there's enough support for this, we could implement it, but it seems like it would be more of a fringe case.
