### ISSUE TITLE
Please update characters in accent insensitive search

### ISSUE THREAD

**Issue by deel77** [snapappointments/bootstrap-select#767]
I am having problems using search without diacritics for some special characters in languages. I have made changes to your function and just want to recommend to use the fastest code from this example:
http://jsperf.com/diacritics/27
It removes much more diacritics characters than actual solution.

**Comment by caseyjhol** [comment]
Released in [v1.13.4](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.4)!
