### ISSUE TITLE
data-live-search on tablet

### ISSUE THREAD

**Issue by ahna88** [snapappointments/bootstrap-select#787]
My issue is regarding using bootstrap-select.js and data-live-search=true. I am not not sure if this issue is new .. but i could not find similar one .. I will appreciate it if you can check this issue. 

this working perfectly on pc ..while i am trying to use the tablet, i could not type full word. Each time i type a new letter, it deletes the old one.

I noticed that i can add more than one letter if i add a space after each letter then delete this space, in this case the search is working. 

Thanks

**Comment by OOPMan** [comment]
This seems to be an issue with the Samsung keyboard on the Note 8.0 and Chrome. I tested on my Note 8.0 and had the same problem until I switched to using the Google AOSP Keyboard.

**Comment by ahna88** [comment]
What is google aosp keyboard ? 
Furthermore, recently i have a pop-up dialog , (modal dialog ) also i got problem with it. As soon as i open the keyboard on screen, i can not scrool down to the end of dialog. Did u notice something like that ?

**Comment by OOPMan** [comment]
Google AOSP Keyboard is the default keyboard that comes with Android. To install it on the Note 8.0 you need to manually download it.

1. Go to http://apps.evozi.com/apk-downloader/
2. Enter https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin in the input field
3. Click Generate Download link
4. Download the APK
5. Copy the APK to your Note 8.0
6. Install the APK using EZ File Manager or something similar.

**Comment by jheissat** [comment]
Hello. I have the same issue regarding data-live-search input box on android samsung S4. Did you manage to fix this issue ? 

Thank you

**Comment by OOPMan** [comment]
The issue is the Samsung keyboard, not bootstrap-select.

**Comment by jheissat** [comment]
Thank you for your reply. 

However, I cannot ask my users to change their keyboard. So i was wondering why there is this issue specifically on the data-live-search input box and how I could fix this. (keyboard seems to be working on other input boxes).

Thanks

**Comment by OOPMan** [comment]
Disable live-search for those users?

**Comment by jheissat** [comment]
Yes I will probably have to do that ! Thanks ;)

**Comment by jheissat** [comment]
A fix is to modify the function liveSearchListener of bootstrap-select.js. and not make the bootstrap select "focus" on the search input automatically. It did it for mobile devices to avoid this bug and avoid having the keyboard automatically appearing when the dropdown is opened

**Comment by OOPMan** [comment]
One would argue that the keyboard should automatically open when the input is tapped though.

Also, as I said, the live search functionality works fine on the Google keyboard (And others too probably), so this is a collision between something in boostrap-select (Maybe the focus thing you mentioned) and something retarded Samsung keyboard does (Samsung keyboard does a lot of really dumb shit...)

**Comment by nonameolsson** [comment]
@jheissat How could I do to disable focus? What was your solution?

**Comment by jheissat** [comment]
I actually modified the plugin and disabled the focus when the dropdown opens...

**Comment by caseyjhol** [comment]
This seems to be a fringe case, so I'm going to recommend anybody still encountering this issue 👍 and follow #1511. As disabling auto-focus is probably the only solution.
