### ISSUE TITLE
IE 9 live search issue after searching non existing item

### ISSUE THREAD

**Issue by bahaa82** [snapappointments/bootstrap-select#835]
Hi,
I am using bootstrap-select  and it is working fine for me except in IE 9 , when I tried to search non existing item via the live search , then deleted the text, the options list does not show up again.I tried it also in the demo page.
Thanks in advance.

**Comment by bahaa82** [comment]
Can you please advise if there is work around for this issue ?

**Comment by ayush15690** [comment]
I also have the same issue, Any suggestions

**Comment by haseeb1431** [comment]
Any chances to have it fixed in near future or next release?

**Comment by arasu-rrk** [comment]
@silviomoreto Is it possible to include this fix in next release?
