### ISSUE TITLE
using bootstrap-select with angular and loading data via ajax

### ISSUE THREAD

**Issue by mmbont0** [snapappointments/bootstrap-select#864]
Hello, I am having problems with the plugin using with angular and loading data via ajax. I did use a directive to wrap things up but continue to see the issue. her's my issue:

http://stackoverflow.com/questions/27952798/bootstrap-select-plugin-with-angular-js-and-ajax-data-not-working

Could you please let me know where I am going wrong. 
Thank You
Mohan

**Comment by VisualBean** [comment]
I am also having the same issue:
bootstrap-select fails "removes" items populated through Ajax.
If i remove the .selectpicker(); initialization from my code (so i get a regular select) everything works fine - but not when selectPicker is used.

**Comment by caseyjhol** [comment]
Check out https://github.com/joaoneto/angular-bootstrap-select

**Comment by caseyjhol** [comment]
Please 👍 and follow #899.
