### ISSUE TITLE
Ajax/JSON data source support

### ISSUE THREAD

**Issue by piernik** [snapappointments/bootstrap-select#899]
Can You add option to load options in ajax?

**Comment by truckingsim** [comment]
@piernik I built a [plugin](https://github.com/truckingsim/Ajax-Bootstrap-Select) just for this.  It goes on top of bootstrap select and should be able to do everything you want.  If you use it and you have any questions/concerns/bugs make an issue on that repo.

**Comment by Jogai** [comment]
Or for a simple usecase you can extend it yourself. Note that this basicly switches local search to ajax search, and will not play nice if there are multiple values returned with ajax.

```javascript
        var responseToSelect = function (data, selectBox) { // convert ajax response ...
            if (data.length > 0) {
                var output = [];
                $.each(data, function (i, dat) {
                    output.push("<option value=\"" + dat.Value + "\">" + dat.Text + "</option>");
                }); // ... into options ...
                selectBox.html(output.join("")); // ... on the original element
                selectBox.selectpicker("refresh"); // refresh the options
            }
        }
        var inp = "";
        $(".autocomplete")
            .each(function () {
                var thi$ = $(this); // hold on to the original element
                thi$.selectpicker({
                    liveSearch: true
                }); // turn it into a bootstrap select with search field
                thi$.next().on("input", function (evt) { // listen on the created elements for input
                    var $earch = $(evt.target); // hold on to the search input field
                    if ($earch.val() !== inp) { // if the search value is changed
                        inp = $earch.val();
                        if (inp.length > 2) { // and it has 3 or more characters ...
                            var url = thi$.data("completeurl") + "/"; // get an url to ...
                            $.get(url, { code: "", search: inp }) // do an ajax call to get more countries
                                .done(function (data) { responseToSelect(data, thi$) });
                        }
                    }
                });
            });
```

**Comment by martin-g** [comment]
+1 for official support for Ajax loading!

**Comment by PoetikDragon** [comment]
Agreed! Official support would be fantastic. Select2 is superior in this regard (but not in many others). I tried ajax-bootstrap-select but it is bloated and buggy, nowhere near the quality of bootstrap-select itself.

**Comment by esaesa** [comment]
+1 for official support for Ajax loading! # #

**Comment by pauloprea** [comment]
+1 and bump

**Comment by niladam** [comment]
+1 and another bump..

**Comment by paulmjarosch** [comment]
Any progress on this?

**Comment by nittolese** [comment]
+1 and bump!

**Comment by caseyjhol** [comment]
First steps taken to support this. It's now possible to load in the the select options using the data property:

```js
$('#test').selectpicker({
  data: [
    {
        text: 'Bread'
    },
    // optgroup
    {
      text: 'Picnic',
      icon: 'fa-home',
      children: [
        {
          text: 'Mustard',
          value: 'mustard',
          selected: true
        },
        {
          text: 'Ketchup',
          value: 'ketchup'
        },
        {
          text: 'Relish',
          value: 'relish'
        }
      ]
    }
  ]
});
```

```js
$('#test2').selectpicker({
  source: {
    data: function(callback) {
      var array = [
        {
          text: 'Tent',
          icon: 'fa-camera'
        },
        {
          text: 'Flashlight',
          selected: true
        },
        {
          text: 'Disabled Option',
          disabled: true
        },
        {
          value: 'divider',
          divider: true
        },
        {
          text: 'Toilet Paper'
        }
      ];

      callback(array);
    }
  }
});
```

See an example here: https://plnkr.co/edit/NXB03TGwGPsD7BSj. This feature required a lot of rewiring under the hood, so it will require additional bug testing. I'll probably have to release a v1.14.0-beta first.

Still todo:
- [ ] Support using a different data source when searching
- [ ] Pull in new or updated data when scrolling (includes pagination support) 

Edit:

Found a bug: for multiple selects, calling `refresh()` resets the select back to its initial state (so any new selected options are reverted). Thinking we'll have to change the API so the default selected status of options is set separately.

**Comment by z1haze** [comment]
if anyone tired of waiting, I came up with a solution that is working pretty well for me. I havent tested much but so far so good.

```js
const axios = require('axios');

module.exports = (selector, url) => {
    const $select= $(selector).selectpicker({
        noneSelectedText: 'Ambassador Search'
    });

    const $input = $select.parent().find('input[type=search]');

    $input
        .on('input', (e) => {
            const value = e.target.value;

            if (value.length < 3) {
                return;
            }

            axios.get(`${url}?search=${value}`)
                .then(({data: results} = []) => {
                    $select.empty();

                    results.forEach((result) => {
                        $(`<option value="${result.discord_user_id}">${result.discord_username} | ${result.discord_nickname}</option>`).appendTo($select);
                    });

                    $select.selectpicker('refresh');
                });
        });
}
```

**Comment by caseyjhol** [comment]
Released in [v1.14.0-beta](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta)!

**Comment by chase439** [comment]
Can you give an example on how remote data loading can tie into the new data property?

**Comment by caseyjhol** [comment]
@chase439 See https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta for some examples.

```js
$('#test2').selectpicker({
    source: {
        data: function (callback) {
            $.ajax('/api/load-options')
                .then((response) => callback(response.data))
        }
    }
});
```

**Comment by NicolasCARPi** [comment]
This issue can be unpinned now that it is closed.

**Comment by uaoleg** [comment]
Is 1.14 supposed to be released?

**Comment by NicolasCARPi** [comment]
@uaoleg this is a dead project: https://github.com/snapappointments/bootstrap-select/issues/2228#issuecomment-1236207188

<img width="500" height="213" alt="Image" src="https://github.com/user-attachments/assets/93c6806b-5ec6-48f7-b982-fe071f6a0ae1" />

**Comment by uaoleg** [comment]
@NicolasCARPi do you know if there is a live fork?

**Comment by NicolasCARPi** [comment]
Not to my knowledge. I'm using tom-select now, you should too, probably.
