### ISSUE TITLE
default select accessible on top-left and top-right corner

### ISSUE THREAD

**Issue by busla** [snapappointments/bootstrap-select#922]
When clicking the top-right and top-left corner of my select form, I get the default Bootstrap select component.

![screen shot 2015-02-16 at 00 10 28](https://cloud.githubusercontent.com/assets/3162968/6205721/92fbc608-b570-11e4-89d2-adf49670e5d0.png)
![screen shot 2015-02-16 at 00 10 57](https://cloud.githubusercontent.com/assets/3162968/6205722/92fc16a8-b570-11e4-91db-69d080ed1859.png)

My code:

```

    <form class="navbar-form navbar-right" action="some-action" method="post">
        <div class="form-group">
            <input name="next" class="form-control" type="hidden" value="some-value" />
            <select name="language" class="selectpicker show-tick">
                    <option>
                                         Stuff 1
                                         Stuff 2
                    </option>
            </select>
        </div>
    </form> 
```

**Comment by caseyjhol** [comment]
Any chance you can link me to that page, or rig up a jsfiddle?

**Comment by busla** [comment]
Sure thing, 

http://beta.sidelinesports.com

Thanks for helping out!

**Comment by caseyjhol** [comment]
Hrmm...I'm not able to reproduce it in Chrome or Firefox on Windows 8. What browser are you using?

**Comment by busla** [comment]
Chrome.. 

did you try clicking in the top-left or top-right corners?

**Comment by caseyjhol** [comment]
Yea - what OS are you using?

**Comment by busla** [comment]
Yosemite 10.10.2

--------------------------------------------------
Jón Levy
nonni@nonni.cc
00 354 779 82 17
Iceland

PGP Fingerprint
F9DD A2C8 9182 DB0E 62FF  3245 4789 57ED 729A 0C42
