### ISSUE TITLE
not working after upgrading to rails 4.2.0

### ISSUE THREAD

**Issue by dougfarre** [snapappointments/bootstrap-select#949]
I am getting the following error when i click on the element: undefined is not an object (evaluating 'that.options') in the following block (line 1):

if (that.options.liveSearch) $parent = $this.parent().parent();

```
  if (that.options.container) $parent = that.$menu;

  $items = $('[role=menu] li a', $parent);

  isActive = that.$menu.parent().hasClass('open');
```

Bootstrap's dropdown-toggle is also not working (i wonder if this is related?). 

Ruby 2.2.0, Rails 4.2.0, bootstrap-select: 1.6.4, bootstrap-sass: 3.3.3

**Comment by yld** [comment]
Everything working fine here with the same versions but without your additional code.
