### ISSUE TITLE
Remote collection as json for selectpicker

### ISSUE THREAD

**Issue by anilmuppalla** [snapappointments/bootstrap-select#953]
I have over 100 selectpickers and each have over 200 options(common to all the selectpickers). This causes the performance to drop drastically, given selectpicker generates the same list for each select tag. Is there a way to feed the collection as a json once and render that on every select (similar to how typeahead.js does)?

**Comment by emilmoe** [comment]
No there isn't. There's an updated version that does this:
https://github.com/truckingsim/Ajax-Bootstrap-Select

But it sucks he didn't make it as a pull request. I will do that.

**Comment by amraei** [comment]
@EmilMoe This issue is 2 years old and still opened. Are you really going to add this feature?

**Comment by EmilMoe** [comment]
I posted a year ago, sorry I think my code is gone as I don't use this anymore

**Comment by caseyjhol** [comment]
Please 👍 and follow #899.
