### ISSUE TITLE
Use a language option for setting the locale

### ISSUE THREAD

**Issue by twifty** [snapappointments/bootstrap-select#955]
Currently, setting the locale is very cumbersome. From what I understand, the strings can be passed in as an option or given as a data attribute, or, a locale file can be loaded after the main class (which overwrites the default values in the class?)

This isn't very developer friendly. Most of the time we would like to supply a minified api, including ALL locales, to the browser, then pass a flag to the api indicating which locale is preferred and default to en_US if it's not available. At the moment, for the web developer, we have to write an extra jQuery function to load the correct locale. And because each locale is a self executing function, that is not easy.

Would it be possible to give selectpicker an option, for example 'language' or 'locale', and have the api try to load the locale strings for us? I realize this will break BC (including the local.js after picker.js), but not all websites are single language. Two forms of the locals could be offered, one for BC and a new one containing them in an keyed array.

**Comment by krazykira** [comment]
+!

**Comment by uapixart** [comment]
+1

**Comment by caseyjhol** [comment]
Closing in favor of #1414. Please 👍 to vote and subscribe 🔉 for updates.
