### ISSUE TITLE
Title showing malformed HTML entities when selected option(s) contains special characters

### ISSUE THREAD

**Issue by jamiewinder** [snapappointments/bootstrap-select#958]
Example:

```
<select class="selectpicker">
    <option>Test &lt;A&amp;B&gt;</option>
</select>
```

Which correctly shows 

```
Test <A&B>
```

in the dropdown, but hovering over makes the title

```
Test &amp;lt;A&amp;B&amp;gt;' 
```

appear.

**Comment by beardfu** [comment]
I'm using an older version (1.5.4) but I found that putting the option text as the title attribute on the <option> fixed the html escaping. Otherwise it falls back to using $(this).html() which does the escaping.
